### ISSUE TITLE
Cannot run demos/presentation

### ISSUE THREAD

**Issue by carlca** [rivo/tview#10]
First of all, I have to say this is a cool looking library with some neat code. The demos all work well apart from the one in `demos/presentation`. I CDd into the folder and ran `go run main.go` but i got the response:
```
# command-line-arguments
./main.go:35:3: undefined: Cover
./main.go:36:3: undefined: Introduction
./main.go:37:3: undefined: HelloWorld
./main.go:38:3: undefined: InputField
./main.go:39:3: undefined: Form
./main.go:40:3: undefined: TextView1
./main.go:41:3: undefined: TextView2
./main.go:42:3: undefined: Table
./main.go:43:3: undefined: Flex
./main.go:44:3: undefined: End
./main.go:44:3: too many errors 
```
I expect I have inadvertently missed out an important step. But which one?

**Comment by rivo** [comment]
The presentation code is spread across multiple files. `go run *.go` should do the trick.

**Comment by carlca** [comment]
Wow! That was quick! Thanks.
Just one thing now, I seem to be stuck on Page 7 "Text 2" - no key that I can find moves the page forward or back.

**Comment by carlca** [comment]
I obviously didn't try escape. How embarrassing!

**Comment by rivo** [comment]
It's not obvious, I admit. But since the primitives that are shown are interactive and they have their own key bindings, sometimes `Enter` has a different meaning.

I actually built in a short cut: Hit `Ctrl-N` to advance to the next slide, `Ctrl-P` for the previous slide.

**Comment by carlca** [comment]
Great. Thanks for that. It's a really impressive library. I've tried a few CLI tools with Golang but this one looks easier to use, with a nice fluent approach, and your color choices are good!

**Comment by lhanson** [comment]
Maybe a Readme could be added to the presentation demo? I ran into the same issue. Maybe it's only an issue for people new to Go, but as a person relatively new to Go looking to use this library, it did introduce a tiny amount of friction.
