### ISSUE TITLE
Is there an easy way to capture "final" output?

### ISSUE THREAD

**Issue by aronchick** [rivo/tview#1008]
When i'm drawing, and then quit, the screen wipes. This is fine, but i'd like to capture the last rendered state, and display it after exiting. I can't seem to find this anywhere - is there guidance how to do it?

**Comment by rivo** [comment]
This is a property of the [`tcell`](https://github.com/gdamore/tcell) package.

I suppose you could supply your own `Screen` object using [`SetScreen()`](https://pkg.go.dev/github.com/rivo/tview#Application.SetScreen) and extract the contents after your program exits.

**Comment by aronchick** [comment]
Oh fascinating - does screen have a string buffer like object that I could
use to render to the console?

**Comment by rivo** [comment]
Check the documentation:

https://pkg.go.dev/github.com/gdamore/tcell/v2#Screen

**Comment by aronchick** [comment]
I ended up just grabbing the final buffer and printing it.
