### ISSUE TITLE
Allow completely disabling style tags in autocompleter

### ISSUE THREAD

**Issue by gpanders** [rivo/tview#1016]
Hello, I'm the author of [ijq](https://github.com/gpanders/ijq), which uses tview.

jq filters often contain text of the form `[0]` to select a value from a JSON array. Whenever a user writes a new jq filter, ijq saves their filter to a history file and later will populate an autocomplete popup using those history entries. This means that the values in the autocomplete popup contain these `[0]` strings (and others like it).

I am calling `Escape()` on all items before adding them to the list of autocomplete values, but this does not always work as expected: for instance, `Escape()` transforms `[0]` into `[0[]`. In the autocomplete popup this correctly appears to the user as `[0]` but when the user selects the item, the text `[0[]` is inserted into the text entry (open issue: https://todo.sr.ht/~gpanders/ijq/11).

For my use case, I do not want style tags in this text input at all or in the autocomplete window. I would like the ability to completely disable style tags in the autocomplete popup and in the text input so that all strings containing `[]` are interpreted literally (with no escaping or stripping needed).

Is this possible to do now, and if not is this something you'd be willing to support?

Thanks very much!

**Comment by rivo** [comment]
The latest commit adds the `List.SetUseStyleTags` and `InputField.SetAutocompleteUseTags` methods as well as an `Unescape` function.
