### ISSUE TITLE
Feature: change List -> listitem -> Maintext for feature of showing status of on/off

### ISSUE THREAD

**Issue by stephencheng** [rivo/tview#102]
I am not sure if this feature is in there but I couldn't find it from source code.

Basically when I select a list item to execute a method, I'd like to add a visible change to the text/color of the listitems's maintext, eg, 

initially the text is: 

- switch on light (status: off)             

Action: click, the main text turns to below fake code:

- switch off light <green color>(status: on)</green color>

Action: click again, the main text turns to initial text

I'd like a exported method such as

- List.SetMainText(index int, text string)
- List.SetSecondaryText(index int, text string)

Since you already supplied a method: GetCurrentItem to obtain the current item's index, it's all set if these methods could be exposed.

Thanks

**Comment by rivo** [comment]
Please have a look at the referenced commit. This should give you functions to change a list item's text.
