### ISSUE TITLE
DropDown disappears when it's inside a form and we don't select anything

### ISSUE THREAD

**Issue by manuecg** [rivo/tview#1026]
If we have a DropDown inside a form, which has the values form.SetFieldTextColor(tcell.ColorBlack) and form.SetFieldBackgroundColor(tcell.ColorWhite), when we click on it and exit without selecting an option, it takes the 'FieldTextColor' value and causes a hiding effect. I believe the effect can be better appreciated with the video.

https://github.com/user-attachments/assets/e3d3d7d3-5aae-449e-9e5e-22202f8c8ea7

`

       app := tview.NewApplication()
	dropdown := tview.NewDropDown().
		SetLabel("Select an option (hit Enter): ").
		SetOptions([]string{"First", "Second", "Third", "Fourth", "Fifth"}, func(text string, index int) {
		
	})
	dropdown.SetLabel("DropDown: ")
	inputF:=tview.NewInputField()
	inputF.SetLabel("InputField")
	
	form:=tview.NewForm()
	form.AddFormItem(inputF)
	form.AddFormItem(dropdown)
	
	form.SetFieldTextColor(tcell.ColorBlack)
	form.SetFieldBackgroundColor(tcell.ColorWhite)
	
	app.EnableMouse(true)
	if err := app.SetRoot(form, true).SetFocus(form).Run(); err != nil {
		panic(err)
	}

`

@rivo Do you think this could be a possible bug? Or am I doing something wrong?

**Comment by rivo** [comment]
The latest commit solves your issue. However, this `DropDown` stuff is very old code and requires some refactoring. So things might still changes slightly.

**Comment by manuelacgu** [comment]
Hi, Thank you very much, I have tested the new version and everything works fine.
