### ISSUE TITLE
Dropdown widget does not indicate visually when it is in focus

### ISSUE THREAD

**Issue by matthewparsons** [rivo/tview#1029]
I'm not certain whether this behavior existed before, but when I navigate to a dropdown, there is not visual indication that it's in focus (e.g. InputField has a cursor).  Should this be the case, or is there a way I can create this behavior?

**Comment by rivo** [comment]
This is related to #1026. I'm closing this issue because the rewrite announced in this other issue will include an "active style" which is what you're asking for.

**Comment by matthewparsons** [comment]
Thank you very much.  Really really appreciate all your hard work, @rivo!
