### ISSUE TITLE
List.RemoveItem doesn't update the indexes

### ISSUE THREAD

**Issue by Ytiuca** [rivo/tview#1030]
When using  List.RemoveItem, it seems that the indexes are not updated causing problems when interacting with the items later on. For example I remove an item from the list and then I select an item in this list but it selects the next one.

**Comment by SamWhited** [comment]
The list indexes are just the position in an internal slice so there's no need to "update" indexes anywhere (ie. they're not stored on list items or anything along those lines), when the item is removed the slice is shortened and the indexes will work.

An example showing this working can be found here, so something else must be going on with your code, but it doesn't appear to be a problem with RemoveItem: https://go.dev/play/p/S40ysrIIkVr

**Comment by rivo** [comment]
@SamWhited is right, there is not index list or anything like that. @Ytiuca, maybe you want to describe the issue a bit more in detail and post some example code that illustrates it?

**Comment by Ytiuca** [comment]
Yeah, it may be a problem with my code, I'm just a beginner X). I found a workaround in my code so
