### ISSUE TITLE
No way to set selected color on TreeView

### ISSUE THREAD

**Issue by SamWhited** [rivo/tview#1045]
With the list view you can set the color of the selected list item with `SetSelectedTextColor`, `SetSelectedBackgroundColor` and `SetSelectedStyle`. However, on tree views there is no similar styling, the selected node always swaps the foreground and background color.

I would like to propose adding similar methods to the tree view so that when using a treeview and a list view in the same UI there can be some consistency between the selector.

**Comment by rivo** [comment]
The latest commit adds `SetTextStyle()` and `SetSelectedTextStyle()` to `TreeView`.
