### ISSUE TITLE
Cannot see text in text area with border set

### ISSUE THREAD

**Issue by lexagon3** [rivo/tview#1049]
Hi there! I'm new to the library (and Go in general) so apologies if this is expected behaviour or I'm just doing something wrong!

If I add a border to a text area, the text I type is not displayed in the text area:
```
func main() {
	app := tview.NewApplication()
	textArea := tview.NewTextArea().SetBorder(true) // No text shown, even if set to false.
	textArea.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		fmt.Fprintln(os.Stderr, event) // Verifying the text area does actually have focus.
		return event
	})
	if err := app.SetRoot(textArea, true).Run(); err != nil {
		panic(err)
	}
}
```

Removing setting the border then displays text when I type.

Thanks for your help!

**Comment by SamWhited** [comment]
`SetBorder` returns a box, not a text area, so you're actually drawing the underlying box but not the text area itself. Modify that to:

	textArea := tview.NewTextArea()
        textArea.SetBorder(true)

And everything should work.

**Comment by lexagon3** [comment]
Ah! I see. Thank you both for the response and clarification!
