### ISSUE TITLE
Border customization

### ISSUE THREAD

**Issue by Srijan619** [rivo/tview#1065]
Hi,

Quiet new here, I am trying to understand how to style border of primitive (flex or textview)? Or is it even possible to have like border radius, or even just the width of the border customizable?

The default border looks like a double border when focus is set to the element.

<img width="440" alt="image" src="https://github.com/user-attachments/assets/4af19eaa-4d06-4aa0-8b10-44f838939c44" />

**Comment by ayn2op** [comment]
https://pkg.go.dev/github.com/rivo/tview#Borders

**Comment by Srijan619** [comment]
Thanks.. This was helpful.
