### ISSUE TITLE
Example for gif shown on ReadMe

### ISSUE THREAD

**Issue by murphy214** [rivo/tview#107]
Hello, 

I was reading through the documentation / demos and couldn't find the application shown in the gif on the read me I realize a lot of the demos or examples are components themselves but I kind of wanted to see how all the apis work from a top level so I could have something to go from.

I realize I should probably just dive deeper into the documentation but it would be nice to have one or two examples where higher level features interface with primitives like a table within a grid or flex table, rather than simply showing how to instance a grid or flex table. 

It could already exist somewhere but the demo png or image wasn't what I was expecting so apologies in advance if so. 

Thanks in advance

**Comment by biax** [comment]
Hi I'm trying to get the presentation example to work

I get a lot of undefined errors. Sorry I'm new in go and am trying to use the presentation to learn.

**Comment by rivo** [comment]
I'm not sure what you do and you're not providing any error message so I'm not sure I can help. `go run demos/presentation/*.go` should start the presentation.

**Comment by biax** [comment]
"go run ." Came across that eventually, should be similar to yours.

Do you know of anything written on github that use tview module? Especially an oldschool style menu-based program. Would like to use that for learning.

**Comment by rivo** [comment]
I would assume most users who write issues here are using it for their projects. Some have posted screenshots in the past. I haven't been tracking its use but if you happen to make a list of popular projects that use `tview`, post it here. I might even  include it in the project README.

**Comment by Bios-Marcel** [comment]
@rivo Could just make a list and let people PR their projects in

**Comment by biax** [comment]
@rivo You're quite on point. The presentation does appeal in visual demonstration but lacks the structure of a typical oldschool[menu] program, which I'm hoping to study. I am reasonable in scripting but have recently found the need to learn a proper language, so what better than go-lang coupled with tview, which does seem to at least make the TUI portion a lot easier.

(BTW, no tabs?)

Is there a tview community anywhere? Say discord | slack or similar? I don't want to litter github with issues that aren't exactly issues but more like questions.

**Comment by biax** [comment]
https://github.com/rivo/tview/network/dependents

It's hard for me to believe that there are no projects that depends on tview.
