### ISSUE TITLE
Feature: make the terminal hyperlink support

### ISSUE THREAD

**Issue by stephencheng** [rivo/tview#108]
I am referring to: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

When user use below command in terminal:
echo -e '\e]8;;http://example.com\aThis is a link\e]8;;\a'

In my case, I could get the link in iterm2/terminal app.

This link could be use in textview/title/table colum

**Comment by rivo** [comment]
For this to work in `tview`, [`tcell`](https://github.com/gdamore/tcell) would have to support it first. `tview` does not write escape sequences to the terminal directly but uses `tcell`'s screen buffer. You could open an issue there but I'm not sure if it will get added. Seems like a larger addition to `tcell` to me.
