### ISSUE TITLE
Add support for ASCII trees

### ISSUE THREAD

**Issue by dastergon** [rivo/tview#109]
It would be great if there was a widget that wraps the [treeprint package](https://github.com/xlab/treeprint) and allows nested lists in a tree-like form that can be traversable from the keyboard. Bonus: The ascii tree can have the ability to collapse/shrink the sub-lists.

Example:
```
.
├── item1
│   ├── sub-item1
│   ├── sub-item2
│   ├── sub-item3
```

**Comment by rivo** [comment]
This doesn't seem too difficult to do. The `treeprint` package appears to give you a string with the tree in it which you could easily write to a `TextView` (e.g. using `textView.SetText()`).

Using `TextView` regions, you could highlight each item and in combination with `SetInputCapture()`, you could implement collapse/expand functionality.

I don't see this as a standard class in `tview` but it doesn't look hard to connect the two packages. So if you need it in your own application, it shouldn't be too much of an effort.

**Comment by dastergon** [comment]
Hi @rivo, 

Thanks for the clarifications, I will attempt to implement this myself. Does TextView support pagination for large texts? Also, is search feasible within the TextView?

**Comment by rivo** [comment]
[`GetRegionText()`](https://godoc.org/github.com/rivo/tview#TextView.GetRegionText) should do what you're looking for.

For a list of currently highlighted regions, see [`GetHighlights()`](https://godoc.org/github.com/rivo/tview#TextView.GetHighlights).

**Comment by dastergon** [comment]
Hi @rivo, I checked those functions, but I am unable to work with nested regions `["0a"]["0b"]something[""]`. GetHighlights() only recognises the latter `["0b"]`. Did I miss anything, or should I open an issue for that?

**Comment by rivo** [comment]
I'm not sure I understand exactly what you are expecting. Regions are not nested. If you start a new region, it automatically ends the previous region. And the special `[""]` only ends the current region, without starting a new one.

Does this clarify it?
