### ISSUE TITLE
Feature Request: Add SetTextFlag() method

### ISSUE THREAD

**Issue by dtoubelis** [rivo/tview#111]
We are working on a TUI application that supposed to run on linux console. We discovered that  `gdamore/tcell` library strictly adheres to terminal definitions on linux and only supports 8 colors by compressing 16 colors into 8 if necessary (for instance `ColorYellow` would become `ColorOlive` on linux console). I talked to Garrett about this [here](https://github.com/gdamore/tcell/issues/217) and I think this is actually desirable behavior.

This said, using all 16 colors can easily be achieved by using `bold` flag on most terminals. We actually currently use a workaround as follows for this:

```go
table.SetCell(row, 0,
    tview.NewTableCell("[::b]URL:[::-]").
    SetTextColor(tcell.ColorGrey).
    SetAlign(tview.AlignRight))
```

So, would it be possible to add method for setting text flags on the cell in addition to color that the code above would become more like this:

```go
table.SetCell(row, 0,
    tview.NewTableCell("URL:").
    SetTextColor(tcell.ColorGrey).
    SetTextFlags(Bold|Blink).
    SetAlign(tview.AlignRight))
```

**Comment by rivo** [comment]
Yeah, makes sense. I added `SetAttributes()` and `SetStyle()` (as a shortcut to the three individual functions).
