### ISSUE TITLE
Dropdowns -- selected func called twice

### ISSUE THREAD

**Issue by hoop33** [rivo/tview#115]
When you select an item in the dropdown, the `selected` func runs twice. First, the wrapped `list` runs it:

https://github.com/rivo/tview/blob/master/list.go#L301

And then the `dropdown` handler runs it:

https://github.com/rivo/tview/blob/master/dropdown.go#L365

I would guess that deferring to the list's call would be fine, and that the dropdown's "Trigger selected event" block could be removed. I can submit a PR.

Thanks for this library!

**Comment by hoop33** [comment]
Actually, removing the call from `dropdown` would cause an issue if the `selected` func changes focus -- the call from `list` would change the focus, and then `dropdown` changes it back ( https://github.com/rivo/tview/blob/master/dropdown.go#L360 ), so it looks like the fix isn't simply to remove that call.

**Comment by rivo** [comment]
Thank you for spotting this. I actually removed the per-item `List` callback to resolve this. I couldn't find any issue with this solution but if this doesn't work for you, let me know.

**Comment by hoop33** [comment]
Ah -- much cleaner solution. Thanks!
