### ISSUE TITLE
Horizontal border is kind of weird 

### ISSUE THREAD

**Issue by zyuyou** [rivo/tview#118]
System: macOS 10.13.4
go version go1.10.2 darwin/amd64
Terminal: iterm3
Terminal font: Menlo (Actually same as other, also on Windows and Linux)

```go
app := tview.NewApplication()

table := xapp.NewDefaultTable("Name", "Desc", "Subversion")

table.AddRow("row1_name", "row1_desc", "row1_subversion")
table.AddRow("row2_name", "row2_desc", "row2_subversion")
table.AddRow("row3_name", "row3_desc", "row3_subversion")

table.Select(0, 0).SetFixed(1, 1).SetDoneFunc(func(key tcell.Key) {
	if key == tcell.KeyEscape {
		app.Stop()
	}
	if key == tcell.KeyEnter {
		table.SetSelectable(true, false)
	}
}).SetSelectedFunc(func(row int, column int) {
	table.GetCell(row, column).SetTextColor(tcell.ColorRed)
	table.SetSelectable(false, false)
})

table.SetBorders(true)
table.SetRect(1, 1, 100, 20)

if err := app.SetRoot(table, true).Run(); err != nil {
	panic(err)
}
```

![image](https://user-images.githubusercontent.com/1913492/40270037-3dcd86b0-5bb9-11e8-9f88-7208542cbe24.png)

**Comment by rivo** [comment]
You closed this yourself. Did you find the cause of the problem?

There was an issue similar to this one: #66. Are they related?

**Comment by rivo** [comment]
Thanks for the feedback!

**Comment by sisyphsu** [comment]
Copy from [gdamore/tcell#203](https://github.com/gdamore/tcell/issues/203)

Another solution, you can force `runewidth` to return 1 for normal symbols, like '-':
```golang
import "github.com/mattn/go-runewidth"

func main() {
    runewidth.DefaultCondition.EastAsianWidth = false
}
```

Other unicode word will still be 2, like '中'.
