### ISSUE TITLE
Question: Is there a way to set a fixed width to table columns?

### ISSUE THREAD

**Issue by 3cb** [rivo/tview#119]
I'm trying to use tview to display streaming price data from websockets in a table and the text strings have variable length which makes the columns shift back and forth when I update and redraw the table.  Is there a way to fix this without manually adding empty spaces to the text strings on each update?

Apologies if I have missed it in the documentation.

**Comment by rivo** [comment]
You haven't missed it. There's no fixed width parameter for table columns at the moment. I know this is what you're trying to avoid but you could do the following to pad your strings:

```go
cell.SetText(fmt.Sprintf("%-10s",mystr))
```

**Comment by 3cb** [comment]
Thanks for the info and the library.
