### ISSUE TITLE
Support for colors via rgb

### ISSUE THREAD

**Issue by tj** [rivo/tview#12]
Awesome project! This is exactly what I had intended on building and never got around to hahah, so thanks :D 

It might be cool to support something like https://github.com/aybabtme/rgbterm for colors, you just pass a regular `rgb()` (or could be hex etc) and it approximates it for you—the tcell stuff is a little awkward in comparison.

Happy to PR if it's something you'd be interested in.

**Comment by rivo** [comment]
Thanks. Let me look into this. Will get back to you.

**Comment by rivo** [comment]
The referenced commit is for RGB color tags in `TextView`.

To specify RGB colors in other places, `tcell` provides the functions you need. Please see [GetColor()](https://godoc.org/github.com/gdamore/tcell#GetColor), [NewHexColor()](https://godoc.org/github.com/gdamore/tcell#NewHexColor), and [NewRGBColor()](https://godoc.org/github.com/gdamore/tcell#NewRGBColor).
