### ISSUE TITLE
Idea of table cell blink?

### ISSUE THREAD

**Issue by stephencheng** [rivo/tview#120]
Just wonder if there is decent way of make an animation of blinking cell when the content of the cell is updated to a different value, could this be a feature or I will have to implement it myself?

What I can think of are something like:

1. use a data model, eg two dimension array
2. when new data arrives, compare the differences of data and keep the record of location Loc(i,j)
3. update the only cells with some sort of style, eg, background color or yellow, put a delay of 200 ms, then update the new value and remove the background color(if needed)

Any suggestion?

Thanks

**Comment by rivo** [comment]
This depends heavily on your application and when/how you are putting data into the table. At some point, you are changing the contents of a cell. You could then compare the new content with the old content and, if the contents differ, start a goroutine which changes the background color back after some delay.

Note that while `Application.Draw()` is thread-safe, the functions of `TableCell` are not. So you may want to use a `sync.Mutex` to coordinate your goroutines.

Of course, if you're updating many table cells at once, the logic would have to be slightly different, so as not to call `Draw()` many times after each other.

**Comment by stephencheng** [comment]
Thanks for your suggestion. That's what I thought too.
