### ISSUE TITLE
Feature: hidden cell for table

### ISSUE THREAD

**Issue by stephencheng** [rivo/tview#121]
Not sure if this is a good idea. 

Sometimes, just for the sake of convenience, it might be good to leave some meta data in the table cell for the later access, but these meta data wouldn't be useful visually for user.

So, I am expecting if there is a way:
1. either we could mark the cell to be an invisible cell,
2. or we could use a separate method other than SetText to just leave the value into table's buffered data and have a method to get access this value using the associated Location: row, col.

I understand that this could be managed as long as I leave a buffered two dimension array there to mirror with the table, but I feel that it's convenient that I could throw the data to the table and forget about it. The access entry would be normally from the selected event, it is just easy to associate the event with the particular row and underneath data.

Thanks

**Comment by rivo** [comment]
How about setting the cell's text color to [`tcell.ColorDefault`](https://godoc.org/github.com/gdamore/tcell#Color)? I haven't tried this myself yet but theoretically, it should make your text invisible.

**Comment by stephencheng** [comment]
Setting both Bg color and Fg color to the same does not make it invisible. I made it less visible by setting the MaxWidth to 1.

Thanks for the idea.
