### ISSUE TITLE
Feature: Borders like Styles

### ISSUE THREAD

**Issue by benweidig** [rivo/tview#123]
Hi,

great library!

I would like to change the rune used for borders, similiar to the Styles in style.go

As a precursor I fixed a mixup in box.go and added comments with the unicode to the current constants #126  

If you think it's a good idea to have a `var Borders` like `var Styles` I could prepare another pull request with the feature, defaulting to the current border runes.

**Comment by benweidig** [comment]
After starting with this feature I realised that just replacing border runes isn't enough to support all widgets/features.

Instead it looks like I'm going refactor all the semigraphics stuff from utils.go to its own space, and add a border/joints logic on top of it.

**Comment by rivo** [comment]
I'm closing this now as I just merged #126.
