### ISSUE TITLE
Feature request: Methods to manually get/set TextView.lineOffset

### ISSUE THREAD

**Issue by albertito** [rivo/tview#124]
Hi!

I am using TextView to implement a "less with links", using regions and highlights, as part of a bigger application.

One think I keep running into is that I'd like to be able to manually get and set the lineOffset, so I can control the position from my application based on external input (and not only user's key movements).

This would also allow me to implement some usability tweaks (such as when the user presses "tab", I can highlight the next _viewable_ region).

Do you think this would be reasonable?

Thanks!

**Comment by rivo** [comment]
I added `ScrollTo()` to the `TextView` primitive. Could you have a look and let me know if this works for you?

**Comment by albertito** [comment]
Thanks for implementing that!

It helps, but what do you think about adding a method like GetPosition to get the current row?

I think the two combined would let me implement the behaviour I am after.
Of course, I'm happy to send patches!

Thanks!

**Comment by rivo** [comment]
You mean you need a function that returns the current scroll position? Like `GetScrollOffset()`?

**Comment by rivo** [comment]
I just added that function. See [`GetScrollOffset()`](https://godoc.org/github.com/rivo/tview#TextView.GetScrollOffset).
