### ISSUE TITLE
Changing Flex proportions

### ISSUE THREAD

**Issue by benweidig** [rivo/tview#125]
Hi,

in my app I want to change the Flex proprotions with the keyboard. So far I need to rebuild the complete Flex with the new proportion, because the flexItem array is private.

First I thought about just building a modified Flex exposing the necessary fields, but Box doesn't expose focus, so I needed to copy/paste Box, too.

What are your opinions on how to solve this? Rebuild the Flex every time, or extend Flex to expose the flexItem array in a non-breaking way? Or did I miss something?

**Comment by rivo** [comment]
Sorry for the late reply. You didn't miss something, it didn't exist. I've added a new function `ResizeItem()` to `Flex` which should do what you're trying to do. Let me know if this works for you.

**Comment by benweidig** [comment]
Thx for the update, but the code isn't working as intended.

The `item` provided by `range` is not pass-by-reference, it's pass-by-value. Only accessing an array by index is pass-by-reference. And to save it in a new variable we need to access it with `&`.

Proposed fix:
```go
func (f *Flex) ResizeItem(p Primitive, fixedSize, proportion int) *Flex {
	for idx := range f.items {
		item := &f.items[idx]
		if item.Item == p {
			item.FixedSize = fixedSize
			item.Proportion = proportion
		}
	}
	return f
}
```

**Comment by rivo** [comment]
Good point. Actually, I think the `items` slice should be a slice of `*flexItem`'s anyway. (Not sure why I didn't do it this way but this was one of the very early types so maybe it grew over time.)

The latest commit should have fixed it. Please let me know if it works for you now.
