### ISSUE TITLE
Question: how do you debug the tview application?

### ISSUE THREAD

**Issue by gagranov** [rivo/tview#129]
I use Windows 10
When I run the binary in the "cmd" window - everything works great!
But when I tried to debug in Visual Code or Lite IDE - i do not see the UI at all :(

Which IDE supports tview and how do you configure it?

Thanks,
Gennady

**Comment by rivo** [comment]
HI Gennady, this is more of a `tcell` issue which `tview` uses. I would suggest that you post your question over on [`tcell`'s issue tracker](https://github.com/gdamore/tcell/issues).

**Comment by gagranov** [comment]
Thanks!
