### ISSUE TITLE
Multiline text in a Table or List get crazy

### ISSUE THREAD

**Issue by KyleBanks** [rivo/tview#130]
Here's a sample program that demonstrates the issue. Basically the `Table` contains a number of default `TableCell` with a multiline string:

```
package main

import (
	"github.com/rivo/tview"
)

const lorem = `Lorem 
ipsum 
dolor 
sit 
amet, 
consetetur 
sadipscing 
elitr,
sed 
diam 
nonumy 
eirmod 
tempor 
invidunt 
ut 
labore 
et 
dolore 
magna 
aliquyam 
erat, 
sed 
diam 
voluptua.`

func main() {
	table := tview.NewTable().
		SetSelectable(true, true)

	for r := 0; r < 50; r++ {
		table.SetCell(r, 0, tview.NewTableCell(lorem))
	}

	app := tview.NewApplication()
	if err := app.SetRoot(table, true).Run(); err != nil {
		panic(err)
	}
}
```

And here are the results when the application starts, and after moving around with the up and down arrows a few times:

<img width="1440" alt="screen shot 2018-06-07 at 8 02 19 pm" src="https://user-images.githubusercontent.com/2164691/41132259-0e08f354-6a8e-11e8-98c8-3f1533632db9.png">

<img width="1440" alt="screen shot 2018-06-07 at 8 02 26 pm" src="https://user-images.githubusercontent.com/2164691/41132260-0e1ab684-6a8e-11e8-93de-47cb71f0009c.png">

**Go Version**: 1.10.2
**OS**: macOS v10.13.2
**Terminal Version**: 2.8

**Comment by rivo** [comment]
Thanks for spotting this. I just rolled out a fix.

Please note that `Table` cells can never contain multi-line text. The content of a table row is only one row on the screen. If you need a table-like structure that is more complex, you'll need to use `Grid`.

**Comment by KyleBanks** [comment]
Awesome, thanks for the quick turnaround. I ended up switching to a large
TextView with regions and managing scrolling and selection myself, but I'll
test this out.
