### ISSUE TITLE
Feature request: Hyperlink support

### ISSUE THREAD

**Issue by lixin9311** [rivo/tview#132]
A lot of modern terminal emulators have supported the hyperlink feature (FYI: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda)
But somehow it's broken when using tview.

**Comment by stephencheng** [comment]
@lixin9311 I raised a similar request before, please see my post for this one

**Comment by rivo** [comment]
I was going to say the same. Please have a look at #108.
