### ISSUE TITLE
Bug: Suspend() doesn't work from goroutine

### ISSUE THREAD

**Issue by kvj** [rivo/tview#134]
I'm trying to get user input using `fmt.Scanf()` by temporarily suspending tview/tcell application and later resuming it. If `Suspend()` is called from same thread with `Run()`/`KeyboardInterceptor()` - everything works, I can get user input, but application hangs (`Run()` finishes) when goroutine is used. Following sample code demonstrates the issue:

```golang
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

func doInput(app *tview.Application) {
	app.Suspend(func() {
		fmt.Printf("Input something: ")
		var code string
		if _, err := fmt.Scan(&code); err != nil {
			log.Fatalf("Unable to read authorization code %v", err)
		}
		fmt.Printf("\r\nInput: %s\r\n", code)
	})
}

func main() {
	os.Setenv("TERM", "xterm-256color")
	box := tview.NewBox().SetBorder(true).SetTitle("Hello, world!")
	app := tview.NewApplication()
	pages := tview.NewPages()
	pages.AddPage("grid", box, true, true)
	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		switch event.Key() {
		case tcell.KeyCtrlR:
			doInput(app)
		default:
			return event
		}
		return event
	})
	if err := app.SetRoot(pages, true).Run(); err != nil {
		panic(err)
	}
}
```
If I call `doInput(app)` - everything is OK, but when I change it to `go doInput(app)` - application hangs

**Comment by kvj** [comment]
I believe there's an issue with mutex `Lock()`/`Unlock()` calls, event loop is terminated here: https://github.com/rivo/tview/blob/master/application.go#L113

**Comment by rivo** [comment]
I've merged your PR so this issue is closed now.
