### ISSUE TITLE
We want FormItem to implement RemoveItem() so that we can remove input fields from a Form element. like how you can remove a primitive from a Flex or Grid object. 

### ISSUE THREAD

**Issue by melt7777** [rivo/tview#137]
We want FormItem to implement RemoveItem() so that we can remove input fields from a Form element. like how you can remove a primitive from a Flex or Grid object. 

Rationale: We want to use the FormItem Checkbox's callback function to add/remove other FormItem InputField elements on the Form based on IsChecked. Also, we notice that the IsChecked does not work on a Checkbox that is a FormItem. Is there a way to expose the functions that are part of the various Primitives even in their FormItem instance? 

I see in https://github.com/rivo/tview/blob/master/form.go#L243 where we are using the items[] to store the items in the Form. 

Until this could be done, I am thinking of a workaround:  Manipulating Form.index[] directly. Do you think this is viable?

Many thanks!

melt
getpimp.org dev team

**Comment by rivo** [comment]
I can certainly give you a `RemoveFormItem()` function but it will be part of the `Form` class. The `FormItem` elements themselves don't keep a reference to their containing `Form` (and I believe they shouldn't) so you'll have to call `RemoveFormItem()` on the form itself. Would that work for you?

I'm not sure what you mean by `Form.index[]`. There is `Form.items` but you won't have access to it from outside the package.

Also, you mentioned that `IsChecked()` does not work. I'm not sure why it wouldn't. Can you give a short example for this?

**Comment by melt7777** [comment]
Yes, that would be great, just like we use var to declare the App and Flex objects to refer to them later, I can refer to, say, form.RemoveFormItem("Name:") to remove items. 

Sorry, I meant items[] not index[]. Alright, that workaround won't work. 

Essentially the reason for this is: I want to have a form with some InputFields, then a CheckBox, then some more InputFields. But I want to have a callback function that only shows the bottom group of fields when the CheckBox is not checked. Example:

Use DHCP: [ ]   // when the box is not checked, show form elements 6,7,8, like:

Static IP: 
....


Thank you very much for your great project. We hope to use it to make our applications very easy to use. 
Let me know if additional information or explanation would help you with this feature.

**Comment by rivo** [comment]
Please check out the latest version. To remove an item, you can now do the following:

```go
form.RemoveFormItem(form.GetFormItemIndex("Name:"))
```

Let me know if this helps you with your application.

**Comment by melt7777** [comment]
This works exactly as we needed. Thank you very much!
