### ISSUE TITLE
Replace all instances of ANSII

### ISSUE THREAD

**Issue by ardnew** [rivo/tview#138]
While I do admire your consistency -- you do not waver from the spelling _anywhere_ -- I'm afraid you are using a misnomer throughout the documentation and API. I think you mean to use `ANSI` ([wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code)) instead of `ANSII` ([wikipedia](https://en.wikipedia.org/wiki/ANSII))

At first I thought you might have meant `ASCII`, but then saw the class is designed to handle e.g. color escape sequences, among other things that `ASCII` doesn't define.

Was there some other reason you chose to use the term `ANSII`? If not, I would recommend replacing all occurrences with the correct term `ANSI`

Thanks for your time, I'm loving tview so far

**Comment by rivo** [comment]
Ha! You're absolutely right! I mean `ANSI` but I guess in my head, I always confused the spelling with `ASCII` and never noticed it. This definitely needs to be fixed.

I can change it or, if you need it more quickly, feel free to submit a pull request that fixes the spelling (in the filename, too, obviously).

**Comment by rivo** [comment]
Just merged the PR. Thanks, I appreciate you spotting and resolving this!
