### ISSUE TITLE
data races/synchronization

### ISSUE THREAD

**Issue by 3cb** [rivo/tview#145]
I'm having trouble synchronizing updates to Primitives and was hoping someone might be able to point me in the right direction.

My goal is to stream websocket data into multiple `Table` primitives which are displayed one at a time.  I'm using a `List` to switch between the Tables by adding and removing items from a `Flex`.  Main.go gives a general idea of what I'm trying to do([https://github.com/3cb/cq/blob/master/main.go](url))

I think the events triggered by the `List` primitive are conflicting with the updates done in the goroutine's select block and don't know the simplest solution.

**Comment by rivo** [comment]
Without having run your code myself, I'm guessing that by pressing on a list item, you sometimes don't see the table change, correct? I believe this is because the activation of a list item causes `app.Draw()` to be called immediately afterwards but your handling of that event happens in a separate goroutine. Most of the time, your goroutine will finish after `app.Draw()` has already been called. (Worst case, it messes up the execution of `app.Draw()` midway.)

There are probably multiple ways to solve this. I would suggest that you make the `selected` callback of the `AddItem()` function wait for the goroutine to finish processing the event. Something like this:

```go
done := make(chan struct{})
// ...
list.AddItem("Overview", "", '1', func() {
	view <- overviewTbl
	<- done
})
// ...
case tbl := <-view:
	// ...
	done <- struct{}{}
```

Let me know if this helps.

**Comment by rivo** [comment]
Will reopen if there is still an open issue here.

**Comment by 3cb** [comment]
I was a few commits behind.  I think [this commit](https://github.com/rivo/tview/commit/cc64ead1ed59123faf6d6f37ae2aa1a51e4af4fe) eliminated part of the problem:
https://gist.github.com/3cb/9b847cebe16f363a232ce18b65b0c00d

The first four listed seem to be due to updating the `Table` primitive directly in a separate goroutine before `app.Draw()` is called:
```go
// direclty update instances of Table
upd.UpdOverviewRow(overviewTbl)
upd.UpdRow(gdaxTbl)
app.Draw()
```
As I mentioned in the previous post the options I see are:
1. Add mutexes to primitives
2. Use `app.SetInputCapture()` to intercept key events and handle updates to `List` primitive in my own code

The last race listed is interesting because `app.Run()` seems to be conflicting with `app.Draw()`:
```
==================
WARNING: DATA RACE
Read at 0x00c4201df880 by goroutine 178:
  github.com/rivo/tview.(*List).Draw()
      /home/marc/go/src/github.com/rivo/tview/list.go:225 +0x2e0
  github.com/rivo/tview.(*Flex).Draw()
      /home/marc/go/src/github.com/rivo/tview/flex.go:173 +0x728
  github.com/rivo/tview.(*Application).Draw()
      /home/marc/go/src/github.com/rivo/tview/application.go:259 +0x160
  main.main.func6()
      /home/marc/go/src/github.com/3cb/cq/main.go:72 +0x4c1

Previous write at 0x00c4201df880 by main goroutine:
  github.com/rivo/tview.(*List).InputHandler.func1()
      /home/marc/go/src/github.com/rivo/tview/list.go:287 +0xeb
  github.com/rivo/tview.(*Box).WrapInputHandler.func1()
      /home/marc/go/src/github.com/rivo/tview/box.go:152 +0xa6
  github.com/rivo/tview.(*Application).Run()
      /home/marc/go/src/github.com/rivo/tview/application.go:146 +0x467
  main.main()
      /home/marc/go/src/github.com/3cb/cq/main.go:89 +0x1322

Goroutine 178 (running) created at:
  main.main()
      /home/marc/go/src/github.com/3cb/cq/main.go:64 +0x12e5
==================
```
The two options above would also solve this I think but I could be missing something easier.  What are your thoughts?

**Comment by 3cb** [comment]
@rivo I just got back to this.  I went ahead and added mutexes to the primitives I was using (`Table` and `List`) as well as `TableCell` to correct the data races.  Any interest in adding this to all primitives to make synchronization easier?

**Comment by rivo** [comment]
I started adding mutexes to these classes myself (I think I'd go for a slightly different solution than in your PR) but then stopped halfway. It adds a lot of boilerplate code to almost all functions throughout the package and I'm not sure it's worth it. In the applications I wrote myself using `tview`, it was never needed.

At the moment I'm considering putting a disclaimer into the package description itself that using the functions of the package in multiple goroutines will require outside synchronization.

So I'm a bit torn now. Which is to say that I haven't made up my mind yet.

What would it take for you to synchronize access to these objects in your application? Do you know any popular Go packages I could look at, that ensure thread-safety for all getters and setters (and other functions) in all objects?

**Comment by 3cb** [comment]
I actually haven't submitted a PR.  I think you got mixed up with @joegrasse and his PR.  Although we are both having problems syncing changes to `Table` it seems.

For my application, all I did was add mutexes and then only updated the methods I use with lock/unlock; I haven't bothered with unused methods so I understand your hesitation to add all that code.

An alternative that I was thinking about is to add a channel to `Application` typed as an `Updater` interface that would allow the user to inject updates to primitives into the event loop.  What do you think about that?

**Comment by rivo** [comment]
Oops, right. I didn't realize that. I'll post this in the other thread, then.

I'm not so familiar with the `Updater` interface. If you know a package that implements something like that, maybe you can point me to it?
