### ISSUE TITLE
Placeholder in LICENSE.txt file

### ISSUE THREAD

**Issue by kdzlvaids** [rivo/tview#149]
Hi,

I recognised that your LICENSE.txt file still have a placeholder.

I am trying to package tview into Debian, and I need an copyright information about this library.
Would you please fill it out?

Thanks a lot of your useful library!

**Comment by rivo** [comment]
Thanks. Did not realize that. I added my name to it.

Maybe a dumb question but I've ever only installed Debian packages of binaries. How does it work with source code libraries like `tview`? Would `apt-get install tview` install the source code in some standard directory?

**Comment by kdzlvaids** [comment]
Thank you for your fix!

As you know, since Go does not yet have features such as shared libraries linking, the source code of the library will be stored in `/usr/share/gocode/src/` when you install the package. The location is documented at the File Locations in [1].

In fact, as following the Naming Conventions in [1], the package name is `golang-github-rivo-tview`.

Thanks a lot again!

[1] [Debian Go Packaging - Debian Go Packaging Team](https://go-team.pages.debian.net/packaging.html)
