### ISSUE TITLE
Escape key on modals not working

### ISSUE THREAD

**Issue by SamWhited** [rivo/tview#150]
The documentation for a the modal `SetDoneFunc` method says:

>  SetDoneFunc sets a handler which is called when one of the buttons was pressed. It receives the index of the button as well as its label text. The handler is also called when the user presses the Escape key. The index will then be negative and the label text an emptry string. 

However, if escape is pressed on a modal the handler is never fired and there does not appear to be any event handler for the escape key in `modal.go`.

**Comment by rivo** [comment]
Just merged your PR. Thanks for spotting this.
