### ISSUE TITLE
feature request: list.RemoveItem

### ISSUE THREAD

**Issue by SamWhited** [rivo/tview#158]
Right now there is no way to remove an item from a list without clearing the list and re-adding everything. It would be nice to have a method to remove an item, probably something like:

```
func (l *List) RemoveItem(index int) *List
```

**Comment by SamWhited** [comment]
I started to implement this in case the request was accepted, but it occurred to me that there's non real way to track where an item ends up, or a way to sort lists, so it may be that the list view just doesn't work well for anything that's not append-only. Maybe it needs more work, or isn't the appropriate view for this.

**Comment by rivo** [comment]
You're right, `List` currently lacks these functions. It should have them and I'll add them in the next few days. I'll update this issue when it's done.

**Comment by rivo** [comment]
Apologies for getting back to you so late. This function is now part of `List`. Let me know in case there's anything else you need.
