### ISSUE TITLE
Proposal: RunWithScreen()

### ISSUE THREAD

**Issue by progrium** [rivo/tview#159]
Creating a custom tcell.Screen is the only way to get these types of systems to work over non-stdio environments (like SSH), but tview doesn't allow you any control over the screen it uses. I'm going to fork and patch for my uses but I'd like to submit a PR to fix this so I'd like to discuss the API.

I figure the easiest thing is to provide an alternative Application.Run that takes a tcell.Screen, perhaps like `RunWithScreen(screen tcell.Screen)`.

**Comment by rivo** [comment]
I've added the `SetScreen()` function to `Application`. I think this should help you achieve what you want to do.

Please note that it there may be issues if you use `Application.Suspend()`. If you really need to use `Suspend()`, I might have to think about a different solution.

Let me know if this works for you.

**Comment by progrium** [comment]
Nice, thank you! This should work perfectly.
