### ISSUE TITLE
Cooperate with Vim

### ISSUE THREAD

**Issue by JesseAldridge** [rivo/tview#164]
Hi, I'm using tview to build a shared note-taking tool: https://github.com/JesseAldridge/dentist
I'm wondering if it's possible to get tview to work well with Vim.
Below is a test script. Vim gets launched successfully but the input seems to be conflicting with tview somehow and it doesn't work well.

I'm new to Go and tview so maybe I'm doing something wrong.

```
package main

import (
	"os"
	"os/exec"

	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

func write_and_open(note_name string) {
	cmd := exec.Command("vim", note_name)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Run()
}

func main() {
	app := tview.NewApplication()

	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		k := event.Key()
		if k == tcell.KeyEnter {
			write_and_open("test name")
		}
		return event
	})

	box := tview.NewBox().SetBorder(true).SetTitle("Hello, world!")
	if err := app.SetRoot(input_field, true).Run(); err != nil {
		panic(err)
	}
}
```

**Comment by JesseAldridge** [comment]
Actually, looks like I just need to wrap the vim call with `Stop` and `Run`:

```
		if k == tcell.KeyEnter {
			app.Stop()
			write_and_open("test name")
			app.Run()
		}
```

**Comment by rivo** [comment]
I know you closed this already but while `Stop()` and `Run()` should probably work, there is a function dedicated to these kind of situations: [`Suspend()`](https://godoc.org/github.com/rivo/tview#Application.Suspend).

I thought this may be useful to you.

**Comment by JesseAldridge** [comment]
Oh cool.  Thanks for letting me know.

**Comment by JesseAldridge** [comment]
Actually I'm still seeing some odd behavior.  Everything works well when I use `vim` as the editor. But if I use `subl` instead, after I finish editing the file and come back to the terminal my next keystroke seems to get dropped.

In the demo below I run the script, hit return to open sublime, close the text file, select the terminal, press return again (nothing happens), press return again (sublime opens again). I get similar behavior if I use `subl -w` instead of `subl`.

`subl` is configured like so: https://www.sublimetext.com/docs/3/osx_command_line.html

Any idea what the issue could be?

```
package main

import (
	"os"
	"os/exec"

	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

func write_and_open(note_name string) {
	cmd := exec.Command("subl", "-w", note_name)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Run()
}

func main() {
	app := tview.NewApplication()

	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		k := event.Key()
		if k == tcell.KeyEnter {
			app.Suspend(func() { write_and_open("test name") })
		}
		return event
	})

	box := tview.NewBox().SetBorder(true).SetTitle("Hello, world!")
	if err := app.SetRoot(box, true).Run(); err != nil {
		panic(err)
	}
}
```

**Comment by JesseAldridge** [comment]
I should probably open a separate issue for this:  https://github.com/rivo/tview/issues/165

**Comment by flowchartsman** [comment]
@JesseAldridge I think your "weird behavior" merits reopening this issue and changing the title or opening a new issue, since  spinning up a temp editor will be a common use-case and I imagine #568 will probably be relatively complicated to implement, so will take longer than digging down on this specific issue and addressing it for the short-term concerns of suspending, opening an external program, and resuming.
