### ISSUE TITLE
Feature Request: modals arrow keys

### ISSUE THREAD

**Issue by porjo** [rivo/tview#167]
Allow left/up + right/down keys to select an option e.g. if the options are 'Cancel' + 'OK', then `↓` or `→` would cycle right and `↑` + `←` would cycle left between the two options.

**Comment by rivo** [comment]
To be sure, you're talking about the [`Modal`](https://godoc.org/github.com/rivo/tview#Modal) class, correct?

**Comment by porjo** [comment]
Yes

**Comment by rivo** [comment]
I've added this with the latest commit.

**Comment by porjo** [comment]
Great, thanks!
