### ISSUE TITLE
Feature Request : Get a `FormItem` typed or add some shortcut on InputField (Ctrl+P)

### ISSUE THREAD

**Issue by joakim-ribier** [rivo/tview#170]
Hi,

I tried to understand how it's possible to get an already typed `FormItem` (example: `InputField`) from `Form`, for to add some shortcuts or to set a text (it what I need), but I did'nt succeed, I think is not possible ?

I read the wiki and the examples but sorry if I missed something...

Thanks to you,

**Comment by joakim-ribier** [comment]
Ok sorry for that, I think I was very tired...

Thanks for your time!

Otherwise awesome library to make text ui app ;-)

**Comment by joegrasse** [comment]
Glad I could help. I am just a user of the library like you :)
