### ISSUE TITLE
Unable to change the background of graphicsColor in treeView

### ISSUE THREAD

**Issue by jantb** [rivo/tview#173]
Hi, it uses the default color of tcell as background.
`lineStyle := tcell.StyleDefault.Foreground(t.graphicsColor)`
can we add a setting for background too?

**Comment by rivo** [comment]
Hi, thanks for letting me know. This was a bug which should now be fixed. The background should be the same as defined with [`Box.SetBackgroundColor()`](https://godoc.org/github.com/rivo/tview#Box.SetBackgroundColor).
