### ISSUE TITLE
Is there a way to delete rows or cells from tables?

### ISSUE THREAD

**Issue by vityavv** [rivo/tview#174]
Trying to remove cells from a table without having to re-make the whole table because I add certain event listeners to it which use scoped variables (so adding those listeners on them inside of a table-making function would mean passing lots of variables to it)

**Comment by rivo** [comment]
I could offer a `RemoveRow()` or a `RemoveColumn()` function. Is that what you would need?

**Comment by rivo** [comment]
I've added those two functions in the latest commit.
