### ISSUE TITLE
inputfield: unable to enter : (colon)

### ISSUE THREAD

**Issue by joegrasse** [rivo/tview#176]
After the 990bc2ebcf815c84073a4fb08c08144808befa7f commit to allow navigation in input fileds, I can no longer enter a colon. I have traced it down to the code starting [here](https://github.com/rivo/tview/blob/990bc2ebcf815c84073a4fb08c08144808befa7f/inputfield.go#L365).

```
			modifiers := event.Modifiers()
			if modifiers == tcell.ModNone {
				ch := string(event.Rune())
				newText := i.text[:i.cursorPos] + ch + i.text[i.cursorPos:]
				if i.accept != nil {
					if !i.accept(newText, event.Rune()) {
						break
					}
				}
				i.text = newText
				i.cursorPos += len(ch)
			} else if modifiers&tcell.ModAlt > 0 {
				// We accept some Alt- key combinations.
				switch event.Rune() {
				case 'a': // Home.
					home()
				case 'e': // End.
					end()
				case 'b': // Move word left.
					moveWordLeft()
				case 'f': // Move word right.
					moveWordRight()
				}
			}
```

I changed it to the following and it works again.

```
			ch := string(event.Rune())
			newText := i.text[:i.cursorPos] + ch + i.text[i.cursorPos:]
			if i.accept != nil {
				if !i.accept(newText, event.Rune()) {
					break
				}
			}
			i.text = newText
			i.cursorPos += len(ch)
```

I suspect the : (colon) key has a modifier in windows.

**Comment by rivo** [comment]
Thanks for letting me know. I couldn't replicate this on my Mac but I made a change that will hopefully fix this for you. If it still doesn't work, let me know.

**Comment by joegrasse** [comment]
That didn't seem to fix it. What fixed it for me after your latest change was adding the following [here](https://github.com/rivo/tview/blob/60a1c63fa9ae3540276aeb26d85b84ac37f713c7/inputfield.go#L398).

```
			} else {
				if !add(event.Rune()) {
					break
				}
			}
```

**Comment by joegrasse** [comment]
@rivo I just created pull request #177 to fix this.

**Comment by rivo** [comment]
It looks like the problem is not the Alt key but some other modifier. So I opted for a slightly different solution. Let me know if it works for you now.

**Comment by joegrasse** [comment]
Yes, it works. Thank you.
