### ISSUE TITLE
advice on editor passthrough (like tmux)

### ISSUE THREAD

**Issue by pomke** [rivo/tview#178]
I'm building a little tool for managing a wiki/collection of markdown documents, I'd like to be able to 'embed' $EDITOR in a view, like tmux does. Any advice on how to approach that would be great.

**Comment by pomke** [comment]
chzyer/temux seems to be an example of how to do this using pkg/term .. question would be how to render inside a tview widget ?

**Comment by rivo** [comment]
Can't find much information on `temux` on their GitHub page so I'm not sure what it is.

`tview` doesn't have a view to embed other applications. I think implementing this would be a major project by itself. It would probably make more sense to have the tools for this one level deeper, in `tcell` but I'm not sure if this is on `tcell`'s roadmap.

There is [`ANSIWriter()`](https://godoc.org/github.com/rivo/tview#ANSIWriter) which can help you when you pipe the output of other processes into `tview`.

And there is [`Application.Suspend()`](https://godoc.org/github.com/rivo/tview#Application.Suspend) which allows you to stop your `tview` application temporarily, to run other processes, and then get back to it.

Both are not exactly what you are looking for but they may help.

**Comment by pomke** [comment]
Thanks for the advice!
