### ISSUE TITLE
Is CTRL+Number supported as a "hot-key"?

### ISSUE THREAD

**Issue by triddell** [rivo/tview#18]
I'm starting to build something similar to your presentation example. On the bottom menu though I'd like to change from screen to screen using CTRL-1, CTRL-2, etc

You are using "tcell.KeyCtrlN" for CTRL-N for example. Do you know if tcell supports something like CTRL-1, CTRL-2, etc? I couldn't find this myself but may it supports combinations in other ways too (hopefully).

**Comment by rivo** [comment]
I'm using `tcell` and at the moment, it doesn't look like you can have something like `Ctrl-1` (see [here](https://godoc.org/github.com/gdamore/tcell#Key)). I'm not sure why, maybe it's something that terminals don't support?

You may want to ask the [tcell](https://github.com/gdamore/tcell) author about this. He has a much better idea of what's possible in this area than I do.
