### ISSUE TITLE
SetInputCapture not working with forms

### ISSUE THREAD

**Issue by dentych** [rivo/tview#181]
Hello.

I don't seem to be able to make SetInputCapture work with forms.

I added a SetInputCapture to the bottom part of the Form primitive demo code.

```go
// Demo code for the Form primitive.
package main

import (
	"fmt"
	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	form := tview.NewForm().
		AddDropDown("Title", []string{"Mr.", "Ms.", "Mrs.", "Dr.", "Prof."}, 0, nil).
		AddInputField("First name", "", 20, nil, nil).
		AddInputField("Last name", "", 20, nil, nil).
		AddCheckbox("Age 18+", false, nil).
		AddPasswordField("Password", "", 10, '*', nil).
		AddButton("Save", nil).
		AddButton("Quit", func() {
			app.Stop()
		})
	form.SetBorder(true).SetTitle("Enter some data").SetTitleAlign(tview.AlignLeft)

        // ADDED THIS METHOD HERE
	form.SetInputCapture(func(e *tcell.EventKey) *tcell.EventKey {
		fmt.Println("TEST OUTPUT")
		return e
	})
        // END OF METHOD

	if err := app.SetRoot(form, true).Run(); err != nil {
		panic(err)
	}
}
```

"TEST OUTPUT" is never printed on the screen. It works fine with for example Lists

**Comment by rivo** [comment]
I'm closing this for now. We can reopen this issue if you'd like to continue the discussion.

**Comment by dentych** [comment]
Oh, sorry. I actually thought I had replied to this issue.

But it is possible to work around this, I just figured that because the method is available on the Form type it should also work as expected. Either that or have the method removed, so people don't get their hopes up 😄

**Comment by rivo** [comment]
I added some clarification to the function comments. I can't remove the function as it is inherited by `Box`.
