### ISSUE TITLE
Bug Fix - SetAcceptanceFunc prevents all key input

### ISSUE THREAD

**Issue by jr81** [rivo/tview#185]
Running demos/inputfield/main.go won't allow any keyboard input. 

I traced the bug from demos/inputfield/main.go:16 SetAcceptanceFunc(tview.InputFieldInteger) 
to inputfield.go:367 where the following change worked for me:

```
367,368c367,368
< 			if i.accept != nil {
< 				return i.accept(newText, r)
---
> 			if i.accept != nil && !i.accept(newText, r) {
> 				return false
```

Thank you for such a beautifully designed and well written library!

**Comment by delaneyj** [comment]
I confirmed this is an issue.

**Comment by rivo** [comment]
Thanks for catching this! Didn't realize that mistake when I made the changes for #103.

**Comment by jr81** [comment]
It's the least I can do, as this is an exceptionally important package,
IMHO. Thank you!  I'm experimenting with a simple HTML to TUI translator
(more TUI than w3m, etc). That way my Web back-end technologies can also
create my CLI tools.
