### ISSUE TITLE
Terminal resize repaints modal multiple times

### ISSUE THREAD

**Issue by andrewuhl** [rivo/tview#19]
Resizing a terminal window draws new modal without clearing the old modal.

- Golang v. 1.9.2
- Affects Windows 7 and Windows 10

![modal](https://user-images.githubusercontent.com/15974852/34900056-dcd198ee-f7ca-11e7-9dc8-a55488285cae.png)

Resizing terminal window also affects other controls, e.g. table. E.g. when table keypress event occurs, the terminal window is permanently resized, requiring user to manually reset window dimensions under terminal properties.

**Comment by rivo** [comment]
Please let me know if my commit fixes what you're seeing. I know it does for the modal example but I'm not 100% sure I understood your second example. If there are still problems, please include some code that illustrates it.

**Comment by andrewuhl** [comment]
Your changes fix related issues I've seen.
