### ISSUE TITLE
Using app.SetInputCapture() to call app.QueueUpdate() could cause deadlock

### ISSUE THREAD

**Issue by 3cb** [rivo/tview#199]
If `Application.QueueUpdate()` is called using `Application.SetInputCapture()` the main event loop will deadlock if the updates channel buffer is already full.  The following example replicates this.  If you hit Ctrl-Q it will freeze:

```go
package main

import (
	"time"

	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

func main() {
	box := tview.NewBox().
		SetBorder(true).
		SetBorderAttributes(tcell.AttrBold).
		SetTitle("A title")

	app := tview.NewApplication()
	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		switch event.Key() {
		case tcell.KeyCtrlQ:
			time.Sleep(3 * time.Second) // allow updates from goroutine to fill updates channel buffer
			app.QueueUpdateDraw(func() {
				box.SetBackgroundColor(tcell.ColorRoyalBlue)
			})
		default:
			return event
		}
		return nil
	})

	go func() {
		count := 1
		t := time.NewTicker(10 * time.Millisecond)
		for {
			<-t.C
			if count%2 == 0 {
				app.QueueUpdateDraw(func() {
					box.SetBackgroundColor(tcell.ColorSeaGreen)
				})
			} else {
				app.QueueUpdateDraw(func() {
					box.SetBackgroundColor(tcell.ColorYellowGreen)
				})
			}
			count++
		}
	}()

	if err := app.SetRoot(box, true).Run(); err != nil {
		panic(err)
	}
}

```

**Comment by rivo** [comment]
I see. Well, the invocation of the `SetInputCapture()` callback is already part of the main event loop. Calling `QueueUpdateDraw()` is not required here. In fact, as you demonstrated, it may even lead to a deadlock. It's kind of already described in the package documentation:

> If your code makes changes in response to key events, it will execute in the main goroutine and thus will not cause any race conditions.

I'll add some more clarification there but I don't think this requires any changes in the code. (Besides, I wouldn't even know how to avoid such a deadlock.)

**Comment by ricochet1k** [comment]
To avoid the deadlock you can check if you are already running in the main loop and just run the update instead of queueing it.

**Comment by rivo** [comment]
Yeah, I guess I could. I'd like to avoid having people call `QueueUpdateDraw()` everywhere, though. It's meant to help you avoid race conditions in some situations. Most programs will not require it. So unless I'm getting lots of issues here where people have trouble understanding the distinction, I'll leave it the way it is. (And if they have trouble understanding it, there may be a different problem to solve.)
