### ISSUE TITLE
"terminal entry not found" error using Termite

### ISSUE THREAD

**Issue by kyoto-shift** [rivo/tview#2]
Running any tview project with Termite gives a "terminal entry not found" error.

I ran the box example: 

```package main

import "github.com/rivo/tview"

func main() {
	box := tview.NewBox().
		SetBorder(true).
		SetTitle("Box Demo")
	if err := tview.NewApplication().SetRoot(box, true).Run(); err != nil {
		panic(err)
	}
}
```
This is the output in Termite:

```
panic: terminal entry not found

goroutine 1 [running]:
main.main()
	/home/shift/dev/go/2proj/main.go:12 +0x22d
exit status 2
```

The project runs fine in other Terminals like XTerm.

**Comment by kyoto-shift** [comment]
Woooops! Turns out it's my fault. I needed to set my terminal to "xterm-256color".

**Comment by rivo** [comment]
Glad you were able to solve it!

**Comment by tidux** [comment]
This is actually not a fix.  `TERM=xterm-termite` is a perfectly valid setting if you have the corresponding terminfo file installed.  Is there some reason tview doesn't use the terminfo database?

**Comment by tidux** [comment]
Looks like that should have been merged recently:

https://github.com/gdamore/tcell/pull/224
