### ISSUE TITLE
Feature request -  add "BackgroundColor" field to TableCell struct

### ISSUE THREAD

**Issue by andrewuhl** [rivo/tview#20]
It would be very nice to be able to set background colors for individual table cells. 

When those (individually colored) cells are selected as part of a highlighted row or column, the current behavior of inverting text and background colors should remain as default behavior. More advanced future behavior might allow for setting all of the following:

- cell text color
- cell background color
- cell selected text color
- cell selected background color

**Comment by rivo** [comment]
Can you provide an example where this could be useful? I'm trying to strike a balance between keeping the package simple and covering common use cases. It would be good to understand where this is needed.

**Comment by andrewuhl** [comment]
In general, having control over cell background coloring allows for better visual contrast. 

Most common use cases that would be immediately useful for me include:

* Column and row headers
* Alternating row colors
* Allows some rows to serve as headers for groups of data (see image below)
* Conditional formatting based on cell value

Controlling text color alone doesn't quite provide the visual contrast needed.

![image](https://user-images.githubusercontent.com/15974852/34907341-1317c3a8-f84b-11e7-9847-fcf5666f0345.png)

Having different text and background colors based on selection state is a nice-to-have but not really that important. But controlling cell background color would be wonderful. 

This is a terrific package, btw. Thanks for all the great work!

**Comment by rivo** [comment]
So I added this. Thank you for your explanation. It will require some people to use the `NewTableCell()` constructor or explicitly define a background color now because `tcell.Color` defaults to black (see #1 for where this would cause issues).

Also, it's quite difficult to make this work with borders. You examples don't have character-wide/high borders but in a terminal, it looks odd when a cell has a background color but the cell borders don't. I implemented a simple solution for now. Might improve this later on.

**Comment by andrewuhl** [comment]
From what I have seen, something like the following should correct at least some of the border issues that come about when using cell background color (not clear what other issues it may cause):

```go
//if cell.BackgroundColor != tcell.ColorDefault && column > 0 {
if (t.rowsSelectable || cell.BackgroundColor != tcell.ColorDefault) && column > 0 {
	leftCell := getCell(row, column-1)
	if leftCell != nil {
		//if cell.BackgroundColor == leftCell.BackgroundColor {
		ch, _, style, _ := screen.GetContent(x+columnX, y+rowY)
		screen.SetContent(x+columnX, y+rowY, ch, nil, style.Background(bgColor))
		//}
	}
}
```

**Comment by rivo** [comment]
I think this causes more problems than before. It includes the left cell border in situations where it shouldn't, in my opinion.

I did make a change for column-only selections, though. Those still looked odd but should be ok now.

If you encounter any situations where it doesn't seem to look correct, you could include a screenshot here or the code which uses the `Table` class.

**Comment by rivo** [comment]
It probably wouldn't be very hard to make it work if there was no space at all between columns. I don't see this as an option, though. It would lead to odd side effects when two neighbouring strings are joined. (And it adds even more complexity to the code.)

Just a slight modification to your code (calling `SetBorders(true)`) illustrates how the situation is much more complex than what can be seen in your screenshots:

![image](https://user-images.githubusercontent.com/480930/35168629-ebce9a56-fd59-11e7-9198-4cc000250552.png)

You can see that the current code joins neighbouring cells' background if they are the same. (Not so with joining horizontal lines.) Here we also have a green cell ("Row 1") and a magenta cell ("-18.44%"), divided by a vertical line. Does the vertical line's background need to be colored? And if so, should it be green or magenta?

Your first example definitely shows an undesired effect so I'm reopening this issue now.

But the solution will require some more thought. I don't see a quick fix here like you suggested.

**Comment by rivo** [comment]
I rewrote the whole background color logic. The new solution should make your examples look like one would expect.

When a table has borders around each cell, it's more difficult because neighbouring cells share the same border so I have to make a tradeoff. But I think the way it is now is the best I can think of.
