### ISSUE TITLE
After init how to set focus in Flex

### ISSUE THREAD

**Issue by delaneyj** [rivo/tview#202]
There appears to be no way to set the focused item in a `Flex` after initialization. I tried adding stuff like

```
func (f *Flex) FocusItem(p Primitive) *Flex {
	for _, item := range f.items {
		item.Focus = item.Item == p
	}
	return f
}
``` but didn't have desired effect

**Comment by rivo** [comment]
I'm not quite sure I understand. (Your code appears to extend this package which confuses me.)

The [`Flex.AddItem()`](https://godoc.org/github.com/rivo/tview#Flex.AddItem) function includes a parameter `focus` which can be set to `true` to give it focus. If you don't know at that time which element should have focus, you can always use [`Application.SetFocus()`](https://godoc.org/github.com/rivo/tview#Application.SetFocus) later and provide your flex item.

Let me know if this clarifies it for you. If not, it would help to see some example code that illustrates your issue.

**Comment by rivo** [comment]
I'll reopen if it turns out this is not yet resolved.
