### ISSUE TITLE
Grid and Flex RemoveItem not removing item

### ISSUE THREAD

**Issue by tc-turner** [rivo/tview#209]
When trying to remove an item from either a Grid or Flex using RemoveItem, nothing happens.

Am I missing something obvious?

Terminal: iTerm2 Build 3.2.6, VSC 1.30.0 built in, Terminal 2.8.2
Go: 1.11.4
tview: f93fbad8f89750bcac42201907aec21d737b394f

```
package main

import (
	"fmt"

	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	var toplevel = tview.NewGrid()
	var nf = tview.NewButton("Button")
	nf.SetBorder(true).SetRect(0, 0, 22, 3)
	toplevel.AddItem(nf, 1, 0, 2, 2, 1, 1, true)
	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		if event.Name() == "Ctrl+V" {
			fmt.Printf(event.Name()) // This happens
			toplevel.RemoveItem(nf)  // This doesn't
                         nf.SetLabel("Nope") // This doesn't
		}
		return event
	})
	if err := app.SetRoot(toplevel, true).SetFocus(nf).Run(); err != nil {
		panic(err)
	}
}
```

![image](https://user-images.githubusercontent.com/16192966/50325242-ad9d4b00-04b1-11e9-8c7d-0c725da23869.png)

**Comment by rivo** [comment]
Your button is removed but the page is not cleared as all that remains is an empty grid with a transparent background colour. See [`NewGrid()`](https://godoc.org/github.com/rivo/tview#NewGrid) for details:

> Note that Box, the superclass of Grid, will have its background color set to transparent so that any grid areas not covered by any primitives will leave their background unchanged. To clear a Grid's background before any items are drawn, set it to the desired color:
>
> `grid.SetBackgroundColor(tview.Styles.PrimitiveBackgroundColor)`

Here's your fixed code:

```go
package main

import (
	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	var toplevel = tview.NewGrid()
	toplevel.SetBackgroundColor(tview.Styles.PrimitiveBackgroundColor)
	var nf = tview.NewButton("Button")
	nf.SetBorder(true)
	toplevel.AddItem(nf, 1, 0, 2, 2, 1, 1, true)
	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		if event.Name() == "Ctrl+V" {
			toplevel.RemoveItem(nf)
		}
		return event
	})
	if err := app.SetRoot(toplevel, true).Run(); err != nil {
		panic(err)
	}
}
```

(I also removed some calls that didn't do anything like `SetRect()` and `SetFocus()`.)
