### ISSUE TITLE
Provide selection info for cell, row or column selection via table.SetSelectedFunc parameters

### ISSUE THREAD

**Issue by andrewuhl** [rivo/tview#21]
For table.SetSelectedFunc, it would be useful to provide as an additional argument whether a full row or column has been selected, rather than having undefined behavior for row index (when a column is selected) or for column index (when a row is selected). E.g. 

SetSelectedFunc(row, column int, selectionState ?)

where selectionState is an enum of three possible states, e.g.:

0: CellSelected = a cell is selected
1: RowSelected = a row is selected
2: ColumnSelected = a column is selected

**Comment by rivo** [comment]
I've added `GetSelectable()` to the `Table` class. This should give you what you're looking for.
