### ISSUE TITLE
How to prevent the app clear the screen?

### ISSUE THREAD

**Issue by ysmood** [rivo/tview#222]
I want to draw the app directly after previous shell prompt like below:

```
$ ./app
  > item
  > item
  > item
```
how to keep the output of the shell?

**Comment by rivo** [comment]
I don't think this is possible. To my knowledge, `tcell` (which `tview` uses) will only use the entire screen and [`tcell.Screen.Init()`](https://godoc.org/github.com/gdamore/tcell#Screen) will clear it before drawing anything.

You may head over to [`tcell`](https://github.com/gdamore/tcell/) to ask if there is any way to limit it to a partial screen. (I don't know of any.)

Let me know if this answers your question.
