### ISSUE TITLE
Treeview's first letter is losted

### ISSUE THREAD

**Issue by bitichonghuihui** [rivo/tview#224]
Hello:
When I run this main.go where path is "github.com/rivo/tview/demos/treeview", I see the folder/file's first letter is losted.

**Comment by rivo** [comment]
This Wiki page has a screenshot with that program's output: https://github.com/rivo/tview/wiki/TreeView

I just tried it again on the latest version (on macOS) and did not see any missing letters. Could you post a screenshot here and also let me know about the OS/terminal you're using?

**Comment by rivo** [comment]
No reply here and I can't reproduce it so I'm closing this. If new information comes up, we can always reopen this issue.
