### ISSUE TITLE
Serial Port Communication

### ISSUE THREAD

**Issue by snmed** [rivo/tview#226]
Hi

Thanks a lot for your great work. I have a little question, i've created a little ui with tview  for our hardware  (Linux Appliance) and it is working well on a virtual console. Unfortunately it won't work over a serial port, is there any chance to get this work with tview?

Best regards,
snmed

**Comment by rivo** [comment]
Hi,

I'm not very familiar with consoles over serial ports. Generally, for questions regarding specific terminals, I'd like to redirect you to [`tcell`](https://github.com/gdamore/tcell/) as that is what `tview` uses. If `tcell` can be made to work for your scenario, `tview` will automatically work there, too.

Cheers.
