### ISSUE TITLE
Grid questions

### ISSUE THREAD

**Issue by dguendisch** [rivo/tview#231]
I have a hard time understanding `Grid`'s meaning of width and height. Either the code documentation is mixing them up a lot (not likely) or I have a different understanding than tview about them (more likely).
Let's take e.g. the doc of its `AddItem(p Primitive, row int, column int, height int, width int, ...)` method:
> The top-left corner of the primitive will be located in the top-left corner of the grid cell at the given row and column and will span "width" rows and "height" columns.

How can something span a width of rows?? I mean the _wider_ an item gets, the more **columns** it spans.
The same for "... span ... height columns": the _higher_ an item gets, the more **rows** it will span.

Later:
> For example, for a primitive to occupy rows 2, 3, and 4 and columns 5 and 6:
  grid.AddItem(p, 2, 4, 3, 2, true)

Ok, so we add `p` at row=2 with a height=3, so it'll span row 2, 3 and 4 => I understand that one, it matches my understanding of width and height :)
But we define col=4 and width=2, so it should span columns 4 and 5 instead of what's written in the documentation.

The same goes on with `SetRows(...)`...

But I guess I got something totally wrong with the `Grid`, so any explanation is appreciated :)

**Comment by rivo** [comment]
I renamed the parameters in `AddItem()` to `colSpan` and `rowSpan`. I also fixed the example which, as you pointed out, was wrong. I believe this should clarify your questions.

If you're still having trouble with this, let me know.

**Comment by dguendisch** [comment]
The names are more clearer, thanks. As I see from 1ac6fbc the doc was indeed wrong. E.g. in the doc `width` was replaced with `rowSpan`, while in the method signature, `height` was replaced with `rowSpan`, so the doc mixed it up.

If you like to continue, see e.g. [`SetRows` doc](https://github.com/rivo/tview/blob/master/grid.go#L78). I understand what it does but the doc states e.g.
> Each value defines the size of one row, starting with the leftmost row.

There is in my understanding no such thing as a "leftmost row", there is either a "topmost row" or a "leftmost column". It continues then with mixing width and height in the same way as in `AddItem` previously. Really confusing for newbies like me :)

**Comment by rivo** [comment]
Thanks for catching this one, too. I think I must have switched `SetColumns()` with `SetRows()` at some point without fully adapting the comments. My latest commit should fix those comments.

Let me know if you find anything else.

**Comment by xhsky** [comment]
The row and columns of the grid's AddItem() seem to be a ratio, not the row and width on the screen? Are there more detailed descriptions and examples of these parameters?

**Comment by rivo** [comment]
The `rowSpan` and `columnSpan` parameters refer to rows and columns of the grid, not the screen. The size of the grid's rows and columns are defined with `SetColumns()` and `SetRows()`. See [`SetColumns()`](https://pkg.go.dev/github.com/rivo/tview#Grid.SetColumns) for a detailed description, including proportional sizing.

**Comment by xhsky** [comment]
> The `rowSpan` and `columnSpan` parameters refer to rows and columns of the grid, not the screen. The size of the grid's rows and columns are defined with `SetColumns()` and `SetRows()`. See [`SetColumns()`](https://pkg.go.dev/github.com/rivo/tview#Grid.SetColumns) for a detailed description, including proportional sizing.

func (g *Grid) AddItem(p Primitive, row, column, rowSpan, colSpan, minGridHeight, minGridWidth int, focus bool) *Grid 
Do the row and column in this function parameter represent the starting position of p on the screen? How exactly is it positioned?

**Comment by rivo** [comment]
Pretty much like [the documentation](https://pkg.go.dev/github.com/rivo/tview#Grid.AddItem) says:

> The top-left corner of the primitive will be located in the top-left corner of the grid cell at the given row and column and will span "rowSpan" rows and "colSpan" columns.

_Grid_ rows and _grid_ columns, that is.
