### ISSUE TITLE
Feature request: add AppendText to TextView

### ISSUE THREAD

**Issue by dguendisch** [rivo/tview#232]
Would be cool if TextView had an `AppendText` in addition to the current SetText one, which always clears the textview before rendering it again.
`AppendText` would be helpful for a log-tail like UI where new lines are appended to the existing text.

**Comment by joegrasse** [comment]
As shown in the [TextView Example](https://github.com/rivo/tview/wiki/TextView), you can use TextView as an ```io.Writer```. This allows you to continue to append text.

```fmt.Fprintf(textView, "%s ", word)```

**Comment by dguendisch** [comment]
I see, thanks for the hint!
