### ISSUE TITLE
Feature request: add GetText method to TextView

### ISSUE THREAD

**Issue by dguendisch** [rivo/tview#233]
Would be helpful to have a `GetText` method on a TextView to get the current text.
Would free myself from tracking this "state" as it is already present in the TextView itself.

(Background: I'm mostly using filterable textviews, that is a TextView surrounded by means to filter and highlight the respective text. Currently I need to wrap all "text-changing" calls to the TextView so that I can track the currently displayed text, so that I can later filter/search on it. If TextView had a `GetText` I wouldn't need to care who is setting or appending new text to the TextView, but simply get the current text with `GetText` whenever I need it)

**Comment by rivo** [comment]
That makes sense. I added this function to the class with the latest commit.
