### ISSUE TITLE
Escaping in the TextView seems faulty 

### ISSUE THREAD

**Issue by Bios-Marcel** [rivo/tview#234]
Hey,

I am currently writing a chat application, that means the textview can get filled with arbitrary text.

I just had a user write a small snippet of code:

```md
`{["print"] = print}`
```

It was basically a line of code with markdown around it. After calling `tview.Escape`, it renders the text like this:

```
`{ 
```

I assume this is a bug, or did I missunderstand `tview.Escape`?

**Comment by Bios-Marcel** [comment]
Can be reproduced using this:

```go
package main

import "github.com/rivo/tview"

func main() {
	textView := tview.NewTextView()
	textView.SetDynamicColors(true)
	textView.SetRegions(true)
	textView.SetText(tview.Escape("`{[\"print\"] = print}`"))

	app := tview.NewApplication()
	app.SetRoot(textView, true)
	app.Run()
}
```

**Comment by rivo** [comment]
Thank you for catching this. I believe I fixed this with the latest commit. Let me know in case you still find anything here.

**Comment by Bios-Marcel** [comment]
Cool, seems to be working fine. Anyhow, what do you think about regression tests? I think it'd be cool to prevent such bugs from happening again. Stuff like parsing logic and such is always quite fragile in my opinion.

**Comment by rivo** [comment]
Yeah, it's on my list. What I would like to have in there is a test stub for [`tcell.Screen`](https://godoc.org/github.com/gdamore/tcell#Screen) whose character buffer could then be checked against in the test cases. So it wouldn't just be parsing logic but also layouts and user input behaviour that could be tested this way.

Haven't had time for this yet, though.
