### ISSUE TITLE
a way to add inputfield at desired position

### ISSUE THREAD

**Issue by shishirsriv** [rivo/tview#237]
Thanks for the awesome library, i really liked tview.
Here is my use case:
I have multiple checkbox and inputfields on a form. i am looking at a way where i can show a few inputfields only if a checkbox is checked. i understand there is no hide/show and hence creating an inputfield at runtime and adding to the form is fine, but that always adds at the end of the form.

**Comment by dguendisch** [comment]
You could use a [Grid Layout](https://godoc.org/github.com/rivo/tview#Grid) in this case. Its `AddItem` method allows you to place primitives at a fixed position in the layout rather than appending them.

**Comment by rivo** [comment]
@shishirsriv, please have a look at #192 and let me know if this would be a solution to your problem. It's not available yet but I'm planning to introduce something like that.

**Comment by rivo** [comment]
Will reopen when there's new information.
