### ISSUE TITLE
Stuck at table end

### ISSUE THREAD

**Issue by gh0st42** [rivo/tview#238]
Shouldn't `trackEnd` also be set to false if `SetOffset` is called on a table? 
https://github.com/rivo/tview/blob/b373355e9db4bec1faba239e4b6dc069c356fe6f/table.go#L370

After scrolling to the end of a table or calling `ScrollToEnd` I am stuck there unless I call `ScrollToBeginning`. Am I missing any function I should call to scroll "up" one row again?

At the moment I'm using the following hack:
```
r, c := table.GetOffset()
table.ScrollToBeginning()
table.SetOffset(r-1, c)
```

**Comment by rivo** [comment]
That's right. Thanks for spotting this. The latest commit should fix this.
