### ISSUE TITLE
Textattributes in tablecell aren't applied to the first rune

### ISSUE THREAD

**Issue by Bios-Marcel** [rivo/tview#241]
When using color and attribute tags in a tablecell, the color applies to the complete string, but the text attributes only apply to everything after the first rune.

![Image of the bug occuring](https://i.imgur.com/KrYqmCc.png)

Reproduce using this code:

```go
package main

import "github.com/rivo/tview"

func main() {
	table := tview.NewTable()
	table.SetCellSimple(0, 0, "[blue][::ub]Hello World")
	textView := tview.NewTextView().SetText("[blue][::ub]Hello World").SetDynamicColors(true)

	layout := tview.NewFlex()
	layout.AddItem(table, 0, 1, false)
	layout.AddItem(textView, 0, 1, false)

	tview.NewApplication().SetRoot(layout, true).Run()
}
```

**Comment by rivo** [comment]
Thanks for catching this. The latest commit should fix this.
