### ISSUE TITLE
The .Walk() functionality on a tree view always returns the parent as nil

### ISSUE THREAD

**Issue by thebsdbox** [rivo/tview#246]
Unless I'm doing this wrong I don't seem to be able to walk up the tree, I'm trying to find the parent with the reference I'm expecting. 

Example below, I need to be able to walk the `pre-boot` Snapshot up the tree to it's parent with the expected reference `virtual machine` which maps to a VM named `server05` where I can then perform the expected action. 

```
│  ├──server05                                                                                                                                                 
│  │  ├──Details                                                                                                                                               
│  │  │  ├──CPUs: 1                                                                                                                                            
│  │  │  ├──Memory: 1024                                                                                                                                       
│  │  │  ├──Type: Ubuntu Linux (64-bit)                                                                                                                        
│  │  │  ├──VMware Tools: toolsNotInstalled                                                                                                                    
│  │  │  ├──VM IP Address:                                                                                                                                     
│  │  │  └──MAC ADDRESS: 00:50:56:A3:91:EE                                                                                                                     
│  │  └──Snapshots                                                                                                                                             
│  │     └──pre-boot    
```

**Comment by thebsdbox** [comment]
Ended up using a struct that carries a pointer back to the VM and pinning it to child nodes with `SetReference(v)`, I presume thats the way to go. (works for me :) )

**Comment by rivo** [comment]
Internally, tree nodes do not keep a reference to their parents, only to their children, i.e. top-down. The `TreeNode` class gives you a lot of freedom to call `SetChildren()` or `AddChild()` anywhere and I didn't want to get into the mess of keeping children and parents in sync. (I'm not even sure if this is possible, e.g. if you use the same `TreeNode` multiple times.)

The only way to access a parent within `tview` is to use the `Walk()` function and then it's only temporary and returns `nil` for the node you call `Walk()` on (see documentation). You'd have to call `Walk()` on the root node (which may be inefficient for your case).

So yeah, you'll have to resort to keeping a reference to the parent by yourself, as you do.

I'll close this for now. If you want to keep the discussion going, we can always reopen this issue.
