### ISSUE TITLE
Support Multi-Colored table cells

### ISSUE THREAD

**Issue by maja42** [rivo/tview#25]
Currently, it is only possible to define a single color in a TableCell.
It would be great if multiple colors could be supported, perhaps using ansi escape characters? (see my previous question/feature request: #24)

Here is my use case:
I display a table with various git projects and the current repository status. If any repository is in an unwanted state, the information should be printed red. For example, if there are still uncomitted files or untracked branches, the user should see it at a glance.

Here is an example output how it should look like:

![image](https://user-images.githubusercontent.com/2649265/34909637-33457198-f8a5-11e7-8b85-9ce2f7238d3e.png)

This was implemented using gocui. With the current way tables (and table cells in particular) in tview work, this can not be accomplished.

**Comment by maja42** [comment]
This is also linked to issue #20

**Comment by rivo** [comment]
I'm looking into this. Will get back to you.

**Comment by rivo** [comment]
This is implemented now. It doesn't just affect tables but all other strings as well. I.e. you can partially color titles, lists, modals etc.
