### ISSUE TITLE
WordWrap fails to break long words

### ISSUE THREAD

**Issue by carldunham** [rivo/tview#251]
eg 
```
msg := "123456789012345678901234567890"
fmt.Printf("wrapping %s: %#v", msg, tview.WordWrap(msg, 10))
```
results in 
```
wrapping 123456789012345678901234567890: []string{"12345678901", "2", "3", "4", "5", "6", "7", "8", "9", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0"}
```
The function docs don't actually mention breaking up words, but the code is trying to do something with it. Suggest that the above should result in
```
wrapping 123456789012345678901234567890: []string{"1234567890", "1234567890", "1234567890"}
```
Thanks!

**Comment by rivo** [comment]
Thanks. Yeah, that seems to be wrong. I'll fix it but it will need to wait a bit because I'll be offline for the next three weeks.

**Comment by rivo** [comment]
I believe  I was able to fix it. This is  way more difficult  than it  seems at first.

**Comment by carldunham** [comment]
Awesome. Yeah, word-wrapping is a lot harder than it seems. Why Knuth took all those years off from writing his books to write TeX 😃

**Comment by rivo** [comment]
Haha! Right. I actually think that the current version won't be the last. Once rivo/uniseg#2 is implemented, I'll have to review my code here (and probably completely rewrite it again).
