### ISSUE TITLE
The default theme has changed (doesn't use the terminals color set anymore?)

### ISSUE THREAD

**Issue by Bios-Marcel** [rivo/tview#252]
Hey,

I have just updated tview in order to make use of the fix in #236 and suddenly the theme of the application is different. I assume this is due to the recent theme PR? Was this supposed to change the default behaviour?

It now looks like this:

![new look](https://user-images.githubusercontent.com/19377618/54609881-19149b80-4a54-11e9-9880-9374dee420e0.png)

Before it looked like this:

![old look](https://user-images.githubusercontent.com/19377618/54610119-9d671e80-4a54-11e9-9c25-780493ec2b3a.png)

I also tested this with a minimal example that just shows a label:

```go
package main

import (
	"github.com/rivo/tview"
)

func main() {
	label := tview.
		NewTextView().
		SetDynamicColors(true).
		SetText("[blue]Hello")
	tview.
		NewApplication().
		SetRoot(label, true).
		Run()
}
```

**Comment by Bios-Marcel** [comment]
Nevermind, this actually seems to be related to changes in tcell. Still, which would be the expected behaviour?

**Comment by kovart** [comment]
I have the same issue

**Comment by diamondburned** [comment]
Try `export TERM=xterm-basic`

**Comment by Bios-Marcel** [comment]
I just specified a custom theme :man_shrugging:

**Comment by Bios-Marcel** [comment]
@rivo I hoped that you'd at least give a statement to why this happened or if this was expected behaviour. Since this technically "broke" my application, it seems like a backwards compatibility issue.

**Comment by rivo** [comment]
Maybe I was too fast here, I don't know. You wrote that this was related to `tcell` so I assumed you would direct your questions there.

I don't know how to make it look like your "original" theme. It was always black for me. (I'm using iTerm2 on macOS.) I would therefore say that's the default look.

The theme PR that you referenced did not include any changes to any colours. I also didn't make any changes to the default colours in other commits (at least not that I recall any). For now, I'm assuming this is indeed a `tcell` issue. But if you can trace the change down to a specific commit in `tview` (leaving `tcell` the same), I may be able to help you.

**Comment by Bios-Marcel** [comment]
Hm, I see. I was just wondering that the whole look changed over night. Before it was using my terminals pastel colors and now it doesn't anymore. In your case iTerm just has a rather default look it seems, so maybe you didn't notice any change. I'll try finding out why this has happened :)

**Comment by dbridges** [comment]
@Bios-Marcel  Did you figure out why this happened, and how to revert back to using default terminal colors?

**Comment by calzoneman** [comment]
Setting the environment variable `TCELL_TRUECOLOR=disable` works for me.

**Comment by by-sabbir** [comment]
`SetBackgroundColor(tcell.ColorBlack.TrueColor())` worked for me.
