### ISSUE TITLE
Let list item activate on more than one char

### ISSUE THREAD

**Issue by cpkio** [rivo/tview#253]
First of all, amazing framework you've done!

The Q is: how about lists to be activated not on one character, but on a few? I mean, when you're using more than one language, you type in not only 'k' character, but 'л' on the same key. Frequent switching back and forth if you're inputting Cyrillics for example is not comfortable.

**Comment by rivo** [comment]
I'm not sure I fully understand what you are describing. How exactly do you enter `k` on your keyboard and how do you enter `л`?

List item activation happens through the input of one rune. Accepting a sequence of runes (if that is what you want) will make interaction with the list quite complex. And it will break backwards compatibility.

But maybe I'm misunderstanding something here, in which case please give me an example of how the user would interact with the list as you'd like it.

**Comment by rivo** [comment]
Will reopen when there is more information.
