### ISSUE TITLE
Anyone know how to put a termui chart (Sparkline) into a tview?

### ISSUE THREAD

**Issue by christoofar** [rivo/tview#255]
I'd like to put a live sparkline inside of a box or some other primitive which is monitoring the number of sessions open on a SIP server.   I'm using termui to build the dashboard to control the phone switch.

https://github.com/gizak/termui/blob/master/_examples/sparkline.go

**Comment by rivo** [comment]
Please look at this: https://github.com/rivo/tview/issues/11#issuecomment-357044887

Again, I don't know if this will actually work but it could be a pointer on how to integrate `termui` with `tview`. Generally, I do have plans to add charts to `tview` but that's something for v2 so it's still quite some time out.
