### ISSUE TITLE
Adding Rows to Table After Root is set

### ISSUE THREAD

**Issue by christopherghenderson** [rivo/tview#258]
I'm noticing that it is impossible to add rows to Tables using table.InsertRow after app.SetRoot has been set.  Is this intentional, is there a way to allow the additions of rows after the fact?

**Comment by rivo** [comment]
I don't see why this wouldn't work. Here's an example:

```go
package main

import (
	"fmt"

	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

func main() {
	table := tview.NewTable().
		SetBorders(true)

	for row := 0; row < 5; row++ {
		for col := 0; col < 5; col++ {
			table.SetCellSimple(row, col, fmt.Sprintf("%d,%d", row, col))
		}
	}

	table.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		if event.Key() == tcell.KeyEnter {
			table.InsertRow(0).SetCellSimple(0, 0, "Inserted")
		}
		return event
	})

	if err := tview.NewApplication().SetRoot(table, true).Run(); err != nil {
		panic(err)
	}
}
```

Maybe you're updating the table in a goroutine? If so, please check out [this Wiki article](https://github.com/rivo/tview/wiki/Concurrency) on concurrency in `tview`.

**Comment by christopherghenderson** [comment]
I was unable to get QueueUpdateDraw to work, or anything outside of an event capture; so I got it updating by adding this as my main loop:

```
	for {
		if time.Now().After(after) {
			app.Draw()
			after = time.Now().Add(1 * time.Second)
		}
	}
```

Then an After Draw function:

```
	app.SetAfterDrawFunc(func(tcell.Screen) {
		mainLoop()
	})
```

Not ideal, but not terrible by any means.

**Comment by rivo** [comment]
This looks to me like you'll have an extremely busy loop (maybe `time.Sleep()` would be better for something like this?).

I don't know why `QueueUpdateDraw()` did not work for you but if you would like me to follow up on it, please send me an example where you tried it and where it didn't work. I'll reopen this issue in that case.
