### ISSUE TITLE
[Question] The first character of the table title is not displayed

### ISSUE THREAD

**Issue by skanehira** [rivo/tview#261]
I run demos form but the table title's first character was not displayed.
Also, the right corner border of the table is not displayed.
But when i use kitty, then it looks like good worked.

I don't know why it is happened.
Please help me.

**OS:**
```
Mac Mojave 10.14.4（18E226）
```

**Terminal:** [Alacritty](https://github.com/jwilm/alacritty), Terminal(default)
![image](https://user-images.githubusercontent.com/7888591/55629407-1a80ea80-57ee-11e9-958a-267d7b49245b.png)

**Terminal:** [kitty](https://sw.kovidgoyal.net/kitty/)
![image](https://user-images.githubusercontent.com/7888591/55630829-94ff3980-57f1-11e9-8ff8-1c9492244f68.png)

**Comment by rivo** [comment]
This seems to me like a configuration issue with your terminal program. Have a look at #66 and #118 for similar issues (and their solutions).

I don't believe there's anything I can do here as I cannot influence the specifics of how some terminals render characters.

**Comment by skanehira** [comment]
I solved this problem.
Thank you :)
