### ISSUE TITLE
[Question] How do I display form above the grid?

### ISSUE THREAD

**Issue by skanehira** [rivo/tview#264]
@rivo 
Hi!
Thank you for develop tview.
This project is very good so I like it :)

BTW I developing the tui client for docker but I have a problem.
I want to display form primitive above the grid but I don't know how to do it.

```go
grid := tview.NewGrid().SetRows(2, 0, 0, 0, 0, 0).
	AddItem(info, 0, 0, 1, 1, 0, 0, true).
	AddItem(tasks, 1, 0, 1, 1, 0, 0, true).
	AddItem(images, 2, 0, 1, 1, 0, 0, true).
	AddItem(containers, 3, 0, 1, 1, 0, 0, true).
	AddItem(volumes, 4, 0, 1, 1, 0, 0, true).
	AddItem(networks, 5, 0, 1, 1, 0, 0, true)

g.app.SetRoot(grid, true)
```

![image](https://user-images.githubusercontent.com/7888591/55924554-4a444e00-5c45-11e9-8520-ddaf5c617aec.png)

I want to do the following.(Current [project](https://github.com/skanehira/docui) uses gocui)
![image](https://user-images.githubusercontent.com/7888591/55924983-f9cdf000-5c46-11e9-8c0b-97c194373e48.png)

**Comment by gstvg** [comment]
Take a look at https://github.com/rivo/tview/wiki/Modal
I think that this should work:

`
grid := tview.NewGrid().SetRows(2, 0, 0, 0, 0, 0).
	AddItem(info, 0, 0, 1, 1, 0, 0, true).
	AddItem(tasks, 1, 0, 1, 1, 0, 0, true).
	AddItem(images, 2, 0, 1, 1, 0, 0, true).
	AddItem(containers, 3, 0, 1, 1, 0, 0, true).
	AddItem(volumes, 4, 0, 1, 1, 0, 0, true).
	AddItem(networks, 5, 0, 1, 1, 0, 0, true)

form := tview.NewForm()....

pages := tview.NewPages().
        AddPage("form", form, true, true)
        AddAndSwitchToPage("main", grid, true, true)

g.app.SetRoot(pages, true)

//on display form event
pages.SwitchToPage("form")
`

**Comment by skanehira** [comment]
@gstvg 
Thank you!
I solved this problem :)

pages.SwitchToPage ("form") will hide the grid, so g.pages.ShowPage ("main") was required.

![image](https://user-images.githubusercontent.com/7888591/55968972-fde62600-5cb7-11e9-8cdb-db4564ac8628.png)
