### ISSUE TITLE
Treeview's first letter is lost

### ISSUE THREAD

**Issue by pathbox** [rivo/tview#267]
My OS  is  macOS Mojave  10.14.3,  I don't know why, the first letter is replaced with a gray block

**Comment by urandom** [comment]
You might lack  the font glyphs needed to render the tree graphics.

**Comment by pathbox** [comment]
@urandom  Yeah, maybe . But  I don't know what the font glyphs that I need

**Comment by rivo** [comment]
What terminal application are you using?

**Comment by pathbox** [comment]
@rivo   ITerm2

**Comment by rivo** [comment]
Have you had a look at #281 already?

If that doesn't help, please right-click on a terminal tab, then go to Edit Session > Text and post a screenshot of that window here.

**Comment by pathbox** [comment]
It works, thanks
