### ISSUE TITLE
SetBackgroundColor(-1) issue

### ISSUE THREAD

**Issue by eu81273** [rivo/tview#270]
To match the background color with the terminal system background color, must set the SetBackgroundColor value to -1(tcell.ColorDefault).

Setting the BackgroundColor to -1 is works fine for most components, but for the List component produces unexpected results like below...

- When the list is updated, the updated list and the previous list are overlapped.
- When move the cursor down, the previous item remains in the selected background color.

**Comment by diamondburned** [comment]
Try

```go
	app := tview.NewApplication()
	defer app.Stop()

	app.SetBeforeDrawFunc(func(s tcell.Screen) bool {
		s.Clear()
		return false
	})
```

**Comment by eu81273** [comment]
@diamondburned 
Thank you. SetBeforeDrawFunc works perfect.
