### ISSUE TITLE
TextView: Vertical Alignment

### ISSUE THREAD

**Issue by amery** [rivo/tview#272]
Hi, could you provide an example about how to center vertically the text of a TextView?

**Comment by diamondburned** [comment]
I tried implementing a Primitive for that here: https://gitlab.com/diamondburned/spotuify/blob/master/views/loading/loading.go#L34

Do note that this is *not* a TextView, which means it does not support markup formatting.

**Comment by amery** [comment]
thanks, I'll study it :)

**Comment by rivo** [comment]
There is no automatic vertical alignment in a `TextView`. This would lead to navigation issues so I don't think such a flag would become part of this primitive.

But if you know in advance how many lines your `TextView` will have, you can center it by putting it in the middle of a three-row `Flex` where only the top and bottom rows have flexible heights.

If the number of lines is unknown and may even be larger than the available height, I cannot think of a solution with `TextView` at the moment.

**Comment by caiguanhao** [comment]
```go
package main

import (
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

type verticalText struct {
	*tview.TextView
}

func (t *verticalText) Draw(s tcell.Screen) {
	_, _, _, height := t.TextView.GetRect()
	t.TextView.SetBorderPadding(height/2, 0, 0, 0)
	t.TextView.Draw(s)
}

func main() {
	app := tview.NewApplication()
	text := tview.NewTextView().
		SetText("This is vertically-aligned text").
		SetTextAlign(tview.AlignCenter)
	vText := &verticalText{text}
	if err := app.SetRoot(vText, true).Run(); err != nil {
		panic(err)
	}
}
```
