### ISSUE TITLE
TextView.ScrollTo(row,column) broken?

### ISSUE THREAD

**Issue by thorsager** [rivo/tview#274]
Having some issues using the `.ScrollTo(row,column)` func on the `TextView`, it seems that it keeps _trackingEnd_ which makes it a bit hard to get it all going (when scrolling up from the buttom). If the `.ScrollToBeginning()` is used first (which sets `trackEnd=false`) it is then possible to _scroll around_.

**Comment by rivo** [comment]
You're right, this is a bug. The latest commit should fix this.
