### ISSUE TITLE
Support specific width/height for table cells

### ISSUE THREAD

**Issue by jaymickey** [rivo/tview#276]
Hi, 

Thanks for this library! Would be awesome if it was possible to set a fixed width and height for table cells. Or even a padding around the text?

**Comment by rivo** [comment]
Each row in a `Table` always has a height of 1. That's built-in and unlikely to change. If you want a table-like structure with more complex content, you'll need to use `Grid`.

You can, however, set a fixed width for cells. See #227 for instructions.
