### ISSUE TITLE
Table Selection Inverts Cell Border Color

### ISSUE THREAD

**Issue by DuckDuckWhale** [rivo/tview#282]
After pasting code from [Table Wiki](https://github.com/rivo/tview/wiki/Table), the enter key to select a cell inverts the cell border color as well as the content color.
### Screenshot from Wiki
![](https://github.com/rivo/tview/raw/master/demos/table/screenshot.png)
### Screenshot
![](https://user-images.githubusercontent.com/28813824/57973246-0e06ba80-7974-11e9-8637-27ff18d7d736.png)

**Comment by rivo** [comment]
Good catch. The screenshot was still from a very old version of the `Table` class. It should match the demo now.

**Comment by DuckDuckWhale** [comment]
Okay, so inverting the color of the cell border is actually intended. What's the reasoning behind this though? Personally I actually think it looks nicer not to invert the cell border color. Is there any way to do that using the API?

**Comment by rivo** [comment]
You can select multiple rows or multiple columns. In those cases also, the highlight must run across cell borders. (Anything else would look weird; I tested that.) Personally, I don't like having borders highlighted in some places and not in others so this is what I ended up with. Apart from rolling your own selection functionality (using [`GetInputCapture()`](https://godoc.org/github.com/rivo/tview#Box.GetInputCapture) and colour tags), there's currently no way to turn this off.

**Comment by DuckDuckWhale** [comment]
Fair enough.
