### ISSUE TITLE
Reset form focused element to 0

### ISSUE THREAD

**Issue by mikeschinkel** [rivo/tview#286]
First, let me thank you profusely for tview. It is empowering me to build a UI for an open-source CLI tool that I would likely never have been able to implement otherwise!

I have a flex with a treeview on the left and a form on the right. If I select a treeview node it my app changes to focus on the form. If the user selects the cancel button it returns to the treeview.

However, when the user selects the treeview node again it returns to the form with the cancel button still selected. I think it would be a better UX if the form reset to having its first element having focus.  However, review the source it appears that `form.focusedElement` is private and there does not appear to be a method to set it.

Am I missing something obvious, or is this currently not possible with the existing feature set? 
If the latter, would you accept a pull request to add this _(assuming I can figure out how?)_

**Comment by rivo** [comment]
The latest commit adds a function `SetFocus()` to `Form` and I believe `form.SetFocus(0)` should do what you're asking for. Cheers!

**Comment by mikeschinkel** [comment]
@rivo Wow, talks about service!  Thank you for such a quick response on an open-source package.
