### ISSUE TITLE
Can not display normally in xshell5

### ISSUE THREAD

**Issue by AkatsukiAkira** [rivo/tview#288]
I run the demos in Xshell5 and their can not display normally,the multi-Text was lost the first character. Xshell5 

Here are the screenshots:
![screenshots](https://user-images.githubusercontent.com/29282808/58774175-bcf0fa80-85f2-11e9-8aa9-5f163e5aaaed.png)
![微信图片_20190603112544](https://user-images.githubusercontent.com/29282808/58774387-cfb7ff00-85f3-11e9-98e1-bf25c39ad5d9.png)

Below is the Xshell5's Properties:
![微信图片_20190603112545](https://user-images.githubusercontent.com/29282808/58777169-aac98900-85ff-11e9-87a5-7cffec4b1673.png)

**Comment by jt6562** [comment]
Try to set env RUNEWIDTH_EASTASIAN=0

**Comment by rivo** [comment]
Any luck with this?

Please also check out #281 and let me know if that helps.
