### ISSUE TITLE
Padding dropdown text?

### ISSUE THREAD

**Issue by mikeschinkel** [rivo/tview#289]
Is there a simple way to pad the dropdown text so that the dropdowns are wider than the widest element?  Dropdowns feel a bit cramped when their text is has no padding in the drop down.

I have found that I can add the spaces to either side of the literal dropdown text and then after the users has entered values into a form trim them but it feel really hacky to do that.

Also, it would be nice if the highlight could always stretch the full width of the drop down no matter what the length of the option text currently is.

I looked at creating a pull request for this but I can see that it might be implemented more than one way so don't want to do it the way you would not prefer, but will be happy to with guidance.

**Comment by rivo** [comment]
My latest commit adds [`SetTextOptions()`](https://godoc.org/github.com/rivo/tview#DropDown.SetTextOptions) to the `DropDown` primitive. This should allow you to add some padding to the drop-down items. I also decided to stretch the selection bar to the entire width as you requested.

**Comment by mks-colibri** [comment]
Thank you!

**Comment by mikeschinkel** [comment]
@rivo Thank you!
