### ISSUE TITLE
<nobr> like functionality for TextView?

### ISSUE THREAD

**Issue by mikeschinkel** [rivo/tview#295]
I am finding a need for a "No Break" feature in TextView similar to the `<nobr></nobr>` of HTML.  Specifically I am using `WordWrap` and I want to have quoted strings to call them out as definitions, e.g. _"Provide a 'TextView' object for displaying text"_ but I am finding that wrapping is happening at the quote and so I get some like thing:

```
......................... Provide a '
TextView' object for displaying text.
```

Maybe an even simpler option would be to not wrap on quoted strings, except inside the string when there is no option?

**Comment by rivo** [comment]
The problem in your case is rather that `WordWrap()` shouldn't have broken the string after the `'`. I think I used the wrong regex character class here. The latest commit fixes this.

Apart from that, it's unlikely that I will introduce a `nobr`-like tag in the near future. With all the tags `tview` already supports, the code has become very complex and I've rewritten it multiple times. It would be heading towards an "HTML widget" which is an entire project on its own. I have no plans for something like that.

**Comment by mikeschinkel** [comment]
@rivo Thanks.
