### ISSUE TITLE
Add "autocomplete" functionality to the InputField

### ISSUE THREAD

**Issue by mikeschinkel** [rivo/tview#299]
Hi @rivo:

See your [comment](/rivo/tview/issues/77#issuecomment-373462878) on #77, which is closed, but you mentioned that you might possibly implement the autocomplete functionality you mentioned.

For my use-case I need to be able to present several items that users can choose from and **either** allow them to select one, or be able to enter a custom value. I have numerous fields that need this but one example is a software version number where I have a list of released version numbers but the user may actually be using a beta version where the version number is not released.

I am willing to _(help)_ implement the autocomplete, as you have probably seen my recent flurry of PRs, but as that would be a bit more complex I would want input from you as to how you would prefer it to be implemented.

**Comment by diamondburned** [comment]
Can be done by hacking in a List on top. I've done it.

**Comment by mikeschinkel** [comment]
@diamondburned Care to share _(code?)_  :-)

**Comment by diamondburned** [comment]
https://gitlab.com/diamondburned/6cord/blob/master/main.go#L266 is where I add things.

The rest of the logic is in `fuzzy*.go`

**Comment by rivo** [comment]
Autocomplete functionality was requested earlier (#77) and I agree it's a useful addition to `InputField`. So I went ahead and added [`SetAutocompleteFunc()`](https://godoc.org/github.com/rivo/tview#InputField.SetAutocompleteFunc) (along with [`Autocomplete()`](https://godoc.org/github.com/rivo/tview#InputField.Autocomplete)) to the `InputField` class.

There are two additional examples in the `demos/inputfield` directory which illustrates their usage. See the [`Wiki`](https://github.com/rivo/tview/wiki/InputField) for an explanation.
