### ISSUE TITLE
looking for the ability to create a "popup" message box for handling error message

### ISSUE THREAD

**Issue by xinity** [rivo/tview#303]
hey there,

Is there any known way to integrate error message handling using tview so we'd have a popup message box with an error message instead of having the application quit immediately?

Would love to be able to do that.

Thanks for your precious help,

**Comment by xinity** [comment]
found how to use modal closing :)

**Comment by Maxiride** [comment]
> found how to use modal closing :)

How did you close a modal? I can't see any method related to "closing" or "hiding" a modal.
