### ISSUE TITLE
any way to put buttons vertically rather than horizontally ?

### ISSUE THREAD

**Issue by xinity** [rivo/tview#305]
hey working with learning tview, i've been wondering if there's a way to create vertical buttons insted of horizontal ones .

Let me know,

Regards

**Comment by rivo** [comment]
Not in a `Form` at the moment, unless you give your form such a narrow width that the no two buttons won't fit in a row.

If you simply need buttons in a column, there are other options, though. You can add them to a `Flex` or a `Grid`. Check out the documentation and the GitHub Wiki for details.

Let me know if this answers your question.
