### ISSUE TITLE
Hide/show a widget in a flex layout on demand

### ISSUE THREAD

**Issue by lenormf** [rivo/tview#309]
Hi,

I want to hide/show a `TextView` widget in a `Flex` layout on demand, the goal would be to show contextual information depending on the state of the application (e.g. tips, completion candidates).

A proposal based on adding `nil` objects to the layout has been hinted at in #104, what is the status of that feature?

Thanks!

**Comment by rivo** [comment]
`nil` objects can be added to `Flex`, see [`AddItem()`](https://godoc.org/github.com/rivo/tview#Flex.AddItem):

> You can provide a nil value for the primitive. This will still consume screen space but nothing will be drawn.

But I'm not sure that this will help you achieve what you want to do. Do you want the `TextView` to be temporarily empty or do you want to take it out of the layout completely? There is a [`RemoveItem()`](https://godoc.org/github.com/rivo/tview#Flex.RemoveItem) function.

**Comment by lenormf** [comment]
I want the `TextView` not to take any screen space unless I'm printing information in it, possibly without having to re-instantiate it every time I need it.

**Comment by rivo** [comment]
You don't need to re-instantiate it. When you call `RemoveItem()`, it's just taken out of the `Flex` layout. You can call `AddItem()` with the same ` TextView` object again.

**Comment by lenormf** [comment]
Thanks, I'll play around with that then. Closing, in the meantime.
