### ISSUE TITLE
Support for charts

### ISSUE THREAD

**Issue by vladimirvivien** [rivo/tview#31]
Great work! 
Was waiting for a project like this (almost went with [nodejs blessed](https://github.com/chjj/blessed) since termui seems unmaintained).  Any plans for chart components (see nodejs [blessed contrib](https://github.com/yaronn/blessed-contrib) or even termui charts) ?

**Comment by rivo** [comment]
Thanks, glad you like it. Actually, this was discussed before, see #11.

**Comment by derivaro** [comment]
//  Try this
//    :-)
//    Rivo, 
//   thanks for ur job, it s just amazing 
//  --------------------------------------------------
package main

import (
	"fmt"
	"math"
	"strings"

	tm "github.com/buger/goterm"

	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()

	tt := tview.NewTextView()

	term(tt)
	if err := app.SetRoot(tt, true).Run(); err != nil {
		panic(err)
	}
}

func term(tt *tview.TextView) {
	chart := tm.NewLineChart(100, 20)

	data := new(tm.DataTable)
	data.AddColumn("Time")
	data.AddColumn("Sin(x)")

	for i := 0.1; i < 10; i += 0.1 {
		data.AddRow(i, math.Sin(i))
	}
	fmt.Fprintln(tt, rp(chart.Draw(data)))

}

func rp(st string) string {
	st = strings.Replace(st, "[31m", "", -1)
	st = strings.Replace(st, "[0m", "", -1)
	return st
}
