### ISSUE TITLE
Named primitives for fast access with a single widget instance

### ISSUE THREAD

**Issue by lenormf** [rivo/tview#311]
Hi,

It'd be nice to be able to get a widget instance from one of its ancestors. When creating an intricate layout with e.g. a `Flex`, code that needs to operate on the children widgets must have access to the variable that stores said widgets:

```go
    widgetA := tview.NewXXX()
    layout := tview.NewFlex().
        AddItem(tview.NewFlex().
            AddItem(widgetA, 0, 1, false))

    layout.Callback(func() {
        widgetA.Foo()
    })
```

It would be more convenient (and scalable) to be able to assign a name/tag (as a string) to widgets, and be able to get their instance using only the parent:

```go
    layout := tview.NewFlex().
        AddItem(tview.NewFlex().
            AddItem(tview.NewXXX().SetName("widgetA"), 0, 1, false))

    layout.Callback(func() {
        if widgetA, ok := layout.GetWidget("widgetA").(SomePrimitive); ok {
            widgetA.Foo()
        }
    })
```

HTH.

**Comment by rivo** [comment]
I'm not going to rule this out completely for the far future but I find that how users organize widgets is very individual and I'm not sure your suggestion (or any other in that  vein) will cover most users' needs. I also don't like that `SetName()` would need to be added to *all* primitives (likely conflicting with [page names](https://godoc.org/github.com/rivo/tview#Pages.AddPage)) and `GetWidget()` would always require a cast to do anything useful.

In your specific case, it probably won't require much code to come up with a structure like this. A simple `map` could do the trick already:

```go
widgets := make(map[string]tview.Primitive)
widgets["widgetA"] = tview.NewXXX()
widgets["widgetA"].(XXX).Foo()
```

**Comment by lenormf** [comment]
I came up with the function names off the top of my head to describe the problem as well as possible, they can be changed.

Since widgets can have different types, a cast is inevitable.

As for storing the instances in a global object, it would be redundant with the framework itself, as the widgets are already stored by it, all we need is a function that returns a given instance.
