### ISSUE TITLE
Clear previously-drawn text on screen.

### ISSUE THREAD

**Issue by iwasaki-kenta** [rivo/tview#312]
I noticed using a scrollable TextView that scrolled-over text is not cleared off of the screen once text I have written to the TextView exceeds the scrollable area.

![image](https://user-images.githubusercontent.com/8392982/59606238-30dae900-9143-11e9-968e-fa0949430d03.png)

Is there any way to forcefully clear the screen before drawing new text?

The view in particular is set to have a default color background.

```go
view := tview.NewTextView()
view.SetBackgroundColor(tcell.ColorDefault)
```

**Comment by eu81273** [comment]
@iwasaki-kenta 
This seems related with #270 
I think tview has problem when BackgroundColor to set tcell.ColorDefault.

**Comment by iwasaki-kenta** [comment]
> @iwasaki-kenta
> This seems related with #270
> I think tview has problem when BackgroundColor to set tcell.ColorDefault.

That worked well, thanks :smile:. Clearing the entire screen buffer is pretty expensive though; would be good for tview to perhaps manually clear tcell views where the background is `tcell.ColorDefault`?

**Comment by rivo** [comment]
@eu81273 is right. This is `tcell.ColorDefault´'s description:

> ColorDefault is used to leave the Color unchanged from whatever system or teminal default may exist.

I don't see why clearing the screen buffer should be very expensive. It's just a virtual buffer and the real bottleneck is more likely in sending the characters to the terminal. But my understanding is that `tcell` optimizes for that, thus we have a lot of freedom to do with the buffer what we want.
