### ISSUE TITLE
Colorized input field

### ISSUE THREAD

**Issue by antonmedv** [rivo/tview#321]
Hi, 

How to colorize user’s input while user typing in input field?

Thanks for awesome library. I think it’s really gold :)

**Comment by rivo** [comment]
Yeah, I don't think this is possible at the moment and it would be quite difficult to implement, I think. (Is this even possible in HTML's `<input>` tag? I've never seen anything like this.)

**Comment by antonmedv** [comment]
This is kinda possible in html in ace or codemirror editor. Also for example in micro terminal editor it's possible to type code with highlighting. I was wondering if it possible in tview as well. I'd like to implement terminal calculator where input is colorized as users types and expression. For example, `1+2` there are 1 and 2 have a blue colour.

**Comment by rivo** [comment]
I'm sure in HTML, one could imitate an input field by handling keyboard/mouse input and outputting a whole bunch of tags which make it look like the input field can display colourized text. But I don't know of a way to make the native `<input>` tag do the same. To my knowledge, it simply displays the `value` attribute which cannot contain any HTML tags itself.

Correspondingly, you can make a more complex input field yourself. Check out [this Wiki page](https://github.com/rivo/tview/wiki/Primitives) for pointers. You could use [`Application.SetAfterDrawFunc()`](https://godoc.org/github.com/rivo/tview#Application.SetAfterDrawFunc) to "post-process" screen output, i.e. colourize your numbers. To find out where the numbers are located on screen, you could use [`InputField.SetDrawFunc()`](https://godoc.org/github.com/rivo/tview#Box.SetDrawFunc). It's not exactly pretty but I think you could make it work that way.

Let me know if this helps.
