### ISSUE TITLE
Getting a selectionChanged notify when application uses Table.Select()

### ISSUE THREAD

**Issue by pktgen** [rivo/tview#323]
Using a Table if I move the selected row/col via keyboard and I have the SetSelectionChangedFunc() the callback works great.

In my case I need to remove or add items to the table. This may mean the I need to change the selected row/col in the application. It would be nice to get a notification or callback called when I call the Table.Select() function.

I could not find anything in the docs about getting some callback for this type of event. As a test I went into the Table.Select() function and modified it to do this:

```go
func (t *Table) Select(row, column int) *Table {
      t.selectedRow, t.selectedColumn = row, column

       // If the selection has changed, notify the handler.
       if t.selectionChanged != nil &&
               (t.rowsSelectable || t.columnsSelectable) {
               t.selectionChanged(t.selectedRow, t.selectedColumn)
       }
       return t
}
```
Do you think this is a reasonable change to get a notify call when the application moves to a different cell?

BTW, excellent package :-)

**Comment by rivo** [comment]
Thanks for catching this. It should have triggered this event all along. The latest commit fixes this.
