### ISSUE TITLE
Some characters cause weird behaviours during input and rendering

### ISSUE THREAD

**Issue by Bios-Marcel** [rivo/tview#324]
I just had someone sent `™` in an app using tview. Every tview is displayed as a two-cell character, even though the actual `TM` is in one cell. Sometimes the second cell is a different color than the rest of the `TextView` and sometimes it copies the character above it.

I can't figure out when which situation occurs, but here are two screenshots:

![copy letter above](https://user-images.githubusercontent.com/19377618/61580266-35166f80-ab10-11e9-8298-fe30d8d2d29c.png)

![empty box behind tm](https://user-images.githubusercontent.com/19377618/61580280-5b3c0f80-ab10-11e9-8d97-f51e86e138fe.png)

The latter can be reproduced with:

```go
package main

import "github.com/rivo/tview"

func main() {
	text := tview.NewTextView()
	text.SetText("Terminals are lovely\nAren't ™ they?")

	app := tview.NewApplication()
	app.SetRoot(text, true)
	app.Run()
}
```

I Also saw this happen with some other characters sometimes. And I tried this on multiple terminals, those being iTerm2(mac OS), termite(vte-based on linux) and alacritity(linux).

The same also happens when for example inputting into an `InputField`.

**Comment by rivo** [comment]
Please check out #278. This is very likely a problem with the [mattn/go-runewidth](https://github.com/mattn/go-runewidth/) package.

```go
package main

import (
	"fmt"

	runewidth "github.com/mattn/go-runewidth"
)

func main() {
	fmt.Println(runewidth.RuneWidth('™')) // Prints "2".
}
```

`tcell` also depends on this package so there there will probably artifacts as long as this is not fixed there. You could open an issue over at `go-runewidth`.

I'm thinking about implementing my own version of `go-runewidth` (there are multiple issues with it) but haven't gotten around to it yet.
