### ISSUE TITLE
Calculating max width

### ISSUE THREAD

**Issue by Syleron** [rivo/tview#327]
Hello,

I'm trying to calculate the max width in spaces for a textview.

Is there a way to do so and if not can someone point me in the right direction?

Cheers

**Comment by rivo** [comment]
I'm not sure if this is what you're looking for but [`textView.GetInnerRect()`](https://godoc.org/github.com/rivo/tview#Box.GetInnerRect) will return the available size for your primitive (i.e. your text view).

Let me know if this answers your question.

**Comment by Syleron** [comment]
@rivo Thank you for getting back to me. I don't think is quite what I need. I'm trying to calculate the total number of space characters a tview primitive utilises. Any ideas? I'm trying to calculate the padding for strings in which I'm printing into a textview. Thanks again.

**Comment by rivo** [comment]
I'm still a bit confused by your explanation. Per default, a `tview` primitive doesn't "utilize space characters". One space rune `' '` occupies one cell in the  terminal.

You can use `go-runewidth`'s [`StringWidth()`](https://godoc.org/github.com/mattn/go-runewidth#StringWidth) if you have a string and need to find out its width on screen.

If that's still not what you're looking for, please provide an example screenshot or code for what you have and what you're expecting.

**Comment by rivo** [comment]
Will reopen if it turns out that this is not resolved yet.

**Comment by Syleron** [comment]
Hi @rivo apologies for not getting back to you.

To clarify, I was attempting to add padding to a textview such that it fits the width of the terminal screen/application hence figuring out the number of spaces required to fill the width of the screen.

I hope that clears my question up. How would I go about doing this? Cheers.
