### ISSUE TITLE
Override/Customize List InputHandler

### ISSUE THREAD

**Issue by jbrodriguez** [rivo/tview#329]
Currently, KeyTab advances the currentItem, but I'd prefer to use it to switch between tviews.

There's no SetInputHandler for List.

Any suggestion on how to achieve this ?

P.S.: I have SetInputCapture in the app to cycle between tviews with KeyTab and it works, but there's an extra scroll in the listview.

My tree is 

```
app
|---flex
      |--- list
      |--- input
```

**Comment by rivo** [comment]
I'm afraid you'll need to provide more information for me to follow. I don't know what you mean by "tviews", i.e. "switch between tviews", or "an extra scroll in the listview".

You can intercept keyboard events with [`SetInputCapture()`](https://godoc.org/github.com/rivo/tview#Box.SetInputCapture) on every primitive, including `List`.

If that doesn't help you, please provide some more detailed clarification.

**Comment by jbrodriguez** [comment]
By tviews I meant primitives.

Based on the tree shown above, I want to tab-cycle between List and InputField widgets. Since List captures KeyTab, what happens is the current element in the list is advanced by one (this is what meant by extra scroll) and at the same time I get the effect from my own KeyTab handler  (set at the app level), which is to switch to the next widget (my InputField widget).

I was just reading the public api for List, but I forgot that it contains Box, so all those functions are available too.

So I could SetInputCapture on the List to override the default behaviour, but would duplicate code.

That works for me.

Let me If you have any other idea.

Thanks !

**Comment by rivo** [comment]
The `Tab` key has a function for some of the primitives. You can intercept it on the [application  level](https://godoc.org/github.com/rivo/tview#Application.SetInputCapture) by returning `nil` but it will affect all other primitives as well. If you only want to intercept the `Tab` key when your `List` has focus, then you only do it there.

So it really depends on how local or how global your  key  override should be.
