### ISSUE TITLE
multi line and auto line break columns for tables

### ISSUE THREAD

**Issue by DaKine23** [rivo/tview#34]
Would be great if there is more then a "one line content" for table cells. e.g. any ASCII art as a symbol in a single cell.

In addition it would be great to add  "auto line break"  as a toggle that together with "maxWidth" allows auto line breaks instead of just cutting out content.

**Comment by rivo** [comment]
I don't think I will extend the `Table` class to do that. It's complicated enough to make it work with one-row content, especially when you want to navigate tables with fixed rows/columns, selections etc.

There is another feature request for grids, though (see #23), which I plan on adding. You could define a grid and put your ASCII art in the grid. Each cell could be a `TextView` which now has word line breaks, too. This should be very similar to tables with multi-line cells.
