### ISSUE TITLE
The tabstop replacement for TextView is incorrect

### ISSUE THREAD

**Issue by dzpao** [rivo/tview#340]
The result of the tabstop replacement should be an integer multiple of tabsize. Instead of simply replacing tabstop with an equal amount of space.

For example, the result of replacing `"abc\tdef"` should be `"abc<space>def"` instead of `"abc<space><space><space><space>def"`.

Hope to fix this problem.

**Comment by rivo** [comment]
The handling of tabs in `tview` is not as it is in other applications. See [here](https://godoc.org/github.com/rivo/tview#TextView.Write):

> Tab characters will be replaced with TabSize space characters.

Granted, this is not the original meaning of a tab. It's a very simple approximation. But I don't see proper tab handling implemented any time soon. It's extremely difficult to make it work, especially with Unicode, wide characters, word-wrapping etc. So for the time being, it will remain as it is.

I'd be open to changing `TabSize` to `2`, though, if enough people agree.

**Comment by rivo** [comment]
Will reopen if this becomes important again.

**Comment by dotnwat** [comment]
I stumbled upon this issue @rivo debugging tabs in virtual table. For example in this

```
func (d *TableData) GetCell(row, column int) *tview.TableCell {
    return tview.NewTableCell(d.lines[row])
}
```

if the text added into the table cell contains one or more leading tabs then they are displayed as if TabSize=0.
