### ISSUE TITLE
The behavior of TextView.SetScrollable() is very strange

### ISSUE THREAD

**Issue by dzpao** [rivo/tview#341]
Talk is cheap, show you the code:

```Golang
package main

import (
	"fmt"
	"time"

	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView()
	textView.SetScrollable(false)  // <------ Please note here
	textView.SetBorder(true)
	textView.SetChangedFunc(func() {
		text := textView.GetText(false)
		textView.SetTitle(fmt.Sprintf("%d bytes", len(text)))
		app.Draw()
	})

	go func() {
		n := 1
		for {
			fmt.Fprintf(textView, "line %d\n", n)
			n++
			time.Sleep(200 * time.Millisecond)
		}
	}()

	if err := app.SetRoot(textView, true).Run(); err != nil {
		panic(err)
	}
}
```

When I ran this code, I observed that the screen would be empty after it was full.
But according to the TextView documentation, it should be that only text that is above the top of the screen will be discarded.

>    If the text is not scrollable, any text above the top visible line is discarded.

So what am I doing wrong?

**Comment by dzpao** [comment]
I have retired several versions and located the problem that should be introduced by fc28d64. The behavior of previous versions of this version is as expected.

**Comment by rivo** [comment]
Thanks. It was really just a typo in the code. Should be fixed now.
