### ISSUE TITLE
Table: be able to fix the width of each column when scrolling

### ISSUE THREAD

**Issue by cespedes** [rivo/tview#345]
In some cases, it would be nice to have the width of all the columns in a Table fixed, so that when using a large table with cells of different size and scroll through it, every column is always in the same place.

I needed this functionality for one of my projects, so I already forked tview and patched it in https://github.com/cespedes/tview adding a SetFixedColumnsWidth(bool) to *Table

It would be nice if you could merge it (or implement it in any other way), so that I could use the main repository instead of a fork.

Thank you,

**Comment by cespedes** [comment]
After reviewing the issues, I see this one is similar to #119 but I still think it would be good if the package could provide one way to fix the columns width...

**Comment by rivo** [comment]
Thanks. I added this. It has a different name, though. See the referenced commit.
