### ISSUE TITLE
Pasting into inputField is slow

### ISSUE THREAD

**Issue by Eucyon** [rivo/tview#349]
Pasting a string with ~ more than 100 characters from the clipboard into an inputField is much slower than pasting the same string into the terminal directly.

**Comment by rivo** [comment]
Yes. There's not much I can do about this. [`tcell`](https://github.com/gdamore/tcell) generates one keyboard event for each character so I cannot bundle them. There will be attempts to speed up redrawing the screen in general but these will only be incremental. I don't expect this to get better significantly. Sorry.
