### ISSUE TITLE
Autocomplete on Form InputFields

### ISSUE THREAD

**Issue by IdlePhysicist** [rivo/tview#350]
I see that Autocomplete functionality has been added to the InputField class (#299). But would be possible to add it to the Form class too? 

Or is it already possible to use in the Form class?

**Comment by rivo** [comment]
Yes, it is. You can add your own `InputField` object to a `Form` using [`Form.AddFormItem()`](https://godoc.org/github.com/rivo/tview#Form.AddFormItem). (`InputField` implements the `FormItem` interface.)
