### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by tupyy** [rivo/tview#351]
Hello.
Great work!! I'm using tview to create a simple app with one TextView and a Table. 
I'm trying to display large log files in the TextView and I'm doing this from go routine.
My problem is I don't know how to debug the app. Every time when I'm trying to debug it crashes.
I tried delve alone (not passing by vs code debugger or vim-go) with no success.
Could you point me in the right direction please?
Thanks
Cosmin

**Comment by Bios-Marcel** [comment]
Can you show any error output?

**Comment by tupyy** [comment]
There's no output. 
It just freeze but I've found the `headless` option in delve.
I'll try and let you know how it goes.

**Comment by tupyy** [comment]
I confirm that the debug must be done as:
`delve --headless debug module`.
It is not an issue of tview.
