### ISSUE TITLE
Unable to update primitives

### ISSUE THREAD

**Issue by zmnpl** [rivo/tview#352]
Hi, maybe it's jut too late and honestly I'm feeling stupid to ask... But I am unable to update primitves once the app is run. Take the minimal example from "Hello World":

```
package main

import (
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	box := tview.NewBox().SetBorder(true).SetTitle("Hello, world!")
	if err := app.SetRoot(box, true).Run(); err != nil {
		panic(err)
	}
	// time.Sleep(time.Second)
	// fmt.Println(5*time.Second)
	box.SetTitle("foo")
	app.Draw()
}

```

The box title simply doesn't change. It seems that this part of the code is not even reached until I terminate the application. 
I added the commented lines and those only seem to be executed after I Ctrl+C'd the app.

Please enlighten me. I know I'm missing something obvious... what am I doing wrong =)

**Comment by Bios-Marcel** [comment]
The call to `Run` is blocking, therefore the following code only gets executed if you kill the application, which is what happens when hitting Ctrl-C. If you wanna execute any further logic, trigger it either by user interaction or start a new goroutine and use `QueueUpdateDraw` like this:

```go
app.Run()
go func() {
    time.Sleep(5*time.Second)
    app.QueueUpdateDraw(func() {
        box.SetTitle("New")
    })
}()
```

**Comment by zmnpl** [comment]
Thats spot on. Thank you and have a good day kind sir!
