### ISSUE TITLE
Question about Pages.SetChangedFunc() callback

### ISSUE THREAD

**Issue by pktgen** [rivo/tview#355]
When I set the callback I do get the callback when a page changes focus. My question is what can I do with the callback as I do not seem to have any context as to what page changed. It seems like the callback should be passing in a values(s) to allows some action based on the change. Maybe I am using it wrong.

Here is what I want to do and maybe you can suggest a different approach.

I have say three pages '1', '2' and '3' using the keyboard numbers to switch pages. When I am on page '3' then press '1' to bring up page '1' I would like page '3' get a callback to shutdown or release resources.

Any suggestions?

**Comment by Bios-Marcel** [comment]
Could still access the Pages struct from within the callback. That's what I'd at least.

**Comment by rivo** [comment]
Multiple pages can be visible at the same time so there is not really *one* page that I could supply to that "changed" callback. But you are right in that `Pages` doesn't provide many functions to inspect its current state. To make your example easier, I added a function [`GetFrontPage()`](https://godoc.org/github.com/rivo/tview#Pages.GetFrontPage) which should solve your problem. Let me know if this helps.
