### ISSUE TITLE
Regression: table cell width broken for certain unicode chars

### ISSUE THREAD

**Issue by Sacules** [rivo/tview#357]
Hi, I've upgraded tview to the latest version (from `f8bc69b90341` to `685bf6da76c2`), and seems that it can't properly calculate the width of some cells with special Unicode chars, like the following:

![image](https://user-images.githubusercontent.com/31902745/67625280-70f95900-f812-11e9-9f85-0a9d6f039cec.png)
![image](https://user-images.githubusercontent.com/31902745/67625284-7c4c8480-f812-11e9-8bdd-52007dbe403c.png)
![image](https://user-images.githubusercontent.com/31902745/67625287-8a020a00-f812-11e9-9e57-f3b870827cdf.png)

This also happens if the cells are at the top of the Table.
![image](https://user-images.githubusercontent.com/31902745/67625308-d8afa400-f812-11e9-9688-20290bb7e895.png)

Text in question is `２８１４`.

**Comment by tslocum** [comment]
I was having similar issues, upgrading go-runewidth resolved them.  I've just added a PR to update the dependency in tview.

**Comment by rivo** [comment]
This was closed implicitly with the merge of #390.

@Sacules can you let me know if your issue is resolved in the latest version?

**Comment by Sacules** [comment]
Yup, I can confirm it works properly now :). Thanks!
