### ISSUE TITLE
Modal buttons: Reset to buttonIndex = 0 ?

### ISSUE THREAD

**Issue by triddell** [rivo/tview#360]
Thanks for tview! I'm now getting back into a project I worked on months back and am very much enjoying this library once again. However, I have an issue that I can't seem to get past.

I'm implementing a modal dialog with text like `Warning: Bad things may happen... are you very sure you want to continue?` And the buttons would read `No way!` and `Of course, I've got this!`

However, the modal dialog is remembering the last selected button index! So if on one attempt, `Of course, I've got this!` is chosen, then the next time the modal dialog is shown, `Of course, I've got this!` is the default value! And with only two buttons displayed, it's hard for the end user to know which button is actually highlighted.

Is there a way to reset the buttonIndex to 0 when redisplaying a model dialog? I believe you added `form.SetFocus(0)` support to forms for a somewhat similar issue.

**Comment by millerlogic** [comment]
I'd also like to be able to set which button I want initially focused. Perhaps a ```SetButtonFocus(index int)```?

**Comment by triddell** [comment]
I just added PR #364 which resolves this issue for me. Please accept or modify as necessary. Thanks.

**Comment by rivo** [comment]
I provided the change myself, mostly because you copy&pasted the function comment from `Form` which didn't make much sense in `Modal`'s context. Anyway, this should be resolved now.
