### ISSUE TITLE
Document charsets / encodings support

### ISSUE THREAD

**Issue by sveinburne** [rivo/tview#37]
Hi and thanks for your awesome work.
I haven't seen any information on the accepted [charsets](http://man7.org/linux/man-pages/man7/charsets.7.html) compatible with this library.
Could you perhaps add information on your README ?

For example

- Are some UI elements using non-ASCII characters ?
- Does it assumes the configured encoding is UTF-8 ?
- What happens if the end-user has the `$LANG` variable set to another encoding like ISO-8859 or UCS-2 ?

Thank you again,

J

**Comment by rivo** [comment]
Hi, `tview` is based entirely on https://github.com/gdamore/tcell. You may want to look there for more information about charsets. The [tcell documentation](https://godoc.org/github.com/gdamore/tcell) says this:

> If the environment is not Unicode by default, such as an ISO8859 based locale or GB18030, Tcell can convert input and outupt, so that your terminal can operate in whatever locale is most convenient, while the application program can just assume "everything is UTF-8". Reasonable defaults are used for updating characters to something suitable for display. Unicode box drawing characters will be converted to use the alternate character set of your terminal, if native conversions are not available. If no ACS is available, then some ASCII fallbacks will be used.

I'm using some UTF-8 box drawing characters (and an ellipsis character) which are listed [here](https://godoc.org/github.com/rivo/tview#pkg-constants). To be honest, though, I haven't tested how these translate to other terminals that don't support them. If you can shed some light, that would be great.
