### ISSUE TITLE
"Optional keyboard shortcuts" - List

### ISSUE THREAD

**Issue by shilangyu** [rivo/tview#371]
The godoc in [the introduction](https://godoc.org/github.com/rivo/tview#hdr-Widgets) states:

> ...
> \- List: A navigable text list with optional keyboard shortcuts.
> ...

However i was not able to find any info on how to get rid of the shortcuts. Im trying to make a list without these shortcuts, how could i achieve that?

**Comment by rivo** [comment]
For `List` objects, you define the shortcuts yourself when calling `AddItem()` or `InsertItem()`. See the documentation:

> The shortcut is a key binding. If the specified rune is entered, the item is selected immediately. Set to 0 for no binding.

So if you provide `0`, there will be no such shortcut.

However, the arrow keys etc. will still work. If you need to, you can also get rid of them. Please have a look at [`SetInputCapture()`](https://godoc.org/github.com/rivo/tview#Box.SetInputCapture). It works for `List`, too.

Let me know if you have any further questions.

**Comment by shilangyu** [comment]
Completely missed the `Set to 0 for no binding.` part, thanks and sorry!

**Comment by rivo** [comment]
No problem. 😊
