### ISSUE TITLE
[Question] Why fullscreen is not a Box property?

### ISSUE THREAD

**Issue by abitrolly** [rivo/tview#374]
It is not obvious that bool argument to `app.SetRoot(list, true)` is `fullscreen` flag. Maybe it is better to maintain it as a Box property and init with `tview.Box().SetFullScreen(true)`?

**Comment by rivo** [comment]
`tview` is not like HTML where every element decides what size it is. It's a top-down layout. So if there's only one primitive, it's the application itself that makes it full-screen.
