### ISSUE TITLE
Example of adding shortcuts to component

### ISSUE THREAD

**Issue by abitrolly** [rivo/tview#375]
Learning `tview` slowly. So far so great. :)

I already found `SetInputCapture` for adding shortcuts to component. Still I feel like https://github.com/rivo/tview/wiki could provide a ready to use example for that use case.

Basically pasting https://github.com/rivo/tview/wiki/Primitives#hooking-into-key-events into its own page.

**Comment by rivo** [comment]
Feel free to send me a link to a gist with a tutorial. It should be similar to the existing tutorials, with examples, explanations etc.  If it is, I'll add it to the Wiki.
