### ISSUE TITLE
TreeView: method to wrap entries or get minimal width

### ISSUE THREAD

**Issue by problame** [rivo/tview#376]
I have a `Flex` with `TreeView | DetailView`.
The `TreeView`'s entry titles have variable sizes unknown at the time the TreeView is added to the `Flex`.

I want to resize the `TreeView` to an **ideal fixed width** such that the entry titles are shown completely.

`Flex.ResizeItem` allows resizing, but there is no way to get the ideal width from `TreeView`, i.e., after it added all indents, etc.

What is the best way to accomplish this?

**Comment by rivo** [comment]
The package currently does not provide methods to calculate such a width. `tview`'s layout is top-down so you have to know yourself how much space you give each element in a `Flex`.

Probably the best way is to determine the depth of your item (times the number of characters `tview` adds per branch) plus the width of your text (using something like [`runewidth.StringWidth()`](https://godoc.org/github.com/mattn/go-runewidth#StringWidth)). For multiple items, you'll need to use the maximum over these widths.

Let me know if  this helps you in any way.

**Comment by rivo** [comment]
Will reopen if this turns out not to be resolved.
