### ISSUE TITLE
resize flashing on windows

### ISSUE THREAD

**Issue by tony--** [rivo/tview#377]
My team is using tview for a console application and our QA team reported a usability bug.  When the window is resized on Windows, the screen flashes.  The flashing continues for a short time after the resize is finished.  It isn't a huge issue, but it is a little ugly.  I captured a gif that shows the flashing.  I resized a few times, with some ridiculous resizes just to emphasize the effect, but you can see that it still occurs with a normal resize:
![tview_redraw_flashing](https://user-images.githubusercontent.com/513830/70582356-1f611f80-1b6f-11ea-95e7-7720a2ee299b.gif)

I believe this can be mitigated by adding some throttling to [the EventResize handling here](https://github.com/rivo/tview/blob/master/application.go#L240).  I'll open a PR with a suggested fix, but I'm not very experienced with golang so please go easy on me!

**Comment by rivo** [comment]
Shuold be fixed with the latest commit (see #378).
