### ISSUE TITLE
How to set display attributes (bold, underline, reverse etc.) on a TreeNode?

### ISSUE THREAD

**Issue by polyzium** [rivo/tview#379]
I'd like my applications to be compatible with real DEC VT terminals. Applications using tcell/tview like to discard colours if `TERM=vt***` e.g. `vt320`. When I was about to fix an application, I couldn't find `SetAttribute` or something like that for `TreeNode`s. So for example if I want to set the currently selected `TreeNode` in a `TreeView`, for `xterm` or similar I simply set the color using `SetColor`. But if I want to indicate that on DEC VT320 for example, I need to set the underline attribute on that node, and I don't have the function for that.

**Comment by rivo** [comment]
You'll want to prepend the text of your tree node with a color tag `[::u]`. That should do the trick.

**Comment by rivo** [comment]
Will reopen if more information is needed.
