### ISSUE TITLE
Help: show modal dialog on table view

### ISSUE THREAD

**Issue by labkode** [rivo/tview#381]
I'm creating an application based on the presentation tview demo.

I'm reusing the table code for one of the pages and I want that when I click 'e' on one of the table rows a modal appears to modify the row. I've done the logic capture the key event and perform any action but the modal is not showing. 

```
	table.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		selected, _ := table.GetSelectable()

		if event.Key() == tcell.KeyEnter {
			table.SetSelectable(true, true)
		}

		if selected && event.Key() == tcell.KeyRune && event.Rune() == 'e' {
			// find row
			row, col := table.GetSelection()
			cell := table.GetCell(row, col)

			modal := tview.NewModal().
				SetText("Name: " + cell.Text).
				AddButtons([]string{"Save", "Cancel"}).
				SetDoneFunc(func(buttonIndex int, buttonLabel string) {
					if buttonLabel == "Cancel" {
						app.Stop()
					}
				})
			app.SetFocus(modal)
			app.ForceDraw()
		}
		return event
	})
```

Thanks and Happy Christmas!

**Comment by Bios-Marcel** [comment]
The modal is just a primitive (Widget), you actually have to set it as the root layout primitive using Application#SetRoot.

**Comment by labkode** [comment]
@Bios-Marcel that would break the layout.

**Comment by Bios-Marcel** [comment]
Drawing things ontop of other things isn't supported afaik.

**Comment by labkode** [comment]
@Bios-Marcel is possible I just managed. The magic is to set the current view as the background of the modal. 

Is explained here: https://github.com/rivo/tview/wiki/Modal

**Comment by Bios-Marcel** [comment]
Oh cool, guess I learned something then, thanks ^^

**Comment by agruenberg** [comment]
Or you use pages, where you put the modal on top most.

**Comment by LazarenkoA** [comment]
> @Bios-Marcel is possible I just managed. The magic is to set the current view as the background of the modal.
> 
> Is explained here: https://github.com/rivo/tview/wiki/Modal

Hi. I have a similar task, can you share the code? Have you used Pages (as in the demo)?

**Comment by LazarenkoA** [comment]
> > @Bios-Marcel is possible I just managed. The magic is to set the current view as the background of the modal.
> > Is explained here: https://github.com/rivo/tview/wiki/Modal
> 
> Hi. I have a similar task, can you share the code? Have you used Pages (as in the demo)?

made it using Pages
