### ISSUE TITLE
Make items in Flex public

### ISSUE THREAD

**Issue by esell** [rivo/tview#385]
Does it make sense to expose the `items` variable in the Flex primitive (https://github.com/rivo/tview/blob/master/flex.go#L31) ? 

The reason I am asking is I have a simple 4 column layout where I would like to cycle through each column when a certain key is pressed. Right now I've setup a `SetInputCapture()` to listen for the key press and then `SetFocus()` on the next item, effectively moving the focus from column to column. The problem with this method is that I need to hard code the primitive that should get focus next. It would be awesome to be able to just use something like `flex.Items[n+1]` or something similar. Since the data is already there in the `items` variable, it seems like a great data source for something like this.

**Comment by tslocum** [comment]
Hey @esell, does a `Flex.GetItem` method which returns the primitive at that index solve your use case? I will submit a PR adding it if so.

**Comment by esell** [comment]
Good timing @tslocum :). I actually just swapped out for your cview and used the Flex.GetChildren (https://godoc.org/git.sr.ht/~tslocum/cview#Flex.GetChildren) function, it was exactly what I was looking for.
Before that I was just keeping track of everything in a slice I created.
