### ISSUE TITLE
Feature Request: colspan for table

### ISSUE THREAD

**Issue by askovpen** [rivo/tview#387]

**Comment by askovpen** [comment]
like this:
<table>
    <thead>
        <tr>
            <th>Layer 1</th>
            <th>Layer 2</th>
            <th>Layer 3</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td >L1 Name A</td>
            <td >L2 Name A</td>
            <td>L3 Name A</td>
        </tr>
        <tr>
            <td colspan=2 align=center>L1-L2 Name B</td>
            <td>L3 Name B</td>
        </tr>
        <tr>
<td >L1 Name C</td>
            <td >L2 Name C</td>
            <td>L3 Name C</td>
        </tr>
    </tbody>
</table>

**Comment by tslocum** [comment]
You may have already considered this: a `Grid` may be able to fill this role, however you must take care of updating its elements as the user scrolls / changes focus.
