### ISSUE TITLE
Help with table border

### ISSUE THREAD

**Issue by vito-c** [rivo/tview#393]
I have a table that has more content than can fit on the screen.  Everything works fine but I was  wondering why the table gridline doesn't show up at the bottom. Ideally I would like it so the table  fits inside the border box and is scrollable. If I shrink the font of my terminal so that the table is completely inside then it shows everything and the table fits  inside the bounding box.

Is  there  a way to set the number of viewable rows AND have it scrollable?

![image](https://user-images.githubusercontent.com/820137/72922241-8bec4400-3d01-11ea-86b4-7280f5389b02.png)

**Comment by agruenberg** [comment]
How did you get the icons inside the table?

**Comment by tslocum** [comment]
Those are emojis (terminal support for them is still maturing, FYI).

**Comment by vito-c** [comment]
🔥✅❌

**Comment by rivo** [comment]
In your screenshot, there is no space to draw the bottom line so it gets cut off. I guess you could try to resize the `Table` widget so that its height is always an even number.
