### ISSUE TITLE
SetDoneFunc in TreeView and List

### ISSUE THREAD

**Issue by agruenberg** [rivo/tview#394]
Hi, first of all: Thank you for your great work and your effort.
I have a List next to a TreeView and would like to switch with the Tab key. I don't know if I missed something, but it seems, that there is no SetDoneFunc in the TreeView and the SetDoneFunc in the List reacts only by pressing the Esc Key.
Any suggestions how to implement the desired behavior?

Thank you
![Bildschirmfoto von 2020-01-23 23-45-04](https://user-images.githubusercontent.com/19472717/73030824-baba0580-3e3a-11ea-8f15-8b0c5e008086.png)

**Comment by tslocum** [comment]
Hey @agruenberg, you're looking for TreeNode.SetSelectedFunc and TreeView.SetSelectedFunc

**Comment by agruenberg** [comment]
@tslocum thank you, but SetSelectedFunc is called by hitting enter. I'm searching for a handlerFunc where I can evaluate, which key was pressed. Usually you navigate with the tab key, therefore my question.

**Comment by rivo** [comment]
Yeah, that one was missing.

Actually, introducing this, I had to remove Tab/Backtab navigation for the `TreeView`. Since this is just a minor change, I think that's ok. (And it's more in line with other primitives.)

**Comment by agruenberg** [comment]
@rivo great! Thank you very much!
