### ISSUE TITLE
How can I get the value of form's element?

### ISSUE THREAD

**Issue by mostafa-asg** [rivo/tview#4]
Hi
First of all, thanks for your great work.
In the [data entry form](https://github.com/rivo/tview/wiki/Form) sample, How can I get the values of form?  
For example in *Save* button, how can I get the value of *first name* input field?
```Go
AddButton("Save", func() {
   // I want something like this
  firstName := form.getInputField("SOME_TEXT_BOX_ID").value()
})
```

**Comment by rivo** [comment]
You're right, this was missing. I don't have form element IDs so it doesn't quite work as in your example. But you now have two options:

(1) Added a change event listener to the input field in the form:

```go
form.AddInputField("First name", "", 20, nil, func(text string) { /* handle the changed text */ })
```

(2) You get the field directly (by its index) and call one its getter (requires a cast, though):

```go
inputField := form.GetElement(0).(*tview.InputField)
text := inputField.GetText()
```

**Comment by mostafa-asg** [comment]
Thank you

**Comment by rivo** [comment]
Please note that I've just committed a change which renames `GetElement()` to `GetFormItem()` for consistency reasons. I hope this won't cause too much trouble.
