### ISSUE TITLE
[Windows] Resize event not sending updated width and height

### ISSUE THREAD

**Issue by kvnxiao** [rivo/tview#401]
Compiling any of the demos on windows and trying to run the exe both directly and through cmd, powershell, and Windows Terminal, the UI does not refresh after resizing at all!

I have to manually press a key for the UI to refresh.

Editing `application.go` and adding `screen.Sync()` before `newWidth, newHeight := screen.Size()` seems to fix it?

Not sure exactly why this issue is happening?

**Comment by tslocum** [comment]
According to the tcell docs on [Screen.Size](https://github.com/gdamore/tcell/blob/2fca0432ba2d854410ab0a63d7d6f3f9ce3a5e48/screen.go#L77):

> Size returns the screen size as width, height.  This changes in response to a call to Clear or Flush.

Clear was not being called before retrieving the new screen size.  I've submitted a PR to resolve this.

**Comment by rivo** [comment]
I made the change that @tslocum suggested. This will hopefully solve your problem. If not, please open a new issue. (I might not see it here anymore.)
