### ISSUE TITLE
Table pageUp & pageDown ignores fixedRows

### ISSUE THREAD

**Issue by mjlumley** [rivo/tview#402]
With a table longer than one page, if you page up or down with fixedRows set to 1 or greater, the text moves up or down the page size including the number of fixedRows, so if you are paging through values, you'll miss out on seeing one (or more) values. For instance if the current number of rows is 1 fixed + 6 non-fixed, the page up/down will move 7 rows when it should (perhaps) only move 6.

You may want to adjust the value of visibleRows in the Draw func when fixedRows is not zero, or perhaps adjust for fixedRows in the InputHandler in the pageUp/pageDown func.

**Comment by rivo** [comment]
Thanks.
