### ISSUE TITLE
QueueUpdateDraw & Draw causes deadlock

### ISSUE THREAD

**Issue by tryffel** [rivo/tview#416]
I bisected the commit to [fe30520](https://github.com/rivo/tview/commit/fe3052019536251fd145835dbaa225b33b7d3088).

I use it as such:
```
//goroutine1 (same as tview):
Application.Draw()

//goroutine2:
Application.QueueUpdateDraw(func() {...})
```
Both goroutines are now deadlocked at 
application.go:524: 
```
<- ch
``` 

Using go1.14 linux/amd64.

**Comment by SoMuchForSubtlety** [comment]
I noticed a similar issue.
Previously this worked
```go
func main() {
	app := tview.NewApplication()
	text := tview.NewTextView()
	text.SetChangedFunc(func() { app.Draw() })
	app.SetRoot(text, true)
	fmt.Fprint(text, "text test")
	app.Run()
}
```
But now it deadlocks.

I also encountered the ChangedFunc `app.Draw()` locking when the application is running. I will try to reproduce it,

**Comment by sarpdoruk** [comment]
+1 on this.

Having `app.Draw()` in `SetChangedFunc` of `textView` makes whole app crash/freeze/unresponsive.

**Comment by rivo** [comment]
The latest commit fixes the problem in @SoMuchForSubtlety's code but I'm not completely sure if your issues are also fixed. Please let me know so I can close this issue (again).

**Comment by tryffel** [comment]
Yes it fixed this. Thanks =)

**Comment by miltalex** [comment]
The issue still persists. Using go1.14.1 darwin/amd64

**Comment by rivo** [comment]
Can you please paste some code that causes this deadlock?

**Comment by rivo** [comment]
Please open a new issue and reference this one if you want me to follow up on this topic.
