### ISSUE TITLE
List PgUp and PgDn window is hardcoded to 5 items

### ISSUE THREAD

**Issue by abitrolly** [rivo/tview#417]
I expected List element to scroll contents according to page height. It doesn't. Because it uses hardcoded page size of 5 elements. Is it possible to fix that?

https://github.com/rivo/tview/blob/cd38d7432498210b9a1bba38ea841b461f7f9c7b/list.go#L501-L504

**Comment by rivo** [comment]
Thanks.  You're right and to be honest, I don't remember why I set this to 5. (This was very early  code, I may not have had the `GetInnerRect()` function yet.)
