### ISSUE TITLE
Feature request: turn off a specific attribute using color tags

### ISSUE THREAD

**Issue by nojus297** [rivo/tview#420]
Currently, the only way one can reset all text attributes with a color is using `[::-]`. This therefore makes it hard to print text like 
normal ~~underlined __bold underlined__ underlined~~ normal
(instead of strikethrough should be underlined)
as all the attributes are removed. Maybe a `!b` could turn off bold only, or if you want to keep single character tags the letter case could determine the difference.

The above example could be accomplished by something like this:
`normal [::u]underlined [::b]bold underlined[::!b] underlined[::!u] normal`
or
`normal [::u]underlined [::b]bold underlined[::B] underlined[::U] normal`
Let me know how this sounds, I can open a PR if this would be suitable for tview.

**Comment by rivo** [comment]
I think this makes sense. I will look into this myself. No need to submit a PR.

**Comment by nojus297** [comment]
I realized that I had a wrong view of these attribute tags. I wrongly assumed that they would stack continuously, that is something like `[::b]A[::u]B` would result in `A` being bold and `B` being both bold and underlined. But actually `A` would only be bold and `B` - only underlined.

This means that you cannot add a single attribute to the current mask and therefore it wouldn't probably make too much sense to have the ability to disable a single one as well.

**Comment by rivo** [comment]
@nojus297 Coming back to this due to #619, your last message here makes it sound like your request wasn't so much about turning off individual attributes but stacking styles. In that case, I'd rather refer to #619 and close this issue.

**Comment by nojus297** [comment]
Sounds good to me

**Comment by rivo** [comment]
Btw, attributes can now also be turned off individually.
