### ISSUE TITLE
SetInputCapture isn't fired on a parent component

### ISSUE THREAD

**Issue by k33nice** [rivo/tview#421]
For me, it's pretty unintuitive that `SetInputCapture` isn't called if a child is focused and the event key was fired. Also `HasFocus` method returns true for the parent block.

```go
func main() {
	app := tview.NewApplication()

	first := tview.NewBox().SetBorder(true).SetTitle("First")
	second := tview.NewBox().SetBorder(true).SetTitle("Second")

	flex := tview.NewFlex().
		AddItem(first, 0, 1, false).
		AddItem(second, 0, 1, false)

	flex.SetInputCapture(func(e *tcell.EventKey) *tcell.EventKey {
		log.Print("Will never gets here")
		return e
	})

	if err := app.SetRoot(flex, true).SetFocus(first).Run(); err != nil {
		panic(err)
	}
}
```

I've found a simple workaround. IMO it looks a bit hacky:

```go
	app.SetInputCapture(func(e *tcell.EventKey) *tcell.EventKey {
		if flex.HasFocus() {
			flex.GetInputCapture()(e)
		}
	})
```

**Comment by rivo** [comment]
I agree with you that this is not optimal. It was an early design decision to keep a global pointer to one element which has focus and route all keyboard input to it directly. Maybe I wasn't sure why one would want to handle some input higher up at the same time (in a `Flex` in your case). The `HasFocus()` function (which, also in retrospect, should not be public but that's another topic) was basically just there to indicate which element has focus (with a two-line border around it) and that wouldn't work if it applied only to leaf elements.

For the newly added mouse support, we do it differently: Mouse events bubble down the tree and can be intercepted anywhere along the way. I will probably look at implementing keyboard input the same way. But I'll have to check how much this affects backwards compatibility.

For now, your workaround is probably the only way to make this work.

**Comment by rivo** [comment]
I implemented this just now. Please let me know if it works for you as you expect.
