### ISSUE TITLE
Feature request: Add getters of colors / attributes for the Box

### ISSUE THREAD

**Issue by bry00** [rivo/tview#427]
It would be useful when developing custom Widgets based on Box, to have possibility to get current value of properties `borderAttributes`, `borderColor`, `backgroundColor`. Currently, these are in fact, write-only properties, as there is group of "set" functions (`SetBorderAttributes`, `SetBorderColor`, `SetBackgroundColor`) but without their exported "get" counterparts one cannot use easily these values. 
It seems to be tiny but useful extension.

Something like this:
```golang

// GetBorderAttributes gets the border's style attributes.
func (b *Box) GetBorderAttributes() tcell.AttrMask {
	return b.borderAttributes
}

// GetBorderColor gets the box's border color.
func  (b *Box) GetBorderColor() tcell.Color {
	return b.borderColor
}

// GetBackgroundColor gets the box's background color.
func  (b *Box) GetBackgroundColor() tcell.Color {
	return b.backgroundColor
}

```

**Comment by rivo** [comment]
I added this with the latest commit.

**Comment by bry00** [comment]
Super, thx.
