### ISSUE TITLE
Panic on TextView.reindexBuffer

### ISSUE THREAD

**Issue by pengux** [rivo/tview#429]
Not sure what's the problem is but it should probably do a bound check and return an error instead of panic if it is out of bound. The stack trace:

```
panic: runtime error: slice bounds out of range [321:252] [recovered]
        panic: runtime error: slice bounds out of range [321:252]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc000885880)
        /home/peter/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200404204604-ca37f83cb2e7/application.go:244 +0x82
panic(0x8bde60, 0xc00039a160)
        /usr/lib/go/src/runtime/panic.go:967 +0x166
github.com/rivo/tview.(*TextView).reindexBuffer(0xc00143a000, 0x8c)
        /home/peter/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200404204604-ca37f83cb2e7/textview.go:719 +0x15bb
github.com/rivo/tview.(*TextView).Draw(0xc00143a000, 0x99a5a0, 0xc000cbe1c0)
        /home/peter/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200404204604-ca37f83cb2e7/textview.go:861 +0x17b
github.com/rivo/tview.(*Flex).Draw(0xc001804330, 0x99a5a0, 0xc000cbe1c0)
        /home/peter/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200404204604-ca37f83cb2e7/flex.go:183 +0x344
github.com/rivo/tview.(*Flex).Draw(0xc0018042d0, 0x99a5a0, 0xc000cbe1c0)
        /home/peter/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200404204604-ca37f83cb2e7/flex.go:183 +0x344
github.com/rivo/tview.(*Pages).Draw(0xc0018042a0, 0x99a5a0, 0xc000cbe1c0)
        /home/peter/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200404204604-ca37f83cb2e7/pages.go:278 +0xa8
github.com/rivo/tview.(*Application).draw(0xc000885880, 0x0)
        /home/peter/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200404204604-ca37f83cb2e7/application.go:582 +0xda
github.com/rivo/tview.(*Application).Run(0xc000885880, 0x0, 0x0)
        /home/peter/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200404204604-ca37f83cb2e7/application.go:332 +0x77d
main.run(0xc000036a80, 0xc00000f300, 0x1)
 
```

**Comment by rivo** [comment]
To determine the best solution to this, it would be helpful to be able to reproduce this panic. Can you please post a small program that will cause this panic?

**Comment by db-tech** [comment]
I've got the same error. For me the main problem was that i wrongly sliced a string.
It took me a while but I could reproduce it:

```go
func main() {
	var app = tview.NewApplication()
	bla := "├─XXXXXXXXX"
	textView := tview.NewTextView().SetWrap(true).SetText(bla[2:])
	textView.SetDrawFunc(func(screen tcell.Screen, x, y, width, height int) (int, int, int, int) {
		return x,y,10,height
	})
	if err := app.SetRoot(textView, true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}
}
```
Seems a problem with those special character, the slicing and the wrapping.
I've no time at the moment but could take a look at it next week.

**Comment by rivo** [comment]
Interesting. This appears to be a problem of converting strings to rune slices and back. If the original string contains invalid code points, the resulting string may be longer. See here:

https://play.golang.org/p/0PrzUP4_4cr

And that conversion is what happens in `go-runewidth`'s [`Truncate()`](https://github.com/mattn/go-runewidth/blob/f9aa72c7456cb586a8a4e22a73f2b1c6bce4ff54/runewidth.go#L148) function which I'm using. I will submit a pull request over there.

**Comment by rivo** [comment]
My long-running PR to `go-runewidth` was just merged and the latest version does not produce a panic anymore with the example posted above. Unless you find that this is still a problem, I will soon close this issue. If there is still a panic, please post a small code snippet to reproduce.

(If you find that this issue is already closed, please open a new issue and reference this one.)

**Comment by pengux** [comment]
I haven't tried out your PR but let's close this issue and I can create a new one if needed.
