### ISSUE TITLE
Fixed TextView on Grid

### ISSUE THREAD

**Issue by xidod** [rivo/tview#430]
Hello, I have a Grid with some primitive that needs resize but one primitive no, it is a TextView with  banner on top left of the terminal with indentation and if I resize the window also the banner in the TextView resize it self and the layout of the banner is destroyed.
Since the Application can hold only one primitive, is possible to have a primitive inside a grid not resizable? Or at least a workaround to this scenario?

Thank you.

**Comment by rivo** [comment]
I'm not exactly sure I understand your explanation but you can set fixed sizes on grid elements with the [Grid.SetColumns()](https://pkg.go.dev/github.com/rivo/tview?tab=doc#Grid.SetColumns) and [Grid.SetRows()](https://pkg.go.dev/github.com/rivo/tview?tab=doc#Grid.SetRows) functions.

If this doesn't answer your question, please provide a screenshot or something that illustrates what you would like to achieve.

**Comment by xidod** [comment]
[Grid.SetColumns()](https://pkg.go.dev/github.com/rivo/tview?tab=doc#Grid.SetColumns) is exactly what I need. 
Thank you!
