### ISSUE TITLE
Question marks showing instead of border for boxes.

### ISSUE THREAD

**Issue by LordRusk** [rivo/tview#438]
![pic-selected-200427-0933-10](https://user-images.githubusercontent.com/54194338/80397047-1b773500-88a5-11ea-8a6e-d67f9aaecbab.png)
When trying out the box demo, instead of a border, it only shows question marks. I'm using st, and I tried it with and without the boxdraw patch. It doesn't effect functionality, but if there's a way to fix it that anyone knows of, [that'd] be cool.

**Comment by tslocum** [comment]
Please try the solution mentioned in #406:

`export LC_CTYPE="en_US.UTF-8"`

**Comment by rivo** [comment]
I started a [FAQ](https://github.com/rivo/tview/wiki/FAQ) in the Wiki that contains this question because it's being asked quite often.

@LordRusk Please let us know if you were able to solve this problem.

**Comment by LordRusk** [comment]
@rivo yes, exporting that before the program is run, or putting it in my .profile worked.

**Comment by drujensen** [comment]
I'm not sure what's going on but I've tried the sample project on mac and linux with iterm2, apple terminal, and on linux xfce_terminal and I always get question marks.  I've tried several different profiles and fonts.

I'm new to golang, so if this is a rookie mistake, apologize in advance for wasting your time.

any help is appreciated!

```
drujensen:~/workspace/go/test
$go mod init github.com/drujensen/test
go: creating new go.mod: module github.com/drujensen/test
drujensen:~/workspace/go/test
$go get github.com/rivo/tview@master
go: downloading golang.org/x/term v0.17.0
go: downloading golang.org/x/sys v0.17.0
go: added github.com/gdamore/encoding v1.0.0
go: added github.com/gdamore/tcell/v2 v2.7.1
go: added github.com/lucasb-eyer/go-colorful v1.2.0
go: added github.com/mattn/go-runewidth v0.0.15
go: added github.com/rivo/tview v0.0.0-20250501113434-0c592cd31026
go: added github.com/rivo/uniseg v0.4.7
go: added golang.org/x/sys v0.17.0
go: added golang.org/x/term v0.17.0
go: added golang.org/x/text v0.14.0
drujensen:~/workspace/go/test
$nvim main.go
drujensen:~/workspace/go/test
$locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
drujensen:~/workspace/go/test
$go run main.go
```

![Image](https://github.com/user-attachments/assets/f42f96d4-e04a-4ed8-b40d-5bb65b9933cc)

![Image](https://github.com/user-attachments/assets/dcaa18f1-c149-479a-8ab2-6def012befcd)
