### ISSUE TITLE
Only shift key press event

### ISSUE THREAD

**Issue by Rasarts** [rivo/tview#45]
Hi,
I need handle only shift key press event. Without other keys with shift.
How I can do that?

**Comment by rivo** [comment]
Hi,

I don't think terminals provide us with that information. I'm using `tcell` to process key events. They give some information [here](https://godoc.org/github.com/gdamore/tcell#EventKey):

> For example, if the rune is 'A', this will be reported without the ModShift bit set, since really can't tell if the Shift key was pressed (it might have been CAPSLOCK, or a terminal that only can send capitals, or keyboard with separate capital letters from lower case letters).
>
> Generally, terminal applications have far less visibility into keyboard activity than graphical applications. Hence, they should avoid depending overly much on availability of modifiers, or the availability of any specific keys.

So I'm afraid you won't be able to listen to Shift key events.
