### ISSUE TITLE
Announcement: Window Manager for tview

### ISSUE THREAD

**Issue by jpeletier** [rivo/tview#450]
Hello,

I just finished [winman](https://github.com/epiclabs-io/winman), a simple, yet powerful window manager for `tview`. It supports floating windows, modal windows, resizable, draggable and more! Check it out here: [https://github.com/epiclabs-io/winman](https://github.com/epiclabs-io/winman).

![showcase](https://github.com/epiclabs-io/winman/raw/master/demos/showcase/showcase.gif)

Please let me know if there is a place to link tview-related building blocks for people to find it easily. Thanks.

**Comment by tsak** [comment]
Nice. Looks very impressive!

**Comment by makeworld-the-better-one** [comment]
Wow, awesome! Do you think it would work with [cview](https://gitlab.com/tslocum/cview/) as well?

**Comment by rivo** [comment]
Thanks for letting us know. I've added `winman` to the front page (the list of projects using `tview`). Cheers!
