### ISSUE TITLE
TextView.GetText(true) returns incorrectly stripped text

### ISSUE THREAD

**Issue by nojus297** [rivo/tview#453]
The method of `GetText` of `TextView` strips out the empty brackets too (`[]`).  Example code:
```go
package main

import (
	"github.com/rivo/tview"
)

func main() {
	text := "brackets[]here"
	tv := tview.NewTextView().SetDynamicColors(true).SetText(text)
	tview.NewApplication().SetRoot(tv, true).Run()
	// Displays brackets[]here
	println(tv.GetText(true))
	// Prints bracketshere
}
```
Possible solution: replace https://github.com/rivo/tview/blob/fe953220389fed743d3d5ee872695abab0ae68e0/textview.go#L290 with custom string replacing function:
```go
text = colorPattern.ReplaceAllStringFunc(text, func(match string) string {
	if len(match) != 2 {
		return ""
	}
	return match
})
```

**Comment by ghostsquad** [comment]
This definitely seems like a bug, since `[]` is not a valid color code according to the docs.

**Comment by rivo** [comment]
Thanks for catching this. The `ReplaceAllStringFunc` solution is a good way to fix it, which I did in the latest commit.
