### ISSUE TITLE
utils.go: Can't output normally if "[xxxx]" in string

### ISSUE THREAD

**Issue by Chen-Haohuang** [rivo/tview#456]
when I output a string into textview, I find it can't output normally if if "[xxxx]" in the string.
e.g.
```go
output = tview.NewTextView()
fmt.Fprintf(output, "%s", "before[unknown]after")
```
I want to show "before[unknown]after" in output textview, but it only leaves "before".
I know maybe I can use "before[unknown[]after", but I can't know what the string contains before I output.

I have found where the bug is.
In function:utils.go:decomposeString
```go
// Because the color pattern detects empty tags, we need to filter them out.
	for i := len(colorIndices) - 1; i >= 0; i-- {
		if colorIndices[i][1]-colorIndices[i][0] == 2 {
			colorIndices = append(colorIndices[:i], colorIndices[i+1:]...)
			colors = append(colors[:i], colors[i+1:]...)
		}
	}
```

We also need to filter it out if the tag is not a color tag. So I modified the function.

```go
// Because the color pattern detects empty tags, we need to filter them out.
	for i := len(colorIndices) - 1; i >= 0; i-- {
		fgColor := colors[i][colorForegroundPos]
		bgColor := colors[i][colorBackgroundPos]
		if colorIndices[i][1]-colorIndices[i][0] == 2  || (fgColor != "" && fgColor != "-" && tcell.GetColor(fgColor) == -1) || (bgColor != "" && bgColor != "-" && tcell.GetColor(bgColor) == -1) {
			colorIndices = append(colorIndices[:i], colorIndices[i+1:]...)
			colors = append(colors[:i], colors[i+1:]...)
		}
	}
```

**Comment by abitrolly** [comment]
Or just use `Escape()` function?

https://pkg.go.dev/github.com/rivo/tview?tab=doc#hdr-Colors

**Comment by rivo** [comment]
Checking for colour names will only work until somebody wants to output "[red]" without escaping it. It's not a good solution in my opinion.

As @abitrolly mentioned, there is an [`Escape()`](https://pkg.go.dev/github.com/rivo/tview?tab=doc#Escape) function. Or simply call [`textView.SetDynamicColors(false)`](https://pkg.go.dev/github.com/rivo/tview?tab=doc#TextView.SetDynamicColors) to ignore any colour tags.

**Comment by ghostsquad** [comment]
I'm a bit confused here. If someone wants to output the literal value of `[red]`, would you use `Escape()` first? then inject/wrap with color?

**Comment by ghostsquad** [comment]
Also, what happens if `[red]` shows up in the text along with ANSI Escape Codes? Would you first `Escape()`, then use `TranslateANSI()` ?

**Comment by rivo** [comment]
> If someone wants to output the literal value of [red], would you use Escape() first? then inject/wrap with color?

I guess that's what I would do.

> Also, what happens if `[red]` shows up in the text along with ANSI Escape Codes? Would you first `Escape()`, then use `TranslateANSI()` ?

`TranslateANSI()` should do the escaping for you. There should be no need to call `Escape()` first if you're translating ANSI escape sequences. If that doesn't work, it's a bug and I have to fix it. (Please let me know if that's the case.)

**Comment by rivo** [comment]
Please let me know if any more help is needed. If not, I'll close the issue soon.
