### ISSUE TITLE
question: why convert ansi escape sequences to "color codes"

### ISSUE THREAD

**Issue by ghostsquad** [rivo/tview#464]
This is just a design question of why you chose to convert ansi escape sequences to "color codes"?

**Comment by rivo** [comment]
The colour tags came first. I wanted a simple way to add colour to widgets*.

But then there were users who wanted to display the output of other processes in a `TextView`, including colour. So now there's a convertor for ANSI escape sequences.

---

* Of course, for some, it's too simple. And it makes it difficult for others who frequently need to display square brackets without changing colours. But it's hard to please everyone so there's a tradeoff here.
