### ISSUE TITLE
not working in git bash

### ISSUE THREAD

**Issue by LazarenkoA** [rivo/tview#469]
I tried to run a demo example in cmd and git bash (windows), in cmd it works, in git bash not work, maybe something else needs to be done for a console like git bash, or is this a particularity of git bash?

**Comment by rivo** [comment]
I'm not very familiar with Git Bash so I can't offer any quick settings that might help you run `tview`. If you need someone to follow up on this, please open an issue on https://github.com/gdamore/tcell as that is the library `tview` uses to display characters on screen. If `tcell` works, `tview` will work, too.

**Comment by LazarenkoA** [comment]
thank
