### ISSUE TITLE
A possibility to show stacked boxes 

### ISSUE THREAD

**Issue by aellwein** [rivo/tview#47]
Hey,

short question: is there a possibility to show stacked boxes/frames (one over another). Like in [here](http://urwid.org/_images/cmenu4.png). If yes, how they are supposed to be arranged in ``tview.Application``?

**Comment by rivo** [comment]
Hi,

I would say your best bet is the [`Pages`](https://godoc.org/github.com/rivo/tview#Pages) class. Its [`AddPage()`](https://godoc.org/github.com/rivo/tview#Pages.AddPage) function has a "resize" parameter which you can set to `false` so your box doesn't become full-screen.

You will have to set the position and size of each of your boxes yourself then. There is no function that lays out boxes automatically like you requested. I think [VladimirMarkelov/clui](https://github.com/VladimirMarkelov/clui) attempts to provide a more Windows-like interface if that's what you prefer.

Let me know if this helps.

**Comment by aellwein** [comment]
Thanks, that is exactly what i've searched for.
