### ISSUE TITLE
Question. How to handle a mouse click on a table cell

### ISSUE THREAD

**Issue by LazarenkoA** [rivo/tview#470]
The task is to perform some actions when clicking on a cell in the table heading, for example, sorting by the current column, how to implement this?

PS
I tried searching in the documentation, did not find

**Comment by LazarenkoA** [comment]
i found, SetMouseCapture

**Comment by LazarenkoA** [comment]
just don't know how to get a cell by position

**Comment by rivo** [comment]
There is the [`Table.SetSelectionChangedFunc()`](https://pkg.go.dev/github.com/rivo/tview?tab=doc#Table.SetSelectionChangedFunc) which you can use. The callback will receive the position of the clicked cell.

Let me know if this helps.

**Comment by LazarenkoA** [comment]
Thanks, but it will not work for my case, I click on the table header, but it is set for it SetSelectable(false)

**Comment by rivo** [comment]
I understand. Makes sense. I've added [`TableCell.SetClickedFunc()`](https://godoc.org/github.com/rivo/tview#TableCell.SetClickedFunc). That should help you implement the sorting function in your table.

**Comment by LazarenkoA** [comment]
I have 2 questions ☺
1. I do `go get -u "github.com/gdamore/tcell@master"` but I don't see the method `SetClickedFunc()`. 
2. how can I find out the cell position? I can't call the current cell from the function (it is got as a parameter)
