### ISSUE TITLE
Improve support for using colors in autocomplete input fields?

### ISSUE THREAD

**Issue by khughitt** [rivo/tview#472]
One more quick idea -- 

Would it be possible to modify autocomplete to make it easier to include choices which are colored differently?

Currently, autocomplete display text in different colors just fine, however, to actually match one of the words, you have to type the color expression in the input field.

For example, for the string "[#ff0000] word" to match, you have to start with the "[".

It would be nice if there was an option to indicate that colors should still be _displayed_ in the autocomplete options, but otherwise stripped from the strings that are being matched against.

Another possible approach would be to allow Maps to be used, with each entry corresponding to a `(label, text)` pair.

**Comment by khughitt** [comment]
Nevermind!

Just realized this was my fault for using `strings.HasPrefix()` in the `inputField.SetAutocompleteFunc()` function.

Switching to a different approach to matching fixed the issue.

Please ignore :)

**Comment by khughitt** [comment]
Reopening for different but related issue (still having to do with color + autocomplete support):

when navigating through autocomplete choices, colors and formatting are rendered as expected, however, in the text that is shown in the inputField, the unformatted text (e.g. `[#ff0000][::b]match...`) is shown instead of the rendered text.

**Comment by rivo** [comment]
That's actually a bug. Colour tags should not appear in the input field when you make an autocomplete selection. I fixed this in the latest commit.

**Comment by khughitt** [comment]
Thanks for the fix! It's much appreciated.
