### ISSUE TITLE
Allow specifying direction of DropDown widget?

### ISSUE THREAD

**Issue by khughitt** [rivo/tview#473]
When a DropDown menu is used near the bottom of the screen, it would be nice to be able to indicate that entries should be displayed in an upwards direction (e.g. similar to `fzf`'s default behavior)

Ideally, option would be extended to AutoComplete functionality as well.

**Comment by rivo** [comment]
This should already be the case. Can you post an example where it doesn't work?

**Comment by khughitt** [comment]
@rivo I just tried to reproduce the issue and it seemed to behave well, so I'm not sure what the issue was.

I usually try and provide more helpful information to reproduce the issue. I think I had just assumed some of the things were expected behavior.

In any case, I'll close this and re-open it if I ever encounter the issue again and can provide more useful feedback.
