### ISSUE TITLE
Allow specifying number of items needed to trigger "fullscreen" autocomplete list?

### ISSUE THREAD

**Issue by khughitt** [rivo/tview#474]
Currently, autocomplete appears to show ~3 items at a time initially when there are a lot of choices. As I type more characters and narrow down the choices, at some point, the menu switches to a "fullscreen" view.

Would it be possible to provide a parameter to control this behavior? (i.e. minimum number of entries required to trigger full screen view)

Similarly, it could be useful to be able to specify the number of items to show in the initial smaller view.

**Comment by rivo** [comment]
The autocomplete list doesn't just show 3 items. Please post a brief example (with code) where only three items are shown but there should be more.

**Comment by khughitt** [comment]
Hmm.. I'm no longer able to reproduce this, so I have no idea what I did to lead to the problem in the first place.

I'm going to close this issue, but If I encounter the same issue in the future I will try and provide a reproducible example.
