### ISSUE TITLE
any hint or possibility to use tview on server?

### ISSUE THREAD

**Issue by hick** [rivo/tview#478]
I mean to develop a telnet server using tview,    and use telnet client to connect to such server resposing with tview terminal ui ?

`tview.NewApplication().SetRoot(box, true).Run()`  will output the tview ui on the server directly

**Comment by tslocum** [comment]
I created [sshtargate](https://gitlab.com/tslocum/sshtargate) to accomplish this for SSH connections by creating a pseudo-terminal and then copying between the input/output of the pty and the SSH connection.

https://gitlab.com/tslocum/sshtargate/-/blob/master/portal/portal.go

**Comment by rivo** [comment]
I'll close this. @hick, please get in touch with @tslocum. He managed to do this and can answer your questions.

**Comment by iamtakingiteasy** [comment]
Linked sources does not seem to use tview at all.

And tview's `NewTerminfoScreenFromTty` seem to be hard-wired to load terminfo details from local environment.

**Comment by progrium** [comment]
The previously mentioned function was merged, so I decided to try it out with an integration example using [gliderlabs/ssh](https://github.com/gliderlabs/ssh) and it works! 

https://github.com/progrium/tview-ssh
