### ISSUE TITLE
Problem with Flex horizontal size

### ISSUE THREAD

**Issue by genzi** [rivo/tview#48]
```
display = tview.NewTable()

	cols, rows := 64, 32
	for r := 0; r < rows; r++ {
		for c := 0; c < cols; c++ {
			display.SetCell(r, c, tview.NewTableCell("|"))
		}
	}
	display.SetBorder(true).SetTitle("Display").SetRect(1, 1, 66, 34)

	flexF1 = tview.NewFlex().
		AddItem(tview.NewFlex().SetDirection(tview.FlexRow).
			AddItem(display, 32+2, 1, false).
			AddItem(tview.NewTextView().SetBorder(true), 0, 1, false), 64+2, 1, false).
		AddItem(tview.NewFlex().SetDirection(tview.FlexRow).
			AddItem(tview.NewBox().SetBorder(true), 0, 1, false).
			AddItem(tview.NewList().SetBorder(true), 0, 1, false), 0, 1, false)

	if err := app.SetRoot(flexF1, true).Run(); err != nil {
		panic(err)
	}
```

I want to use a table like kind of display. To visualize something I will call display.GetCell(px, py).SetBackgroundColor(tcell.ColorGreen) function when pixel should be on. 
The code above should make "display" 64 x 32. Vertical size is OK (32; +2 for border), but horizontal size is less than 64.

**Comment by rivo** [comment]
Hi,

You're correctly setting the required width to `64+2` in the `Flex` view. (The `SetRect()` call is not needed.) When I tried your example, the width of `display` got set to 64 or 66 with the border. See here:

![image](https://user-images.githubusercontent.com/480930/35553204-26f5bbec-0597-11e8-9ecd-366c2aca131d.png)

I'm counting 32 vertical bars with one blank cell after each one = 64.

If you're getting a different output for this code, maybe you can include a screenshot.

**Comment by genzi** [comment]
Hi, 
Thank you for the answer. I didn't know that in a table there is additional blank cell after each one.
I that case I should set flex fixedSize to 128. I will try it in that way. 
I know that this is "table" not "display" object, but is there a way to remove blank cells?
Because this breaks my "display" probably. Or can you suggest a different way to reach my goal?
Sorry for questions about not standard use your package.

**Comment by rivo** [comment]
Currently, the character between columns cannot be removed. But you can change it to something else than a blank character with [`SetSeparator()`](https://godoc.org/github.com/rivo/tview#Table.SetSeparator):

```go
table.SetSeparator('|')
```

If you don't need the other `Table` functionality such as scrolling and selections, I would suggest using `TextView` instead. Just draw your bars into it:

```go
textView := tview.NewTextView()
for row := 0; row < 32; row++ {
  fmt.Fprintln(textView, strings.Repeat("|", 64))
}
```

You can change colors like this:

```go
textView := tview.NewTextView().SetDynamicColors(true)
// ...
textView.Clear()
fmt.Fprint(textView, "[red]")
for row := 0; row < 32; row++ {
  fmt.Fprintln(textView, strings.Repeat("|", 64))
}
```
