### ISSUE TITLE
how to remove [List] left and right key event?

### ISSUE THREAD

**Issue by xing64** [rivo/tview#484]
i used left and right key to change [tview.Pages] page, but one page have a List, so the event conflict.
how to remove [List] left and right key event? or fix the conflict

**Comment by nojus297** [comment]
https://github.com/rivo/tview/wiki/CustomKeys
If I understand your request correctly, you just need to return nil in case of key event being `tcell.KeyRight` or `tcell.KeyLeft`.
With function `SetInputCapture` on the list primitive.

**Comment by xing64** [comment]
> https://github.com/rivo/tview/wiki/CustomKeys
> If I understand your request correctly, you just need to return nil in case of key event being `tcell.KeyRight` or `tcell.KeyLeft`.
> With function `SetInputCapture` on the list primitive.

think you, fix it.
