### ISSUE TITLE
Sorting tables by column

### ISSUE THREAD

**Issue by IdlePhysicist** [rivo/tview#485]
Hi,

I would like to be able to sort tables by selecting a column. At present I do not see a way to do this in tview, but please correct me if there is!

If it is not possible please consider this a feature request.

**Comment by LazarenkoA** [comment]
There is such a need too. 
I use in a workaround, i.e. sorting the original array, clearing the tview and refilling it

**Comment by rivo** [comment]
At the moment, yes, you'd have to clear the table and refill it. I was thinking about adding an index map which would map the screen position of the table cell to the position in the original table data. Then you could sort the index map yourself. But I'm afraid this would pose a few problems. For example, how about fixed rows/columns (@tslocum, how did you solve that?). And when you access a cell, would you want to have the original position or the sorted position?

I'm more inclined to implement something like #248 where you have complete control over the data.

**Comment by rivo** [comment]
Virtual tables are now part of the package. This should allow you to implement sorting on your end. So I'm closing this issue for now.
