### ISSUE TITLE
Some assets which have a border line are displayed with irregular surface

### ISSUE THREAD

**Issue by RyuseiNomi** [rivo/tview#488]
Hi. thanks for giving us a very useful library.
I was just wondering that I got a  assets having irregular surface as below when I tried to use Modal assets with reference [the wiki code](https://github.com/rivo/tview/wiki/Modal).
![modal](https://pbs.twimg.com/media/EgBAHxxUYAcE36G?format=png&name=small)

[Environment]
* macOS Catalina 10.15.5
* iTerm2

Does anyone have any idea about it? If you happen to know about it, please reply to me.
Thanks :)

**Comment by rivo** [comment]
This is in the [FAQ](https://github.com/rivo/tview/wiki/FAQ). Please open another issue if the linked issues didn't help solve your problem.
