### ISSUE TITLE
How to: Move between form items using up/down button

### ISSUE THREAD

**Issue by rustyoz** [rivo/tview#491]
Hi, 

Just wondering if you had any idea on how i would implement the input handler to move between form items using the up/down buttons?

Cheers
Russ

**Comment by rivo** [comment]
You can always override the default key bindings with [`Box.SetInputCapture()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetInputCapture). This works on all primitives. Let me know if this helps.

**Comment by rivo** [comment]
If you still require information, please open another issue and reference this one.
