### ISSUE TITLE
failing installation

### ISSUE THREAD

**Issue by Roderick-Jonsson** [rivo/tview#492]
When doing a `go get github.com/rivo/tview` I get the following message and cant use tview for development.
I am doing this on a mac os x Mojave 10.14.3

What do I have to do to resolve this issue? I assume it must be something basic I missed

```
rmb:github-repo Rod$ go get github.com/rivo/tview
# github.com/rivo/tview
../../go/src/github.com/rivo/tview/box.go:343:63: cannot convert b.borderAttributes (type tcell.AttrMask) to type tcell.Style
../../go/src/github.com/rivo/tview/table.go:318:108: cannot convert attributes (type tcell.AttrMask) to type tcell.Style
../../go/src/github.com/rivo/tview/table.go:875:150: cannot convert cell.Attributes (type tcell.AttrMask) to type tcell.Style
../../go/src/github.com/rivo/tview/table.go:944:63: cannot convert a (type tcell.AttrMask) to type tcell.Style
../../go/src/github.com/rivo/tview/table.go:1007:24: invalid operation: t.selectedStyle != 0 (mismatched types tcell.Style and int)
```

**Comment by Roderick-Jonsson** [comment]
Seems same is happening on a freshly installed ubuntu box

**Comment by drawm** [comment]
:eyes: Same on my Manjaro laptop ```go get github.com/rivo/tview
# github.com/rivo/tview
../../../go/src/github.com/rivo/tview/box.go:343:63: cannot convert b.borderAttributes (type tcell.AttrMask) to type tcell.Style
../../../go/src/github.com/rivo/tview/table.go:318:108: cannot convert attributes (type tcell.AttrMask) to type tcell.Style
../../../go/src/github.com/rivo/tview/table.go:875:150: cannot convert cell.Attributes (type tcell.AttrMask) to type tcell.Style
../../../go/src/github.com/rivo/tview/table.go:944:63: cannot convert a (type tcell.AttrMask) to type tcell.Style
../../../go/src/github.com/rivo/tview/table.go:1007:24: invalid operation: t.selectedStyle != 0 (mismatched types tcell.Style and int)```

**Comment by drawm** [comment]
Did you init your go module? After I ran into a similar problem with another library I went back and read https://golang.org/doc/code.html and figured I forgot to run `go mod init my/module/path`.

**Comment by Roderick-Jonsson** [comment]
@drawm Yes that solved it for me. Thanks for helping out so fast 🏆
