### ISSUE TITLE
tcell.KeyEnter handles CTRL + SHIFT + V pasting as ENTER

### ISSUE THREAD

**Issue by codeliger** [rivo/tview#493]
```
	urlField.SetDoneFunc(func(key tcell.Key) {
		switch key {
		case tcell.KeyEnter:
			pages.SwitchToPage("Dashboard")
		}
	})
```
When I press CTRL+SHIFT+V to paste its returning as an ENTER key

How do i prevent this?

**Comment by rivo** [comment]
Could it be that you're pasting text that includes the `\n` character?

**Comment by rivo** [comment]
There was no answer to my question. If you still require information, please open another issue and reference this one.
