### ISSUE TITLE
Feature Request: shell widget

### ISSUE THREAD

**Issue by tculp** [rivo/tview#496]
A widget that gives access to a shell (or a generic command) would be useful. This could be used for something similar to a tmux pane, or the integrated terminals present in many IDEs

**Comment by rivo** [comment]
I agree it would be nice but I believe the way `tcell` (on which `tview` is based) is structured, this would not be trivial. You'd basically end up writing some kind of terminal emulator. Maybe somebody with experience coding something like that can weigh in. But for now, it seems like a huge undertaking to me.
