### ISSUE TITLE
Issue: Error go get'ing tview

### ISSUE THREAD

**Issue by J-M1** [rivo/tview#501]
As of 16/09/2020

`# github.com/rivo/tview
..\..\go\src\github.com\rivo\tview\box.go:343:63: cannot convert b.borderAttributes (type tcell.AttrMask) to type tcell.Style
..\..\go\src\github.com\rivo\tview\table.go:331:108: cannot convert attributes (type tcell.AttrMask) to type tcell.Style
..\..\go\src\github.com\rivo\tview\table.go:888:150: cannot convert cell.Attributes (type tcell.AttrMask) to type tcell.Style
..\..\go\src\github.com\rivo\tview\table.go:957:63: cannot convert a (type tcell.AttrMask) to type tcell.Style
..\..\go\src\github.com\rivo\tview\table.go:1020:24: invalid operation: t.selectedStyle != 0 (mismatched types tcell.Style and int)`

To reproduce, `go get  github.com/rivo/tview`

**Comment by airborneastro** [comment]
A look at (solved) issue #492 solved it for me (go mod init my/module_name)

**Comment by J-M1** [comment]
> A look at (solved) issue #492 solved it for me (go mod init my/module_name)

Fixes the issue. Cheers!
