### ISSUE TITLE
Feature request: get a treenode's level

### ISSUE THREAD

**Issue by rfc2119** [rivo/tview#502]
Hi, I'd like to first thank you warmly for this library. Truly every aspect of the library is well-written. Thank you

I have a situation where I need to act differently based upon the level of current `tview.TreeNode` in a `tview.TreeView`. Ideally, I would like to have a `GetLevelIndex()` method on a TreeNode type, which simply returns the unexported `level` integer. Would that be an issue to add ?

**Comment by rivo** [comment]
I added this in the latest commit. Let me know if this works for you.
