### ISSUE TITLE
Install error - cannot convert b.borderAttributes

### ISSUE THREAD

**Issue by m-ivanov** [rivo/tview#506]
go get fails with following error

```
go get github.com/rivo/tview
# github.com/rivo/tview
Workspace/go/src/github.com/rivo/tview/box.go:343:63: cannot convert b.borderAttributes (type tcell.AttrMask) to type tcell.Style
Workspace/go/src/github.com/rivo/tview/table.go:331:108: cannot convert attributes (type tcell.AttrMask) to type tcell.Style
Workspace/go/src/github.com/rivo/tview/table.go:888:150: cannot convert cell.Attributes (type tcell.AttrMask) to type tcell.Style
Workspace/go/src/github.com/rivo/tview/table.go:957:63: cannot convert a (type tcell.AttrMask) to type tcell.Style
Workspace/go/src/github.com/rivo/tview/table.go:1020:24: invalid operation: t.selectedStyle != 0 (mismatched types tcell.Style and int)
```

**Comment by rivo** [comment]
I'm not sure how you get this. I just tried it myself:

```
% go mod init gogettest
go: creating new go.mod: module gogettest
% go get github.com/rivo/tview
go: downloading github.com/rivo/tview v0.0.0-20200915114512-42866ecf6ca6
go: github.com/rivo/tview upgrade => v0.0.0-20200915114512-42866ecf6ca6
```

Works fine here. It seems that you're using a different/newer version of [`tcell`](https://github.com/gdamore/tcell) as the `tcell.Style` type has been changed recently. I haven't gotten around to updating this module yet.

But as noted, it should work nonetheless because in `go.mod`, the `tcell` version is [1.3.0](https://github.com/rivo/tview/blob/42866ecf6ca6fc1361dc008f76eda11056ab4dc7/go.mod#L6). And in `tcell` 1.3.0, [`Style` is `int64`](https://github.com/gdamore/tcell/blob/4d152cc2622d491e1b0a034c3211b9df28c0ba2d/style.go#L35).

**Comment by m-ivanov** [comment]
i got that error whithout using modules, with works just fine. So the issue can be closed. maybe add a line to readme. Thanks for fast feedback

**Comment by odddollar** [comment]
I got the same error. How did people fix it?

**Comment by ledongthuc** [comment]
@odddollar which Go version are you using? Maybe missing  go modules in a package, it mismatch version dependencies

**Comment by odddollar** [comment]
I'm using go1.15

**Comment by ledongthuc** [comment]
@odddollar When you call ```go get github.com/rivo/tview```, do you have any module in folder you stay?
If you call it from random folder without go.mod, it will got error because mismatch dependencies version

**Comment by odddollar** [comment]
I open the cmd from the start menu and run the command in the default location of cmd. I've never had any issues installing libraries like this before.

**Comment by ledongthuc** [comment]
@odddollar 
It relates to dependencies linking.
The `github.com/rivo/tview` uses `github.com/gdamore/tcell`

When you build with folder that has go module, it will link with locked version of `github.com/gdamore/tcell`, the `github.com/rivo/tview v0.0.0-20200915114512-42866ecf6ca6`

But when you build with random folder without go.mod, unfortunally, it get the latest version of `tcell`, the 2.xx. It doesn't backward compatible with locked version that `github.com/rivo/tview` are using.

**Comment by afroewis** [comment]
I am getting the same error when installing this library with a clean go installation (1.15). 

```
C:\Users\afroewis\go\src\github.com\rivo\tview\box.go:343:63: cannot convert b.borderAttributes (type tcell.AttrMask) to type tcell.Style
C:\Users\afroewis\go\src\github.com\rivo\tview\table.go:331:108: cannot convert attributes (type tcell.AttrMask) to type tcell.Style
C:\Users\afroewis\go\src\github.com\rivo\tview\table.go:888:150: cannot convert cell.Attributes (type tcell.AttrMask) to type tcell.Style
C:\Users\afroewis\go\src\github.com\rivo\tview\table.go:957:63: cannot convert a (type tcell.AttrMask) to type tcell.Style
C:\Users\afroewis\go\src\github.com\rivo\tview\table.go:1020:24: invalid operation: t.selectedStyle != 0 (mismatched types tcell.Style and int)
```

**Comment by ledongthuc** [comment]
@afroewis yes, please install it in folder that has go.mod currently.

**Comment by rivo** [comment]
I can bump `tcell` to the latest version but I'm not yet sure if I should. The latest version is [v2.0.0-dev](https://github.com/gdamore/tcell/releases/tag/v2.0.0-dev) and the "dev" part looks to me like there may be more breaking changes coming up.

Even if I upgraded to v2.0.0-dev now, it would break `tview` as well (but only in [one function](https://pkg.go.dev/github.com/rivo/tview#TableCell.SetStyle), from what I can see upon a quick glance, so maybe it's not that bad).

But generally, as some of you maybe have seen here already, I don't want to break backwards compatibility. It would be unfortunate if `tview` forced me to. @gdamore, could you maybe weigh in? Do you plan on making more breaking changes like the one to `tcell.Style`?

**Comment by gdamore** [comment]
I don’t plan anything else breaking.  The one thing still left to do is bracketed paste support.  Once that is done I will tag for release. I plan to do that shortly.  That change should not be incompatible with what’s already there.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by rivo** [comment]
Thanks, @gdamore ! I'll upgrade `tview` to the latest version then.

**Comment by gdamore** [comment]
Be advised that in formal v2, you may get some new events which aren't defined yet.  Make sure that won't break your code.  It shouldn't, and I don't consider it a breaking change, except that folks may have code that can't cope with receiving an event type that they didn't code to handle.

**Comment by gdamore** [comment]
(I'm specifically planning for EventPasteStart, EventPasteEnd type of events.)

**Comment by rivo** [comment]
New events should be fine.

Regarding `Style`, I'm using `AttrMask` in a few places. Would it be possible to add a `SetAttr(attr AttrMask)` function to the `Style` type? Otherwise, I may have to decompose `AttrMask` and call all of the functions such as `Style.Bold()` myself.

**Comment by gdamore** [comment]
Sounds reasonable to me.  Do you want to submit a PR?

**Comment by gdamore** [comment]
Btw v2 is now released.

**Comment by rivo** [comment]
Everybody, I've upgraded `tview` to the latest `tcell` version.  Due to the changes in `tcell`, the [`TableCell.SetStyle()`](https://pkg.go.dev/github.com/rivo/tview#TableCell.SetStyle) function has changed. I hope this doesn't break too many systems.

I believe this should make `tview` work without modules again.
