### ISSUE TITLE
Creating input field dynamically on a form

### ISSUE THREAD

**Issue by JCzz** [rivo/tview#510]
Hi and thank you very much for this well structured package!

I am sure I am doing something wrong, I have the following "working" code - but it is not optimal. Can you see if there is a better way?

I am adding InputFields dynamically to a Form, but it is like the enclosed keys is always the last key. Therefore this do not work:
`inputFormItems.InputFields[sortKey]`
in the accept or changed function in AddInputField

In Pseudo code:
1. add InputFielde from a list of key values
2. update the list with any changes on each InputField

This code works:
```
var keys []string
for key := range inputFormItems.InputFields {
    keys = append(keys, key)
}
sort.Strings(keys)

for _, sortKey := range keys {
    v := inputFormItems.InputFields[sortKey]
    inputForm.AddInputField(sortKey, v, 20, nil, func(text string) {
        i, _ := inputForm.GetFocusedItemIndex()
        inputFormItems.InputFields[inputForm.GetFormItem(i).GetLabel()] = text

    })
}

```

Thanks again and I hope I was able to describe the issue

**Comment by tslocum** [comment]
[Form.AddInputField](https://godoc.org/github.com/rivo/tview#Form.AddInputField) adds a *new* `InputField` to the form.  [Form.AddFormItem](https://godoc.org/github.com/rivo/tview#Form.AddFormItem) may be used to add an existing `InputField`.

**Comment by JCzz** [comment]
Thanks
