### ISSUE TITLE
Textview: non-dynamic background color

### ISSUE THREAD

**Issue by tjmtmmnk** [rivo/tview#514]
Hi, Thank you for a wonderful library!

I want the background color to be fixed when using Textview with `SetDynamicColors` set to true. 

For example, if the terminal's background color is not white or black, running an external command like the `bat` command with `color=always` and `TranslateANSI` to display it.

<img width="357" alt="スクリーンショット 2020-10-15 0 44 27" src="https://user-images.githubusercontent.com/31027514/96012918-a2ce5a00-0e7f-11eb-9861-f1cb2be7b52c.png">

Please let me know what you think about my request.

**Comment by rivo** [comment]
I'm not completely sure I understand. Does the screenshot show `tview` with `bat`'s output piped into it using `TranslateANSI`? And if so, do you want these grey bars or don't you want them?

**Comment by tjmtmmnk** [comment]
I’m sorry I was misunderstanding.

I thought the terminal background color was reflected in the result when I run `bat` command with `--color=always`, which was wrong.
Actually, only the foreground color was specified and the background color was not specified.

It was gray because the background color (`bat` result) was not set and the background color of the terminal was reflected. 

Setting the `TextView` background color to `tcell.ColorDefault` used the terminal background color (https://github.com/rivo/tview/blob/master/box.go#L337), which solved this problem.
