### ISSUE TITLE
New Version Error

### ISSUE THREAD

**Issue by xing64** [rivo/tview#517]
Version: github.com/rivo/tview v0.0.0-20201018122409-d551c850a743
Error:
![image](https://user-images.githubusercontent.com/6317240/96450999-82204e80-1249-11eb-9619-40d6007f7865.png)
![image](https://user-images.githubusercontent.com/6317240/96451041-92d0c480-1249-11eb-8ed3-82763155eacf.png)

**Comment by rivo** [comment]
You'll have to use v2 of [`tcell`](https://github.com/gdamore/tcell) now. Are you importing "github.com/gdamore/tcell/v2"?

**Comment by xing64** [comment]
> You'll have to use v2 of [`tcell`](https://github.com/gdamore/tcell) now. Are you importing "github.com/gdamore/tcell/v2"?

Yes, I can`t change to v2 tcell, thank you!

**Comment by xing64** [comment]
change to v2 fix it
