### ISSUE TITLE
Feature request:  add Checkbox.SetCheckedRune

### ISSUE THREAD

**Issue by emicklei** [rivo/tview#518]
Currently, the Checkbox has a hard coded value `X` for the `checkedRune` variable.

See https://github.com/rivo/tview/blob/master/checkbox.go#L174

By add the setter, users can override this.

**Comment by rivo** [comment]
Thanks. Makes sense. I've added `SetCheckedString()` with the latest commit. It's a string because some people may want to use emojis and those often require more than one rune.
