### ISSUE TITLE
Modal border background color no longer matches modal's background color

### ISSUE THREAD

**Issue by polothy** [rivo/tview#519]
The modal border background color used to match the background color of the modal itself.  Now it appears that the border background color is the default background color.

I think this change introduced the new behavior: https://github.com/rivo/tview/blob/d551c850a7435cbb7829ce6703fd470c664801f3/box.go#L73

On the modal, the border is set on the `frame` which is private, so cannot workaround it by just updating the border style:

https://github.com/rivo/tview/blob/d551c850a7435cbb7829ce6703fd470c664801f3/modal.go#L49-L51

This PR could help to provide a way to implement a workaround: https://github.com/rivo/tview/pull/458 - but that's just an FYI. I of course do not mind how it is fixed or if it is actually implemented as intended and this is not a bug.

Since I'm making an issue, I'll take the opportunity to thank you for the amazing project! Been having a lot of fun using it 😄

**Comment by mevdschee** [comment]
I have also seen this happen and I would appreciate a fix.

**Comment by polothy** [comment]
![presentation_demo](https://user-images.githubusercontent.com/634657/98141788-e3683480-1e7b-11eb-94c7-29bcdb7ad026.png)

You can see an example of the coloring in the presentation demo on the Flex and Grid demo pages.

**Comment by mevdschee** [comment]
@polothy Thank you, I see exactly the same. And @rivo thank you for creating this wonderful library. I really like building stuff with it!

**Comment by rivo** [comment]
The latest commit should fix this. Could you please give me feedback whether it works for you now?

(Sorry for the delay, btw.)

**Comment by mevdschee** [comment]
![image](https://user-images.githubusercontent.com/1288217/110970899-7f3e0b80-835a-11eb-9c16-f4a59fe3fc8a.png)

Works on my machine! Thank you.

**Comment by rivo** [comment]
More fixes. (Please refer to https://github.com/rivo/tview/issues/520#issuecomment-797659408.) Does it work for you with the latest update?

**Comment by mevdschee** [comment]
>Does it work for you with the latest update?

I tried the "Hello world again" code and it failed previously, but works fine for me when upgraded from:

    github.com/rivo/tview v0.0.0-20201018122409-d551c850a743 => v0.0.0-20210312174852-ae9464cc3598

I hope this of use to you. Kind regards, Maurits

**Comment by rivo** [comment]
Great! Thanks!
