### ISSUE TITLE
Form border lines are rendered white on white since tcell update

### ISSUE THREAD

**Issue by berrange** [rivo/tview#521]
If I build the 'demos/form/main.go' demo program and run, the form used to have a double line border around it with background in black and lines in white, along with the title text in white.

Since the update to tcell in 

```
commit e4d167311d7708471e449a05b3d1c9dfb061abfc (HEAD)
Author: Oliver <oliver@stockperformer.com>
Date:   Sun Oct 18 14:15:57 2020 +0200

    Upgraded to latest tcell version. Results in a minor incompatibility in the Table class.```

The form now does not render the border correctly, both the background and lines and the text are all in white.

**Comment by rivo** [comment]
I cannot reproduce this with the latest version:

![image](https://user-images.githubusercontent.com/480930/99435686-c36f5100-2910-11eb-8018-a05d2cf87b33.png)

Which terminal / OS are you using?

**Comment by berrange** [comment]
This is with latest tview source, cloned right now, and then building from the git root

```
$ go build demos/form/main.go 
go: downloading github.com/rivo/uniseg v0.2.0
go: extracting github.com/rivo/uniseg v0.2.0
go: downloading github.com/gdamore/tcell/v2 v2.0.1-0.20201017141208-acf90d56d591
go: extracting github.com/gdamore/tcell/v2 v2.0.1-0.20201017141208-acf90d56d591
go: downloading golang.org/x/sys v0.0.0-20201017003518-b09fb700fbb7
go: downloading golang.org/x/text v0.3.3
go: extracting golang.org/x/sys v0.0.0-20201017003518-b09fb700fbb7
go: extracting golang.org/x/text v0.3.3
go: finding github.com/gdamore/tcell/v2 v2.0.1-0.20201017141208-acf90d56d591
go: finding golang.org/x/text v0.3.3
go: finding golang.org/x/sys v0.0.0-20201017003518-b09fb700fbb7
go: finding github.com/rivo/uniseg v0.2.0
$ ./main
```

I'm using Fedora 33, x86_64, with GNOME Terminal  (gnome-terminal-3.38.1-1.fc33.x86_64).

Normally I'm using a white-ish background, and black text, but for this screenshot I've set my terminal background to pink, to make it obvious that the borders are inheriting the terminal's default background colour instead of any tview colour theme:

![tview-borders](https://user-images.githubusercontent.com/1517315/99510960-93ab6200-297f-11eb-99f2-6a0903767180.png)

**Comment by joegrasse** [comment]
I am also running into this issue. With me though, it is anything that has a boarder. I can set the color of the border line with `SetBorderColor`, but there is actually a color behind (around) the line that matches the terminal color (black). 

Here is another example. 

```Go
// Demo code for the Box primitive.
package main

import (
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

func main() {
	box := tview.NewBox().
		SetBackgroundColor(tcell.ColorGreen).
		SetTitle("Hello").
		SetBorder(true).
		SetBorderPadding(0, 0, 0, 0).
		SetBorderColor(tcell.ColorWhite)

	if err := tview.NewApplication().SetRoot(box, true).Run(); err != nil {
		panic(err)
	}
}
```

![image](https://user-images.githubusercontent.com/4334144/109969357-6cbc3600-7cb9-11eb-94cb-d5cd56431c0f.png)

**Comment by rivo** [comment]
Please check out https://github.com/rivo/tview/issues/520#issuecomment-797659408 and let me know if the latest version resolves your issue.

**Comment by mevdschee** [comment]
![image](https://user-images.githubusercontent.com/1288217/111023189-ecdc4d00-83d7-11eb-891f-72bac661b8eb.png)

Seems fixed to me.

**Comment by rivo** [comment]
Great! Thanks for the feedback!

**Comment by joegrasse** [comment]
Yes, fixed for me as well.
