### ISSUE TITLE
Forum for asking questions

### ISSUE THREAD

**Issue by syacko-sote** [rivo/tview#526]
Hello Rivo,
I'm new to tview and I have a number (maybe a lot) of questions about what is possible and what is not.  I love the package and want to make it a central part of my work.  So, is there a place to ask questions that are not issues with the product? Is this the right place?
Thanks in advance,
Scott

**Comment by rivo** [comment]
I'm ok with people asking questions here. Answers from me can sometimes take a while. But sometimes, other users chime in with their comments, too.
