### ISSUE TITLE
Treeview: Call a function for each node traversed with keyboard keys?

### ISSUE THREAD

**Issue by telefax** [rivo/tview#527]
Is there a way to call a function each time I traverse a node?
For instance, I would like to automatically send my node reference to a textview in another grid column while I'm running over the nodes with arrow keys.

Right now I have only figured out how to send this text when pressing the enter key (selectedfunc), but I want to do this without having to press any additional key, just by landing on a node without pressing enter.

Any ideas?

Thanks!

**Comment by telefax** [comment]
I poked around and came up with this:

```
app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		ref := tree.GetCurrentNode().GetReference()
		textView.Clear()
		switch event.Key() {
		case tcell.KeyDown:

			if ref != nil {
				fmt.Fprintf(textView, "%s ", ref)
			}
		case tcell.KeyUp:
			if ref != nil {
				fmt.Fprintf(textView, "%s ", ref)
			}
		}
		return event
	})
```

First I need to capture all in built keyboard shortcuts that you can navigate with on the tree, but the biggest problem is that..SetInputCapture plays out before the node is actually traversed, so this gives me the reference of the previous node and not the current one.

Any other clever way to solve this?

**Comment by rlmaers** [comment]
Isn't [TreeView.SetChangedFunc](https://pkg.go.dev/github.com/rivo/tview#TreeView.SetChangedFunc) exactly what you're looking for?

**Comment by pentiumoverdrive** [comment]
Wow!! How could I miss this?
Thanks!! 👍

**Comment by telefax** [comment]
Pretty impressive how I could miss this! Thanks!

**Comment by telefax** [comment]
Solved.
