### ISSUE TITLE
[Bug] TreeView mouse selection off when scrolling inside a grid

### ISSUE THREAD

**Issue by normen** [rivo/tview#528]
To reproduce:
- add a grid layout
- add a TreeView to that grid layout
- add enough nodes to be able to scroll the TreeView
- scroll the TreeView down a few rows
- select a node by mouse
- the selection is off

idk if I missed something here and the TreeView needs to be updated somehow but I didn't find any documentation about that.

Thanks for this library!

Cheers,
Normen

**Comment by rivo** [comment]
Thanks for letting me know. This should be fixed now.

**Comment by normen** [comment]
woosh 🚀

thank you!

Am 17.11.2020 06:09 schrieb rivo:

**Comment by normen** [comment]
Could it be theres a similar issue in text view? A mouse click always seems to select the top most highlight that is visible, not the one I clicked on.

To reproduce:
- add a textView
- add sufficient paragraphs as ["highlights"]
- scroll down
- click an entry
- the topmost entry is selected instead of the one you click on

Am 17.11.2020 06:09 schrieb rivo:
