### ISSUE TITLE
How to select items inside a grid container?

### ISSUE THREAD

**Issue by manikandanraji** [rivo/tview#535]
I have this grid, inside this grid each children is a flex widget. How to select these flex items?

![rtv](https://user-images.githubusercontent.com/34580944/100533101-a434c580-3226-11eb-9458-685b44833bbf.png)

**Comment by rivo** [comment]
What do you mean by "select"? Do you want to set the focus to a specific flex item? In your code? Or by the user (and if so, with the keyboard or with the mouse)?

I'm not sure I understand your request.

**Comment by manikandanraji** [comment]
Yep, I want the user to set the focus to a flex item. For example, by default the first flex item will be focussed, if the user presses 'J' set the focus to the next flex item

Similar to how rtv (reddit terminal viewer) does:
![output](https://user-images.githubusercontent.com/34580944/101196317-964bce00-3686-11eb-8d4d-19867100a367.gif)

**Comment by tslocum** [comment]
Container widgets such as Flex and Grid pass focus to the first contained widget with the focus property set. When multiple widgets have focus set, only the first receives focus. To switch focus you must manage the focus state of the application. You can do this by capturing user input via SetInputCapture and listening for Tab and Shift+Tab key events. I created [FocusManager](https://docs.rocketnine.space/gitlab.com/tslocum/cview/#FocusManager) ([code](https://gitlab.com/tslocum/cview/-/blob/master/focus.go)) to make this process less cumbersome.
