### ISSUE TITLE
Is there an issue in the go.mod file?

### ISSUE THREAD

**Issue by maryamtahhan** [rivo/tview#537]
should github.com/gdamore/tcell/v2 v2.0.1-0.20201017141208-acf90d56d591 be github.com/gdamore/tcell v2.0.1-0.20201017141208-acf90d56d591

**Comment by tslocum** [comment]
Hi @maryamtahhan.  `github.com/gdamore/tcell/v2` is the correct import path.  Please see [this blog post](https://blog.golang.org/v2-go-modules) for more info.

**Comment by rivo** [comment]
Please open a new issue and reference this one if this issue still persists.
