### ISSUE TITLE
box.go:271:31: b.borderStyle.Attributes undefined

### ISSUE THREAD

**Issue by soease** [rivo/tview#538]
github.com/rivo/tview
../../box.go:271:31: b.borderStyle.Attributes undefined (type tcell.Style has no field or method Attributes)
../../table.go:889:138: tcell.StyleDefault.Foreground(cell.Color).Attributes undefined (type tcell.Style has no field or method Attributes)
../../table.go:958:49: style.Background(bg).Foreground(fg).Attributes undefined (type tcell.Style has no field or method Attributes)

**Comment by tslocum** [comment]
You are importing `github.com/gdamore/tcell` in your project rather than `github.com/gdamore/tcell/v2`, or you need to upgrade `tcell` to the latest version.

**Comment by rivo** [comment]
Please open a new issue and reference this one if this issue still persists.
