### ISSUE TITLE
treeview show text incorrent

### ISSUE THREAD

**Issue by l1b0k** [rivo/tview#541]
hi , i found treeview won't show first letter, what do i missing?

![image](https://user-images.githubusercontent.com/4043362/103119943-9ac93c80-46b0-11eb-9dcc-3748fd6cb0dd.png)

here is the code
```go
	ids := []string{
		"1",
		"2",
		"10",
		"11",
	}
	for i := 0; i < len(ids); i++ {
		node := tview.NewTreeNode(ids[i])
		root.AddChild(node)
	}
```

**Comment by rivo** [comment]
I can't reproduce this. This is what it looks like to me:

![image](https://user-images.githubusercontent.com/480930/104203038-f7a45100-542b-11eb-9e30-3e6e6f9f04cc.png)

You might want to look at the FAQ: https://github.com/rivo/tview/wiki/FAQ

I contains an entry which could be relevant to your issue.

Let me know if this helps.

**Comment by l1b0k** [comment]
@rivo hi, thanks for reply, solved with `export LC_CTYPE="en_US.UTF-8"`
