### ISSUE TITLE
Double borders rendered incorrectly on vmware console

### ISSUE THREAD

**Issue by SimoneLazzaris** [rivo/tview#544]
Hi all;
I've got an application that runs fine in terminal emulator but shows incorrect double borders when run through vmware console.

![Screenshot_20210107_110444](https://user-images.githubusercontent.com/11316967/103879465-3064c300-50d8-11eb-85f3-9497d6b9c6fb.png)

Single line borders are displayed correctly.
I've already tried and set LC_CTYPE as suggested in the FAQ.

My locale:
![Screenshot_20210107_110644](https://user-images.githubusercontent.com/11316967/103879689-7c176c80-50d8-11eb-9fd9-371e50c36d81.png)

Any tips? It would also be acceptable to convert all double borders to single one

**Comment by rivo** [comment]
It looks to me like your terminal emulator isn't able to print all the required characters. For example, if you run something like this in your terminal:

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("\u2550")
}
```

You should see a double line like this:

![image](https://user-images.githubusercontent.com/480930/104213356-79997780-5436-11eb-914e-ec3567d733a1.png)

If you don't, then the font used by the emulator may be incomplete. You could check the settings and change the font maybe, I don't know. Or like you suggested yourself, change the semigraphics characters used in the [`Borders`](https://pkg.go.dev/github.com/rivo/tview#Borders) variable.

Let me know if any of this helps.

**Comment by SimoneLazzaris** [comment]
I've ended up changing the semigraphics characters to always use single borders. Thanks
