### ISSUE TITLE
Mouse binding is not working after resuming back from Application.Suspend()

### ISSUE THREAD

**Issue by ajaxray** [rivo/tview#545]
Hello folks,
Need your kind help for [geek-life](https://github.com/ajaxray/geek-life), a CLI To-Do List Manager.

I am trying to edit some content (task detail) using external editor. 
So, I am doing this:

- Writing the content in a temporary file
- Using `Application.Suspend()` for opening the temporary file in vim (or `$EDITOR` from env)
- On Save and Exit of editor, reading back the tmp file content

```  
app.Suspend(func() {
    // Opening a tmp file in external editor
    // Reading tmp file content after returning back
})
// ... 
app.EnableMouse(true)
```
You may check actual code [here](https://github.com/ajaxray/geek-life/blob/master/app/task_detail.go#L236).

It's working as expected and the new content is being saved. 
But the problem is, Mouse bindings are no more working after resuming application.
Even calling `app.EnableMouse(true)` manually after Suspend is not working. :( 

Any support/clue is very much appreciated. Thanks!

**Comment by rivo** [comment]
Thanks for noticing this. The `tcell.Screen` object is replaced after the `Suspend()` function returns but I forgot to enable the mouse on that new object. This should be fixed now.

**Comment by ajaxray** [comment]
@rivo Thanks a lot! 
The issue is now fixed after updating.
