### ISSUE TITLE
Autocomplete keybinding behavior

### ISSUE THREAD

**Issue by tfrs1** [rivo/tview#546]
Hello,

I'm writing a CLI utility and I'd like to change the autocomplete behavior of the input field inside a form. More specifically I'd like the tab button to complete the current autocomplete suggestion instead of going to the next one. What would be a good way to achieve this?

It looks like exposing `autocompleteList` would allow for this modification.

Thanks!

**Comment by rivo** [comment]
Actually, I think the Tab key's behaviour should have been like that to begin with. The latest commit fixes this. (Along with some other minor improvements to the autocomplete functionality.)

**Comment by tfrs1** [comment]
Well that was fast. Thank you @rivo!
