### ISSUE TITLE
SetTitle() hides tview.List

### ISSUE THREAD

**Issue by natdm** [rivo/tview#547]
Taking the List "hello world" example and adding a SetTitle call to it:

```go
package main

import (
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	list := tview.NewList().
		AddItem("List item 1", "Some explanatory text", 'a', nil).
		AddItem("List item 2", "Some explanatory text", 'b', nil).
		AddItem("List item 3", "Some explanatory text", 'c', nil).
		AddItem("List item 4", "Some explanatory text", 'd', nil).
		AddItem("Quit", "Press to exit", 'q', func() {
			app.Stop()
		}).SetTitle("Borked")
	if err := app.SetRoot(list, true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}
}
```

will not render anything to the console.

**Comment by rivo** [comment]
[`SetTitle()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetTitle) is a function of `Box` and it returns an instance of `Box`. So your `list` variable actually points to a box, and this is what gets drawn. It has no border, thus no title, so nothing gets drawn.

If you want to add a title, put the `SetTitle()` call in a separate line:

```go
list.SetTitle("Borked")
```

**Comment by natdm** [comment]
Excellent. Amazing work here, man. Thank you!
