### ISSUE TITLE
Update github.com/mattn/go-runewidth to v0.0.10

### ISSUE THREAD

**Issue by zemzale** [rivo/tview#548]
In [glab](https://github.com/profclems/glab/pull/561) we use both `tview` and `go-runewidth`

We can't update `go-runewidth` since this package requires v0.0.9. And there is a breaking change from v0.0.9 to v0.0.10 that removes `runewidth.ZeroWidthJoiner` which is used in `https://github.com/rivo/tview/blob/master/util.go#L56`

I locally did an update and nothing seemed to break, so I am ready to open an PR for this, if you are fine with this.

**Comment by rivo** [comment]
`go-runewidth` is imported indirectly by [`tcell`](https://github.com/gdamore/tcell) and I opened an issue there (gdamore/tcell#423) to upgrade to the latest version so `tview` also gets the new version.

All of this happened yesterday so I'm assuming (slash hoping) that it will be resolved these days. It shouldn't be a big deal.

**Comment by zemzale** [comment]
Okay that's nice. Will wait for that then

**Comment by vainkop** [comment]
```
go get github.com/orisano/dlayer
# github.com/rivo/tview
go/src/github.com/rivo/tview/util.go:56:2: undefined: runewidth.ZeroWidthJoiner
```

**Comment by rivo** [comment]
I don't know why you're getting this. `tview` still uses v0.0.9 of `go-runewidth`, see [here](https://github.com/rivo/tview/blob/c818a0c789ee6b8327cf55de5415109181f63bcb/go.mod#L8), which shouldn't result in this error. Make sure to use modules when importing `tview`.

**Comment by rivo** [comment]
`tcell` was updated and this should be resolved with the latest commit now, too.

**Comment by zemzale** [comment]
Thanks!
