### ISSUE TITLE
Feature request: add keybindings to InputField

### ISSUE THREAD

**Issue by minefuto** [rivo/tview#549]
Hi,

It seems InputField provides Bash-like keybinding.
It is very useful.
> - Left arrow: Move left by one character.
> - Right arrow: Move right by one character.
> - Home, Ctrl-A, Alt-a: Move to the beginning of the line.
> - End, Ctrl-E, Alt-e: Move to the end of the line.
> - Alt-left, Alt-b: Move left by one word.
> - Alt-right, Alt-f: Move right by one word.
> - Backspace: Delete the character before the cursor.
> - Delete: Delete the character after the cursor.
> - Ctrl-K: Delete from the cursor to the end of the line.
> - Ctrl-W: Delete the last word before the cursor.
> - Ctrl-U: Delete the entire line.

But it looks like the following keys are missing.
- Left arrow: Move left by one character. <- add Ctrl-B
- Right arrow: Move right by one character. <- add Ctrl-F
- Delete: Delete the character after the cursor. <- add Ctrl-D

Is there a reason why it is not implemented?
I would like to suggest closer to the operation feeling to Bash keybinding.

**Comment by rivo** [comment]
I just added them.

The reason was quite simple: I didn't know about them, hadn't used them myself. ;-)
