### ISSUE TITLE
Cannot get `demos/table` to render correctly on Windows 10.

### ISSUE THREAD

**Issue by true-zero** [rivo/tview#553]
I'm having issues getting the demo for tables to render correctly on Windows 10

![image](https://user-images.githubusercontent.com/46781337/104880979-72073080-5958-11eb-9db5-28a433037bb9.png)

**Comment by joegrasse** [comment]
Could it be related to this issue #66?

**Comment by true-zero** [comment]
> Could it be related to this issue #66?

Nope, doesn't seem to be related.

**Comment by true-zero** [comment]
![image](https://user-images.githubusercontent.com/46781337/105398054-c42aa900-5c19-11eb-84e8-22ae12bac515.png)

Fixed, needs to use a font which doesn't cause the issue.

**Comment by joegrasse** [comment]
Glad I could help.
