### ISSUE TITLE
Feature request: Configurable autocompleteselect in inputfield

### ISSUE THREAD

**Issue by rmasp98** [rivo/tview#554]
Hi, 

Firstly, thank you for such a great library!

I was wondering if you would be open to a configurable autocompleteselect function in the inputfield primitive. This would allow for more sophisticated autocomplete functionality without much complexity, which would be helpful for my app because the search bar I am writing accepts quite complex queries, so I would prefer the autocomplete function to only alter parts of the query rather than the entire text.

This is fairly simple to create (with just a member, setter and getter, and a check in the InputHandler) and I have tested it in my app and it seems to run fine. I would be happy to create a pull request for this.

If you wanted to check out what I am trying to achieve, you can see my app [here](https://github.com/rmasp98/kube-review). It is currently written using go-cui but I am in the middle of rewriting it with tview.

**Comment by rivo** [comment]
I suppose you could use [`SetChangedFunc()`](https://pkg.go.dev/github.com/rivo/tview#InputField.SetChangedFunc) to listen to changes to the input field (including the ones made via autocomplete) and then setting its text to the full string again. You'd just have to be careful not to create an infinite loop. What do you think about that?

**Comment by rmasp98** [comment]
How would I do that? As far as I can work out, all knowledge of the original string is lost by the time it reaches the changed function. I think I.text is the only thing that tracks the contents of the field and that is changed to the new string each time just before changed is called

**Comment by rivo** [comment]
Can you make a suggestion for an actual configurable autocompleteselect function, i.e. what would such a function look like which would satisfy your requirements? I'm not quite sure what information you need to determine partial queries and how you would replace the selection in the input. (It sounded like you have an implementation already so it would be good to see how you solved this.)

**Comment by rivo** [comment]
Any interest in this still?
