### ISSUE TITLE
ANSI example cannot run due to panic

### ISSUE THREAD

**Issue by tculp** [rivo/tview#556]
If trying to run the ANSI example (https://github.com/rivo/tview/wiki/ANSI), the code panics on line 25:

```
=> docker run -it --rm -w /go -e GO111MODULE=auto -v "${PWD}/main.go:/go/main.go" golang
root@608d711d1786:/go# go get "github.com/rivo/tview"
root@608d711d1786:/go# ls -l --color=always | go run main.go
panic: inappropriate ioctl for device

goroutine 1 [running]:
main.main()
        /main.go:25 +0x39f
exit status 2
root@608d711d1786:/#
```
Even `echo 'hello' | go run main.go` fails with the same panic.

I have confirmed this behavior both in a fresh container, and natively.

OS: MacOS
Terminal: iTerm2
Go version(s):
- go version go1.14.4 darwin/amd64
- go version go1.15.6 darwin/amd64
- go version go1.15.7 darwin/amd64
- go version go1.15.7 linux/amd64

**Comment by tculp** [comment]
Actually, using the latest version of all go packages, `echo 'hello' | go run main.go` fails, even locally (iTerm2, MacOS)

**Comment by rivo** [comment]
I cannot reproduce this. I just tried it on macOS with iTerm2. I'm not sure this has something to do with `tview` but rather with how pipes work in your environment. Maybe you can google this error message and find out a bit more about that message? It could give us a hint of where to look.

**Comment by tculp** [comment]
Have you tried my steps using docker? I still get this consistently both in docker and locally. Pipes shouldn't work any differently for my environment.

This other project seemed to have a similar error: https://github.com/c-bata/go-prompt/issues/88

**Comment by neezer** [comment]
@rivo In testing out a new version as you suggested for https://github.com/rivo/tview/issues/542, I ran into this same issue.

The version before the bump does not panic with this error.

```diff
- github.com/rivo/tview v0.0.0-20201204190810-5406288b8e4e
+ github.com/rivo/tview v0.0.0-20210312174852-ae9464cc3598
```

**Comment by rivo** [comment]
I don't have Docker on my Mac so it'll take me a little bit to try this. In the meantime, could you let me know if the following program gives you the same error?

```go
package main

import (
	"io"
	"os"
	"time"
)

func main() {
	go func() {
		if _, err := io.Copy(os.Stdout, os.Stdin); err != nil {
			panic(err)
		}
	}()
	time.Sleep(2 * time.Second)
}
```

```
ls -l --color=always | go run main.go
```

(I know this has appeared with newer `tview` versions but it's worth a shot.) It's a bit odd that there's no callstack. I also couldn't find any useful information when googling this error message.

**Comment by neezer** [comment]
This might be relevant: https://github.com/gdamore/tcell/issues/432 (suspecting because of https://github.com/rivo/tview/commit/745e4ceeb711f2db613627be9570d4c61ee2c191)

---

Your [code snippet](https://github.com/rivo/tview/issues/556#issuecomment-799611453) works fine for me (no error). FWIW I get the initial error running locally (not in Docker) in my repo.

**Comment by rivo** [comment]
Good catch. I'm prettty sure this is the same as https://github.com/gdamore/tcell/issues/432 as I'm basically doing the same thing in `tview`.

**Comment by neezer** [comment]
I'm guessing [this change](https://github.com/gdamore/tcell/commit/e9095fe4f117459e3d961ea4eb3f55bf8f45e91c) is the underlying cause. It fits the timeline. Given the author [doesn't want to revert behavior but instead has some future plan](https://github.com/gdamore/tcell/pull/433#issuecomment-791180918), I'm not sure where to go from here.

What's the recourse for `tview`? I can reproduce @tculp 's original issue locally on macOS and inside Docker using their instructions, and my app (which operates on piped input from stdin in a similar way) is also broken.

**Comment by mevdschee** [comment]
Like @neezer I can reproduce the issue in tview and tcell and not in the go-only example (on Ubuntu).

**Comment by rivo** [comment]
@neezer, I'm not sure what to do here. If `tcell` occupies `os.Stdin`, I can't work around that in `tview`. As soon as @gdamore lets us know how we can read input from a pipe, I'll update the Wiki example. As for your application, if there are no alternatives for you, I would suggest that you revert to a previous commit of `tview` for the time being. As I mention in various places (and in the README), I'm trying to keep `tview` backwards-compatible. So you should be able to upgrade easily once a solution has been found.

**Comment by rivo** [comment]
Is this still an issue? I can run the ANSI example on my Mac as described and it works.

If this still doesn't work for some configurations, a solution I found was to use temporary named pipes instead of relying on `os.Stdin`:

```go
package main

import (
	"io"
	"os"

	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView().
		SetDynamicColors(true).
		SetChangedFunc(func() {
			app.Draw()
		})
	textView.SetBorder(true).SetTitle("Stdin")
	if len(os.Args) < 2 {
		panic("Enter the file or named pipe as the first argument")
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		panic(err)
	}
	defer f.Close()
	go func() {
		w := tview.ANSIWriter(textView)
		if _, err := io.Copy(w, f); err != nil {
			panic(err)
		}
	}()
	if err := app.SetRoot(textView, true).Run(); err != nil {
		panic(err)
	}
}
```

Then you can do this:

```sh
go run main.go <(ls -l)
```

Please let me know if this issue is resolved or not. If it's not resolved, I'll update the Wiki accordingly.

**Comment by mevdschee** [comment]
>Is this still an issue? I can run the ANSI example on my Mac as described and it works.

I tested the latest versions of tview and tcell and this issue is resolved now. No need for a workaround. Thank you for your hard work!
    package main

    import (
        "io"
        "os"

        "github.com/rivo/tview"
    )

    func main() {
        app := tview.NewApplication()
        textView := tview.NewTextView().
            SetDynamicColors(true).
            SetChangedFunc(func() {
                app.Draw()
            })
        textView.SetBorder(true).SetTitle("Stdin")
        go func() {
            w := tview.ANSIWriter(textView)
            if _, err := io.Copy(w, os.Stdin); err != nil {
                panic(err)
            }
        }()
        if err := app.SetRoot(textView, true).Run(); err != nil {
            panic(err)
        }
    }

That works now!

**Comment by rivo** [comment]
Great! Thanks for the feedback.
