### ISSUE TITLE
List does not unselect items when navigating

### ISSUE THREAD

**Issue by njkleiner** [rivo/tview#558]
I'm running the following code, adapted from the flex and list demos.

```go
package main

import (
    "github.com/gdamore/tcell/v2"
    "github.com/rivo/tview"
)

func main() {
    app := tview.NewApplication()

    channels := tview.NewList()
    channels.
        SetBackgroundColor(tcell.ColorDefault).SetBorder(true).SetTitle("").SetBorderPadding(0, 0, 1, 1)
    channels.
        AddItem("Channel A", "", 0, nil).AddItem("Channel B", "", 0, nil).
        ShowSecondaryText(false).SetMainTextColor(tcell.ColorDefault).SetSelectedTextColor(tcell.ColorDefault)

    items := tview.NewBox().SetBorder(true).SetTitle("").SetBackgroundColor(tcell.ColorDefault)

    content := tview.NewFlex().
        AddItem(channels, 0, 1, true).
        AddItem(items, 0, 5, false)

    if err := app.SetRoot(content, true).EnableMouse(true).Run(); err != nil {
        panic(err)
    }
}
```

When I navigate to the second item using the arrow keys, the first one stays selected. Once the second item is selected too, they both stay selected and further navigating the list does nothing.

The behavior I would have expected is for the list to work normally (i.e., only select one item at a time). I'm not sure what I'm doing wrong, because I don't think what I'm doing is much different from the list demo, which works as expected.

**Comment by SoMuchForSubtlety** [comment]
I just encountered this issue myself. Looks it was introduced with this commit. https://github.com/rivo/tview/commit/d7d44cb0d26e6f45c3591e8f1c29956cb8a3deee

@rivo can you shine some light on the reason behind this?

**Comment by rivo** [comment]
Please don't use [`tcell.ColorDefault`](https://pkg.go.dev/github.com/gdamore/tcell#Color). It basically means "transparent" so it has pretty much no effect and therefore leads to strange side effects such as this one.

**Comment by njkleiner** [comment]
> Please don't use [`tcell.ColorDefault`](https://pkg.go.dev/github.com/gdamore/tcell#Color).

The reason why I used `ColorDefault` was because I use a terminal with a white background. Is there a different (preferred) way to reset the colors to a "light mode"?

**Comment by rivo** [comment]
I understand. This has come up multiple times as many people assume `ColorDefault` means something like `ColorTerminalBackground`.

I'm currently not aware of any way to use the terminal's theme colours. There was some related work done in https://github.com/gdamore/tcell/issues/314 but the attached commit isn't in the main branch so I don't know what the status is. (There are also no further comments in that issue.)

**Comment by SoMuchForSubtlety** [comment]
I changed the behaviour in this commit https://github.com/SoMuchForSubtlety/tview/commit/c4de038979df4f0c2f1891d71511b37cbb703bd3

Now tview respects the terminal background colour and things like transparent terminals work
![image](https://user-images.githubusercontent.com/15961647/108207989-bf79e780-7128-11eb-8b10-ddd1e3f673fa.png)
Before my patch it looked like this (note that the `TextView` borders are still transparent)
![image](https://user-images.githubusercontent.com/15961647/108208322-30210400-7129-11eb-8296-b3c73c3870cf.png)

**Comment by rivo** [comment]
I realize I looked at the wrong `tcell` documentation and maybe my previous comment is not accurate anymore.

I will look at this again.

**Comment by rivo** [comment]
Coming back to this, in your application, you can now set the general background colour to your terminal's default as follows:

```go
tview.Styles.PrimitiveBackgroundColor = tcell.ColorDefault
```

However, `tcell` doesn't provide any equivalent for the default text colour. So if you only make this one change, the text colour in your light terminal will still be white. Of course, you can set it to black:

```go
tview.Styles.PrimaryTextColor = tcell.ColorBlack
```

But then it's black even on dark terminals.

Overall, I don't see a way to make it adapt to different terminal themes.
