### ISSUE TITLE
Feature: Run Vim inside a widget

### ISSUE THREAD

**Issue by nickw8** [rivo/tview#568]
This is kinda related to issue #164 where I would like to interact with vim, but instead of leaving my go program, opening vim, editing, leaving vim and opening up the go program again, I would just like to have Vim open in one of the widgets so it looks something like this:

![Screen Shot 2021-02-17 at 3 14 30 PM](https://user-images.githubusercontent.com/1335600/108275255-521f8400-7133-11eb-93cf-a95962f1fac4.png)

**Comment by rivo** [comment]
It's unlikely this is going to be part of `tview` any time soon. This would require reimplementing a lot of control sequences that `vim` uses to draw its screen and `tcell` (on which `tview` is built) follows a very different model. This cannot be mapped easily. I already implemented ANSI colouring sequences (which was a lot of work already) so you can at least pipe some coloured output into `tview` but making it interactive is a whole different ballgame.

If someone familiar with this can demonstrate that the whole thing can be done with just a few simple escape sequences, I might look at it and put it on the roadmap. But if that's not the case, you're probably better off using `screen` or `tmux` or suspend your application to make edits.

**Comment by rivo** [comment]
A quick note before I close this issue: Please fill out #578, I've put this request in the wish list you can vote for.
