### ISSUE TITLE
transparent border background -  tview.Styles.PrimitiveBackgroundColor

### ISSUE THREAD

**Issue by JCzz** [rivo/tview#576]
```
	tview.Styles.PrimitiveBackgroundColor = tcell.ColorBlue
	box := tview.NewBox().
		SetBorder(true).
		SetBorderColor(tcell.ColorRed).
		SetBorderAttributes(tcell.AttrBold).
		SetTitle("title")
	if err := tview.NewApplication().SetRoot(box, true).Run(); err != nil {
		panic(err)
	}
```

The border background use to be the same color as "tview.Styles.PrimitiveBackgroundColor", now it is transparent?

<img width="71" alt="image" src="https://user-images.githubusercontent.com/1861398/110773316-e5446900-825c-11eb-9bb1-b94a0ab97842.png">

**Comment by joegrasse** [comment]
This seems related to #575 and #521.

**Comment by rivo** [comment]
Thanks. Please check out https://github.com/rivo/tview/issues/520#issuecomment-797659408 and let me know if the latest version resolves your issue.

**Comment by mevdschee** [comment]
![image](https://user-images.githubusercontent.com/1288217/111267174-e3e3b980-862b-11eb-93f9-902091af67d3.png)

@JCzz seems fixes to me.

**Comment by JCzz** [comment]
Thanks, just verified - it works!
