### ISSUE TITLE
treeview changed callback behavior changed

### ISSUE THREAD

**Issue by polothy** [rivo/tview#579]
If you scroll to the bottom of change set https://github.com/rivo/tview/commit/4624fa9b671e8c401922c1794ec40c392229e464, you will see the removal of `t.process()`.

This had (I think) an unintended side effect.  I'm using the `SetChangedFunc` function to register a callback that updates other views whenever the currently selected treeview item changes.  The other views show extended details about the currently selected treeview item.

With the removal of `t.process()` in the input event loop, the updates to other views does not get drawn.  Instead, the other views show the last selected treeview item instead of the currently selected.

Maybe there is a better way to accomplish what I'm doing? I tried calling various draw and update functions in my callback, but those ended in deadlocks.

Thanks for any help in advance! Cheers 🍻

**Comment by polothy** [comment]
Just wanted to add: I did try adding this line back and prior behavior was restored.  I'm not sure if that's the actual fix though.

**Comment by rivo** [comment]
It was. I guess I did not remember that `process()` also fired the `changed` callback.

Thanks.
