### ISSUE TITLE
Question: How do I arbitrarily position primitives and leverage tview.Application? 

### ISSUE THREAD

**Issue by zaquestion** [rivo/tview#58]
How do you draw multiple boxes at arbitrary coordinates? 

I'm trying to create something like this. The below I did with https://github.com/jroimartin/gocui which makes it pretty easy to just draw some boxes on the screen, but working with primitives is lacking. 
![pipeline](https://user-images.githubusercontent.com/2358914/36355540-af2fd158-1499-11e8-8d0f-9ed86f5765a1.png)

tview seems to have the right ideas for working with primitives, but I can't figure out how to draw multiple boxes at arbitrary coordinates. I saw @rivo talking about laying out primitives by yourself in https://github.com/rivo/tview/issues/57#issuecomment-366508543 , but I've got some disconnect between starting the application and drawing the boxes.

I don't really have any meanful code snippets, I've just been going through different iterations
```
	root := tview.NewBox().SetBorder(true)
	if err := tview.NewApplication().SetRoot(root, true).Run(); err != nil {
		log.Fatal(err)
	}

        // try to mac more boxes
	b := tview.NewBox().SetBorder(true)
	b.SetRect(20, 20, 20, 20)
```
Also tried creating my own screen, but without the event loop the program exits immediately
```
	s, err := tcell.NewScreen()
	if err != nil {
		log.Fatal(err)
	}
	b := tview.NewBox().SetBorder(true)
	b.SetRect(20, 20, 20, 20)
	b.Draw(s)
```

**Comment by zaquestion** [comment]
Okay might have given in too soon. Just saw https://github.com/rivo/tview/issues/47 which suggested using `Page`s and that seems to let me draw boxes with arbitrary size/position. Still haven't broken into drawing lines, but I suspect I'll be able to call into `tcell` for that. If this sounds like the right approach feel free to close this out.

**Comment by rivo** [comment]
To give some background, the `Application` takes one root primitive. But you obviously have more than one primitive so you'll need to use one of the container primitives such as `Flex` or `Pages` (and soon `Grid`). `Flex` overrides the position of the contained primitives so this is not what you want. That leaves you with `Pages` (with the `resize` flag set to `false`).

Drawing lines is probably a bit more difficult. You could use the `TextView` or create your own `Primitive`. The latter will give you direct access to the `Screen` object but is a bit more sophisticated. I meant to write a Wiki entry on how to write your own `Primitive` but haven't gotten around to it yet.

The primitives don't depend on `Application` directly so you could theoretically write your own `tcell` event loop. This would also give you more direct control over the screen. But you'd obviously do a few things yourself, like reacting to keyboard or resize events, handling panics etc.

Let me know if you need any more help here.

**Comment by zaquestion** [comment]
Thanks this is exactly what I needed!

**Comment by zaquestion** [comment]
@rivo was able to get lines drawing, and get more or less to parody with where I was with `gocui`
![tview_ci_pipeline](https://user-images.githubusercontent.com/2358914/36411652-7011b8be-15cb-11e8-9940-12a41833b375.png)

To do so I had to make these changes to get direct access to the screen since I didn't make a primitive. https://github.com/rivo/tview/pull/59 (curious if something in that direction is desired?)

Otherwise, some advice on implementing a primitive would be nice. Perhaps a general purpose line primitive could handle this well, but I'm guessing handling the connections will be tricky for all cases. In my application its pretty specific so I can hack around most of it. For reference this function connects the jobs in the pictured pipeline: https://github.com/zaquestion/lab/blob/ci/cmd/ci.go#L193

Willing to contribute to tview as part of figuring this out, just need some direction on what that should be.
