### ISSUE TITLE
How to do button handling in forms?

### ISSUE THREAD

**Issue by kudoakiyama** [rivo/tview#582]
I have this code
```go
form := tview.NewForm().
  AddInputField("Search", "", 20, nil, nil).
  AddButton("Go", func() {
    textView1.SetText(form.GetFormItem(0).GetText)
  }
```
```
./main.go:20:4: undefined: textView1
./main.go:20:16: undefined: form
```

but it gives out an error because it doesn't know where `form` is. I'm actually new to how Go works with methods anonymous functions so please bear with me here. Thank you.

Edit: added the error message.

**Comment by rivo** [comment]
This is the way closures work in Go. The variable is not yet known to functions on the same line. (I think this could be changed. It bit me a couple of times in the past, too.)

You'll want to declare `form` first:

```go
var form tview.Form
form = tview.NewForm()...
```
