### ISSUE TITLE
Mouse click breaks `SetFocus`

### ISSUE THREAD

**Issue by paulbdavis** [rivo/tview#585]
Setting up a view like this:

```go

modal := tview.NewModal().
SetText("foo").
AddButtons([]string{"OK"}).
SetDoneFunc(func(buttonIndex int, buttonLabel string) {
  input, view := getInputAndView()
  app.SetRoot(view, true).SetFocus(input)
})

app.SetRoot(modal, true).SetFocus(modal)
```

The return values from the mock function `getInputAndView()` are `(*tview.InputField, tview.Primitive)`

When I use the keyboard to dismiss the modal, the input is properly focused when the root and focus are set, but if I use the mouse to do it, it does not focus the input.

Calling `SetFocus` in a goroutine afterwards half fixes the problem; keyboard events are taken but the cursor does not display until typing starts

```go
SetDoneFunc(func(buttonIndex int, buttonLabel string) {
  input, view := getInputAndView()
  app.SetRoot(view, true)
  go func(input *tview.InputField) {
    app.SetFocus(input)
  }(input)
})
```

**Comment by rivo** [comment]
I had a look at the `tview` code but it's not obvious how this can happen. Can you please post a small program (not just a snippet) that I can run that reproduces this issue?

**Comment by rivo** [comment]
Might be related to #612. If there are no further problems, I will close this issue soon.

**Comment by gdamore** [comment]
It certainly sounds like #612 to me.
