### ISSUE TITLE
Feature: New AdvancedList widget

### ISSUE THREAD

**Issue by mrusme** [rivo/tview#588]
It would be cool if list items would support either intentional line breaks or auto-wrapping of lines in order to be able to nicely display long lines.

**Comment by rivo** [comment]
This would require a complete rewrite of the component as pretty much everything in it is based on the one/two-line-per-item assumption.

It would rather suggest that you use `TextView` to achieve something similar.

**Comment by mrusme** [comment]
Hey @rivo, thank you for getting back! In fact I already used TextView in a different project where no highlighting of the currently active line is required. 👍🏼 However, right now I'm facing the need to have an actual list that can highlight individual items and have a selection callback. From what I saw, this wouldn't be easily possible with a TextView either.

I changed the title of this issue. I would be willing to help with parts of the implementation and definitely with the testing (because I would need that widget right now), however I'm not exactly what would be the best way to implement this.

**Comment by rivo** [comment]
Have you tried using [regions](https://pkg.go.dev/github.com/rivo/tview#TextView)? If you run the presentation demo included in the repo, you'll find that the bottom line is also implemented using `TextView` and highlighting is done with regions.

**Comment by rivo** [comment]
You can reopen if this issue requires further discussion.
