### ISSUE TITLE
why go build for win display different?

### ISSUE THREAD

**Issue by supersensen** [rivo/tview#593]
![屏幕截图 2021-04-27 102845](https://user-images.githubusercontent.com/30255258/116176608-01389700-a745-11eb-9ed2-5b0292adee4e.png)
i use ubuntu in docker on win10 system, run ' env CGO_ENABLED=0 GOOS=windows GOARCH=amd64  go build main.go', get 'main.exe', docker cp this file to win10 and execute, then display different. is this golang build problem? how can i fix this?

**Comment by rivo** [comment]
Your build command looks ok to me. As far as I know, the output should be identical to builds on Windows directly. (You could try, though, just to be sure.)

People often report similar issues for `tview` but these are almost never actual `tview` issues. Check out the [FAQ](https://github.com/rivo/tview/wiki/FAQ) for a list of previous discussions with similar problems and let me know if there's anything that helped you solve this problem.

**Comment by supersensen** [comment]
thank you
