### ISSUE TITLE
wiki/InputField needs a tiny update

### ISSUE THREAD

**Issue by shtukas** [rivo/tview#595]
The example here: https://github.com/rivo/tview/wiki/InputField needs a tiny update because as it stands it errors with 

./main.go:14:15: cannot use func literal (type func("github.com/gdamore/tcell".Key)) as type func("github.com/gdamore/tcell/v2".Key) in argument to tview.NewInputField().SetLabel("Enter a number: ").SetFieldWidth(10).SetAcceptanceFunc(tview.InputFieldInteger).SetDoneFunc

The fix is to use this import : "github.com/gdamore/tcell/v2"

Thanks :)

**Comment by rivo** [comment]
Thanks for the hint. I've updated this page and all the others in the Wiki (and also the gist with the PostgreSQL browser).
