### ISSUE TITLE
is it possible to set locale(to non asian language) at program startup?

### ISSUE THREAD

**Issue by xtaci** [rivo/tview#596]

**Comment by xtaci** [comment]
found a way to:
https://github.com/xtaci/safebox/blob/main/main.go#L36-L63

**Comment by rivo** [comment]
I'm not sure I understand neither the question nor your last comment. Does this mean you found a solution?

**Comment by xtaci** [comment]
> I'm not sure I understand neither the question nor your last comment. Does this mean you found a solution?

yes, I've found a solution.

**Comment by xtaci** [comment]
https://github.com/xtaci/safebox/blob/main/charset_other.go
