### ISSUE TITLE
desire callback when formitem receives focus

### ISSUE THREAD

**Issue by gdamore** [rivo/tview#604]
I have a second pane which provides additional help on screen -- ideally I'd like to have a callback that occurs when the focused item changes, so that I can provide text relevant to that particular input field.  Sort like an OnFocus() function or something.

**Comment by gdamore** [comment]
I'd be happy to have that as a method on the FormItem, but it could also work to do do this in the Form itself.

**Comment by rivo** [comment]
[`Primitive`](https://pkg.go.dev/github.com/rivo/tview#Primitive) and therefore also `FormItem` has `Focus()` which is called when it receives focus. Have you tried that?

**Comment by rivo** [comment]
[`Box.SetFocusFunc()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetFocusFunc) exists now. Let me know if this helps you.
