### ISSUE TITLE
Is there text wrap for TableCell?

### ISSUE THREAD

**Issue by aemengo** [rivo/tview#606]
I'm loving this `Table` Primitive, but I have some lines that are overflowing past the edge of my terminal.

I'd love to be able to toggle text wrapping, if there's a way to do it.

**Comment by rivo** [comment]
No, `Table` uses one line for a cell (plus the grid lines if you have them turned on). You can have multi-line text in `Grid`s but it's functionality will be different from a `Table`.

Note that generally, `tview` lays out its contents top-down so even `Grid` will have no knowledge of how many lines its elements occupy. So it's different from how browsers lay out their elements. It's less "automatic".

**Comment by aemengo** [comment]
Alright, thanks!
