### ISSUE TITLE
Project using tview - twad: a terminal wad launcher

### ISSUE THREAD

**Issue by zmnpl** [rivo/tview#608]
Hi,

I wasn't 100% sure how to communicate this, so sorry if an "Issue" is the wrong channel for that. Just wanted to mention that I've build a project with tview, which - if you like - you can add to the list of projects in your Readme.
[Link to the project](https://github.com/zmnpl/twad)

Regards
Simon

**Comment by rivo** [comment]
You can submit a PR for this with your link added to the README.

**Comment by zmnpl** [comment]
Ah, sure will do!
