### ISSUE TITLE
Would be nice to expose tcell.Style directly

### ISSUE THREAD

**Issue by gdamore** [rivo/tview#611]
Many of the widgets here use tcell styles, but the tview API only exposes the Color explicitly.  This leads to inconsistencies in some places.  For example, the border can usually have attributes set on it, but other things can't.  Some things can have their background color changed, and others can't.

I have a use case where I'd like to be able to provide underlining via attributes to things (basically I want to use List with colors and an underbar to make it look like sort of like hyperlinks).

It  turns out that making Attributes available everywhere is also possibly very important, because in some settings we are not permitted to use color exclusively to convey meaning.  (Due to color blindness).  Using attributes would let us change the way the text is rendered to add underbars, reverse text (which *can* be simulated with colors), blink, italics, etc.

Essentially, I'd like *every* widget to have methods:

SetStyle(), SetBorderStyle(), SetTitleStyle(), etc.

**Comment by rivo** [comment]
It's just a historical artifact that `tview` uses `Color` more than `Style`. I guess when I started the project, I thought colours would be all people needed. But I was obviously wrong.

I can look into adding additional functions to set styles. But it has to be backwards compatible.

**Comment by golangdojo99** [comment]
+1

**Comment by rivo** [comment]
I'm closing this as there's no need to track this issue anymore. I have added a lot of methods to set/get the `tcell.Style` object directly already and continue to add them where they are still missing.
