### ISSUE TITLE
Inexplicable mouse focus behavior

### ISSUE THREAD

**Issue by gdamore** [rivo/tview#612]
I'm building a form with a modal, which works fine.  But when I use the mouse to click the button to dismiss the modal (or to change page), the focus seems to be lost.  I've tried forcing the focus back by using app.SetFocus(), but that doesn't seem to work.  The only way to get focus back on my application is to use the mouse to click on a visible component.

This isn't a huge deal, but it *is* confusing.  I spent a lot of time trying to figure out workarounds in my application, but to no avail.  I haven't debugged it further in your code.

**Comment by rivo** [comment]
Do you have some brief code that I can run to reproduce this?

**Comment by gdamore** [comment]
I figured you'd ask for this.  At present I don't (part of a bigger app) but I suspect if you have a list and a modal you'd observe that after clicking the button on the modal with the mouse the focus is lost.  I will see if I can put together a small reproducer this weekend.

**Comment by rivo** [comment]
I was able to reproduce this. I believe the latest commit fixes it.
