### ISSUE TITLE
TreeView should be scrolled no matter the toppest item is selected or not.

### ISSUE THREAD

**Issue by liwnn** [rivo/tview#613]
TreeView should be scrolled no matter the toppest item is selected or not.
![treeview](https://user-images.githubusercontent.com/4005513/120136673-46009380-c205-11eb-8fa0-936830702a57.gif)

**Comment by rivo** [comment]
You didn't provide any explanation why this is useful. I'm not a fan of having invisible selections.

**Comment by liwnn** [comment]
I want to select "db55" by mouse.
![image](https://user-images.githubusercontent.com/4005513/120163136-c4702c00-c22b-11eb-9562-123d2c1546e3.png)

**Comment by rivo** [comment]
Ok, that makes sense. I've made those changes in the latest commit.
