### ISSUE TITLE
Error when running demo/presentation/main.go

### ISSUE THREAD

**Issue by Zeebrow** [rivo/tview#620]
I appologize in advance if I missed something obvious; I started learning Go today.

Output:
```
~$ go run demos/presentation/main.go
# command-line-arguments
./main.go:35:3: undefined: Cover
./main.go:36:3: undefined: Introduction
./main.go:37:3: undefined: HelloWorld
./main.go:38:3: undefined: InputField
./main.go:39:3: undefined: Form
./main.go:40:3: undefined: TextView1
./main.go:41:3: undefined: TextView2
./main.go:42:3: undefined: Table
./main.go:43:3: undefined: TreeView
./main.go:44:3: undefined: Flex
./main.go:44:3: too many errors
~$
```
Reproduce with commands (Ubuntu 20.04):
```
cd `mktemp -d`
git clone https://github.com/rivo/tview.git
cd tview/
go run demos/presentation/main.go
```

Other info:
`go version go1.16.5 linux/amd64`
```
~$ uname -a
Linux zeebrow-pc 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by Zeebrow** [comment]
I made [this](https://github.com/Zeebrow/tview-demo-pres-wrkarnd/tree/master) in case anyone else wants to try the presentation demo, albeit in a more limited capacity (see readme).

**Comment by marcelocantos** [comment]
You should usually `go run` packages, not individual files:
```bash
go run ./demos/presentation
```
What you tried is valid, but treats `main.go` as a standalone package all by itself, so it's missing symbols it needs that are defined in other Go files in the same package.

**Comment by Zeebrow** [comment]
Thanks @marcelocantos! Running `go run .` indeed gives me the nice presentation.
