### ISSUE TITLE
Suspending and coming back to previous screen

### ISSUE THREAD

**Issue by ankitpokhrel** [rivo/tview#624]
Suspending and coming back to previous screen seems broken since recent update.

Given a simple program that launches vim and goes back to previous screen after exit.
```go
package main

import (
	"os"
	"os/exec"

	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	form := tview.NewForm()

	form.SetInputCapture(func(ev *tcell.EventKey) *tcell.EventKey {
		if ev.Key() == tcell.KeyRune {
			if ev.Rune() == 'q' {
				app.Stop()
				os.Exit(0)
			}
		}
		return ev
	})

	form.AddButton("Edit with vim", func() {
		app.Suspend(func() {
			cmd := exec.Command("vim", "/tmp/foo")
			cmd.Stdout = os.Stdout
			cmd.Stdin = os.Stdin
			_ = cmd.Run()
		})
	})

	form.SetBorder(true).SetTitle("Launch vim & go back to main screen after exit, Press 'q' to exit")

	if err := app.SetRoot(form, true).SetFocus(form).Run(); err != nil {
		panic(err)
	}
}

```

The code above worked as expected before but panics since 36f5c190eaafcadd0c581ab5efd5125db0306c22.

```
panic: EOF

goroutine 1 [running]:
main.main()
	/go/src/tview-dbg/broken/main.go:37 +0x3b7
exit status 2
```

The cause of the issue can be traced back to this particular change where we are stopping the app `app.Stop` when handling `tcell.EventError` in an event loop.
https://github.com/rivo/tview/blob/29d673af0ce2281f8b517d1bd14aab453b8fc8ef/application.go#L373-L375

Is there anything I am missing?

**Comment by darkhz** [comment]
It's broken for me too. Panics with:
`panic: read /dev/tty: i/o timeout`

**Comment by rivo** [comment]
This appears to be a problem with `tcell`. I opened an issue there: gdamore/tcell/issues/480

**Comment by rivo** [comment]
@ankitpokhrel & @darkhz Can you please try this with the latest `tcell` commit and let me know if it works for you?

**Comment by darkhz** [comment]
@rivo Yes, it works well with the commit in the [fix480](https://github.com/gdamore/tcell/tree/fix480) branch. Thank you very much.

**Comment by ankitpokhrel** [comment]
@rivo works fine for me too with latest `tcell` commit. Thank you!
