### ISSUE TITLE
Problems with installing tview (tcell dependency)

### ISSUE THREAD

**Issue by ajvn** [rivo/tview#640]
Hey there,

Thank you for your work on this package.

There are issues with revision number of `tcell` version specified in `go.mod` file.
This is what happens when I try to freshly install `tview`:
```bash
go get: github.com/rivo/tview@none updating to
        github.com/rivo/tview@v0.0.0-20210904173154-2f13f81dcb15 requires
        github.com/gdamore/tcell/v2@v2.4.1-0.20210904044819-ae5116d72813: invalid version: unknown revision ae5116d72813
```

Regards,
Ivan

**Comment by rivo** [comment]
I'm not sure how you're getting this. I just installed `tview` locally again to reproduce it but I'm not getting that message. What steps exactly did you perform?

**Comment by ajvn** [comment]
This is the command: `# go get github.com/rivo/tview` and output is as what I pasted above. I managed to workaround it by cloning this repository, and specifying 2.3.1 version of `tcell` in `go.mod` file.

**Comment by rivo** [comment]
Please have a look at #643. Could you let me know if you're still getting this problem with the latest commit?

**Comment by ajvn** [comment]
Yes, that fixed it, thank you:
```bash
go get github.com/rivo/tview
go: downloading github.com/rivo/tview v0.0.0-20210909154944-f7430b878d17
go: downloading github.com/gdamore/tcell/v2 v2.4.1-0.20210905002822-f057f0a857a1
```

Should I close this this issue or is there any other followup needed?

**Comment by rivo** [comment]
It's ok, I'm closing it. Thanks for re-testing.
