### ISSUE TITLE
Feature request: table.SetBorders(horizontal,  vertical bool)

### ISSUE THREAD

**Issue by treesong** [rivo/tview#647]
Table is used frequently to select by table row, table.SetBorders(horizontal=true,  vertical=false) could get more nice look

**Comment by rivo** [comment]
I'm not sure this is a very common request. If you need to modify the default behaviour of `Box` (which is also the superclass of `Table`), you can use [`SetDrawFunc()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetDrawFunc).
