### ISSUE TITLE
Context Menus

### ISSUE THREAD

**Issue by ka1r03** [rivo/tview#654]

**Comment by rivo** [comment]
Please provide a description.

**Comment by ka1r03** [comment]
> Please provide a description.

@rivo looks like there is an [open PR](https://github.com/rivo/tview/pull/434) implementing context menus to tview.

**Comment by rivo** [comment]
Ok, got it. Yeah, it's currently not very high on the todo list. But I understand `cview` has this implemented?

**Comment by ka1r03** [comment]
> Ok, got it. Yeah, it's currently not very high on the todo list. But I understand `cview` has this implemented?

Looks like cview does implement context menus, but there are few issues with cview, here are some of them:
- Though cview's API is fairly identical to tview's, it consists of breaking changes. Furthermore, some of the functions like TreeNode.GetLevel() are missing.
- The repository is self-hosted which makes it difficult for me to open issues and pull requests (you cannot login with GitHub).

**Comment by rivo** [comment]
To be honest, I don't follow `cview`'s progress so I can't tell you anything about its current state. (I don't even know if it's still actively maintained.)

Anyway, I was thinking you might be able to implement context menus yourself by intercepting mouse events with [`SetMouseCapture()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetMouseCapture). Now you need to place a context menu widget (e.g. a `List`) where the user clicked. You can take a clue from [this Wiki page](https://github.com/rivo/tview/wiki/Modal).

I would think it's possible even without having this specific functionality part of the library.

**Comment by ka1r03** [comment]
> To be honest, I don't follow `cview`'s progress so I can't tell you anything about its current state. (I don't even know if it's still actively maintained.)
> 
> Anyway, I was thinking you might be able to implement context menus yourself by intercepting mouse events with [`SetMouseCapture()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetMouseCapture). Now you need to place a context menu widget (e.g. a `List`) where the user clicked. You can take a clue from [this Wiki page](https://github.com/rivo/tview/wiki/Modal).
> 
> I would think it's possible even without having this specific functionality part of the library.

:+1: Alright, sounds great, closing this issue
