### ISSUE TITLE
Hi :hand: 

### ISSUE THREAD

**Issue by gh-ninja** [rivo/tview#655]
hello how could i write on the box? I know there is: [primitive](https://github.com/rivo/tview/wiki/Primitives#hooking-into-a-primitives-draw-function) but I found it a bit complex, I just want to write inside the box, something like:
 +-----Box Name-----+
my name: name
 +------------------------+

I'm starting to study this lib

**Comment by gh-ninja** [comment]
hey, @rivo help

**Comment by rivo** [comment]
@gh-ninja `Box` is just the superclass for all other primitives. In most cases, you don't need to use it directly. (Only if you really just want to display an empty box.)

If you want to write something inside the box, use `TextView`.

Let me know if this helps.

**Comment by gh-ninja** [comment]
@rivo ok but how could i use textview to create? Sorry, I'm still learning...

**Comment by rivo** [comment]
Check out the `demos/textview` directory for examples. You can call the `SetText()` function to set your text or use the `io.Writer` interface to write to it.

**Comment by gh-ninja** [comment]
Aaaaaa,  it worked, thank you so much @rivo  you are a best dude

My Code: 
```
func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView()
	textView.SetBorder(true)
	textView.SetTitle("box name")
	textView.SetText("hi, im cool box ^^")
	app.SetRoot(textView, true).EnableMouse(true).Run()
}
```
Do you have any social networks? like Telegram, so if I have any questions, I'll get in touch with you there, so you don't have to open the issue for a question.

**Comment by rivo** [comment]
It's fine to open issues here. I might respond right away like today but maybe others can help you, too.

**Comment by gh-ninja** [comment]
> It's fine to open issues here. I might not respond right away like today but maybe others can help you, too.

okay, thanks ! 😁
