### ISSUE TITLE
In the treeview example (demos) when the directory visited does not have read permission, the app crashes  

### ISSUE THREAD

**Issue by serge-hulne** [rivo/tview#659]
In the treeview example (demos) when the directory visited does not have read permission, the app crashes :

https://github.com/rivo/tview/tree/master/demos/treeview

**Comment by rivo** [comment]
I know. I wouldn't say it crashes, it panics. It's not meant to be a fully featured file browser. It just demonstrates the use of the `TreeView` primitive.

**Comment by serge-hulne** [comment]
Thanks! 
How could I catch this exception?

**Comment by rivo** [comment]
It's uncommon to catch panics in Golang. You'll need to decide what to do with a directory for which you don't have permission, then do that instead of panicking. This is where it happens:

https://github.com/rivo/tview/blob/ee97a7ab3975c51dba32df8979eb97b31cada430/demos/treeview/main.go#L26

**Comment by serge-hulne** [comment]
Thank you!
