### ISSUE TITLE
Border Is not Drawn Properly in Windows Command Prompt

### ISSUE THREAD

**Issue by joegrasse** [rivo/tview#66]
When trying to run your [Box demo](https://github.com/rivo/tview/tree/master/demos/box) in the windows 10 command prompt, the border is not drawn correctly.

OS: Windows 10
Go: 1.9.4

![image](https://user-images.githubusercontent.com/4334144/37174999-ccc6240e-22dd-11e8-91af-b892df2b482c.png)

**Comment by KingRikkie** [comment]
You sure about this? Works on my end. 

As a side note, there will be an offset of one col on the right side if I compile it and run the exe directly or call the *.go file with `go run`. The offset vanishes if I call the exe from an existing commandline.

![Offset](https://i.imgur.com/EJTG5LQ.png)

**Comment by glycerine** [comment]
I can repro this in the windows 10 cmd.exe (cmd.exe is a piece of c**p which ms has never cared about).  But it works fine in ConEmu, an actual terminal emulator for windows. https://conemu.github.io/

**Comment by jopbrown** [comment]
The layout may break in certain code page and font .
You can fix it by changing the code page to utf-8 (`chcp 65001`) and set the font to `Consolas`.

**Comment by glycerine** [comment]
> changing the code page to utf-8 (chcp 65001) 

Be very careful with that. Test on a box you have backed up/can wipe and reload the OS. Quoting 

https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8

> Changing HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\OEMCP value to 65001 appear to make the system unable to boot in my case.
>
> Proposed change of HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\Autorun to @chcp 65001>nul served just well for my purpose. (thanks to Ole_Brun)

and 

> The Windows console is riddled with bugs when the encoding is set to an unsupported multi-byte code page like 65001. Any software using the output counts of the Win32 WriteFile/ReadFile APIs will get the wrong results and consequently stuff build on that like the MSVCRT's implementation of the stdlib will produce mangled/repeated output and hang on input when confronted with non-ASCII. Until MS get around to fixing it — and it has been decades with no sign of that happening — globally changing console code page to 65001 is an extraordinarily bad idea. – bobince Oct 14 '16 at 8:51

**Comment by rivo** [comment]
I wasn't able to reproduce this on Win10. I did see the extra column once (using a compiled version of the Box demo). But selecting parts of the screen seemed to indicate that it was an issue with the Terminal window, not `tview` or `tcell`. Resizing the window made it go away (at least for a while).

I don't see anything I can do here so I'll close this issue.

**Comment by joegrasse** [comment]
For other that have this issue, my problem was that I had set the cmd font to a different font. When I switch the font back to Courier New, I don't have the problem anymore.
