### ISSUE TITLE
Example of popup Modal by shortcut

### ISSUE THREAD

**Issue by abitrolly** [rivo/tview#662]
https://github.com/rivo/tview/wiki/Modal example list modal hardwired to root or Pages elements. But I already have List as my root element, and I want to show modal (without buttons) when I press `i` and close it on `Esc` or clicking outside. Would be nice to have an example that demonstrates how that's possible.

The straightforward approach I tried that doesn't work.

```go
        // Create UI elements
        list := tview.NewList()
        // Set Box properties on the List component
        list.SetBorder(true).SetTitle(" package updates ")
        // Set List properties
        list.ShowSecondaryText(false)

        infobox := tview.NewModal().
                AddButtons([]string{"Quit", "Cancel"}).
                SetText("Lorem Ipsum Is A Pain")

        // Attach elements and start UI app
        app := tview.NewApplication()
        app.SetRoot(list, true) // SetRoot(root Primitive, fullscreen bool)
        app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
                if event.Key() == tcell.KeyESC {
                        app.Stop()
                }
                // Key is a character
                if event.Key() == tcell.KeyRune {
                        if event.Rune() == 'q' {
                                app.Stop()
                        }
                        if event.Rune() == 'i' {
                                app.SetFocus(infobox)
                        }
                }
                return event
        })
```

After pressing `i` the List border becomes single line, and it stops responding to events. Nothing else is shown. Pressing `Esc` doesn't revert to previous state, but exits the application.

**Comment by abitrolly** [comment]
@rivo why it is not possible to attach the Modal dynamically to the root element?

**Comment by rivo** [comment]
Sure, it's possible. Just use `app.SetRoot()`:

```go
package main

import (
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

func main() {
	// Create UI elements
	list := tview.NewList()
	// Set Box properties on the List component
	list.SetBorder(true).SetTitle(" package updates ")
	// Set List properties
	list.ShowSecondaryText(false)

	infobox := tview.NewModal().
		AddButtons([]string{"Quit", "Cancel"}).
		SetText("Lorem Ipsum Is A Pain")

	// Attach elements and start UI app
	app := tview.NewApplication()
	app.SetRoot(list, true) // SetRoot(root Primitive, fullscreen bool)
	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		if event.Key() == tcell.KeyESC {
			app.Stop()
		}
		// Key is a character
		if event.Key() == tcell.KeyRune {
			if event.Rune() == 'q' {
				app.Stop()
			}
			if event.Rune() == 'i' {
				app.SetRoot(infobox, false)
			}
		}
		return event
	})
	app.Run()
}
```

**Comment by abitrolly** [comment]
Nice. I think this high level overview is not described anywhere. Namely that for building a UI with `rivo` you first define a tree of elements, and then attach that tree to the app screen with `app.Root()` call. If you define an element that is not in a tree or not attached, then it won't be visible.

Now for the example - it works, but the list is gone from the background when switching root to infobox, because as you said it is not attached anymore. So is it possible to attach the infobox as a child modal to the list?

**Comment by rivo** [comment]
> I think this high level overview is not described anywhere.

I realize that. I have yet to add more examples and tutorials. It's just due to lack of time that this doesn't exist yet.

> So is it possible to attach the infobox as a child modal to the list?

As mentioned in my first reply, to attach multiple primitives to the application, you need a container primitive (`Flex`, `Grid`, or `Pages`) at the root. In your example, I would suggest `Pages`, to which you add your list and your modal. Then use [`SwitchToPage()`](https://pkg.go.dev/github.com/rivo/tview#Pages.SwitchToPage) to switch between the two.

**Comment by abitrolly** [comment]
In `Qt/PySide2` any `Widget` can be root, much like in `tview`, but also any widget can have a parent and children - https://wiki.qt.io/Qt_for_Beginners#parenting_system - so I kind of expected something similar. In `tview` the only widgets that allow children are "layout" widget with its own APIs:

 * Pages - `.addPage()`
 * Flex - `.addItem()`
 * Grid - `.addItem()`

**Comment by rivo** [comment]
Yes, that's correct.

**Comment by abitrolly** [comment]
@rivo what do you think about adding bit flags to `.AddPage()` API. Right now the code like this is not really readable.
```go
		AddPage("background", background, true, true).
```
I am thinking about something line this.
```go
		AddPage("background", background, Resize | Visible).
```
Or maybe a backward compatible solution.
```go
		AddPage("background", background, Resize, Visible).
```

**Comment by abitrolly** [comment]
@rivo `SwitchToPage()` hides the `list` too instead of sending it to the background. The example at https://github.com/rivo/tview/wiki/Modal is not using switching, so it is not affected.

**Comment by abitrolly** [comment]
I have to use `.ShowPage("infobox")` to bring up modal on a background and then use `.SwitchToPage("list")` to turn it off.

**Comment by abitrolly** [comment]
Now I need to figure out how to deal with modal specific shortcuts, so that `Esc` closed modal and not the whole app.

**Comment by rivo** [comment]
[`Box.SetInputCapture()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetInputCapture) is your friend.

**Comment by abitrolly** [comment]
Is there a way for a Modal to "quit" itself without holding a reference to global `Page`? 

```go
          infobox := tview.NewModal().
                  AddButtons([]string{"Quit", "Cancel"}).
                  SetText("Lorem Ipsum Is A Pain").
                  SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
                          if event.Key() == tcell.KeyESC {
>>                                pager.HidePage("infobox")
                          }
                          return event
                  })
```

**Comment by abitrolly** [comment]
I can not stop ESC event from propagating by returning `nil`. With the following code the app still exits when ESC is pressed in the modal.
```go
          infobox.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
                  if event.Key() == tcell.KeyESC {
                          log.Println("ESC pressed")
                          //pager.HidePage("infobox")
                          return nil
                  }
                  return nil //event
          })
```

**Comment by rivo** [comment]
I don't know why your app exits when hitting <kbd>Esc</kbd>. That is not built-in. It only exits upon <kbd>Ctrl-C</kbd>. If you want to stop it from doing that, you can do that with [`Application.SetInputCapture()`](https://pkg.go.dev/github.com/rivo/tview#Application.SetInputCapture) on the application level. So I'm not sure what the issue with <kbd>Esc</kbd> is here. If you post some code that I can run, I might be able to tell you.

> Is there a way for a Modal to "quit" itself without holding a reference to global `Page`?

The package doesn't provide a way for primitives to make themselves "disappear" and have container primitives handle that automatically. You can probably code up your own dependency injection by creating a custom constructor for your modal. Or you handle [`Modal.SetDoneFunc()`](https://pkg.go.dev/github.com/rivo/tview#Modal.SetDoneFunc) somewhere outside. But eventually, the `Pages` class needs to switch the order of the primitives displayed to make that visible to the user.

**Comment by abitrolly** [comment]
@rivo here is the code.

```go
package main

import (
	"fmt"
	"log"

	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

// Define some constants for readability
const Fullscreen = true
const Resize = true
const Visible = true
const Hidden = false

type PackageUpdate struct {
	name    string
	oldver  string
	newver  string
	summary string
}

// UpdateList runs and parses `dnf repoquery` command that returns the list
// of upcoming updates
func UpdateList() []PackageUpdate {
	var result []PackageUpdate
	result = append(result, PackageUpdate{"pkg1", "", "0.1", "package 1"})
	result = append(result, PackageUpdate{"pkg2", "", "0.1", "package 2"})
	result = append(result, PackageUpdate{"pkg3", "", "0.3", "package 3"})
	result = append(result, PackageUpdate{"pkg4", "", "0.1", "package 4"})
	return result
}

func main() {
	// Setup logging
	log.SetFlags(0)

	// Read `dnf` data
	log.Println("[INFO] Getting `dnf` data ...")
	updates := UpdateList()

	// Create UI elements
	// 1. list of updates
	list := tview.NewList()
	// Set Box properties on the List component
	list.SetBorder(true).SetTitle(" package updates ")
	// Set List properties
	list.SetWrapAround(false)
	list.ShowSecondaryText(false)
	for _, u := range updates {
		verstr := u.newver
		if u.newver != u.oldver {
			verstr += " (" + u.oldver + ")"
		}
		update := fmt.Sprintf("%-30s  %-20s %s", u.name, verstr, u.summary)
		list.AddItem(update, "", 0, nil)
	}
	// 2. modal with detailed info
	infobox := tview.NewModal().
		AddButtons([]string{"Quit", "Cancel"}).
		SetText("Lorem Ipsum Is A Pain")
	// 3. layout with two pages (second page is needed to show modal)
	pager := tview.NewPages().
		AddPage("list", list, Resize, Visible).
		AddPage("infobox", infobox, Resize, Hidden)

	// Attach UI elements tree to app and start it
	app := tview.NewApplication()
	app.SetRoot(pager, Fullscreen)
	// Set event handling
	infobox.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		if event.Key() == tcell.KeyESC {
			log.Println("ESC pressed")
			//pager.HidePage("infobox")
			return nil
		}
		return nil //event
	})
	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		if event.Key() == tcell.KeyESC {
			app.Stop()
		}
		// Key is a character
		if event.Key() == tcell.KeyRune {
			if event.Rune() == 'q' {
				app.Stop()
			}
			if event.Rune() == 'i' {
				pager.ShowPage("infobox")
			}
			if event.Rune() == 'o' {
				pager.SwitchToPage("list")
			}
		}
		return event
	})
	if err := app.Run(); err != nil {
		log.Panicln(err)
	}
}
```

**Comment by rivo** [comment]
Ok, well, that makes sense. The `Application.SetInputCapture()` call is evaluated first before any other overrides in primitives. So if you globally stop the application upon hitting <kbd>Esc</kbd>, that will always happen, regardless of what you do in your `Modal`. Same with <kbd>q</kbd>.

It seems to me that you only want to close the application with <kbd>Esc</kbd> when the user is in the `List`. So you'll want to capture the <kbd>Esc</kbd> event in your list instead of globally in the application.
