### ISSUE TITLE
Is it possible to remove line numbers in lists?

### ISSUE THREAD

**Issue by JCzz** [rivo/tview#668]
Thanks for a very nice ui tool!

Is it possible to remove line numbers in lists?

```
	myListView := tview.NewList()
	myListView.SetTitle("Resources")
        // myListView.ShowLineNumners(false)
```

**Comment by rivo** [comment]
I don't understand this. `List` doesn't include any line numbers.

**Comment by JCzz** [comment]
Sorry, I found that I was setting shortcut in list.AddItem

Thanks again for a great tool!

**Comment by JCzz** [comment]
Is it possibel to leave out shortcuts, so it does not show "( )"?



Thanks again for a great tool!

**Comment by rivo** [comment]
It's in the [documentation](https://pkg.go.dev/github.com/rivo/tview#List.InsertItem):

> The shortcut is a key binding. If the specified rune is entered, the item is selected immediately. **Set to 0 for no binding.**

If you set all of them to `0`, none of them will show up. If you see `( )`, I suspect you've specified an empty space instead of `0`.

**Comment by JCzz** [comment]
Right, thanks - very nice
