### ISSUE TITLE
Please Add Functionality to set BackgroundColor For autocomplete. 

### ISSUE THREAD

**Issue by aditya-K2** [rivo/tview#671]
The [Default](https://github.com/rivo/tview/blob/badfa0f0b301e121ab4c072ffb4bdc81451541f0/inputfield.go#L280) Background color doesn't look good. Having a method to change the Autocomplete menus background would be useful.

**Comment by rivo** [comment]
There is now a function `InputField.SetAutocompleteStyles()` that allows you to change the styles of the autocomplete drop-down.
