### ISSUE TITLE
position doesn't change after extracting the autocompleteSelect function

### ISSUE THREAD

**Issue by aditya-K2** [rivo/tview#673]
Upon extracting [this](https://github.com/rivo/tview/blob/master/inputfield.go#L528) function out the position doesn't change and the cursor remains at the beginning what is happening

**Comment by aditya-K2** [comment]
i was talking about in the context of [this](https://github.com/rivo/tview/pull/622#issuecomment-968548488)

**Comment by rivo** [comment]
I don't understand what you're describing. What do you mean by "extracting this function"? Can you describe in detail what exactly it is that you're doing?
