### ISSUE TITLE
bug: The text in the border is missing the first character

### ISSUE THREAD

**Issue by chyroc** [rivo/tview#674]
system: macos 10.15.7

+ iTerm2

+ zsh

code:

```go
package main

import (
	"os"

	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()

	box := tview.NewBox().SetBorder(true).SetTitle("box demo")

	app.SetRoot(box, true)

	os.Exit(errToExitCode(app.Run()))
}

func errToExitCode(err error) int {
	if err != nil {
		return 1
	}
	return 0
}

```

result:

![image](https://user-images.githubusercontent.com/15604894/142569275-9fdfb265-864c-4938-8666-58d79719dea0.png)

**Comment by joegrasse** [comment]
Looks like some rendering issues happening. Maybe try changing your font.

For reference #66

**Comment by rivo** [comment]
It's the first question in the FAQ: https://github.com/rivo/tview/wiki/FAQ

Please refer to that for a solution.
