### ISSUE TITLE
Render table without background color

### ISSUE THREAD

**Issue by Naatan** [rivo/tview#678]
It seems at the moment the table logic defaults to using a black background. I can override this, but only with another color.

But what if I want NO color? Quite simply; don't set a background color. It doesn't seem like this is currently possible, and so you HAVE to provide a background color and in the case where you don't want to now have to deal with figuring out what color to use.

Please provide a way to render UI without  background colors. Or even a way to render UI with all coloring stripped out.

**Comment by darkhz** [comment]
If you're talking about using the terminal's background color, you can do this by supplying tcell.ColorDefault to SetBackgroundColor.

**Comment by rivo** [comment]
Please see the FAQ for more info on this: https://github.com/rivo/tview/wiki/FAQ

In short, there is no "no colour".
