### ISSUE TITLE
can't type text into input field 

### ISSUE THREAD

**Issue by argb** [rivo/tview#688]
github.com/rivo/tview v0.0.0-20220106183741-90d72bc664f5
this version doesn't work, can't type anyting to input field
I changed back to an old version: github.com/rivo/tview v0.0.0-20210125085121-dbc1f32bb1d0,  it worked again.

first time use this package, I don't know what's the problem, sorry I can't feed more useful infomation back, i have no clue.

**Comment by rivo** [comment]
Please post a code example that I can run that illustrates your problem. I tried the demos in the package and they all worked fine.
