### ISSUE TITLE
question: How to handle normal keys?

### ISSUE THREAD

**Issue by lesovsky** [rivo/tview#69]
Hi,

I've found in examples how to handle special keys, but nothing about normal, regular keys such as 'a','b','c', etc. Could you provide simple example?

Thanks

**Comment by lesovsky** [comment]
Answer is found on [tcell godoc](https://godoc.org/github.com/gdamore/tcell#Key) --
For normal keys, like ASCII letters, we use KeyRune, and then expect the application to inspect the Rune() member of the EventKey.

```
	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		switch event.Key() {
		case tcell.KeyCtrlQ:
			app.Stop()
			os.Exit(0)
		case tcell.KeyRune:
			switch event.Rune() {
			case 'a':
				fmt.Fprintln(cmdl, "a is pressed")
			case 'F':
				fmt.Fprintln(cmdl, "F is pressed")
			default:
				fmt.Fprintln(cmdl, "rune is pressed")
			}
		}
		return event
	})
```

**Comment by rivo** [comment]
Yes, this is how it works. Glad you found it yourself. :-)
