### ISSUE TITLE
Detect end of TextView scrollable area

### ISSUE THREAD

**Issue by AuHau** [rivo/tview#697]
I would need to detect if a user reached the end of `TextView`, is that possible? I have not discovered the way. There is half-way solution trying to calculate this using `GetScrollOffset()` and `GetInnerRect()` and counting how many lines the `TextView` has. But if the wrapping is enabled and is in the game then I don't know how to get how many lines the `TextView` actually has as I don't have access to its `index`.

**Comment by rivo** [comment]
Apologies for the late reply. Is this still relevant? Yes, I realize there is currently no way to check for this. Let me know if you still need it.

**Comment by AuHau** [comment]
I'm not actively working on the original project, but as you said tview lack this capability.
