### ISSUE TITLE
Inconsistency between documentation and code

### ISSUE THREAD

**Issue by us91** [rivo/tview#699]
In the documentation for  `func (*Box) SetInputCapture ` , it is mentioned that:

"Note that this function will not have an effect on primitives composed of other primitives, such as Form, Flex, or Grid. Key events are only captured by the primitives that have focus (e.g. InputField) and only one primitive can have focus at a time. Composing primitives such as Form pass the focus on to their contained primitives and thus never receive any key events themselves. Therefore, they cannot intercept key events."

However, in the demo code `presentation`, the Grid page uses `SetInputCapture` which seems to work when Enter is pressed. This is not necessarily a bug. But some clarification on how the input capture works for composite primitives would be appreciated.

**Comment by rivo** [comment]
You're right. This behaviour was changed a while back but I forgot to update this part of the documentation. I just fixed that.
