### ISSUE TITLE
Application deadlock with very high CPU usage on pressing the Up key in a blank Table

### ISSUE THREAD

**Issue by darkhz** [rivo/tview#705]
Please treat this as a critical issue. A pull request has been made, see #706.

When a blank Table is:
- Selectable (`Table.SetSelectable(true, true)`)
- In Focus, and 
- the Up key is pressed, 

the application immediately deadlocks and incurs extremely high CPU usage.

Here is the code that illustrates the issue
```go
package main

import (
	"github.com/rivo/tview"
)

func main() {
	App := tview.NewApplication()

	Table := tview.NewTable()
	Table.SetBorder(true)
	Table.SetSelectable(true, true)

	TextView := tview.NewTextView().
		SetText("To trigger the application deadlock, press the Up key.")

	Flex := tview.NewFlex().
		AddItem(Table, 0, 1, true).
		AddItem(TextView, 0, 1, false).
		SetDirection(tview.FlexRow)

	if err := App.SetRoot(Flex, true).SetFocus(Table).Run(); err != nil {
		panic(err)
	}
}
```

**Comment by darkhz** [comment]
cc @rivo @tslocum(since this might affect cview, please test)

**Comment by rivo** [comment]
Thanks. Should be fixed with the latest commit.
