### ISSUE TITLE
Question / Feature request

### ISSUE THREAD

**Issue by jagottsicher** [rivo/tview#709]
This repo looks very promising if one is looking for an alternate to goncurses. Also more features and from scratch built up in Go.

My Question: Does it support to "printf" or "sprintf" to specific coorditnates on the screen (terminal)? and can I determinate the position of the cursor? is utf-8 fully supported? And does this repo support a windows command line as terminal without the need to have a third party terminal like cygwin?

**Comment by rivo** [comment]
Based on your questions, my impression is you're rather looking for something like https://github.com/gdamore/tcell/. `tcell` gives you full control over what you want to print on screen.

`tview` is based on `tcell` and focuses on providing common widgets such as buttons, input fields, forms, tables, and text views. If you want to put some text at a specific screen coordinate, there are ways to do that but that's not it's main focus so it might be cumbersome.

`tview` supports UTF-8 fully and it supports all terminals that `tcell` supports, including the Windows command line.

**Comment by jagottsicher** [comment]
True, thanks for turning my head into direction tcell. I am not really searching for something that specific but want to create some cool examples for a course. Also the long term maybe create a tool like mc which could (as a vision) become something like an super-extended tui proving a serious tui with graphic-like features and can be served over ssh terminal. 

Imagine macos or kde/gnome with mc and/or total commander all over ssh but server-sided executed. But that's a vision only cause I like Go much. :-) 

My questions answered, thanks, I'll close the issue (asap as I don't know I can close it with the APP)

**Comment by rivo** [comment]
Just another small note, `tcell` allows you to print individual UTF-8 characters on screen but if you want to print entire strings that contain UTF-8 characters, it gets complicated very quickly. `tview` handles this for you but `tcell` doesn't. I spent way more time making this work than I initially expected.

**Comment by jagottsicher** [comment]
Thanks! I'll keep that in mind, and when I face that problem I will thankfully remember it!
