### ISSUE TITLE
Setting a form field's background color does not apply when there is a placeholder

### ISSUE THREAD

**Issue by beeb** [rivo/tview#716]
Consider the following example:

```go
form := tview.NewForm()
form.SetFieldBackgroundColor(tcell.ColorWhite).SetFieldTextColor(tcell.ColorBlack)
form.AddFormItem(tview.NewInputField().SetLabel("field1").SetPlaceHolder("foo").SetPlaceholderTextColor(tcell.ColorDarkGrey))
form.AddFormItem(tview.NewInputField().SetLabel("field2"))
```

The second field will show the white background color, but the first field with a placeholder shows a different background color until some text is written in the field.

There is no function `SetPlaceholderBackgroundColor()` which could help in this case.

![image](https://user-images.githubusercontent.com/703631/159707913-bd74c441-5b7a-43c4-af97-b5865614c049.png)

**Comment by rivo** [comment]
You can use [`SetPlaceholderStyle()`](https://pkg.go.dev/github.com/rivo/tview#InputField.SetPlaceholderStyle) for this.
