### ISSUE TITLE
Feature Request: Demo file for colors

### ISSUE THREAD

**Issue by marioemmanuel** [rivo/tview#720]
It would be useful to find a working example on changing Colors under the demo folder, for example how to change the background color of a form.

**Comment by rivo** [comment]
You can call [`SetBackgroundColor()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetBackgroundColor) on any primitive, including forms. (Be aware, though, that this function returns a `Box`, not a `Form`, so you probably shouldn't chain it.)

**Comment by marioemmanuel** [comment]
In case it helps someone else, aside from rivo's comment, I also found the presentation demo files helpful to understand how colors are used in tview.
