### ISSUE TITLE
Question on modal form

### ISSUE THREAD

**Issue by marioemmanuel** [rivo/tview#721]
I would like to know if it is possible to implement a modal form. Reading the documentation I understand that only a message with two buttons conform the Modal widget. I am not sure if that is the case or I misunderstood the functionalities and I am wondering if it would be possible to display a complete entry modal form.

The use case is to have a Page with a table with values (front-end from a database) and then when user press a key he can enter a new record filling in InputFields, Checkboxes etc in a modal window that appears in front of the table.

If that is possible any sample code would be appreciated.

**Comment by rivo** [comment]
Check out the Wiki: https://github.com/rivo/tview/wiki/Modal

It contains instructions on how to make any other primitive a modal, for example a `Form`.
