### ISSUE TITLE
DropDown selection list is not adjusted to the right screen edge

### ISSUE THREAD

**Issue by dimonomid** [rivo/tview#726]
DropDown always aligns the _left_ edge of selection list and the main widget, but when the widget is too close to the right screen edge, the list ends up being drawn only partially, see screenshot (here, the "Menu" is the dropdown)

![image](https://user-images.githubusercontent.com/1329932/164967737-eb4a8ecf-b4e4-49bb-9a02-1bd0b4cd2cd3.png)

**Comment by rivo** [comment]
I merged it, thank you!

**Comment by dimonomid** [comment]
Thank you too!
