### ISSUE TITLE
Draw a graph, open a png image  

### ISSUE THREAD

**Issue by OsvaldoTCF** [rivo/tview#729]
Hello. I need to generate graphics and present them.
I would like in a box, open an image with framebuffer, for example.

**Comment by rivo** [comment]
I'd like to add the display of images at some point but demand for this is low so it's not high on the list.

I.e. currently, `tview` doesn't support graphics.

**Comment by Awesome-Sauces** [comment]
Would be nice if it did.

**Comment by aditya-K2** [comment]
Hi, does this mean rendering an Image like [ueberzug[(https://github.com/seebye/ueberzug)? or some other way?

**Comment by rivo** [comment]
Not really sure that the `uberzug` GitHub page provides a good explanation of what exactly it does. But it sounds to me like it's using some X11 trickery to display images. I don't think `tview` will ever go that way. It's supposed to be platform-independent, at least to the extent that `tcell` is platform-independent. And it's also supposed to stay within the terminal so you can, for example, use a `tview` application over an SSH connection.

What I meant above was using primitive UTF-8 characters along with some colour information to roughly display an image. Something along the lines of this: https://justine.lol/printimage.html
