### ISSUE TITLE
Ability to disable default style.

### ISSUE THREAD

**Issue by lesovsky** [rivo/tview#73]
Hi, 

Is it possible to disable default color style and use console-defined style?

In most cases people use their own color themes in their terminals and IMO programs have to use colors used by terminal and colors defined by programs should be optional. In my experience, changing style automatically from console-defined to program-defined might give unexpected visual appearance in some circumstances.

![image](https://user-images.githubusercontent.com/953312/37251407-603445fe-2531-11e8-94db-23ae2673ff3c.png)

**Comment by rivo** [comment]
Please see [`Styles`](https://godoc.org/github.com/rivo/tview#pkg-variables) on how to change the default styles.

I don't know if terminal applications have access to any individually predefined colors? This would be a [`tcell`](https://github.com/gdamore/tcell) topic. Maybe you can find out?

**Comment by lesovsky** [comment]
I've already familiarized with `Styles` variable, and as I understand it defines primitive's default color scheme automatically at program startup and thus overrides colors defined by terminal.

Anyway, I going to dig into `tcell` and try to find out how it works with colors.

Thanks!

**Comment by lesovsky** [comment]
Could you provide simple example how to work with `Style`? I trying to manipulate with struct variables such as `Style.PrimaryTextColor`, Style.PrimitiveBackgroundColor`, but see no color changes in primitives.

**Comment by lesovsky** [comment]
ok, i see, styles have to be changed before primitives initialization.

**Comment by lesovsky** [comment]
Well, I've completely solved the issue.
Before initializing primitives, it needs to setup `Styles` variable, in particular `Styles.PrimaryTextColor` and `Styles.PrimitiveBackgroundColor` shoul be set to `tcell.ColorDefault`. Thus program will get terminal colors for foreground text and background. Probably, adjusting other Style's variables to `tcell.ColorDefault` will make the same behaviour but I didn't check.

**Comment by rivo** [comment]
Yes, `tcell.ColorDefault` basically means "transparent". I haven't checked myself how this affects the drawing of primitive backgrounds but if you say you were able to achieve the desired effect, then I assume that's the solution.

The `Styles` struct is really only meant to be set once in the beginning, to define the overall style of your application. These are the defaults that are used during instantiation of primitives. (That's why they don't have an effect afterwards anymore.)
