### ISSUE TITLE
Scrolling table makes it loosing expansion

### ISSUE THREAD

**Issue by p3g4asus** [rivo/tview#731]
Hi,
I developed an app that uses tview.Table with many linses (much more lines that can actually be visualized) with expansion set. Before scrolling, the expansion is correctly applied. If I scroll down to see "hidden" lines the table "looses" the expansion properties and the columns are not expanded (as if SetExpansion was not called). If I scroll again to the top, the expansion is applied again.
Scrolled to the top:
![immagine](https://user-images.githubusercontent.com/3275734/167418588-d80108c9-490e-4ab1-8a35-c45297dd6a49.png)
On line below the top:
![immagine](https://user-images.githubusercontent.com/3275734/167418808-75d6145b-9f83-4f0a-a848-dcbd248c164d.png)
Is this the expected behaviour?
Thanks in advance for support and thank you for this great library.

**Comment by rivo** [comment]
Are you sure you have the expansion set on _all_ rows? From what you're describing, it seems that you only have the expansion value set on cells in the first row. So when it goes out of view, nothing is expanded anymore.

**Comment by p3g4asus** [comment]
> Are you sure you have the expansion set on _all_ rows? From what you're describing, it seems that you only have the expansion value set on cells in the first row. So when it goes out of view, nothing is expanded anymore.

You are absolutely right. I am sorry. That was my stupid fault. I am closing this issue.
Thanks again.

**Comment by rivo** [comment]
No problem at all. I'm glad you were able to resolve it.
