### ISSUE TITLE
New tview based app

### ISSUE THREAD

**Issue by aurc** [rivo/tview#734]
Hello,

Just released an app based on tview/tcell and I was wondering it could be listed with the apps on your page. 
https://github.com/aurc/loggo

Thanks
Aurelio

**Comment by rivo** [comment]
Please leave a pull request with your change for the README file and I'll merge it.

**Comment by aurc** [comment]
Thanks! Done: A terminal app for structured log streaming (GCP stack driver, k8s, local streaming)
