### ISSUE TITLE
grid border title

### ISSUE THREAD

**Issue by xhsky** [rivo/tview#735]
Is there a way to add a title to the grid's border?

**Comment by rivo** [comment]
You can add a title to any primitive using [`Box.SetTitle()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetTitle).

If you mean to add a title to each grid item, drawn over the grid lines, there is no direct way. You could [remove](https://pkg.go.dev/github.com/rivo/tview#Grid.SetBorders) the [gaps](https://pkg.go.dev/github.com/rivo/tview#Grid.SetGap) and add borders and titles to each of your grid items. But this will draw separate boxes for each item. Not as pretty as the grid lines but it might do the trick for you.
