### ISSUE TITLE
Table.RemoveColumn() does not update lastColumn

### ISSUE THREAD

**Issue by cespedes** [rivo/tview#736]
When removing a column in a table by calling RemoveColumn(), even if the removal is successful, the table continues to have the same number of columns.

A simple fix is to include these lines at the end of `func (t *tableDefaultContent) RemoveColumn` (table.go line 332):

    if column <= t.lastColumn {
            t.lastColumn--
    }

I can prepare a pull request if you prefer.

**Comment by rivo** [comment]
Thank you! It's fixed now.
