### ISSUE TITLE
word wrap on List

### ISSUE THREAD

**Issue by jbrodriguez** [rivo/tview#741]
how to achieve word wrap on list items ?

![Screen Shot 2022-07-02 at 11 03 53](https://user-images.githubusercontent.com/1305422/177007899-1e69683a-cec0-444e-a017-e329037919bc.png)

there's text after `you` which is cut by the terminal window size.

if not using a list, any other suggestion on how to do it ?

i looked at grid, but each column of a grid is independent, so you lose the list behavior

**Comment by rivo** [comment]
Lists don't implement word-wrapping and likely won't in the future. Word-wrapping is implemented in `TextView`. If you use "regions" in a text view, you can highlight parts of the text. You can then also override the keys using [`SetInputCapture()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetInputCapture) to fit your needs.

(See also #588)
