### ISSUE TITLE
Not renderring real-time

### ISSUE THREAD

**Issue by ashis0013** [rivo/tview#744]
Trying to use a basic counter but the UI doesn't update. Am I doing anything wrong here?
```go
package main

import (
    "fmt"
    "time"
    "github.com/rivo/tview"
)

func main() {
    app := tview.NewApplication()
    status := tview.NewTextView().SetDynamicColors(true).SetWrap(false)

    var t = 0
    go func() {
        for true {
            status.SetText(fmt.Sprintf("Time is %d", t))
            t++
            time.Sleep(time.Second)
        }
    }()
    if err := app.SetRoot(status, true).SetFocus(status).Run(); err != nil {
		panic(err)
	}
}
```

**Comment by apprehensions** [comment]
what did you do to solve this????!?!?!

**Comment by rivo** [comment]
There are multiple ways this could be done. Either install a listener on the `TextView`, see [`SetChangedFunc`](https://pkg.go.dev/github.com/rivo/tview#TextView.SetChangedFunc). Or simply call [`app.Draw()`](https://pkg.go.dev/github.com/rivo/tview#Application.Draw) in your goroutine.

**Comment by apprehensions** [comment]
Using `SetChangedFunc` with `app.Draw` froze the application. I am using `QueueChangedFunc` with the changed text inside it and it works. Thanks.

**Comment by rivo** [comment]
Can you post the version which froze the application? Either there is a bug or the documentation is wrong. Both cases should be investigated.
