### ISSUE TITLE
ANSI writer - cursor movement to history

### ISSUE THREAD

**Issue by dcrystalj** [rivo/tview#746]
I would like to have an option to move cursor back and forth? just like writing to terminal does.

Can ansi writer modify something that was already written with characters like `\r` or `\b` ? If I am redirecting terminal output to ANSI writer a lot of things are broken because of this.

for example writing `\b` character should move cursor one char back, so effectively next written character should override the last one.

**Comment by rivo** [comment]
The ANSI writer will convert basic text and colour escape codes. But it won't translate any control sequences. In short, piping another program's output into `tview` is doable in many cases, but running another interactive application inside `tview` is not possible. At this point, `tview` is not like tmux/screen.

Btw, this is one of the suggested (major) features in the questionnaire (#578) but demand for it is low. There are other features that seem to be much more important to many users.

**Comment by dcrystalj** [comment]
ok, thank you. Currently I am using tview to display other programs output and it's quite annoying when there is some kind of loading.

I have submitted the questionnaire now, but didn't know that there was any. Maybe you should consider linking it in root readme.md to get more realistic feedback?

I hope this feature will be eventually added to tview 🙏

**Comment by rivo** [comment]
The questionnaire was pinned to the top of the issues page for quite a long time. I think I have a good idea now what people need. I might post an updated questionnaire at some point.
