### ISSUE TITLE
Support for InputFields hints/placeholders

### ISSUE THREAD

**Issue by muesli** [rivo/tview#75]
It would be nice if InputFields supported hints (also known as placeholders sometimes).

**Comment by rivo** [comment]
Similarly to my question in #77, is this an actual requirement you came across in your application? All input fields have labels. Maybe you can provide an example where they aren't enough?

**Comment by muesli** [comment]
It would be nice to give user some form of indication what a reasonable / expected value would look like, without having to pre-set it as an InputField's value. One could add this information to the label, but in case of longer hints, this quickly breaks the layout and looks a bit messy from a UX perspective.

**Comment by rivo** [comment]
Have a look at the latest commit. This adds `SetPlaceholder()` to `InputField`.

**Comment by muesli** [comment]
Works nicely, the only minor nitpick I have is that it's barely readable with the default color scheme.

**Comment by rivo** [comment]
It looks good in my terminal. The idea is to give it low contrast (just like HTML placeholders are usually also low-contrast) so it's not confused with actual input. But you're free to set `Styles.ContrastSecondaryTextColor` to your own choice of color.
