### ISSUE TITLE
 hides contents of table for table example

### ISSUE THREAD

**Issue by veezhang** [rivo/tview#760]
Commit: v0.0.0-20220911190240-55965cf21d8e
Bash Version:  GNU bash， version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
OS: CentOS Linux 7 (Core)
uname: Linux harris-test4 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

<img width="638" alt="image" src="https://user-images.githubusercontent.com/14001308/189873644-ff27da8f-cb61-40a0-8197-5a97e61ac522.png">

**Comment by rivo** [comment]
Please check out the FAQ:

https://github.com/rivo/tview/wiki/FAQ

**Comment by veezhang** [comment]
@rivo Thanks a lot!
