### ISSUE TITLE
If a DropDown opens over another flex container, mouse clicks don't get recognized and the DropDown doesn't close as expected

### ISSUE THREAD

**Issue by MarvinJWendt** [rivo/tview#761]
### Description

When a `DropDown` opens over another flex container, the options cannot be clicked with the mouse. It also does not close properly (leaves the part, that is reaching into another flex container, open).

### DropDown opened
<img width="405" alt="image" src="https://user-images.githubusercontent.com/31022056/190343307-a914433a-70ec-4b34-a0a5-5e582ad88043.png">

### DropDown closed
<img width="332" alt="image" src="https://user-images.githubusercontent.com/31022056/190343380-effc4dc7-507b-4234-8e13-133224716499.png">

### Reproduction code

```go
package main

import (
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	wrapper := tview.NewFlex()

	topBar := tview.NewFlex()
	topBar.SetBorder(true)
	topBar.SetBackgroundColor(tcell.ColorDefault)

	mainContent := tview.NewFlex()
	mainContent.SetBorder(true)
	mainContent.SetBackgroundColor(tcell.ColorDefault)

	wrapper.SetDirection(tview.FlexRow)
	wrapper.AddItem(topBar, 3, 0, false)
	wrapper.AddItem(mainContent, 0, 1, false)

	dropDown := tview.NewDropDown()
	dropDown.SetBackgroundColor(tcell.ColorDefault)
	dropDown.SetLabel("Placeholder: ")
	dropDown.SetOptions([]string{"Option 1", "Option 2", "Option 3"}, nil)

	topBar.SetDirection(tview.FlexColumn)
	topBar.AddItem(dropDown, 20, 0, false)

	app.EnableMouse(true)
	app.SetRoot(wrapper, true)
	app.Run()
}
```

**Comment by rivo** [comment]
The mouse handling for drop-downs was indeed buggy. Thanks for catching this. The latest commit fixes this.

Regarding the lingering option, there are two things to consider:

1. An empty `Flex` has "nothing" in it. So it also doesn't delete anything. You may want to put a `Box` in there instead. (See code below.)
2. Don't use `tcell.ColorDefault`. It never works the way you would expect. See the [FAQ](https://github.com/rivo/tview/wiki/FAQ) for more details.

```go
package main

import (
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	wrapper := tview.NewFlex()

	topBar := tview.NewFlex()
	topBar.SetBorder(true)

	mainContent := tview.NewBox()
	mainContent.SetBorder(true)

	wrapper.SetDirection(tview.FlexRow)
	wrapper.AddItem(topBar, 3, 0, false)
	wrapper.AddItem(mainContent, 0, 1, false)

	dropDown := tview.NewDropDown()
	dropDown.SetLabel("Placeholder: ")
	dropDown.SetOptions([]string{"Option 1", "Option 2", "Option 3"}, nil)

	topBar.SetDirection(tview.FlexColumn)
	topBar.AddItem(dropDown, 30, 0, false)

	app.EnableMouse(true)
	app.SetRoot(wrapper, true)
	app.Run()
}
```

**Comment by rivo** [comment]
To be honest, I'm not that familiar with the capabilities of different terminals. @gdamore from `tcell` is the expert here. I do know that we had issues with `ColorDefault` in the past and the solution was always to pick a specific colour. Also, people often ask for default colours in a sense that `tview` might adjust accordingly on dark terminals (black background) or light terminals (white background) but my understanding is that this can't be made to work reliably on a variety of terminals. But if `tcell` ends up finding a way to do this somehow, I'm happy to include it in `tview`.
