### ISSUE TITLE
Feature request: floating window/modal

### ISSUE THREAD

**Issue by golangdojo99** [rivo/tview#763]
Currently, a widget is set as root using `(*tview.Application).SetRoot` method and the current root widget can be changed can be using the same method. Only a single widget can be root at once, widgets like Flex and Grid allow users to layout widgets into a single widget and set it as root to display multiple widgets. However, there is no such widget that can "float" above the root widget and still display the content of the root widget as is.

**Comment by rivo** [comment]
Please check out `Pages`.

**Comment by golangdojo99** [comment]
`Pages` widget can be used to switch between multiple widgets, not display one on top of the other while conserving the background of the widget that is at the bottom.

**Comment by rivo** [comment]
Yes, it can. Check out the Wiki:

https://github.com/rivo/tview/wiki/Modal
