### ISSUE TITLE
Differentiate FormItems by type

### ISSUE THREAD

**Issue by adrianhalten** [rivo/tview#765]
Hi,

I have a form with dropdowns and inputfields and want automatically write a config file out of the inputs.

With  ```form.GetFormItem(1).(*tview.DropDown).GetCurrentOption()``` I get the current option of my dropdown.

My Problem is to differntiate between the FormItems to get the content of them.
How can I manage to do something like in the pseudocode?

Pseudocode:

```
for _, formitem =: range form { 

       if formitem.getType() == "dropdown" { 

                contentToWrite := formitem.(*tview.InputField).GetText()

       } else {

                contentToWrite := formitem.(*tview.DropDown).GetCurrentOption()

      }
}
```

**Comment by adrianhalten** [comment]
Found the solution by using the reflect package.

```reflect.TypeOf(form.GetFormItem(i))```

**Comment by rivo** [comment]
You can also use [type switches](https://go.dev/tour/methods/16). That's probably faster than using `reflect`.
