### ISSUE TITLE
feature request: InputField.SetTextAlignment()

### ISSUE THREAD

**Issue by carpii** [rivo/tview#771]
Apologies if this feature is already supported, but I haven't been able to find it in the API docs

It would be very useful to have a TextInput which supports right alignment (for entry of financial amounts, for example)

Currently it just left aligns the value in the Form

**Comment by carpii** [comment]
would cause a few UI issues. 

I didn't think this through properly. Closing ticket :-)

**Comment by rivo** [comment]
It would probably also be helpful for other languages, e.g. Hebrew. But it would add a _lot_ of complexity to the package that I'm not considering it at this point.
