### ISSUE TITLE
Form example outdated?

### ISSUE THREAD

**Issue by Thijxx** [rivo/tview#772]
https://github.com/rivo/tview/wiki/Form

this seems to be no longer a working example
`tview.NewForm` has no  `AddTextArea`

when I use `AddFormItem` it does not accept `tview.NewTextArea()` as input so not sure how to fix it

**Comment by rivo** [comment]
It does:

https://pkg.go.dev/github.com/rivo/tview#Form.AddTextArea

You'll want to upgrade to the latest version.

**Comment by Thijxx** [comment]
Thanks for the quick reply, how does that work without versions in the repo? 
I have tried `go install github.com/rivo/tview@latest` and `go get -u github.com/rivo/tview`

**Comment by Thijxx** [comment]
`go mod vendor`  
` go get github.com/rivo/tview@latest`
