### ISSUE TITLE
broken links in InputField wiki

### ISSUE THREAD

**Issue by carpii** [rivo/tview#775]
I couldn't find a way to fork the wiki repo, so I'll report them here instead

https://github.com/rivo/tview/wiki/InputField

The two autocomplete links are broken 

They have since moved from `demos/inputfield/autocomplete.go` ->  `demos/inputfield/autocomplete/main.go`), and likewise for async

**Comment by rivo** [comment]
Thanks for letting me know. I fixed the broken links.

I don't know if a PR can be submitted for a Wiki.

**Comment by rivo** [comment]
By the way, @carpii, thank you for sponsoring me! 😊

**Comment by carpii** [comment]
No probs, great lib thanks :-)

**Comment by rivo** [comment]
I didn't know you could run `tview` (or `tcell` for that matter) in VSCode. I always get

> "open /dev/tty: device not configured"

when I try to do that. But anything related to terminal support is a matter of [`tcell`](https://github.com/gdamore/tcell). You might want to ask for help there. I don't know much about that topic.

**Comment by carpii** [comment]
Thanks, didn't think to try tcell support, but makes sense since they provide the coloring features


For debugging in vscode, I thinkit's just a case of adding    `"console": "integratedTerminal",` to your `.vscode/launch.json` (and then select the launch profile from the Run and Debug tab)

Trimmed down version of mine below...

````
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "UI",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "console": "integratedTerminal",
            "args": ["ui"]
        },
        {
            "name": "Import OFX",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "console": "integratedTerminal",
            "args": ["import", "--filename", "data/barclays_test.ofx"]
        }
    ]
}
````

Then I can debug my tview app directly in vscode terminal (although color palette seems restricted). Still, it's pretty handy :)

![](https://i.imgur.com/J6xpUGN.png)

**Comment by carpii** [comment]
Found the solution, you have to set this in vscode settings..

`"terminal.integrated.minimumContrastRatio": 1`
