### ISSUE TITLE
Rendering magic

### ISSUE THREAD

**Issue by eighty4** [rivo/tview#778]
I took a glance at the codebase and couldn't find how ANSI or VT100 is used to render terminal window size aware interfaces.

I've read that this can be done by doing a resize to 99 lines and 999 columns and then getting the size of the terminal?

```
CUP 999 999
DSR 6
```

I couldn't find these vt100 escape sequences in your codebase so I'm still stumped (but still searching).

Thanks!

**Comment by rivo** [comment]
You'll want to ask @gdamore about this. `tview` uses [`tcell`](https://github.com/gdamore/tcell) which does all the heavy lifting regarding terminals and ANSI sequences.

Since I can't help you with this inquiry, I'll close this issue.
