### ISSUE TITLE
[QUESTION] About automatically coloring specific word patterns in TextView

### ISSUE THREAD

**Issue by AmrGanz** [rivo/tview#782]
Hello Rivo,

I usually use the same method as in [here](https://github.com/rivo/tview/blob/master/demos/textview/main.go) to color specific words. For example, making the word "error" shown in red and the word "success" shown in green.

I was wondering, is there a way to make it happen without explicitly reformat each instance of these words? Maybe to give an example, when I use a terminal like MobaXterm, it has this functionality of coloring specific words with a unique color automatically.

If this is can be already achieved, then I would really appreciate you pointing me to the document covering it and I will read more about it.

Kind regards

**Comment by rivo** [comment]
Every colour tag introduces a new color for the following characters, until the next colour tag. So, no, there is no way to automatically colour specific words. But I think it should be fairly straightforward to come up with a regular expression to wrap specific words with colour tags.

**Comment by digitallyserviced** [comment]
Check out https://github.com/pgavlin/femto

I use it in my project as a js editor with syntax highlighting.... Makes it a bit easier to handle styling/formatting if you can define a syntax/format for your text.... The dude basically stripped micro 1.4 down to the textarea and wrapped tview primitive around it. 


![image](https://user-images.githubusercontent.com/1828125/209579203-27446d94-1023-42e7-a4c5-8216096dab8a.png)

**Comment by AmrGanz** [comment]
Thanks @digitallyserviced , I am currently testing it and hopefully it will get me the results I am seeking.

@rivo @digitallyserviced BTW, the reason I am asking this question is because when I use a `TextView` (while enabling dynamic coloring) and I wanted to format the shown text, lets say by [column-formatting](github.com/ryanuber/columnize) the output.  The added color tags mess it up.

For example:

This code block will work perfectly fine and will show the desired column-formatted output:
```
package main

import (
	"github.com/rivo/tview"
	"github.com/ryanuber/columnize"
)

func main() {

	data := []string{"field1" + "|" + "fiel2"}
	data = append(data, "value1"+"|"+"value2")

	app := tview.NewApplication()
	textView := tview.NewTextView().
		SetChangedFunc(func() {
			app.Draw()
		}).SetDynamicColors(true)
	textView.SetBorder(false)
	textView.SetWrap(true)
	FormatedOutput := columnize.SimpleFormat(data)
	textView.SetText(FormatedOutput)

	app.SetRoot(textView, true).SetFocus(textView).EnableMouse(false)
	app.Run()
}
```
output:
```
field1  fiel2                                                                                                                                                                                 
value1  value2
```

Now, if I added color tags like the below example, it will mess up the output formatting:

```
package main

import (
	"github.com/rivo/tview"
	"github.com/ryanuber/columnize"
)

func main() {
	Yellow := "[#FFFF00]"
	White := "[#FFFFFF]"

	data := []string{"field1" + "|" + "fiel2"}
	data = append(data, Yellow+"value1"+White+"|"+"value2")

	app := tview.NewApplication()
	textView := tview.NewTextView().
		SetChangedFunc(func() {
			app.Draw()
		}).SetDynamicColors(true)
	textView.SetBorder(false)
	textView.SetWrap(true)
	FormatedOutput := columnize.SimpleFormat(data)
	textView.SetText(FormatedOutput)

	app.SetRoot(textView, true).SetFocus(textView).EnableMouse(false)
	app.Run()
}
```
output (coloring will work fine in the terminal):
```
field1                    fiel2                                                                                                                                                               
value1  value2
```

I understand that this is working as designed since the `Columnize` see the colors tag as text and working as expected. And this is why I am looking for other ways to natively color specific words/patterns instead.

**Comment by digitallyserviced** [comment]
@AmrGanz 
I see... well you may want to look if you can hack the columnize lib to have the width functions use [`TaggedStringWidth`](https://github.com/rivo/tview/blob/master/util.go#L438) which will give you the width without tags involved. Or at least look at how `iterateString` is used to index/draw/colorize with a callback to write contents into the screens... using `decomposeString` which gives you indices of the tags/stripped text/width that you can then paint/output on your own.

**Comment by rivo** [comment]
@AmrGanz I think you'll want to add color tags at the end of your text processing chain, i.e. after using `columnize`. You might be able to insert them at specific locations in the string or use regular expressions to insert them.

Finally, to answer your initial question, no, there is no way to apply colours to specific word patterns. This kind of behaviour is meant to be implemented outside of `tview`.

I'm closing this now as I don't think there is anything to do for me here. Feel free to respond or open a new issue if necessary.
