### ISSUE TITLE
STDIN of tview process skipping some characters

### ISSUE THREAD

**Issue by sharadregoti** [rivo/tview#785]
I have the following program, which tries to get a shell access into a running kubernetes pod. I am trying to achieve the same functionality but using tview. With below program i am able sync stdout, stdin, stderr of the kubectl process with tview UI.

But while inputting something (as it is a shell). I have to press the same key multiple times to view it on the UI.
```
package main

import (
	"fmt"
	"os"
	"os/exec"
	"time"

	"github.com/rivo/tview"
)

func main() {
	arr := []string{"exec", "-it", "-n", "db", "postgres-dev-6844b6cb77-hqh9r", "--", "bash"}
	cc := exec.Command("kubectl", arr...)

	app := tview.NewApplication()

	textArea := tview.NewTextView()

	cc.Stdin = os.Stdin
	cc.Stdout = os.Stdout
	cc.Stderr = os.Stderr

	if err := cc.Start(); err != nil {
		fmt.Println("failed to start", err)
		return
	}

	go func() {
		if err := cc.Wait(); err != nil {
			fmt.Println("failed to wait", err)
			return
		}
	}()

	if err := app.SetRoot(textArea,
		true).EnableMouse(false).Run(); err != nil {
		panic(err)
	}
}
```

![image](https://user-images.githubusercontent.com/24411676/208962940-bbacf137-5765-403f-8604-2f814967b67b.png)

For example, In this image I had to press `l` 2 times, `s` 2 times & `enter` key 2 times to execute the ls command. And also i am not able to view the cursor of shell.

What am I doing wrong here?

**Comment by sharadregoti** [comment]
@rivo Any update on this?

**Comment by rivo** [comment]
I'm not able to run this program as it requires external dependencies.

But in any case, I don't think assigning `os.Stdin`/`os.Stdout` to other processes will work with `tview` (or `tcell`, for that matter). `tcell` needs these two for itself. So whatever the problem is here, it's very likely due to two different processes trying to access the same resource.
