### ISSUE TITLE
Forms can grow beyond terminal dimensions

### ISSUE THREAD

**Issue by joegrasse** [rivo/tview#79]
If you add too many form items to a form, it can vertically grow beyond the terminal's height. It would be nice if one could scroll within a form in such a case.

**Comment by rivo** [comment]
Thanks for the hint. I just fixed this.

**Comment by joegrasse** [comment]
This works as long as you don't specifically set the Form's Box size. See issue #81 as to why you might do that.

**Comment by joegrasse** [comment]
@rivo Looks like you still can set the Form's Box size just as long as it is less than the terminal window size. When you set the Box size bigger than the terminal size, that is when this change no longer works.

**Comment by rivo** [comment]
See #81 for details about layouts in `tview`.

Setting a box to a size larger than the screen will lead to undefined effects.

**Comment by joegrasse** [comment]
Ok, maybe you can clarify something then. If do ```form.SetRect(``` to change the Forms size, this change doesn't work, but if I do ```form.Box.SetRect(```, this change works. Why would that be?

**Comment by joegrasse** [comment]
@rivo Sorry for the multiple comments, but I noticed something. Even without changing the Form's Box size the default Box can be bigger than the terminal size (granted unlikely). Under this condition though this change still doesn't work as expected. So my setting of the Form's box size explicitly wasn't what was causing this change to not work.

**Comment by joegrasse** [comment]
@rivo Ok, I believe I have discovered the issue. I will submit a pull request for you to look at.

**Comment by rivo** [comment]
Can you explain why you're setting the `Form` to a size that exceeds the screen?

None of the primitives are made for this case (and fixing it only in the `Form` class introduces an inconsistency which I'm not particularly happy about).

**Comment by joegrasse** [comment]
The issue exists even if I don't set the form size. The box default size can be bigger than the screen size, and in this situation keeping the form item in focus didn't work.

**Comment by joegrasse** [comment]
The end user can also resize the terminal which can cause the form/box size to be bigger than the screen.

**Comment by rivo** [comment]
Again, this is what `Flex` and `Grid` are for. They adjust their size according to the screen, even when the user resizes it. I would go so far as to say that calling `SetRect()` or using the default size of a primitive is something most applications will never do.

Check out the demo in the `demos/form/` directory. You can resize the screen and the form will always adjust. And with the new modifications, the currently selected form field will always be in view.

**Comment by joegrasse** [comment]
>I would go so far as to say that calling SetRect() or using the default size of a primitive is something most applications will never do.

Yeah, I was just getting it to work in this situation as well. My case was for the form to have a more pop over look rather than it come up full screen over the main application view.

**Comment by rivo** [comment]
Ah, so you would like to set the form to a fixed size at first but it should become smaller automatically if that size exceeds the available screen space. Would something like that help you?

**Comment by joegrasse** [comment]
Yes :)

**Comment by rivo** [comment]
Let me think about this.

**Comment by rivo** [comment]
I just added some code to `Box` that will ensure that the box contents remain within the screen. I think this should help you achieve what you would like to do. Please have a look and let me know if this works for you.

**Comment by joegrasse** [comment]
@rivo Just so I make sure we are on the same page, The form outline still goes past the terminal screen (which is what I would want), but I can now tab between form items and it focuses as expected. Is this the expected result?

**Comment by rivo** [comment]
Every primitive has an "outer" position and size (this is what you see when the border gets drawn) and an "inner" position and size (this is the space where the primitive's content is drawn). The functions are [`GetRect()`](https://godoc.org/github.com/rivo/tview#Box.GetRect) and [`GetInnerRect()`](https://godoc.org/github.com/rivo/tview#Box.GetInnerRect), respectively.

I modified `GetInnerRect()` such that it is always fully contained in the screen. So if your form is larger than the screen, it is expected that while the border still looks like it extends beyond the screen, the form elements will scroll with the focus.

If you don't see this behaviour, let me know.

**Comment by joegrasse** [comment]
It is working as you described. 

Thank you.
