### ISSUE TITLE
[Question] Why `SetInputCapture` in for-loop not work

### ISSUE THREAD

**Issue by eeeXun** [rivo/tview#794]
Having two textarea, `a` and `b`. And I want to get their text when press `<C-n>`.
But it always get text of `b`, even I focused on `a` and press `<C-n>`
```go
package main

import (
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

func main() {
	flex := tview.NewFlex()
	app := tview.NewApplication()

	a := tview.NewTextArea()
	b := tview.NewTextArea()
	flex.AddItem(a, 0, 1, true).AddItem(b, 0, 1, true)

	for _, area := range []*tview.TextArea{a, b} {
		area.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
			key := event.Key()
			switch key {
			case tcell.KeyCtrlN:
				text := area.GetText()
				panic(text)
			}
			return event
		})
	}

	if err := app.SetRoot(flex, true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}
}
```

**Comment by rivo** [comment]
This is a Golang issue, not a `tview` issue. Check out https://github.com/golang/go/discussions/56010 for a discussion. Incidentally, this will be a breaking change in Golang, i.e. in some future Go version, your example will work as you expected it.

**Comment by eeeXun** [comment]
Thanks @rivo for sharing this discussion!
