### ISSUE TITLE
Question: Implementing Progress bar Draw Method

### ISSUE THREAD

**Issue by aditya-K2** [rivo/tview#795]
Hi, I have implemented a progress bar [primitive](https://github.com/aditya-K2/gomp/blob/master/ui/progressBar.go). It works as follows:

1. You set the `progressFunc` which returns the values that you need to show (e.g BarTitle, BarText, percentage)
2. And then the Draw() method draws the progressbar from the value it receives from the progressFunc()

As far as I have read the documentation and used `tview`, the `Draw` Method is called upon Events (correct me if I am wrong). I wanted to Draw only the progress bar primitive every second. Upon using `QueueUpdate` and `QueueUpdateDraw` the whole "screen" seems to stop responding maybe it's because:
> The provided function will be executed as part of the event loop 
\- tview [documentation](https://pkg.go.dev/github.com/rivo/tview#Application.QueueUpdate)

> Please take into consideration that the progressFunc I use takes some time to retrieve the values hence the blockage (ig?)

So I have been left but no choice but to Draw the whole app every time. like so:

```go
	go func() {
		for {
			App.Draw()
			time.Sleep(time.Second)
		}
	}()
```

This seems to work fine. I have been using this for a long time. But I keep wondering is this the right way or if is there a more elegant way to do this. Any help would be welcome. Thanks for your time.

**Comment by digitallyserviced** [comment]
What you are doing is currently the only way to handle it with vanilla tview's application methods. 

However, the most minimal steps would be to use the `screen.SetContent` methods, and then call `screen.Show`.

Those methods update the backend cell/frame buffers handled by `tcell.Screen` and mark dirty cells which are then actually rendered to the terminal with the `screen.Show()`. 

However for me the `application.Draw` also seemed a little heavier then necessary when only wanting to redraw certain primitives... Maybe these will help you? The functions are made variadic so you do not have to update any existing code, but can pass multiple primitives when you want to...

The `SetContent`/`Show`/`Draw(primitive)` combo's are what I use for my app that has animations that only redraw affected/dirty cells...

The code below may be missing other pieces but hopefully you can get the gist of how this can be helpful to target primitives....

```go

// Draw refreshes the screen (during the next update cycle). It calls the Draw()
// function of the application's root primitive and then syncs the screen
// buffer. It is almost never necessary to call this function. It can actually
// deadlock your application if you call it from the main thread (e.g. in a
// callback function of a widget). Please see
// https://github.com/rivo/tview/wiki/Concurrency for details.
func (a *Application) Draw(p ...Primitive) *Application {
  a.DrawTo(a.screen, p...)
	return a
}

func (a *Application) DrawTo(scr tcell.Screen,p ...Primitive) *Application {
  a.QueueUpdate(func() {
		if len(p) == 0 {
			a.draw()
			return
		}
		a.Lock()
		if scr != nil {
			for _, primitive := range p {
				primitive.Draw(scr)
			}
			// a.screen.Show() -- called in my event loop elsewhere
		}
		a.Unlock()
	})
	return a
}

```
![demo3](https://user-images.githubusercontent.com/1828125/214762118-338cc82d-1f42-4568-ab67-89cf67e3366f.gif)

**Comment by digitallyserviced** [comment]
I remembered where I picked up the Draw variadic...

https://github.com/tslocum/cview/blob/master/application.go#L652

**Comment by aditya-K2** [comment]
> @aditya-K2 What you are doing is currently the only way to handle it with vanilla tview's application methods. 
> 
> However, the most minimal steps would be to use the `screen.SetContent` methods, and then call `screen.Show`.
> 
> Those methods update the backend cell/frame buffers handled by `tcell.Screen` and mark dirty cells which are then actually rendered to the terminal with the `screen.Show()`. 
> 
> However for me the `application.Draw` also seemed a little heavier then necessary when only wanting to redraw certain primitives... Maybe these will help you? The functions are made variadic so you do not have to update any existing code, but can pass multiple primitives when you want to...
> 

I see. Thanks for the help. 🤝🏽
