### ISSUE TITLE
checkbox style

### ISSUE THREAD

**Issue by vendelin8** [rivo/tview#803]
Hi,

Nice library, thanks!
I have an issue with how the checkbox looks like, or rather that it's too invisible for me. I tried to find unicode characters, eg. ☐ but it's very small in my terminal, doesn't help too much.

So my other choice would be eg. wrapping the original solution inside square brackets like `[X]` and `[ ]`. It would be still the smallest widget, and I think the only downside of this would be (other than most likely backward incompatibility) when someone wants them very dense eg. a minesweeper. But for a minesweeper I'd choose a more lightweight solution anyway than hundreds of checkbox widgets.

What do you think?

**Comment by carpii** [comment]
As a workaround in the meantime, you could pad it with spaces a little...

    NewCheckbox().SetCheckedString(" X ")

**Comment by petr-stupka** [comment]
I this was solved in https://github.com/rivo/tview/issues/803?

**Comment by rivo** [comment]
The latest commit, https://github.com/rivo/tview/commit/b3bd1aa5e9f23ba61af8160d1021dab4df701eb0, adds the `SetUncheckedString` function. Together with `SetCheckedString`, this should allow you to customize the checkbox to your needs.
