### ISSUE TITLE
Not fill the full width/height in a layout

### ISSUE THREAD

**Issue by tcurdt** [rivo/tview#805]
I am struggling with some of the layout specifics. I created this layout by using multiple flex layouts.

<img width="1325" alt="Screenshot 2023-01-31 at 01 36 06" src="https://user-images.githubusercontent.com/13697/215628719-cdd25423-6f21-4090-bd0c-de7ddbdaa2e0.png">

Which was quite straight forward. But this way I can only configure ratios.

The dropdowns are filling a full cell while they should only stay at their intrinsic size. Same goes for the button that is way too big. It's fine for the List to fill the available space, but all other controls should not.

The right side looks like this:

```
	layout := tview.NewFlex().SetDirection(tview.FlexRow)

	dropdown := tview.NewDropDown().
		SetLabel("Select: ").
		SetOptions([]string{
			"First",
			"Second",
			"Third",
			"Fourth",
			"Fifth",
		}, nil)
	dropdown.SetBorder(true)

	button := tview.NewButton("Run")
	button.SetBorder(true)

	layout.AddItem(dropdown, 0, 2, false)
	layout.AddItem(button, 0, 1, false)
```

I have the feeling I am missing something.

Did I miss something in the docs?
Could you give me some pointers?

**Comment by digitallyserviced** [comment]
@tcurdt The AddItem function supports a fixed size...

**Comment by tcurdt** [comment]
Ahhh! Thanks for that pointer.
When I was trying with a size of 1 the control just disappeared - because the border required a minimum of 3.

But that's just for the direction of the flex.
Is there also a way for the items not to span the full width?

**Comment by digitallyserviced** [comment]
Yes, specify a fixed size. Just include the necessary size for borders....

Experiment...

**Comment by tcurdt** [comment]
As said: I did.
But it just disappeared because the border needed at least 3.

Anyway. Clear now.
