### ISSUE TITLE
Exposing open state for the DropDown widget

### ISSUE THREAD

**Issue by konaraya** [rivo/tview#810]
This library has been very useful to quickly build a terminal UI. Many thanks for the great work.

I was trying to make form navigation slightly more easier to use, especially in places where BackTab doesn't work. I can use SetInputCapture, and push KeyTab events when Arrow events are received and it makes it better. Only minor hiccup is the DropDown where the arrow keys are used to select the items themselves. Currently the open flag is private to the DropDown struct, so I can't use it in the logic within SetInputCapture. Having a IsOpen() member function that returns this value would be useful in my opinion.
It would be a single line change, I can gladly open a PR if you agree.

**Comment by rivo** [comment]
I added `IsOpen()` with the latest commit.
