### ISSUE TITLE
Help with List

### ISSUE THREAD

**Issue by rmasci** [rivo/tview#819]
So I am able to create a list, I can see that list, but what I want to do is be able to have someone arrow down and hit enter, or double click with mouse, or when they select that element in the list. I'd like to see a popup so that the user can edit what the value is for that section of the list. Wondering if there was a way to do this?

**Comment by rivo** [comment]
You'll want to use [`SetSelectedFunc()`](https://pkg.go.dev/github.com/rivo/tview#List.SetSelectedFunc) to listen to list item selection events. Then you place your list and your form into a `Pages` element and show the form when the user selects an item. See the [Wiki](https://github.com/rivo/tview/wiki/Modal) for an example of how to center an element.

**Comment by rivo** [comment]
Since there were no further comments, I'm assuming this has been solved.
