### ISSUE TITLE
Add Ctrl-P `up()` and Ctrl-N `down()` support

### ISSUE THREAD

**Issue by convto** [rivo/tview#820]
In Emacs and similar editors, Ctrl-P/Ctrl-N is equivalent to arrow up/arrow down.
I am familiar with such shortcuts and would like to add support for this if possible.

I have checked the code for this project and it does not have critical interference with existing shortcuts,
Ctrl-P/Ctrl-N are only used in [demos](https://github.com/rivo/tview/blob/ae9464cc3598d81fff6813af3e28f292a9de6c15/demos/presentation/main.go#L89-L95).

And Ctrl-P/Ctrl-N support would be possible to add by adding `tcell.KeyCtrlP` or `tcell.KeyCtrlN` to the part that detects the arrow key input, like this:
https://github.com/rivo/tview/blob/db36428c92d90d1bea934451c4f78bba88058854/table.go#L1590-L1593

If maintainers agree with this opinion, I will try to create a patch.

Thanks for making an awesome project!

**Comment by rivo** [comment]
No need for a patch. You can use [`SetInputCapture`](https://pkg.go.dev/github.com/rivo/tview#Box.SetInputCapture) to customize your key binds.

**Comment by convto** [comment]
I thought it would be less hassle if I could add it to the master branch,
but the library has designs and policies, so I'll follow your guide!

Thanks for answering!

**Comment by convto** [comment]
I'll close this ticket now that it's resolved, Thanks!
