### ISSUE TITLE
TreeView SetCurrentNode is not triggering changed callback

### ISSUE THREAD

**Issue by jdfa** [rivo/tview#823]
While it is really good that current behavior is documented in comment, I would like to have get different thing.

I am using `TreeView` and reimplemented navigation for few keys. It is nothing extraordinary: LeftArrow will switch to parent node, RightArrow - to first child with some extra conditions. 
For that, In `inputCapture` I am calling `SetCurrentNode` which doesn't trigger `changed` callback. I would do that manually, but there is no method to access that callback.

**Comment by digitallyserviced** [comment]
You have to call the Draw method for the treeview. That is where it triggers changed I believe.

**Comment by jdfa** [comment]
@digitallyserviced Thanks, that helped me to find workaround. In my case I just moved my "OnChanged" logic from `TreeView::SetChangedFunc` to `Application::SetBeforeDrawFunc`.
But I am sure that this is not clean solution, `TreeView` api should handle such scenario.

**Comment by rivo** [comment]
@digitallyserviced is right in that the call to the "changed" function is delayed until `Draw` is called next time. I would think, though, that if you rebind keys using `SetInputCapture()`, this would lead to a call to `Draw` immediately afterwards, thus triggering the "changed" callback. Without any more details, though, I can't tell why this isn't happening.

**Comment by rivo** [comment]
Actually, looking at this again in some more detail, the way it was implemented, there was indeed no good way to trigger the "changed" callback when calling `SetCurrentNode()`. This should be fixed with the latest commit. It will still only be triggered during drawing, but it will be triggered in any case.
