### ISSUE TITLE
Run App with Debug mode crashes

### ISSUE THREAD

**Issue by tchaton** [rivo/tview#827]
Hey there,

I am trying to write a tool similar to k9s. However, It is very clear how to easily debug the tview. I tried to use the debugger but somehow, the App crashes.

Any suggestions ?

**Comment by tchaton** [comment]
Also, it would be great to have more advanced examples with interactions. All the examples are pretty static.

**Comment by rivo** [comment]
You're providing too little information to determine what the issue may be. I've successfully debugged `tview` applications in VS Code. Some by attaching the debugger to an existing process, others by directly running them in VS Code's built-in terminal. You might want to provide some details if you want us to help you.

Sure, more examples and/or tutorials would be nice. It's all a matter of having the time to create them. Consider [sponsoring this project](https://github.com/sponsors/rivo?metadata_source=tview_issue_827) to boost the creation of such material.

**Comment by rivo** [comment]
Since there was no further information provided, I'm assuming this issue has been resolved.

**Comment by spearson78** [comment]
I ran into the same issue. Its not a tview or tcell issue rather that the default dlv config does not have a terminal. I followed the instructions here. https://github.com/microsoft/vscode-go/issues/843#issuecomment-526888927 and was able to debug tview applications.
