### ISSUE TITLE
Feature Request: Progress Bar

### ISSUE THREAD

**Issue by SommerEngineering** [rivo/tview#83]
Dear rivo,

thanks for this great library. I'm working on a music playing app (VLC as backend) with tview: https://github.com/SommerEngineering/MusicPlayer Right now, it works only with macOS.

It would be great to have a simple progress bar: I could use it to show the current position of a song. Just need a `SetProgress(percent int)` function to set the position at the interval [0,100].

Is this doable?

Best regards
Thorsten

**Comment by rivo** [comment]
Hi Thorsten, glad that you like `tview`. At the moment, there is no progress bar. This is somewhat related to #11 where people asked for charts. I'm planning to add chart functionality to `tview` at some point the future but probably not soon enough for you if you need it now.

Until then, I suggest that you build your own progress bar. You may be able to use the `TextView` element for it, by writing `U+25A0` characters to it. Or, if you need to get more advanced, you can use [`SetDrawFunc()`](https://godoc.org/github.com/rivo/tview#Box.SetDrawFunc) to write characters to a `Box`. I believe this should be help you implement a progress bar.

I'm currently working on a Wiki page with examples how to implement your own widget: https://github.com/rivo/tview/wiki/Primitives It's not complete yet, though. I'll try to finish it in the next few days.

**Comment by muesli** [comment]
Shouldn't we keep the issue open since it's still a valid ticket worth tracking?

**Comment by rivo** [comment]
If there's ever going to be a progress bar (which I'm really not sure at this point), it is going to be part of the charts. And the charts are really far out, v2.0 or something. I don't believe @SommerEngineering  will wait that long, especially when he has other options to achieve his goal right now.

**Comment by majimboo** [comment]
Still waiting for this or a sample code for the implementation with a box would be acceptable too.

**Comment by rivo** [comment]
Apologies. I'm traveling at the moment with very little internet access. Will get back to the open issues when I get back.

Sent from my iPhone

**Comment by lancerushing** [comment]
Using rivo's suggestion to use U+25A0 characters, I made this example:
```golang
package main

import (
	"fmt"
	"strings"
	"time"

	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView().
		SetChangedFunc(func() {
			app.Draw()
		})

	messages := make(chan struct{}, 50)

	go func() { // Simple channel status gauge (progress bar)
		ccap := cap(messages)
		barSize := 100
		for {
			clen := len(messages)
			barComplete := barSize * clen / ccap
			textView.Clear()
			_, _ = fmt.Fprintf(textView, "channel status:  %s%s %d/%d",
				strings.Repeat("■", barComplete),
				strings.Repeat("□", barSize-barComplete),
				clen, ccap)

			time.Sleep(100 * time.Millisecond)
		}
	}()

	go func() { // Example: add work onto the channel
		for {
			messages <- struct{}{}
			time.Sleep(30 * time.Millisecond)
		}
	}()

	go func() { // Example: remove work from channel
		time.Sleep(time.Second)
		for range messages {
			if len(messages) < 10 { // let a few messages queue up for this example
				time.Sleep(1000 * time.Millisecond)
			}

			time.Sleep(20 * time.Millisecond) //
		}
	}()

	if err := app.SetRoot(textView, true).SetFocus(textView).Run(); err != nil {
		panic(err)
	}
}

```

**Comment by issadarkthing** [comment]
A slightly more simple example
```golang
package main

import (
	"fmt"
	"strings"
	"time"

	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

type Progress struct {
	textView *tview.TextView
	full     int
	limit    int
	progress chan int
}

// full is the maximum amount of value can be sent to channel
// limit is the progress bar size
func (p *Progress) Init(full int, limit int) chan int {
	p.progress = make(chan int)
	p.full = full
	p.limit = limit


	go func() { // Simple channel status gauge (progress bar)
		progress := 0
		for {
			progress += <-p.progress

			if progress > full {
				break
			}

			x := progress * limit / full
			p.textView.Clear()
			_, _ = fmt.Fprintf(p.textView, "channel status:  %s%s %d/%d",
				strings.Repeat("■", x),
				strings.Repeat("□", limit-x),
				progress, full)

		}
	}()

	return p.progress
}

func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView().
		SetChangedFunc(func() {
			app.Draw()
		})

	textView.SetBorder(true)
	textView.SetBackgroundColor(tcell.ColorDefault)

	progress := Progress{textView: textView}
	progChan := progress.Init(360, 20)



	go func() { // update progress bar

		i := 0

		for {
			i++
			progChan <- 1

			if i > progress.full {
				close(progChan)
				break
			}

			time.Sleep(100 * time.Millisecond)
		}
	}()

	if err := app.SetRoot(textView, true).SetFocus(textView).Run(); err != nil {
		panic(err)
	}
}
```

**Comment by tslocum** [comment]
A [ProgressBar](https://gitlab.com/tslocum/cview/-/blob/master/progressbar.go) widget is available in [cview](https://gitlab.com/tslocum/cview), a fork of tview. A PR to include the widget in tview was submitted as #388.
