### ISSUE TITLE
SetAcceptanceFunc handler could use an index param

### ISSUE THREAD

**Issue by atzub** [rivo/tview#832]
Currently the handler gets the text coming from the InputField and the rune which was just entered.  If the rune appears more than once in the text, there's no telling which one it is.  Based on its location, the acceptance logic could change, as just happened for me when I used it to validate an IP with netmask length.  I needed to know if the number is to the right of the '/' or not.

Also wanted to say, I'm a big fan of your work rivo, tview is incredible and I enjoy using it very much.

**Comment by rivo** [comment]
That's true. I don't know how to change it without breaking compatibility, though.
