### ISSUE TITLE
Escape function for texts

### ISSUE THREAD

**Issue by muesli** [rivo/tview#84]
When trying to display texts like `[foobar]` (as an actual text, not a color definition), a convenient little escape function would be handy, otherwise those texts are incorrectly interpreted as a color-markup.

**Comment by rivo** [comment]
Yeah, I want to add this. Not just for strings but also for `io.Writer`'s so you can use it in the `TextView` primitive as well.

**Comment by rivo** [comment]
Btw, this also affects #91 so I will probably do this after introducing background colors.

**Comment by KingRikkie** [comment]
Please make it handle Umlauts `äüö` and brackets `( )` correctly. The current workaround with a `strings.NewReplacer("]", "[]")` fails when there are any of said chars inside the square brackets as tview will ignore the brackets then leading to something like this in viewport

`string with [Ümlauts] in brackets` -> `string with [Ümlauts[] in brackets`
`string with [bra(kets] in brackets` -> `string with [bra(kets[] in brackets`

**Comment by rivo** [comment]
The package now has an escape function. See [`Escape()`](https://godoc.org/github.com/rivo/tview#Escape) for details.
