### ISSUE TITLE
Ability to specify "BorderStyleFocus"

### ISSUE THREAD

**Issue by aditya-K2** [rivo/tview#840]
Right now one can only specify Box.BorderStyle through [`SetBorderStyle`](https://pkg.go.dev/github.com/rivo/tview#Box.SetBorderStyle) It would be really useful to specify `BorderStyleFocus` which would be the style that will be used for the border when the Box has focus.

**Comment by digitallyserviced** [comment]
@aditya-K2 

While my fork has a ton of stuff you may not need, has junk everywhere, and may reference things not included(animation). 


The border focus global style...
[styles.go](https://github.com/digitallyserviced/tview/blob/611a26b9bad195005135a6ce0215280c68d57903/styles.go#L11)

Setting per-box border styles (full struct/runes)
[box.go](https://github.com/digitallyserviced/tview/blob/611a26b9bad195005135a6ce0215280c68d57903/box.go#L411)

Border has extra few runes for handling corners of border
[borders.go](https://github.com/digitallyserviced/tview/blob/611a26b9bad195005135a6ce0215280c68d57903/borders.go#L13)

**_Also beware, just take the border style stuff you need. Do not take the border drawing functions unless you want it to be totally different...._**

It uses different characters and draws them offset of rivo's.

![Screenshot_2023-03-30-23-11-52_3520x1080](https://user-images.githubusercontent.com/1828125/233268199-c44d647c-f8f6-4ba7-83ff-f6959a4352b9.png)
