### ISSUE TITLE
Go Get is Deprecated

### ISSUE THREAD

**Issue by nrtyc4** [rivo/tview#843]
The installation instructions for tview include the command "go get github.com/rivo/tview". Command should be changed to "go install github.com/rivo/tview".

**Comment by rivo** [comment]
`go get` is not deprecated. Installing executables with `go get` is. If anything, the header "Installation" in the README should be changed since `tview` doesn't come with an executable.

I'm open for suggestions.

**Comment by nrtyc4** [comment]
Thank you for the feedback, @rivo. Possibly changing the header to <h1>Download Packages</h1> would be my suggestion.
