### ISSUE TITLE
Persistent activity in terminal

### ISSUE THREAD

**Issue by FunTimeCoding** [rivo/tview#846]
tview appears to be triggering the activity detection of at least iTerm

I wonder what could be the cause and how I might change my code to avoid that.

My goal is to only redraw the window when data I'm fetching actually changes, therefore notifying the terminal that there is "something new". I've had a working implementation with termui before, but switched to tview because it has more granular color control.

![Screenshot 2023-05-08 at 12 56 12](https://user-images.githubusercontent.com/1647065/236807110-2be22414-873d-47f8-b342-61f4b8b31032.png)

**Comment by rivo** [comment]
You didn't provide much info about your application, e.g. what `tview` primitives you're using. So it's difficult for me to help you here.

Of course you can always fetch data separately in a goroutine and once you detect any changes, you update any of the primitives you're using. Be sure to checkout [the Wiki page on concurrency](https://github.com/rivo/tview/wiki/Concurrency) when working with goroutines.

**Comment by rivo** [comment]
I'm going to close this issue if no further information is provided.

**Comment by FunTimeCoding** [comment]
I shall put together a small prototype to replicate the behavior.
