### ISSUE TITLE
How to access Custom Events from the Event Loop?

### ISSUE THREAD

**Issue by devppratik** [rivo/tview#847]
The [tcell-term](https://git.sr.ht/~rockorager/tcell-term) is a library based on tcell. At the moment, it has a custom event that determines if the terminal has exited or not. 
How do I access this event in tview? 
Is there a way to call this event and then use it in the application?

**Comment by devppratik** [comment]
I figured out I can queue a event using the QueueEvent function but how do I access the event from the app event loop itself??

**Comment by rivo** [comment]
There is currently no way to do this. Can you provide some context? What do you want to achieve with these custom events?

**Comment by digitallyserviced** [comment]
@devppratik currently it is not an easy thing to hook into because of tview taking over the event loop polling through tcell. I have hacked my local tcell/tview libraries to have a special event for pastes and also included it within the event loop polling, and a callback handler within my fork...

https://github.com/digitallyserviced/tview/blob/611a26b9bad195005135a6ce0215280c68d57903/application.go#L412

The EventLoop: label has the polling loop and you can hook into any custom events from there. 

```go
    case *tcell.EventPaste:
      if a.onPaste != nil {
      a.onPaste(a.screen, event)
      if event != nil {
        a.GetFocus().OnPaste([]rune(event.Text()))
      }
      break
    }
    fmt.Println("No paste handler", event)
```

While this requires a custom application.go and hacking your local tview library. I am not sure the best way to go about it in your context, since I have had the freedom to hack at will wherever necessary to get the job done.

**Comment by devppratik** [comment]
> There is currently no way to do this. Can you provide some context? What do you want to achieve with these custom events?

@rivo @digitallyserviced 
https://git.sr.ht/~rockorager/tterm is a library based on https://git.sr.ht/~rockorager/tcell-term for t view. 

This allows to use a terminal as a view for tview. It works quite well and without any issues. 
I am trying to create a TMux sort of application using this library

However, when the shell exits (e.g. the user typed user) tcell-term emits a `EventClosed` event to let the user know that the terminal has exited. I would like to capture the `EventClosed` in tview and then perform a set of actions accordingly.

**Comment by digitallyserviced** [comment]
@devppratik 

The problem there is that tterm (the tview wrapper) swallows the eventclosed event you are wanting to get...

the best way to resolve this is just to use the tterm.go terminal struct as your own code and not an outside library because of the scope of the *VT needed to attach the event handler... see example code at bottom, it merges the tterm library and example code into one so you can access all events and you can see where i commented and added the case for handling eventclosed... see gif for what happens...


![Peek 2023-07-03 15-54](https://github.com/rivo/tview/assets/1828125/418497d2-1f1b-452b-a781-ed399d448715)

```go
package main

import (
	"bytes"
	"log"
	"os"
	"os/exec"
	"sync"

	tcellterm "git.sr.ht/~rockorager/tcell-term"
	"github.com/gdamore/tcell/v2"
	"github.com/gdamore/tcell/v2/views"
	"github.com/rivo/tview"
)

type Terminal struct {
	*tview.Box

	term    *tcellterm.VT
	running bool
	cmd     *exec.Cmd
	app     *tview.Application
	w       int
	h       int
	flex *tview.Flex
	boxmsg *tview.Box
	keymsg *tview.Box

	sync.RWMutex
}

func NewTerminal(cmd *exec.Cmd, app *tview.Application) *Terminal {
	t := &Terminal{
		Box:  tview.NewBox(),
		term: tcellterm.New(),
		cmd:  cmd,
		app:  app,
	}
	t.boxmsg=tview.NewBox()
	t.keymsg=tview.NewBox()
	t.flex = tview.NewFlex().SetDirection(tview.FlexRow).AddItem(t.boxmsg, 0, 2, false).AddItem(t.keymsg, 0, 2, false).AddItem(t, 0, 10, true)
	t.boxmsg.SetBorder(true).SetTitleAlign(tview.AlignCenter)
	t.keymsg.SetBorder(true).SetTitleAlign(tview.AlignCenter)
	t.boxmsg.SetTitle(`Welcome to digitallys hacked tterm for more control! a tview widget built with tcell-term`)
	t.keymsg.SetTitle(`press CTRL-Q to quit and CTRL-D to kill term or type "exit" or "logout"`)
	t.boxmsg.SetTitleColor(tcell.ColorBlack).SetBackgroundColor(tcell.ColorGreenYellow)
	t.keymsg.SetTitleColor(tcell.ColorBlack).SetBackgroundColor(tcell.ColorGreenYellow)
	// just so we dont die from ctrl-c
	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		switch event.Key() {
		case tcell.KeyCtrlQ:
			app.Stop()
		case tcell.KeyCtrlC:
			return nil
		}
		return event
	})
	return t
}

func (t *Terminal) Draw(s tcell.Screen) {
	t.Box.DrawForSubclass(s, t)

	x, y, w, h := t.GetInnerRect()
	view := views.NewViewPort(s, x, y, w, h)
	t.term.SetSurface(view)
	if w != t.w || h != t.h {
		t.w = w
		t.h = h
		t.term.Resize(w, h)
	}

	if !t.running {
		err := t.term.Start(t.cmd)
		if err != nil {
			log.Print(err)
			return
			// panic(err)
		}
		t.term.Attach(t.HandleEvent)
		t.running = true
	}
	if t.HasFocus() {
		cy, cx, style, vis := t.term.Cursor()
		if vis {
			s.ShowCursor(cx+x, cy+y)
			s.SetCursorStyle(style)
		} else {
			s.HideCursor()
		}
	}
	t.term.Draw()
}
// the tterm tview wrapper swallows the eventclosed 
// that is emitted here so we add the event type to switch 
// and handle accordingly?
func (t *Terminal) HandleEvent(ev tcell.Event) {
	switch evv := ev.(type) {
	case *tcellterm.EventClosed:
		go func() {
			t.app.QueueUpdateDraw(func() {
				// run closed in main event  loop thread
				t.Closed(evv)
			})
		}()
	case *tcellterm.EventRedraw:
		go func() {
			t.app.QueueUpdateDraw(func() {})
		}()
	}
}

func (t *Terminal) InputHandler() func(event *tcell.EventKey, setFocus func(p tview.Primitive)) {
	return t.WrapInputHandler(func(event *tcell.EventKey, setFocus func(p tview.Primitive)) {
		t.term.HandleEvent(event)
	})
}

func (t *Terminal) MouseHandler() func(action tview.MouseAction, event *tcell.EventMouse, setFocus func(p tview.Primitive)) (consumed bool, capture tview.Primitive) {
	return t.WrapMouseHandler(func(action tview.MouseAction, event *tcell.EventMouse, setFocus func(p tview.Primitive)) (consumed bool, capture tview.Primitive) {
		return t.term.HandleEvent(event), nil
	})
}

// define global so its easier to access for this example
var term *Terminal

// just do a bg change and title set
func (t *Terminal) Closed(ev *tcellterm.EventClosed)  {
	term.boxmsg.SetBackgroundColor(tcell.ColorDarkRed)
	term.boxmsg.SetTitle("WE FUCKED")
}

func main() {
	logbuf := bytes.NewBuffer(nil)
	log.SetOutput(logbuf)
	log.SetFlags(log.LstdFlags | log.Lshortfile)

	app := tview.NewApplication()

	cmd := exec.Command(os.Getenv("SHELL"))
	term = NewTerminal(cmd, app)

	term.SetBorder(true)
	term.SetBorderPadding(4, 4, 12, 12)

	// set a flex as root so we not relying on terminal 
	// as well as having the box for msging inside it
	app.SetRoot(term.flex, true)
	if err := app.Run(); err != nil {
		panic(err)
	}
	os.Stdout.Write(logbuf.Bytes())
}

```

**Comment by devppratik** [comment]
This really solved what I wanted to do!
Thanks!!
