### ISSUE TITLE
Disabling/ignoring external keyboard shortcuts

### ISSUE THREAD

**Issue by alessandrodetta** [rivo/tview#849]
Is there a way to disable/ignore external keyboard shortcuts of other programs (i.e keeping only the ones implemented in tview itself) while running so that e.g pasted selected text in Windows Terminal doesn't gets replaced/overriden by Windows Terminal keyboard shortcut ctrl+v itself ? The same happens while running the app in Visual Studio Code terminal, but for the copy operation, which conflicts with ctrl+q.

or is it just normal behavior that the user/developer should take care of?

**Comment by rivo** [comment]
That's not a question for `tview` to answer but rather an issue with the terminal you're using. I don't know if it's possible to block certain keys from being captured by Windows Terminal or VS Code. You'll have to check out the respective documentation.

I don't believe any application running inside a terminal can break out of its sandbox and modify external shortcuts, unless that's a specific feature provided by the terminal. This would probably be a security issue. A program running inside VS Code could then keep you from closing VS Code, for example.

I think you can change the <kbd>Ctrl</kbd>-<kbd>Q</kbd> key in VS Code to something else. But that might not be what you want.
