### ISSUE TITLE
Feature: Global Menu Primitive

### ISSUE THREAD

**Issue by muesli** [rivo/tview#86]
I've started working on a little Menu primitive, which I seem to need rather often in my apps. I'm wondering if it's a common enough feature, that would warrant integrating something like it directly in tview.

This would allow for a tighter integration with `tview.Application`, the fullscreen layout/screen and global shortcuts.

Link to my (still bare-bone) implementation: https://github.com/muesli/service-tools/blob/master/service-monitor/menu.go

**Comment by rivo** [comment]
Originally, the `List` primitive was implemented as a kind of menu. That's why it has shortcuts to select list items. Unless you're adding sub-menus etc., I don't see the difference between this and a `List` yet.

**Comment by muesli** [comment]
But that doesn't feature global shortcuts and is usually a focusable UI component you control with your cursor keys. Have you checked out my example?

**Comment by rivo** [comment]
I just had a brief look at the code. Didn't realize it installs a global key listener.

This use case is exactly what `app.SetInputCapture()` is for. I use it in the presentation demo, too. You could use that to call `SetCurrentItem()` on a `List`. I update a `TextView` component with it. I guess everybody has a different idea of what such a menu could look like.

It's conceivable to extend the `List` primitive to draw the list items horizontally. But it doesn't feel right to introduce a primitive that has global effects, potentially conflicting ones with other primitives.
