### ISSUE TITLE
White foreground with dim flag makes yellow

### ISSUE THREAD

**Issue by apprehensions** [rivo/tview#863]
Following go snippet:

```go
package main

import (
	"fmt"
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView().SetDynamicColors(true)
	fmt.Fprintf(textView, "[white::d]Hello World![-::-]\n")
	
	if err := app.SetRoot(textView, true).Run(); err != nil {
		panic(err)
	}
}
```

makes the following:
![20230721_02h12m30s_grim](https://github.com/rivo/tview/assets/47404953/c9d02909-8706-43ad-82c3-030abe46e48a)

**Comment by apprehensions** [comment]
![20230721_02h17m16s_grim](https://github.com/rivo/tview/assets/47404953/2e97d93a-8f10-45dc-b53c-27d734bf584e)

**Comment by digitallyserviced** [comment]
Have you tried to print out your white with dim attr in the terminal outside of tview? Like a palette test/colorwheel type thing?

Not all terminal emulators handle dim/bold the same. Sometimes they alter the contrast depending on the bg, sometimes bold can alter it.

I am not able to reproduce your issue. Can you try another terminal/theme? 

Forgive this horribly quick test i made. it prints using escapes to the terminal outside tview. Forgive the dirty spaces/lines... but they should help detect differences.



```go
package main

import (
	"fmt"
	"strings"

	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

func getName(c tcell.Color) string {
	for k, v := range tcell.ColorNames {
		if c == v {
			return k
		}
	}
	return "shit"
}
func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView().SetDynamicColors(true)
	escStrs := make([]string, 0)
	for i := 0; i < 8; i++ {
		fgidx := 30 + i
		bgidx := 40 + i
		fgbrightidx := 90 + i
		bgbrightidx := 100 + i

		escStr := (fmt.Sprintf(" [0m [7;98;%dm  %10s ] [0m[2;%dm (dim attr set)   |   [0m (reset sgr)   |   [0m [2;%dm (dim + color attr set)  |   [0m[7m [2m [%dm (dim + reverse + color set)", bgidx, getName(tcell.PaletteColor(i)), fgidx, fgidx, fgidx))
		escStrs = append(escStrs, escStr)
		escStr = fmt.Sprintf(
			" [0m [7;98;%dm  %10s ] [0m[2;%dm (dim attr set)   |   [0m (reset sgr)   |   [0m [2;%dm (dim + color attr set)  |   [0m[7m [2m [%dm (dim + reverse + color set)",
			bgbrightidx,
			getName(tcell.PaletteColor(i+8)),
			fgbrightidx,
			fgbrightidx,
			fgbrightidx,
		)
		escStrs = append(escStrs, escStr)
	}
	fmt.Fprintf(
		textView,
		tview.TranslateANSI(strings.Join(escStrs, "\n")),
	)

	fmt.Println(strings.Join(escStrs, "\n"))
	fmt.Scanln()

	if err := app.SetRoot(textView, true).Run(); err != nil {
		panic(err)
	}
}

```

In this gif you can see white is the very last color, but my scheme causes it to be a different color/contrast... but it is consistent, in both the raw terminal escapes, and the `TextView`... yours should be too unlss your scheme, or terminal app is doing weirdness.

![Peek 2023-07-29 01-53](https://github.com/rivo/tview/assets/1828125/6085e543-7df9-4306-8e9b-ab7c1fe9787c)

**Comment by apprehensions** [comment]
By using escape sequences, you're effectively bypassing what is allowed by tview...

**Comment by apprehensions** [comment]
Use this program:
```go
package main

import (
	"fmt"
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView().SetDynamicColors(true)

	colors := []string{
		"black",
		"maroon",
		"green",
		"olive",
		"navy",
		"purple",
		"teal",
		"silver",
		"gray",
		"red",
		"lime",
		"yellow",
		"blue",
		"fuchsia",
		"aqua",
		"white",
	}

	for _, c := range colors {
		fmt.Fprintf(textView, "[%s::b]Hello World![-::-] ", c)
		fmt.Fprintf(textView, "[%s::br]Hello World![-::-] ", c)
		fmt.Fprintf(textView, "[%s::]Hello World![-::] ", c)
		fmt.Fprintf(textView, "[%s::r]Hello World![-::-] ", c)
		fmt.Fprintf(textView, "[%s::d]Hello World![-::-] ", c)
		fmt.Fprintf(textView, "[%s::dr]Hello World![-::-]\n", c)
	}
	
	if err := app.SetRoot(textView, true).Run(); err != nil {
		panic(err)
	}
}
```

However, you are right:
![image](https://github.com/rivo/tview/assets/47404953/278efb3a-fbfc-4a84-8e8d-b29082ff3b26)
I'll look into this.

**Comment by apprehensions** [comment]
Yep, you're right. my terminal is the issue, thanks alot for clarifying!

**Comment by digitallyserviced** [comment]
> By using escape sequences, you're effectively bypassing what is allowed by tview...

@apprehensions lol that was the point... to make it obvious it was your terminal
