### ISSUE TITLE
Drawing Primitives at any coords on the screen

### ISSUE THREAD

**Issue by indeed999** [rivo/tview#866]
Hi, is it possible to draw any Primitive at any given coords on the screen above the Grid which is set as root?

Fo example I want to draw ```inputField``` above the ```mainGrid```
```go
mainGrid.SetRows(1, -1).
		SetColumns(30, -1).
                AddItem(Primitive1, 0, 1, 1, 1, 0, 0, false).
		AddItem(Primitive1, 0, 1, 1, 1, 0, 0, false).
		AddItem(Primitive2, 1, 0, 2, 1, 0, 0, false).
		AddItem(Primitive3, 1, 1, 2, 1, 0, 0, true)

inputField = tview.NewInputField() 


if err := app.SetRoot(mainGrid, true).Run(); err != nil {
		panic(err)
	}	
```

**Comment by digitallyserviced** [comment]
@indeed999 @enterus3rname

The way that I handle this is by using `tview.Pages`

You setup the main root as that pages object. As usual you add and switch to your default primitive/view.

Any view/primitive you want to draw in a dynamic position subclass/wrap it so you can override the `Draw/SetRect` methods.

Then when you need to push stuff onto a dynamic positioned layer in front of your default view, add it to the pages, bring to front, and dont set the resize/fullscreen flag when `pages.AddItem`.

The pages works as a layering sort of mechanism and doesnt force a `SetRect` positioning. Also layers in front are drawn last. 

This is a basic example showing how you could alter the coords/geometry.

```go

type Floater struct {
  *tview.Box
}

func NewFloater() *Floater {
  f := &Floater{
    Box: tview.NewBox(),
  }

  // a set draw func will be run BEFORE the `Draw` method
  f.Box.SetDrawFunc(func(screen tcell.Screen, x,y,w,h int) (x,y,w,h int){
    x = newX
    y = newY

    // optionally do some drawing here...
 
    // the x,y,w,h you return here modifies what the `Draw` method
    // will see as the x,y,w,h for this primitive 
    return x,y,w,h
  })
}

// For cases where you need complete control.. override Draw
func (f *Floater) Draw(screen tcell.Screen){
  // handle your own drawing here using `screen.SetContent`
  // you can set some other/unrelated primitive position/size using 
  otherBox := tview.NewBox()
  otherBox.SetRect(newx,newy,neww,newh)
  otherBox.Draw(screen)
}

```

Also look at https://github.com/rivo/tview/wiki/Primitives this describes how `SetDrawFunc` return `x,y,w,h` values can modify the available position/geometry for the underlying primitive.

**Comment by digitallyserviced** [comment]
@indeed999 i just noticed this on the projects using tview

https://github.com/epiclabs-io/winman

**Comment by rivo** [comment]
@indeed999 As @digitallyserviced mentioned, you'll want to use `Pages` to put primitives on top of each other. And you can always call `SetRect()` to set a specific screen position. (IMO, it's not necessary to create your own primitive. If you simply want to display an `InputField`, place it into a "page" and call its `SetRect()` function.)

From a UI point of view, however, I would suggest not trying to calculate screen positions yourself but rather use `Grid` or `Flex` to position the element. For example, the following Wiki page shows how to center a primitive on a page:

https://github.com/rivo/tview/wiki/Modal

This has the advantage that it will work with different screen sizes and you don't even have to know much about the screen yourself.
