### ISSUE TITLE
Crashes when run as a Github action

### ISSUE THREAD

**Issue by zreigz** [rivo/tview#867]
I need to test some CLI application using Github action. It crashes without any error. I was able to reproduce it using the demo app:
https://github.com/zreigz/table-view/actions/runs/5879993817/job/15945282829

**Comment by rivo** [comment]
Something with the environment this runs in. Maybe there is no terminal? You're trying to run an interactive application. It's not going to stop unless someone hits <kbd>Ctrl</kbd>-<kbd>C</kbd>. How do you want to send that event to your application? Maybe GitHub Actions kills it because it doesn't stop?

This doesn't look like a `tview` issue to me. You'll want to look at how to run these kind of applications in a "headless" environment.

**Comment by digitallyserviced** [comment]
> I need to test some CLI application using Github action. It crashes without any error. I was able to reproduce it using the demo app: https://github.com/zreigz/table-view/actions/runs/5879993817/job/15945282829

@zreigz you can add a helper or something that runs in goroutine to queue event to quit or whatever.. 

here is an example of what I use for running my apps and replicating key presses to operate the app into the certain parts/pages/pieces I am working on without having to do them manually on each rebuild/reload...

```go

// whether to do events, could be a build tag or arg for CI
var doEvents bool = true

// basic app startup but call doEvents prior to Run()
func main() {
	app := tview.NewApplication()
	if doEvents {
    // goroutine event emitter
		go DoEvents(app)
	}
	if err := app.SetRoot(YOURCONTAINER, true).Run(); err != nil {
		panic(err)
	}
}

// SimEventFunc is a function that emits events for ticks at idx
type SimEventFunc func(idx int)

// DoEvents handles running simulated events on a ticker.
func DoEvents(app *tview.Application) {
	tkr := GetSimEventTicker(app)
	t := time.NewTicker(500 * time.Millisecond)
	idx := 0

	for range t.C {
		tkr(idx)
		idx++
	}
}

// GetSimEventTicker returns a SimEventFunc queues events according to tick idx
func GetSimEventTicker(app *tview.Application) SimEventFunc {
	emitEvent := app.QueueEvent
	return func(idx int) {
		switch idx {
		// first tick hit down
		case 0:
			emitEvent(tcell.NewEventKey(tcell.KeyDown, 0, tcell.ModNone))
		// second tick hit enter
		case 1:
			emitEvent(tcell.NewEventKey(tcell.KeyEnter, 0, tcell.ModNone))

    //  ...

		// many ticks later because load times or whatever ctrl+o
		case 10:
			emitEvent(tcell.NewEventKey(tcell.KeyRune, 'o', tcell.ModCtrl))

		// whatever now somepoint/tick later call quitting shortcut
		case 20:
			emitEvent(tcell.NewEventKey(tcell.KeyCtrlQ, 'q', tcell.ModCtrl))
		}
	}
}

```

**Comment by zreigz** [comment]
@digitallyserviced thanks!
