### ISSUE TITLE
Could TableCell.SetClickedFunc callback pass a ref to *TableCell?

### ISSUE THREAD

**Issue by carpii** [rivo/tview#871]
Issue #470 resulted in `TableCell.SetClickedFunc()` being added

This allows you to provide a callback fn, when a cell is clicked (even if it is unselectable)

The issue is, the callback provides no way to identify which cell was clicked (and it cannot be retrieved from `Table.GetSelection()` if the cell is unselectable. Also I suspect this event is triggered before the selection would be updated anyway).

This makes it very difficult to attach a generic click handler to all your header cells  - for example if you wanted to install the same callback for all your header cells, then use `TableCell.GetReference()` to decide how to sort the table

Not sure if I'm missing something, but is there a way to identify the cell which was clicked?

Could the tableCell be passed as a parameter to the callback fn?

**Comment by digitallyserviced** [comment]
This is rather simple.


```go
type MyTableCell struct {
*tview.TableCell
}

... somewhere else
func (mtc *MyTableCell) HandleClicked() {
mtc.whatever()
}

func somewhere(){
mtc := &MyTableCell{
TableCell:tview.NewTableCell(),
}
mtc.SetClickedFunc(mtc.HandleClicked)
}

```

Now your method is the handler, it has a handle to the table cell

**Comment by carpii** [comment]
Good catch, thanks!
