### ISSUE TITLE
Wiki -> docs/*.md

### ISSUE THREAD

**Issue by verdverm** [rivo/tview#876]
Just wanted to float the idea by, it would make contributing words or examples easier and part of the pull request workflow.

Thoughts?

**Comment by rivo** [comment]
I don't want to add Wiki contents into this package so it would have to be a separate repo. But that means keeping track of another repo for me. So, to be honest, given the little changes that have been requested for the Wiki so far, it's probably easier to just open up an issue here. This has worked quite well in the past.

**Comment by verdverm** [comment]
> given the little changes that have been requested

The wiki is the cause, the change rate is the symptom, that's why I'm asking

... and now remembering why I forked this repo 5 years ago and again this year, symptom of another cause...

**Comment by rivo** [comment]
> the change rate is the symptom

Do you think so? My experience is that people generally don't like to write documentation. Let's say, if you volunteer to be in charge of the Wiki and turn it into a major information resource for `tview` users, i.e. write a lot of the content yourself, I might actually think about it.

Btw, I'm also frequently getting a comment along the lines of, "I did not know there was a Wiki."

**Comment by verdverm** [comment]
Have you seen how many `tview` forks are out there? People are making little fixes or changes and not thinking to contribute back. There are some really great improvements out there, even people trying to bring them all together into one place.

Have you ever wondered why that is?

_(I ask only to pose a question for reflection, this project has an unusual & interesting history, and as one of these people who have forked and not looked back, I certainly have a few opines on the matter)_

**Comment by rivo** [comment]
I fail to see how any of this is related to putting the Wiki source in a repo. I haven't seen anyone put up an alternative documentation resource for `tview`. (If you know one, I'd be very interested in seeing it.)

Regarding the forks, which I assume is a separate topic you brought up, sure, that's what Open Source is all about, isn't it? If people don't like the direction this project is going, they can fork it and present their own opinion on the matter. If people find that one of these alternatives better suits their needs, they will use that instead. I don't have a problem with that.

As I can dedicate only my free time to this project (of which I have very little to begin with), I will always keep my workflow streamlined, while keeping the project stable, making improvements, and adding new features every now and then. All of this for the long run. I've seen forks on day 1 which nobody talks about anymore. Abandonware is rampant. Unless I get sick or something, that's not going to happen with `tview`.
