### ISSUE TITLE
Adding my app the list of "Projects using tview"?

### ISSUE THREAD

**Issue by migcaraballo** [rivo/tview#878]
Hi Rivo,

i'm in the process of wrapping up the first version of my project. It's a terminal-based app built with tview. I'd like to get some exposure to it because i think its a handy tool, but also neat given the UI. Anyhow, let me know how i can get this going and i'll let you know when i'm done in the next few days.

thanks,
mig

**Comment by rivo** [comment]
If you want your project in the README, please submit a pull request.
