### ISSUE TITLE
Is it possible to increase the fontSize ?

### ISSUE THREAD

**Issue by vaibhav135** [rivo/tview#881]
Hi, 
I am new to golang and trying to build a simple cli application. I have a question, is it is possible to increase the font-size of the text ? I tried to find anything related to this, but couldn't find any.

P.S: I also looked at a lot of apps that are using `tview`. It seems like none of them are using any title or heading (as in big size text). but rather this box title thing. Is this the norm that we should follow while building cli-application?

<img width="424" alt="image" src="https://github.com/rivo/tview/assets/39329182/369c82f3-2bb1-44fe-b93b-cedb230f9593">

**Comment by digitallyserviced** [comment]
@vaibhav135 
The font size on your terminal is defined in you terminal settings.  All characters will be that font size.

Add spaces around the title, and change the color to a more prominent contrasting color from the background to help your visibility. 

It is usually dependant on how you utilize the colors, space and characters to make your layouts visibily usable. Need not increase font size.

Here is someone using a figlet font module to print large text using ASCII figlet fonts.

https://github.com/vilmibm/gh-chat/blob/1112f5c5d71fe3c0e508cf55724231150a1ddff7/main.go#L20

Here I use my tdfgo library and use `tview.TranslateANSI` to parse the output and write it into a textview.

![image](https://github.com/rivo/tview/assets/1828125/f79edaa5-f656-428a-9e13-953afea842ba)

**Comment by vaibhav135** [comment]
@digitallyserviced @rivo  So I tried to show figlet text in textview but couldn't do it properly

Here is the result that I am getting
<img width="1440" alt="image" src="https://github.com/rivo/tview/assets/39329182/4dd6c52d-4bd5-462f-9049-ed1e1093ff95">


<details>
<summary> Here is my code </summary>

```golang

package main

import (
	"fmt"
	"io"
	"os"
	"embed"
	"github.com/rivo/tview"
	"github.com/lukesampson/figlet/figletlib"
)

//go:embed figlet-fonts/*
var font embed.FS
func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView().
		SetDynamicColors(true).
		SetChangedFunc(func() {
			app.Draw()
		})
	textView.SetBorder(true).SetTitle("Stdin")

  data, err := font.ReadFile("figlet-fonts/big.flf")
  
  if err != nil {
    fmt.Println(err.Error())
    return 
  }


  f, err := figletlib.ReadFontFromBytes(data)
  if err != nil {
    fmt.Println(err.Error())
    return 
  }

  msgView := tview.NewTextView()

  _, _, width, _ := textView.GetRect()
  message  := figletlib.SprintMsg("Git is Great", f, width, f.Settings(), "left")
  // tview.TranslateANSI(message)
  // textView.SetText(tview.TranslateANSI(message))
  textView.SetText(message)
	go func() {
		w := tview.ANSIWriter(textView)
		if _, err := io.Copy(w, os.Stdin); err != nil {
			panic(err)
		}
	}()
	if err := app.SetRoot(textView, true).Run(); err != nil {
		panic(err)
	}
} 
```
</details>

I tried to follow this code from here -> https://github.com/vilmibm/gh-chat/blob/1112f5c5d71fe3c0e508cf55724231150a1ddff7/main.go#L20


P.S. : If possible, can you guys please give an example as to how I can show the figlet text in the cli-application.

**Comment by rivo** [comment]
I guess you'll want to [disable wrapping](https://pkg.go.dev/github.com/rivo/tview#TextView.SetWrap).

**Comment by vaibhav135** [comment]
@rivo unfortunately disabling wrapping didn't work. Can you show me an example of how I can use it with textview if possible.

**Comment by vaibhav135** [comment]
@rivo @digitallyserviced So I was able to show the figlet text in cli using [this](https://github.com/mbndr/figlet4go) library. But here is the problem if I print a long sentence (wrapping enabled) the words will crumble into each other and with wrapping enabled it will go out of the screen. How do I make it so that my sentence remain in the screen viewport and don't crumble. Is there anything I am missing?

<details>
<summary> Here is my new code </summary>

```golang

package main

import (
	"embed"
  "io"
  "os"

  "github.com/mbndr/figlet4go"
	"github.com/rivo/tview"
)

//go:embed figlet-fonts/*
var font embed.FS
func main() {
  app := tview.NewApplication()
  textView := tview.NewTextView().
  SetDynamicColors(true).
  SetChangedFunc(func() {
	  app.Draw()
  })
  textView.SetBorder(true).SetTitle("Stdin")

  ascii := figlet4go.NewAsciiRender()

  options := figlet4go.NewRenderOptions()
  options.FontName = "contessa"
  ascii.LoadFont("./figlet-fonts/bigchief.flf")

  renderStr, _ := ascii.RenderOpts("Git is a type of VCS, created by Linus Torvalds also the creator of Linux.", options)

  textView.SetWrap(false)
  
  textView.SetText(renderStr)

  go func() {
    w := tview.ANSIWriter(textView)
    if _, err := io.Copy(w, os.Stdin); err != nil {
	    panic(err)
    }
  }()

  if err := app.SetRoot(textView, true).Run(); err != nil {
    panic(err)
  }
} 


```

</details>


### Here are the results :-

**For simple words** :-
<img width="1432" alt="image" src="https://github.com/rivo/tview/assets/39329182/72824593-a0b6-4e75-88aa-88389f7ec214">


**For long Sentences (wrapping enabled)** :-

<img width="1432" alt="image" src="https://github.com/rivo/tview/assets/39329182/b853dedd-0b1a-4844-a050-37c89f9cdba3">


**For long Sentences (wrapping disabled)** :-

<img width="1432" alt="image" src="https://github.com/rivo/tview/assets/39329182/b8c7d17d-2fe1-44ba-a50e-26ecf226a2a9">

**Comment by rivo** [comment]
You're creating big letters out of characters like slashes, backslashes, and underscores. If you turn on wrapping, `tview` will wrap your slashes, backslashes, and underscores. It has no concept of a "big font" like this. Wrapping will always lead to problems like this.

You might have some luck using the `WordWrap()` function:

https://pkg.go.dev/github.com/rivo/tview#WordWrap

Wrap your text _before_ you convert it into big letters. But (A) you'll need to know beforehand how many letters can fit your screen and (B) it will fail in some cases because this seems to be a variable-width font so results will not be consistent. For example, the "i" is more narrow than the "G".

You're trying to do something that terminal UIs are not really made for. Maybe you'll want to look into graphical user interfaces? They are much more suited for variable font sizes.

**Comment by vaibhav135** [comment]
Got it thanks for the info. I will close this issue now
