### ISSUE TITLE
Unexpected line breaks in TextView

### ISSUE THREAD

**Issue by sshelll** [rivo/tview#882]
When I tried to run the codes in the Wiki of TextView,
I modified the codes because I wanted to highlight some chars instead of words.
Here's the code:
![image](https://github.com/rivo/tview/assets/49158400/36d09de0-6e42-4c58-a058-33ed83a3ae2a)

And then I got the result like this:
![image](https://github.com/rivo/tview/assets/49158400/4e5d695e-92da-4433-b296-9d7cd07d9576)

There're many unexpected line breaks after the target char ('t' in this example).

Is this a bug?
Or there's another way to achieve the goal: highlight single char without line breaks?

PS: I also want to refresh the screen char by char, that's why I called `time.Sleep()` in each round.

My Env:
- OS = MacOS Ventura 13.5.1
- Term = Alacritty
- Font = Hack Nerd Font

**Comment by rivo** [comment]
I found the issue. The latest commit should fix this.
