### ISSUE TITLE
Creating a dropdown inside NewModal

### ISSUE THREAD

**Issue by csudharsan** [rivo/tview#884]
Hi,
I am trying to create a Dropdown inside a Page->Modal. But couldnt get it to working.
Can anyone help with example code?

Also, I see there is a new Type NewModalForm, but couldnt find a example for the same.

**Comment by digitallyserviced** [comment]
@csudharsan what could you not get working? 

Are you getting an error? Is it not showing up? 

Show your code you have tried and we can help!

**Comment by rivo** [comment]
I'm closing this as there was no follow-up. You can always open a new issue if this becomes relevant again.
