### ISSUE TITLE
Long text in TextView

### ISSUE THREAD

**Issue by marek-kuticka** [rivo/tview#895]
Hi

what would be the best option to implement TextView component, inside some Flex container, or whatever, that contains scrollable text and I can keep focus at the end? something in sense of console logger.

I have bit struggles to getting this to work. would there be any example of this?

thx a lot

Marek

**Comment by rivo** [comment]
You can call [`TextView.ScrollToEnd()`](https://pkg.go.dev/github.com/rivo/tview#TextView.ScrollToEnd):

> ScrollToEnd scrolls to the bottom left corner of the text if the text view is scrollable. _Adding new rows to the end of the text view will cause it to scroll with the new data._

You can use `TextView` as a `io.Writer` and simply write your text to it (use [`SetChangedFunc()`](https://pkg.go.dev/github.com/rivo/tview#TextView.SetChangedFunc) to redraw the text view). Make sure to also read the section on [large texts](https://pkg.go.dev/github.com/rivo/tview#hdr-Large_Texts).

**Comment by marek-kuticka** [comment]
thx, my question was rather aimed to adding text itself. what method is most suitable, and if TextView then handles the scroll by itself. 

thx

**Comment by digitallyserviced** [comment]
> thx, my question was rather aimed to adding text itself. what method is most suitable, and if TextView then handles the scroll by itself.
> 
> thx

No `TextView` will NOT automatically scroll when new content is written or appended.

However, you can control this behavior yourself using the callback functions and the `ScrollToEnd()`

https://github.com/hofstadter-io/hof/blob/ce99f98a3db35047fe413c2aff4b07f35b287181/lib/tui/hoc/console/err.go#L17-L25

```go
func NewErrConsoleWidget() *ErrConsoleWidget {
    textView := tview.NewTextView()
    textView.
        SetTextColor(tcell.ColorMaroon).
        SetScrollable(true).
        SetChangedFunc(func() {
            tui.Draw()
            textView.ScrollToEnd()
        })
}
```

**Comment by rivo** [comment]
> No `TextView` will NOT automatically scroll when new content is written or appended.

Not true. `TextView` behaves exactly how it's described in the comment I quoted above. It will automatically scroll. It is not necessary to call `ScrollToEnd()` every time something is changed, like in the example @digitallyserviced posted. Once is enough.

@marek-kuticka Check out the following example which is how you could implement a continuous text stream (but again, please also look at the section about "Large Texts"):

```go
func main() {
	app := tview.NewApplication()

	textView := tview.NewTextView().
		ScrollToEnd().
		SetChangedFunc(func() {
			app.Draw()
		})

	go func() {
		var i int
		for {
			fmt.Fprintf(textView, "%d\n", i)
			time.Sleep(10 * time.Millisecond)
			i++
		}
	}()

	if err := app.SetRoot(textView, true).Run(); err != nil {
		panic(err)
	}
}
```

**Comment by digitallyserviced** [comment]
> > No `TextView` will NOT automatically scroll when new content is written or appended.
> 
> Not true. `TextView` behaves exactly how it's described in the comment I quoted above. It will automatically scroll. It is not necessary to call `ScrollToEnd()` every time something is changed, like in the example @digitallyserviced posted. Once is enough.
>

lol Not not true... While @rivo is correct about this happenning automatically on the initial call,  @marek-kuticka Please note, that my example is still justified...

:grinning: 

- 1x call to `ScrollToEnd` **_WILL_** automatically keep scrolling IF you are sitting at the end of the `TextView`
- 1x call to `ScrollToEnd` **_WILL NOT_** automatically keep scrolling IF you are NOT at the end of the `TextView`
- Scrolling up one line **_WILL STOP_** this automatic scroll which justifies calling `ScrollToEnd` in the `changed` handler to ensure this continues...

![Peek 2023-10-04 20-06](https://github.com/rivo/tview/assets/1828125/3583031a-9bc7-4687-b154-7779782b3189)
