### ISSUE TITLE
Question about textview refreshing content in real time

### ISSUE THREAD

**Issue by 7yyo** [rivo/tview#899]
After adding setDoneFunc to an item, execute a piece of code logic. This process will print some logs. These logs will be transferred to another textview for display. However, the program can only display all logs after setDoneFunc ends and will not output them in real time. This Why? I can provide pseudocode if necessary. The code is similar to the demo of textview

**Comment by rivo** [comment]
Yes, please provide some brief code that can be run to reproduce this.

**Comment by 7yyo** [comment]
@rivo Thanks for the response. The following code can be run directly. There is a treeView and a textView. When setDoneFunc is executed, some strings will be output to textView for display, but they can only be displayed after setDoneFunc is executed. Strings cannot be printed out in textView in real time.

```go

package main

import (
	"fmt"
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
	"time"
)

func main() {
	app := tview.NewApplication()
	grid := tview.NewGrid().SetRows(0, 0).SetColumns(0, 0)
	treeView := tview.NewTreeView()
	root := tview.NewTreeNode("hello world - tree")
	treeView.SetRoot(root).SetCurrentNode(root).SetTitle("tree").SetBorder(true)
	textView := tview.NewTextView()
	textView.SetTitle("text").SetBorder(true)
	textView.SetChangedFunc(func() {
		app.Draw()
	})
	grid.AddItem(treeView, 0, 0, 1, 1, 0, 0, true)
	grid.AddItem(textView, 1, 0, 1, 1, 0, 0, true)

	treeView.SetDoneFunc(func(key tcell.Key) {
		fmt.Fprintf(textView, "%v - %s\n", time.Now(), "hello")
		time.Sleep(1000 * time.Millisecond)
		fmt.Fprintf(textView, "%v - %s\n", time.Now(), "world")
		time.Sleep(5000 * time.Millisecond)
		fmt.Fprintf(textView, "%v - %s\n", time.Now(), "tview")
	})

	if err := app.SetRoot(grid, true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}
}

**Comment by digitallyserviced** [comment]
@7yyo 

your issue is your doing stuff in the main thread like sleeping, which obviously wont let things trigger as needed because well you're blocking by calling sleep in the mains... 

see below, goroutine wrap your sleeps, changed handler just calls queueupdatedraw so the draw occurs on main ui thread... this works fine live/whatever

```go


package main

import (
	"fmt"
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
	"time"
)

func main() {
	app := tview.NewApplication()
	grid := tview.NewGrid().SetRows(0, 0).SetColumns(0, 0)
	treeView := tview.NewTreeView()
	root := tview.NewTreeNode("hello world - tree")
	treeView.SetRoot(root).SetCurrentNode(root).SetTitle("tree").SetBorder(true)
	textView := tview.NewTextView()
	// textView.SetText(text string)
	textView.SetTitle("text").SetBorder(true)
	textView.SetChangedFunc(func() {
		// make your changed function queue a draw on main UI thread
		// as part of changed handler that it does trigger
		// dont have to do shit inn it just makes it call draw on main
		app.QueueUpdateDraw(func() {
		// app.Draw()
		})
	})
	grid.AddItem(treeView, 0, 0, 1, 1, 0, 0, true)
	grid.AddItem(textView, 1, 0, 1, 1, 0, 0, true)

	treeView.SetDoneFunc(func(key tcell.Key) {
		// justin case you never read the documentation for SetText
		// SetText sets the text of this text view to the provided string. Previously contained text will be removed. 
		// As with writing to the text view io.Writer interface directly, 
		// THIS DOES NOT TRIGGER AN AUTOMATIC REDRAW BUT IT WILL TRIGGER 
		// the "changed" callback if one is set.
		textView.SetText("NOTHING")
		// goroutine so we dont block main threads
		go func() {
			fmt.Fprintf(textView, "\n%v - %s\n", time.Now(), "LOOKY")
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "dont")
			time.Sleep(100 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "sleep")
			time.Sleep(500 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "in")
			time.Sleep(500 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "main")
			time.Sleep(500 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "thread")
		}()
	})

	if err := app.SetRoot(grid, true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}
}

```

**Comment by rivo** [comment]
@digitallyserviced is generally right in that your `SetDoneFunc` is part of the main goroutine. So if you're blocking that function (with your sleep calls, in this example), you're blocking everything basically. If you want to stream text to your `TextView`, you need to do it from a separate goroutine. If you know all text in advance, however, just use [`SetText()`](https://pkg.go.dev/github.com/rivo/tview#TextView.SetText) without the `time.Sleep` calls (no goroutine needed in that case).

A few additional notes:

* Just call `app.Draw()` from your `SetChangedFunc`. No need to call `QueueUpdateDraw()` like @digitallyserviced suggested (see the [documentation](https://pkg.go.dev/github.com/rivo/tview#TextView.SetChangedFunc) for details).
* The `SetDoneFunc` can be used in theory but it's usually reserved to be used internally for forms. (Yes, it shouldn't have been exposed in the first place.) Maybe [`SetSelectedFunc`](https://pkg.go.dev/github.com/rivo/tview#TreeView.SetSelectedFunc) or [`SetInputCapture`](https://pkg.go.dev/github.com/rivo/tview#Box.SetInputCapture) with your own bindings is better.
* The `.SetRows(0, 0).SetColumns(0, 0)` calls are not needed: ["A value of 0 is assumed for any undefined column."](https://pkg.go.dev/github.com/rivo/tview#Grid.SetColumns).

**Comment by 7yyo** [comment]
@rivo @digitallyserviced thanks!
To summarize, this code solves the problem I raised
```go
package main

import (
	"fmt"
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
	"time"
)

func main() {
	app := tview.NewApplication()
	grid := tview.NewGrid().SetRows(0, 0).SetColumns(0, 0)
	treeView := tview.NewTreeView()
	root := tview.NewTreeNode("hello world - tree")
	treeView.SetRoot(root).SetCurrentNode(root).SetTitle("tree").SetBorder(true)
	textView := tview.NewTextView()
	textView.SetTitle("text").SetBorder(true)
	textView.SetChangedFunc(func() {
		app.Draw()
	})
	grid.AddItem(treeView, 0, 0, 1, 1, 0, 0, true)
	grid.AddItem(textView, 1, 0, 1, 1, 0, 0, true)

	treeView.SetDoneFunc(func(key tcell.Key) {
		go func() {
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "hello")
			time.Sleep(1000 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "world")
			time.Sleep(5000 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "tview")
			grid.RemoveItem(treeView)
		}()
	})

	if err := app.SetRoot(grid, true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}
}
```
However, I added grid.RemoveItem(treeView) and tried to delete the treeview before the goroutine ended, but it failed. Why is this?

**Comment by rivo** [comment]
You can't make other, especially structural changes to your widgets in a separate goroutine. For example, if the application is currently re-drawing the screen while you change objects that need to be drawn, you will run in to race issues. (The `io.Reader` interface of `TextView` is an exception here.)

Please read the following article about concurrency in `tview`:

https://github.com/rivo/tview/wiki/Concurrency

For your specific program, you will have to wrap `grid.RemoveItem(treeView)` in a `app.QueueUpdateDraw()`.

**Comment by 7yyo** [comment]
@rivo I modified it like this but it still doesn't work. What's the problem?

```go
	treeView.SetDoneFunc(func(key tcell.Key) {
		go func() {
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "hello")
			time.Sleep(1000 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "world")
			time.Sleep(1000 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "tview")
			time.Sleep(1000 * time.Millisecond)
			go func() {
				app.QueueUpdateDraw(func() {
					grid.RemoveItem(textView)
				})
			}()
		}()
	})
```

**Comment by rivo** [comment]
You don't need the second goroutine.

Can you be a bit more specific? What exactly does not work?

**Comment by 7yyo** [comment]
@rivo The code is like this, but textview cannot be automatically hidden

```go
func main() {
	app := tview.NewApplication()
	grid := tview.NewGrid().SetRows(0, 0).SetColumns(0, 0)
	treeView := tview.NewTreeView()
	root := tview.NewTreeNode("hello world - tree")
	treeView.SetRoot(root).SetCurrentNode(root).SetTitle("tree").SetBorder(true)
	textView := tview.NewTextView()
	textView.SetTitle("text").SetBorder(true)
	textView.SetChangedFunc(func() {
		app.Draw()
	})
	grid.AddItem(treeView, 0, 0, 1, 1, 0, 0, true)
	grid.AddItem(textView, 1, 0, 1, 1, 0, 0, true)

	treeView.SetDoneFunc(func(key tcell.Key) {
		go func() {
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "hello")
			time.Sleep(1000 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "world")
			time.Sleep(1000 * time.Millisecond)
			fmt.Fprintf(textView, "%v - %s\n", time.Now(), "tview")
			time.Sleep(1000 * time.Millisecond)
			app.QueueUpdateDraw(func() {
				grid.RemoveItem(textView)
			})
		}()
	})
	if err := app.SetRoot(grid, true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}
}
```

**Comment by rivo** [comment]
It did disappear but the screen was not cleared before redrawing everything so you could still see the remainders of the last `app.Draw` cycle. With the latest commit, the application will always clear the screen before drawing all elements. Try your example with the newest version of `tview`.

**Comment by rivo** [comment]
@7yyo Thank you for the nice words. I try to fix bugs quickly but there may be times when I'm too busy to respond as quickly as I have in this case. Any way, I'm glad it works now.
