### ISSUE TITLE
Not support unicode

### ISSUE THREAD

**Issue by mylxsw** [rivo/tview#9]
Hello,

I found this library not support unicode currently, do you have any plan to add this feature?
Tcell has [support to unicode](https://github.com/gdamore/tcell/blob/master/_demos/unicode.go).
when I input **中文支持**，It juse show **中支**

**Comment by rivo** [comment]
Hi,

Yes, I would like to support unicode. At first, reading [this](https://godoc.org/github.com/gdamore/tcell#Screen)

> Note that wide (East Asian full width) runes occupy two cells, and attempts to place character at next cell to the right will have undefined effects.  Wide runes that are printed in the last column will be replaced with a single width space on output.

made me think there is no good way to deal with it. But the `mattn/go-runewidth` package appears to have all the functions that are needed.

I will get back to you when I have it.

**Comment by rivo** [comment]
I've added support for wide characters. Please have a look. If you still see issues with that, please let me know.

**Comment by rivo** [comment]
By the way, if you have a short code example with Chinese characters that you can send me, I'm happy to include it in the demos and the wiki.

**Comment by mylxsw** [comment]
@rivo I've created a pull request with chinese characters demo #15

**Comment by rivo** [comment]
Saw it. Thanks. It's also in the Wiki now.
