### ISSUE TITLE
List Widget: add setFocus parameter to selected callback

### ISSUE THREAD

**Issue by soyking** [rivo/tview#90]
For a normal scene: select an item in `List` and jump to other widget.

Currently I have to rewrite `InputHandler`:

```
type CustomWidget struct {
        *tview.List
        otherWidget tview.Primitive
}

func (w *CustomWidget) InputHandler() func(event *tcell.EventKey, setFocus func(p tview.Primitive)) {
	h := w.List.InputHandler()
	return func(event *tcell.EventKey, setFocus func(p tview.Primitive)){
		h(event, setFocus)
		switch key := event.Key(); key {
		case tcell.KeyEnter:
			setFocus(otherWidget)
		}
	}
}
```

Or any better way to make it? Thanks.

**Comment by rivo** [comment]
The `Application` class has a public function [`SetFocus()`](https://godoc.org/github.com/rivo/tview#Application.SetFocus). That's what you would usually use.

**Comment by soyking** [comment]
Thank you.
