### ISSUE TITLE
Split terminal view in two-page layout

### ISSUE THREAD

**Issue by bphd** [rivo/tview#901]

**Comment by digitallyserviced** [comment]
@bphd 
I assume you got to filling in the subject of the issue, and just hit submit because you assumed that people will know what you are asking... 

but we dont

please elaborate, code, specifics, cute hand made drawings?

**Comment by bphd** [comment]
> @bphd I assume you got to filling in the subject of the issue, and just hit submit because you assumed that people will know what you are asking...
> 
> but we dont
> 
> please elaborate, code, specifics, cute hand made drawings?

it's about split terminal view in two-page layout. Like it would be great for tiny screen to see the output on two-page layout, like two pages side by side, to we can see more on one screen. Because otherwise the screen have to be in portrait to display all its length

**Comment by rivo** [comment]
Check out the [`Flex`](https://pkg.go.dev/github.com/rivo/tview#Flex) component. This will allow you to place two widgets side by side. Same with the [`Grid`](https://pkg.go.dev/github.com/rivo/tview#Grid) component.

If you simply want to display text, you can use [`TextView`](https://pkg.go.dev/github.com/rivo/tview#TextView) for that.
