### ISSUE TITLE
TextView can now scroll past the end of the text

### ISSUE THREAD

**Issue by polothy** [rivo/tview#907]
Greetings!

Noticed a behavior change after upgrading recently and I'm not sure if it is intentional or configurable. It's easy to reproduce with the demo code, specifically I used this:

```go
// Demo code for the TextView primitive.
package main

import (
	"github.com/rivo/tview"
)

const corporate = `Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.

Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.

Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.

[yellow]Press Enter, then Tab/Backtab for word selections`

func main() {
	app := tview.NewApplication()
	textView := tview.NewTextView().
		SetDynamicColors(true).
		SetRegions(true).
		SetWordWrap(true).
		SetChangedFunc(func() {
			app.Draw()
		})
	textView.SetText(corporate)
	textView.SetBorder(true)
	if err := app.SetRoot(textView, true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}
}
```

If I checkout 892d1a2, I get the behavior that I'm familiar with, the text view doesn't scroll unless I make my terminal window really small. And then it'll scroll up/down to the start/end of the text.

If I checkout master (2dfe060117906c7e8654ff9f8ca3c99803bdd69c) and re-run the program and then hit down arrow, I can start scrolling down past the end of the text.  I can scroll until nothing is shown as well.

Another interesting key combo on master branch, if I hit End key, then down arrow, it's the old behavior (doesn't scroll down anymore). But if I hit up arrow then hit down arrow, I can start scrolling past the end again.

I suspect https://github.com/rivo/tview/commit/7344139b5532c2f04b436664643246d86afcc853 introduced the change, but I couldn't spot anything.

Again, sorry if this is intentional - maybe I need to set something on my end to change behavior.  Either way, thanks! Great package!

**Comment by rivo** [comment]
Thank you for reporting this. The adjustment of the line offset must have gotten lost in the recent changes. The latest commit should fix this.

**Comment by polothy** [comment]
Thanks so much, I'll try it out on Monday!

**Comment by polothy** [comment]
Fix worked, thanks!
