### ISSUE TITLE
How to do scrolling text status

### ISSUE THREAD

**Issue by rhugga** [rivo/tview#917]
I'm trying to determine if this is the correct library for me. I have an interactive automation tool that manages large software defined storage platforms like ceph, etc...

One of the modes loops thru a list of hosts and does various maintenance tasks serially. I want to output each host's status as it occurs on the tty.

Basically I'll be appending to the tty.
Something like this: (sorry github is munging the formatting)
```text
processing host1                               SUCCESS
processing host2                               ERROR
processing host3        upgrading kernel       PENDING
```

So while host3 is processing, it updates the current task it is doing:
```text
processing host1                                 SUCCESS
processing host2                                 ERROR
processing host3        applying firmware        PENDING
```

Is this possible with this library?

**Comment by digitallyserviced** [comment]
@rhugga This is something that is just done with a separate goroutine and updating whatever view's text/content within a `app.QueueUpdateDraw`.

```go
app := tview.NewApplication()
tv := tview.NewTextView().SetDynamicColors(true)

go func(){
  for{
    <-time.After(1*time.Second)
    app.QueueUpdateDraw(func(){
      tv.SetText("One more second without an act of god")
    })
  }
}()
```

**Comment by rivo** [comment]
I assume this is resolved as there haven't been any further responses by OP.
