### ISSUE TITLE
flashing (screen redraws) on any interaction with widgets

### ISSUE THREAD

**Issue by wibobm** [rivo/tview#919]
Updated from version  github.com/rivo/tview@v0.0.0-20230406072732-e22ce9588bb4 to the most recent version (v0.0.0-20231115183240-7c9e464bac02) and noticed when running apps over remote desktop that the entire app will now redraw if you  interact with any widget.  On the prior version of tview the screen did not redraw and performed very smoothly over remote desktops.

![flashing](https://github.com/rivo/tview/assets/1387795/5b7db69e-78f2-47b6-8bfa-d7a14636daae)

**Comment by rivo** [comment]
The latest commit upgrades to the newest `tcell` version which fixed this issue for Windows. So the flickering should be gone after you upgrade.
