### ISSUE TITLE
TextArea -> does not have a SetDynamicColors(true)

### ISSUE THREAD

**Issue by taha-cmyk** [rivo/tview#928]
How to implement Dynamic Colors in TextArea 
my case : i want to implement a syntax highlighting for C language but it render color flags as strings not ANSI
```
#include<studio.h>

struct typeof {
 int size;
}Token;
```

OUTPUT IN TextArea

```
#include<studio.h>

[red]struct[-] typeof {
 [red]int[-] size;
}Token;
```

**Comment by rivo** [comment]
`TextArea` does not support syntax highlighting. That was never within the planned scope. You might have some luck with external `tview` widgets. Maybe an issue search will turn something up.

For read-only text, `TextView` supports coloured text, of course.

**Comment by digitallyserviced** [comment]
@rivo sorry for bumping closed thread, just information for @taha-cmyk 

There is a widget from pgavlin that I have forked and updated the color handling and re-added some features back that were stripped out. 

The editor is an old version of the micro editor's main text view for code editing with syntax highlighting enabled, albeit in a rather simplistic form. It is fairly simple to use, both repo's linked below have example usages.

![image](https://github.com/rivo/tview/assets/1828125/93364462-d629-4bc3-86ce-c51d87e3b09c)

[digitallyserviced/femto](https://github.com/digitallyserviced/femto) and [pgavlin/femto](https://github.com/pgavlin/femto)

**Comment by taha-cmyk** [comment]
> @rivo sorry for bumping closed thread, just information for @taha-cmyk 
> 
> There is a widget from pgavlin that I have forked and updated the color handling and re-added some features back that were stripped out. 
> 
> The editor is an old version of the micro editor's main text view for code editing with syntax highlighting enabled, albeit in a rather simplistic form. It is fairly simple to use, both repo's linked below have example usages.
> 
> ![image](https://github.com/rivo/tview/assets/1828125/93364462-d629-4bc3-86ce-c51d87e3b09c)
> 
> [digitallyserviced/femto](https://github.com/digitallyserviced/femto) and [pgavlin/femto](https://github.com/pgavlin/femto)
> 

Thank u for that , I really appreciate it
