### ISSUE TITLE
customised command mode input field

### ISSUE THREAD

**Issue by stephencheng** [rivo/tview#93]
I have special need to implement a command mode input field.

Basically, I use this type of field to hook up with defined key for quick value change. For example:

* use ctrlj/ctrlk to increase/decrease the value by 1  (not sure if j/k alone is possible), I tested with ctrlj/ctrlk anyway.
* use ctrlh/ctrll to increase/decrease the value by 10
* allow user to define a initial value

I hacked the code for the test, it worked perfect, shown as below:

`

		switch key := event.Key(); key {
		//case tcell.KeyRune: // Regular character.
		//	newText := i.text + string(event.Rune())
		//	if i.accept != nil {
		//		if !i.accept(newText, event.Rune()) {
		//			break
		//		}
		//	}
		//	i.text = newText

		case tcell.KeyCtrlJ:
			i.text = i.text + "+10"
		case tcell.KeyCtrlK:
			i.text = i.text + "-10"

`

I thought I should follow the guid of the primitive sample to make it my own inputfield, so I did a copy of the inputfield go file in order to just add my own logic to handle the key binding part. I could replace all different inner function with exported public method, like Getxx in order to remove compilation errors, but there is one left, which is the border(bool)

`
	if i.border {
		x++
		y++
		rightLimit -= 2
	}
`

so my questions:

1. Is it worth doing my way or you could provide a way to extend the existing inputfield, if so, I will require a few things:

* allow user to add more key binding
* provide a way to disable: case tcell.KeyRune

2. or could you provide a expose method for board method?

Thank you

**Comment by rivo** [comment]
I think what you'll want is [`SetInputCapture()`](https://godoc.org/github.com/rivo/tview#Box.SetInputCapture). There is an example in the [Wiki](https://github.com/rivo/tview/wiki/Primitives#hooking-into-key-events). It's on the `Application` level but it works the same for primitives.

Let me know if this works for you.

**Comment by stephencheng** [comment]
Thanks. primitive level SetInputCapture is exactly what I needed.

It's great to have all these loving feature already there
