### ISSUE TITLE
how can I can use color or style to warn that input is invalid 

### ISSUE THREAD

**Issue by stalwartgiraffe** [rivo/tview#931]
The Form InputField has an Acceptance Function where if the input string is invalid the accept handler can returns false and the users  key press is ignored. 

Rather than ignoring a key press, I would rather allow the input text to be incorrect but give the user a visual indicator that the input string is considered invalid. For example, turn the input text field red to signal an error. 
But I am not seeing the expected color change when I try to set the field color update in the event handler...

```
	const Description = "Description"
	isEven:= false // simulate bad input with even odd
	form.AddInputField(Description, "", 60,
		func(textToCheck string, lastChar rune) bool {
			field := form.GetFormItemByLabel(Description).(*tview.InputField)
			isEven = !isEven // imp
			if isEven {
				field.SetFieldBackgroundColor(tcell.ColorPink)
			} else {
				field.SetFieldBackgroundColor(tcell.ColorBlue)
			}
			return true
		},
		nil,
	)
```

**Comment by stalwartgiraffe** [comment]
Ah. I based my initial code on the basic Form demo, but the AddFormItem documentation at
https://pkg.go.dev/github.com/rivo/tview#Form
says
" Note, however, that the Form class will override some of its attributes to make it work in the form context."

So ok... making custom items style in this manner appears unsupported with the default Form.

ok I guess the new question is there a good tutorial on making a custom form with custom items? How much work  is it to do that?

**Comment by digitallyserviced** [comment]
@stalwartgiraffe 
The `Form` is a helper container to basically contain a bunch of `FieldItem` primitives.

The `FieldItem` is an interface, so whatever object has the methods it requires can be added using `AddFormItem`.

This makes it super simple to make your own custom fields...

```go
type FancyInputField struct {
    *tview.InputField
}

func NewFancyInputField() *FancyInputField {
  fif := &FancyInputField{
    InputField: tview.NewInputField(),
  }
  fif.SetAcceptanceFunc(func(textToCheck string, lastChar rune) bool {
     // change color, smoke dope, commit attrocities here defying form 
     // standards
     // screw you guys, im going home
     return lastChar == '!'
  })
  return fif
}

func (fif *FancyInputField) SetFormAttributes(labelWidth int, labelColor, bgColor, fieldTextColor, fieldBgColor tcell.Color) FormItem {
  // ignore the fuck out of what it wants to do, or apply some of them
  fif.InputField.SetLabelColor(labelColor)
  return fif
}
```

**Comment by stalwartgiraffe** [comment]
I see. SetAttributes is called from the Form Draw() loop, which iterates the collection of items and buttons doing layout and then draws each one.

**Comment by digitallyserviced** [comment]
@stalwartgiraffe yes,technically you could do it that way too. subclass/embed the form and override it's draw methods. but that doesn't give rise to re-use or easy uncoupling from things. 

```go
type MyForm struct {
  *tview.Form
}

func (mf *MyForm) Draw(screen tcell.Screen){
  mf.Form.Draw(screen)
  mf.Form.UnFuckFormItems()
}
```

**Comment by stalwartgiraffe** [comment]
Ok thank you.

**Comment by stalwartgiraffe** [comment]
Ok Thank you
