### ISSUE TITLE
Bug in TextView demo: no highlighted regions in view

### ISSUE THREAD

**Issue by ok-go** [rivo/tview#941]
First case: 
Run demo -> Press Enter. 
Expected: first region highlighted. 
Actual: nothing happens

Second case: 
Run demo -> Click on to first region -> First region highlighted -> Press Tab
Expected: jump to next region
Actual: highlights disappeared

Bug is reproduced in both cases when text fits into the view and doesn't.

Fix in demo: remove ScrollToHighlight call or disable scrolling on TextView

tview version: 742cf086196e
macOS: 14.1.1
app: iTerm2

**Comment by rivo** [comment]
Thanks for notifying me of this. I made a mistake in a commit yesterday. This should be fixed now.
