### ISSUE TITLE
Set TextView.trackEnd to true when "MouseScrollDown" reaches the bottom of the textview

### ISSUE THREAD

**Issue by iopotato** [rivo/tview#945]
In addition to what the title says, it would be nice if `func (t *TextView) ScrollTo(row, column int) *TextView` also sets trackEnd to true whenever the scroll reaches the bottom of the textview.

I tried to implement this behaviour but I could not find a way to detect whether the scroll has reached the bottom of the textview.

By the way, thanks a lot for creating and maintaining this amazing project!

**Comment by rivo** [comment]
With the latest commit, tracking is turned on automatically when scrolling to the end with the mouse.

`ScrollTo` will not have such a functionality. I think the expectation is that calling this function will result in a specific part of the text being shown. If we turned on `trackEnd` and we had scrolled to the end, it would immediately disappear again and that's not what we want. In fact, I'm explicitly turning `trackEnd` off in that function so it remains wherever it is. Users can call `ScrollToEnd` if they want tracking to be on.
