### ISSUE TITLE
Trouble with the implicit SetFocus()

### ISSUE THREAD

**Issue by snabb** [rivo/tview#95]
I had trouble setting focus when using a Table within a Flex. The following code does not work:

```
package main

import (
        "github.com/rivo/tview"
)

func main() {
        app := tview.NewApplication()

        w1 := tview.NewTextView()
        w1.Write([]byte("testing 123"))

        w2 := tview.NewTable()
        w2.SetSelectable(true, false)
        w2.SetCellSimple(0, 0, "foo")
        w2.SetCellSimple(1, 0, "bar")

        layout := tview.NewFlex().
                SetDirection(tview.FlexRow).
                AddItem(w1, 0, 1, false).
                AddItem(w2, 0, 1, false)

        app.SetFocus(w2)

        if err := app.SetRoot(layout, false).Run(); err != nil {
                panic(err)
        }
}
```
The focus is not in the table. I can not move between the table rows.

If I change the `app.SetFocus(w2)` call to the following it works:
```
        go func() {
                time.Sleep(time.Second)
                app.SetFocus(w2)
        }()
```

I browsed through all the closed issues and in one of them it was mentioned that `app.SetRoot(foo, false)` implicitly calls `app.SetFocus(foo)`. How can I work around this? Would it make sense to eliminate the implicit `app.SetFocus()` call and let the user set the focus? (Or perhaps I am missing something obvious?)

PS. Great stuff!

**Comment by rivo** [comment]
You'll want to pass `true` in the `AddItem()` call for your table:

```go
AddItem(w2, 0, 1, true)
```

The application will initially set the focus to the `Flex` element. But then the `Flex` element will pass the focus on to your table. See the [documentation](https://godoc.org/github.com/rivo/tview#Flex.AddItem) for details.

Alternatively, you can also call `SetFocus()` between `SetRoot()` and `Run()`:

```go
if err := app.SetRoot(layout, false).SetFocus(w2).Run(); err != nil {
    panic(err)
}
```

Let me know if this helps.

**Comment by snabb** [comment]
I figured out the `AddItem(x, x, x, true)` method. It feels troublesome, because I need to define the full "path" through several Flex'es (if the application has many Flex'es within each other) instead of just telling which widget should have focus initially.

However calling `app.SetFocus()` after `app.SetRoot()` is easy and straight-forward. I apologize for not figuring this out.

Again: Great stuff! Thanks for making this package available!
