### ISSUE TITLE
Bug in TextArea Select

### ISSUE THREAD

**Issue by eeeXun** [rivo/tview#958]
Given the following code, you can press `C-q` to see the selection range. I want to select all text, so `textArea.Select(0, len(textArea.GetText()))`

```go
package main

import (
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()

	textArea := tview.NewTextArea().
		SetPlaceholder("Enter text here...").
		SetSelectedStyle(tcell.StyleDefault.Background(tcell.ColorYellow).Foreground(tcell.ColorRed))
	textArea.SetTitle("Text Area").SetBorder(true)

	textArea.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		if event.Key() == tcell.KeyCtrlQ {
			textArea.Select(0, len(textArea.GetText()))
			return nil
		}
		return event
	})

	if err := app.SetRoot(textArea,
		true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}
}
```
![image](https://github.com/rivo/tview/assets/58657914/4e3ac62f-15e1-4f57-be9a-25cf6727072d)

The bug is when your text is too long to fit on a line in terminal.
![image](https://github.com/rivo/tview/assets/58657914/f395aaa7-326b-468f-bfa3-320c43af3dbc)

This could not be solved even I increase the value of second parameter in `Select`. `textArea.Select(0, 10000)`

**Comment by naviji** [comment]
I'm able to reproduce this. I'll see if I can fix this.

**Comment by naviji** [comment]
I see that the Ctrl-L key can also be used to select the entire text. 

For some reason selecting via Ctrl-L doesn't  seem to trigger the selection issue.  Does that help you?

**Comment by eeeXun** [comment]
@naviji Hi, thanks for your help.
But my problem is I want to use `TextArea.Replace` instead of `TextArea.SetText` to reserve the undo history. (I want to clear the text, `textArea.Replace(0, len(textArea.GetText()), "")
`)

When I call `TextArea.Replace`, it case the similar problem as mentioned above. So I trace the code and find this function calls `TextArea.Select`.

That's why I report the bug in `TextArea.Select`

**Comment by rivo** [comment]
Hi everyone, thanks for reporting this bug. The latest commit should fix this.
