### ISSUE TITLE
Box title has space with local set zh_CN

### ISSUE THREAD

**Issue by nzlov** [rivo/tview#96]
```
╔ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ A colorful colorful title═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═
```

**Comment by rivo** [comment]
Could you maybe include instructions on how reproduce this, preferably on macOS?

**Comment by nzlov** [comment]
I think the reason is the problem of [mattn/go-runewidth](https://github.com/mattn/go-runewidth), because `LC_CTYPE=zh_CN.UTF-8`, if it is `en_US.UTF-8` there is no problem
