### ISSUE TITLE
Configuration for debug with vscode on linux ( open /dev/tty: no such device or address )

### ISSUE THREAD

**Issue by OsvaldoTCF** [rivo/tview#962]
Could anyone help me with configuring VSCode to be able to debug the code with TView?

It would be cool to have this on the wiki.

I am very grateful!

VSCode: 1.87.2
OS: Linux x64 5.15.0-94-generic
Ubuntu 22.04

.
![image](https://github.com/rivo/tview/assets/5272869/7c80337d-b30a-478f-8c75-fdea5e32c862)
.

**Comment by rivo** [comment]
I have this line in my `launch.json` file:

```json
"console": "integratedTerminal",
```

I'm not exactly sure if this is what you need but it might be. If it solves your problem, please let me know.

**Comment by OsvaldoTCF** [comment]
After a few days, now, your tip helped me find the information I needed, thank you very much.

https://github.com/golang/vscode-go/issues/124

my launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Cli",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "debugAdapter": "dlv-dap",
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/cmd/main.go",
            "args": [],
        },
    ]
}

**Comment by OsvaldoTCF** [comment]
After a few days, now, your tip helped me find the information I needed, thank you very much.

https://github.com/golang/vscode-go/issues/124

my launch.json

{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"name": "Debug Cli",
"type": "go",
"request": "launch",
"mode": "debug",
"debugAdapter": "dlv-dap",
"console": "integratedTerminal",
"cwd": "${workspaceFolder}",
"program": "${workspaceFolder}/cmd/main.go",
"args": [],
},
]
}
