### ISSUE TITLE
Hello world doesn't work on cmder on windows.

### ISSUE THREAD

**Issue by jeet-parekh** [rivo/tview#97]
When trying to run the hello world code on windows, it works if run from the native command prompt.

But when tried to run from [cmder](http://cmder.net/), it panics and says

```
panic: character set not supported

goroutine 1 [running]:
main.main()
        F:/go_dev/tview_hw.go:10 +0x167
exit status 2
```

If it helps, output of `locale` on cmder is

```
LANG=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=
```

**Comment by rivo** [comment]
This seems to be an error message coming from [`tcell`](https://github.com/gdamore/tcell). You may want to open an issue there to find out if `cmder` is supported. The `tcell` repo also includes demos. You can check if you get the same error message there.
