### ISSUE TITLE
Wrong color in DropDown SetListStyles

### ISSUE THREAD

**Issue by eeeXun** [rivo/tview#990]
In the following code, I want to set `unselected` background color to red.

```go
package main

import (
	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	dropdown := tview.NewDropDown().
		SetLabel("Select an option (hit Enter): ").
		SetOptions([]string{"A", "AA", "AAA", "AAAA", "AAAAA"}, nil)
	dropdown.SetListStyles(tcell.StyleDefault.Background(tcell.ColorRed), tcell.StyleDefault)
	if err := app.SetRoot(dropdown, true).SetFocus(dropdown).Run(); err != nil {
		panic(err)
	}
}
```

This is before 03bdc867bee4ce7355079090c396d9ec861fc4bb
![image](https://github.com/rivo/tview/assets/58657914/de7dc2d8-f8fa-476d-8b8a-032ad33a0c52)

This is after 03bdc867bee4ce7355079090c396d9ec861fc4bb, some areas did not change to red.
![image](https://github.com/rivo/tview/assets/58657914/a3089cae-e88b-4277-aafe-75097df470f7)

**Comment by rivo** [comment]
The latest commit should give you the previous behaviour again.

However, I should note that using [`tcell.ColorDefault`](https://pkg.go.dev/github.com/gdamore/tcell/v2#ColorDefault) will almost always have unintended side effects. Your code uses these implicitly by using `tcell.StyleDefault`. I would advise you to always specify an actual color for both background and foreground (unselected and selected).
