### ISSUE TITLE
`SetPlaceholderTextColor` method not available for `*tview.TextArea`

### ISSUE THREAD

**Issue by HicaroD** [rivo/tview#995]
Is there any good reason for this? 
I want to change the color of the placeholder text from the text area, but this method is not available for some reason

**Comment by eeeXun** [comment]
Did you try the [`SetPlaceholderStyle`](https://pkg.go.dev/github.com/rivo/tview#InputField.SetPlaceholderStyle)?

**Comment by rivo** [comment]
The `Set__Color` methods are just there for backwards compatibility. At some point, only `Set__Style` methods were added (and will be added). They allow you to specify many more attributes, like background colour, underline/bold etc. You can even add hyperlinks if you want.
